### ISSUE TITLE
能咨询个关于软件更新的问题吗？

### ISSUE THREAD

**Issue by gafish** [zzzgydi/clash-verge#1]
实在不好意思，找不到可以留言的地方，只能在Issues里给您发个消息

我看您的项目中有更新配置

```json
    "updater": {
      "active": true,
      "endpoints": [
        "https://github.com/zzzgydi/clash-verge/releases/download/updater/update.json"
      ],
      "dialog": false
    }
```

我试尝试下载了 v0.0.12 版本，但打开软件后并没有触发更新提醒，想问下这个更新机制能正常使用吗？

之所以问这个问题，是因为我在学习使用Tauri开发小工具，在尝试使用更新配置时，可以看到更新提醒弹层，但没有真正的更新，看到您的项目中也有更新配置，所以特来向你请教一下。

**Comment by zzzgydi** [comment]
你好，我这个项目实现的更新是不用tauri默认的弹窗提示的，设置`dialog: false`了。

如果你可以正常访问我的更新链接（<https://github.com/zzzgydi/clash-verge/releases/download/updater/update.json>因为可能是在国内访问github失败导致没有触发更新）的话，更新提示会在左上角那只猫图标的右下角有个`New`按键，点击之后会触发更新流程。

**Comment by zzzgydi** [comment]
我的ui实现是这样的，可以留意一下：

![image](https://user-images.githubusercontent.com/27361820/151594332-585e5306-3100-4e3a-b304-0c4f5671e262.png)

**Comment by layou233** [comment]
> 如果你可以正常访问我的更新链接（<https://github.com/zzzgydi/clash-verge/releases/download/updater/update.json>因为可能是在国内访问github失败导致没有触发更新）的话，更新提示会在左上角那只猫图标的右下角有个`New`按键，点击之后会触发更新流程。

如果改使用jsDelivr的镜像来检测更新是不是可以避免大陆DNS污染的问题？

**Comment by zzzgydi** [comment]
> 如果改使用jsDelivr的镜像来检测更新是不是可以避免大陆DNS污染的问题？

jsDelivr最近好像也有问题？现在已经增加了一个 https://hub.fastgit.xyz/ 做github的代理，不知道好不好使。
