### ISSUE TITLE
在 Windows 中无配置文件的时候UI无法启动

### ISSUE THREAD

**Issue by ericclose** [zzzgydi/clash-verge#10]
建议软件本身检测是否有配置文件的 path，没有则创建 `%USERPROFILE%\.config\clash`

**Comment by zzzgydi** [comment]
默认会在用户目录创建文件夹和初始化一些配置文件的，路径是`~/.config/clash-verge`。

如果你首次运行这个项目的时候，没有创建这个文件夹的话，有两个可能：

1. 创建文件夹的时候异常没处理，程序挂掉了
2. 端口33333被占用了

**Comment by ericclose** [comment]
> 默认会在用户目录创建文件夹和初始化一些配置文件的，路径是`~/.config/clash-verge`。
> 
> 如果你首次运行这个项目的时候，没有创建这个文件夹的话，有两个可能：
> 
> 1. 创建文件夹的时候异常没处理，程序挂掉了
> 2. 端口33333被占用了

---

看了下没有进程占用这个端口，删了 `~/.config` 重新安装，发现 `~/.config` 目录确实没有创建成功，手动创建 `~/.config` 就能开了

```batch
netstat -aon|findstr "33333"
```

**Comment by zzzgydi** [comment]
了解了解，没处理`~/.config`不存在的问题，草率了

**Comment by zzzgydi** [comment]
这个修复已发布 Version 0.0.22。
