### ISSUE TITLE
win10 64位系统，无法启动clash-verge

### ISSUE THREAD

**Issue by zhangkaiitugithub** [zzzgydi/clash-verge#102]
便携版 无法启动。
安装版无法完成安装，显示一下内容：
there is a problem with this Windows Installer package,A program required for this install to complete could not be run Contact your support personnel or package vendor.

**Comment by zhangkaiitugithub** [comment]
便携版 无法启动。
安装版无法完成安装，显示一下内容：
there is a problem with this Windows Installer package,A program required for this install to complete could not be run Contact your support personnel or package vendor.

**Comment by zzzgydi** [comment]
有安装webview2 的runtime没

**Comment by zhangkaiitugithub** [comment]
> 
没有

**Comment by zzzgydi** [comment]
没有webview2运行不了的，https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by zhangkaiitugithub** [comment]
多谢您的回复

**Comment by zzzgydi** [comment]
没啥问题的话，先close啦
