### ISSUE TITLE
mac端的一些问题

### ISSUE THREAD

**Issue by BrightVan** [zzzgydi/clash-verge#110]
- 一开始添加远程配置，下载失败，有个错误提示，那个黑色背景的提示会显示不全
- 图标目前不符合MacOS的新标准，不统一
- command+Q，这个常用快捷键无法退出，没反应
- 深色模式下，标题栏还是白色的，且文字的显示，对比不太明显，会有点看不清
- MacOS的设计，有个菜单栏，clashX 、clash for windows，都会有个菜单栏的操作，比较方便

> 总的来说，和clash for windows有点像，但毕竟不如那个做的久，功能细节上差很多，但UI细节要比它好，还可以直接换内核
对比下，目前还是clashx用起来方便些，clashx的问题主要是那个dashboard有点卡，且不能直接换内核；

**Comment by zzzgydi** [comment]
感谢支持和反馈！

- 提示不全有没有截图可以提供一下
- 这个新标准是指啥，不太了解macOS
- mark
- mark
- 这个菜单栏的操作是指哪些，切换节点啥的吗

**Comment by zzzgydi** [comment]
第一个问题已经修复

**Comment by BrightVan** [comment]
- 图标可以参考这个[网站](https://macosicons.com/)，目前新的规范都是圆角矩形的
- 菜单栏可以看下clashX的截图。macOS除非全屏，顶部是始终显示个菜单栏的，一些操作就很方便，详细的设置可以放在dashboard里，但clashX的dashboard就比较简单，且会卡，不过如果个人不用Mac的话，开发测试起来可能不太方便。我觉得clash-verge 和[CFW](https://github.com/Fndroid/clash_for_windows_pkg/releases)很像，但CFW功能细节非常完善。
<img width="249" alt="image" src="https://user-images.githubusercontent.com/9381559/173761412-56bd9cbf-a13e-4808-b449-f03b6122d0d3.png"><img width="1387" alt="image" src="https://user-images.githubusercontent.com/9381559/173761804-698c9390-9d37-4816-ad13-e7158a3a7b7a.png">

**Comment by zzzgydi** [comment]
macos的图标我也更新了一下

**Comment by skill7899** [comment]
> macos的图标我也更新了一下

为啥没有m1版本的，可以编译多一个m1版本的吗？

**Comment by zzzgydi** [comment]
@skill7899 1.0.3现在有适配m1的了，可以试试。

**Comment by skill7899** [comment]
> @skill7899 1.0.3现在有适配m1的了，可以试试。

tun的开启不了，提示权限不足

**Comment by skill7899** [comment]
> @skill7899 1.0.3现在有适配m1的了，可以试试。

@zzzgydi tun开启不了，提示权限不足。

**Comment by zzzgydi** [comment]
> tun开启不了，提示权限不足。

@skill7899 正常，macOS权限这块还没做处理。

**Comment by skill7899** [comment]
> > tun开启不了，提示权限不足。
> 
> @skill7899 正常，macOS权限这块还没做处理。

@zzzgydi 还需要多久，这个客户端不错。可以参考一下cfw和clashx pro。。clashx是开源，pro好像没有开源。

**Comment by zzzgydi** [comment]
> 还需要多久

@skill7899 佛系开发和迭代，时间不好说。如果有什么实现上的参考资料，也可以分享一下。

**Comment by skill7899** [comment]
> > 还需要多久
> 
> @skill7899 佛系开发和迭代，时间不好说。如果有什么实现上的参考资料，也可以分享一下。

问了一下做macos的软件开发，需要launchd让它作为特权用户运行

**Comment by zzzgydi** [comment]
1.3.0版本支持了在界面中对clash内核提权，然后就可以用TUN了
