### ISSUE TITLE
failed to parse the server报错

### ISSUE THREAD

**Issue by 2715481617** [zzzgydi/clash-verge#113]
设置里面改内核或者选择配置就报错failed to parse the server
配置文件
`# Default Config For Clash Core
mixed-port: 7080
log-level: info
allow-lan: false
mode: rule
external-controller: "127.0.0.1:9099"`

**Comment by zzzgydi** [comment]
这个文件格式是不是有问题

**Comment by zzzgydi** [comment]
可以升级最新版1.0.3试试，优化了这一块的错误提示
