### ISSUE TITLE
任务栏缩略图好像出问题了

### ISSUE THREAD

**Issue by Rsaike** [zzzgydi/clash-verge#115]
最新版本的便携版
![image](https://user-images.githubusercontent.com/32381925/175009341-fc9bff95-277d-421b-b653-4376833239cd.png)

**Comment by zzzgydi** [comment]
对的，下一个版本再修复一下。你的系统方便告知一下吗，目前已知win10有问题

**Comment by CyberShike** [comment]
> 对的，下一个版本再修复一下。你的系统方便告知一下吗，目前已知win10有问题

Windows 11 21H2

**Comment by zzzgydi** [comment]
这个问题已经修复了忘了关
