### ISSUE TITLE
自动更新订阅好像又有问题了

### ISSUE THREAD

**Issue by vinzst** [zzzgydi/clash-verge#116]
windows x64 便携版

**Comment by zzzgydi** [comment]
能具体讲讲啥问题吗

**Comment by vinzst** [comment]
> 能具体讲讲啥问题吗

就是无法自动更新订阅

**Comment by FoundTheWOUT** [comment]
定时器的更新任务在每次app启动的时候会重新初始化，如果更新周期大于app重启时间，那将无法更新配置。比如更新周期*1440min*，即一天，那么如果我软件没有开**足**一天，定时任务不会运行，第二天开机又会重新开始计算，结果是永远无法更新。

方案：
用 [tauri-plugin-store](https://github.com/tauri-apps/tauri-plugin-store) 把上次更新时间存起来
https://github.com/zzzgydi/clash-verge/blob/f1a68ece01c10e42cb861587656d86926157f85d/src-tauri/src/core/mod.rs#L91-L94
在初始化阶段比对上次更新时间是否超过设置的时间周期，超过则立即运行一次定时任务
