### ISSUE TITLE
Windows Portable的数据路径

### ISSUE THREAD

**Issue by delphinuz** [zzzgydi/clash-verge#117]
按理应数据应放在 portable/.config下，但试了一下，仍会放在 USERNAME/.config里，这样应无法做到portable？

试著将 USER/.config 搬到 portable/.config 也无法正常使用。

**Comment by zzzgydi** [comment]
portable如何设置配置目录到exe所在目录，可以看这里 https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88
