### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by lxtx528** [zzzgydi/clash-verge#118]
app 速度挺快的，主要希望UI界面能美化一下就完美了，还有选择中文以后有些地方还是英文，希望选择中文后就全是中文，代理界面希望能延迟排序。启动代理设置开关有点变扭，不太顺手，希望能换个地方比如在设置下面增加一栏开关。代理界面希望能像cfw那样挺美观的。望采纳

**Comment by zzzgydi** [comment]
感谢建议

> 代理界面希望能延迟排序

这个是有了的，你点测速之后，再点排序，点到按`sort by delay`就可以了。

> 启动代理设置开关有点变扭

这是指的哪个按键，系统代理开关？

**Comment by lxtx528** [comment]
收到，是系统代理开关，每次要拉下去才能点按。

GyDi ***@***.***>于2022年6月27日 周一19:43写道：

**Comment by zzzgydi** [comment]
系统代理的开关不是可以通过左下角的托盘图标设置吗

**Comment by jsjcjsjc** [comment]
我都不好意思提,因为这款是目前windows下最棒的! 哈哈

**Comment by zzzgydi** [comment]
系统代理的切换可以设置热键啦，可以更新试一下
