### ISSUE TITLE
好像初始安装第一次打开都会无法加载配置文件

### ISSUE THREAD

**Issue by shuuiran** [zzzgydi/clash-verge#122]
具体表现：
首次安装，运行，下载配置文件并选中，代理界面仍然空白，无法启动代理。
只要重新再启动一下App后就会正常。
装了好几台电脑都100%复现
环境：win11 or win10

软件版本1.0.3

**Comment by zzzgydi** [comment]
感谢反馈，问题已定位！

**Comment by zzzgydi** [comment]
1.0.4版本里已修复该问题。
