### ISSUE TITLE
clash for windows  支持网页版更换更分流策略，verge也可以，但没有入口

### ISSUE THREAD

**Issue by fscarmen** [zzzgydi/clash-verge#123]
入口是 https://clash.razord.top/?host=127.0.0.1&port=63166#/proxies
现在我都是把这个放在浏览器的收藏夹，希望 verge 那里有个入口，并支持自定义端口会更好
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/62703343/178027646-f5400fdf-4c12-42cd-b5b2-3bea63e2f798.png">

**Comment by zzzgydi** [comment]
这个我后面加一下

**Comment by Synchronized1** [comment]
> 这个我后面加一下

我在clash-verge中使用如下配置
`mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
**external-controller: '127.0.0.1:9090'** #该配置即使修改端口,在ui访问的时候发现依然是9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
`
测试发现:
https://clash.razord.top/?host=127.0.0.1&port=9090#/proxies
http://yacd.haishan.me/ 
均可使用,猜测内核是不是写死了external-controller的端口

**Comment by zzzgydi** [comment]
@Synchronized1 改了配置要重启软件才生效

**Comment by Synchronized1** [comment]
> 
更改external-controller端口后,尝试退出 clash verge 启动,依然通过9090端口访问
希望大佬后期能在UI界面显式提供这个两个面板

**Comment by zzzgydi** [comment]
v1.0.5增加了web ui管理，可以自行添加url。

如：https://clash.razord.top/?host=%host&port=%port&secret=%secret#/proxies

`%host`, `%port`, `%secret`会替换成对应的值。
