### ISSUE TITLE
请求支持跟随系统主题切换亮暗主题

### ISSUE THREAD

**Issue by txyyh** [zzzgydi/clash-verge#127]
本人配置了 Windows 系统亮暗模式在日出日落时候自动切换，然而 clash-verge 并没有像其他 App 一样跟随系统切换亮暗主题，还望开发者可以考虑实现下。

文档我只翻到点 [win32](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes) 的（好像是 UISettings），看到还有[读取注册表](https://stackoverflow.com/a/58494769)的，然后[这个](https://docs.microsoft.com/en-us/answers/questions/715081/how-to-detect-windows-dark-mode.html)是啥我也看不太懂。我本身也不是开发者，麻烦项目主自己评估下吧

**Comment by zzzgydi** [comment]
用的框架好像支持 https://tauri.app/v1/api/js/classes/window.WebviewWindow#theme mark一下

**Comment by Limsanity** [comment]
`listen('tauri://theme-changed')`, [refer link](https://github.com/tauri-apps/tauri/pull/3937).

**Comment by zzzgydi** [comment]
1.0.4版本已支持。
