### ISSUE TITLE
Add User-Agent request

### ISSUE THREAD

**Issue by betaxab** [zzzgydi/clash-verge#13]
Some airport's subscription API needs User-Agent to identify client type and return profile, could you add User-Agent support for this? Thanks.

**Comment by zzzgydi** [comment]
No problem.

**Comment by zzzgydi** [comment]
Now it is supported on ^0.0.22. You can edit the old profile(Remote type), click the  left bottom setting icon and then customize your user-agent.

**Comment by betaxab** [comment]
I have tried, but it looks couldn't save. :(

When I added (click Edit -> Settings -> Fill clash into the UA textbox -> Update), then ( click Update) update subscription, the UA just added will disappear and the subscription is not downloading correctly either.

**Comment by betaxab** [comment]
Thanks, waiting for your new release.

btw, is it possible to add a default UA for clash verge, e.g. clash-verge/1.0? (It will be awesome!)

**Comment by zzzgydi** [comment]
Version 0.0.23 is now available! I will consider whether to include a default UA.
