### ISSUE TITLE
[Feature Request] 通过 NetFilter SDK 支持Windows下的透明代理

### ISSUE THREAD

**Issue by Masaiki** [zzzgydi/clash-verge#130]
tun模式很好 但存在一个问题
ping、bt客户端这种需要真实IP的软件哪怕通过PROCESS-NAME指定了直连，他们发出的dns请求还是会返回fake-ip
qbittorrent 有指定网卡的功能（libtorrent提供），但DNS请求也是发向默认网卡的（也就是tun虚拟出的网卡），更糟糕的是，很多软件都无法指定网卡
之前clash.NET 通过[NetFilter SDK](https://netfiltersdk.com/)实现了透明代理，但作者已经删库溜了
希望verge能支持相关功能

**Comment by Riajyuu** [comment]
这个还要提权 倒不如直接 https://docs.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page

**Comment by Masaiki** [comment]
> 这个还要提权 倒不如直接 https://docs.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page 虽然微软这套东西似乎太复杂了些

（我康康

**Comment by Mirr0ch1** [comment]
其实我有一点好奇（对着方面不太懂 诚心求问。。。

**为什么 TUN 开启后 DNS 默认配置不是 redir-host 呢？** ：
就……fake ip 虽然返回快，但是撞上游戏、p2p 这类的场景直接 gg
redir-host 虽然返回慢了点儿，但胜在兼容确实好。。。
之前我努力学着从官方内核切到 Meta 也是看中了 Meta 依旧保留对 redir-host 完整支持才选的。。。
