### ISSUE TITLE
无法自动更新

### ISSUE THREAD

**Issue by raycke** [zzzgydi/clash-verge#131]
Hi, @zzzgydi 

Clash图标上显示`New`按钮，点击后在打开的窗口中显示了更新日志以及`Update`按钮，但是点击`Update`按钮实际没有更新。当前版本V1.0.3

**Comment by raycke** [comment]
补充一张截图 ![image](https://user-images.githubusercontent.com/70388114/179431641-1ebdb41e-30ab-46ab-b013-e56d167de38a.png)

**Comment by zzzgydi** [comment]
更新的安装包地址是github的release，所以点了update没反应，应该是被墙了。

**Comment by raycke** [comment]
> 更新的安装包地址是github的release，所以点了update没反应，应该是被墙了。

谢谢回复。
我开启了设置面板里`系统代理`选项，从Clash-Verge日志里看到github是走的代理，否则我也不开github站点。所以，是否Clash-Verge更新没有自动走代理呢？

**Comment by zzzgydi** [comment]
> 是否Clash-Verge更新没有自动走代理呢？

是的，这个更新不走系统代理，开tun就管用。

**Comment by raycke** [comment]
> > 是否Clash-Verge更新没有自动走代理呢？
> 
> 是的，这个更新不走系统代理，开tun就管用。

原来如此。因为其他一些原因我把tun关掉了。 是否可以让其在非tun模式下也能走系统代理或者Clash-Verge自身监听的代理端口（有时候可能系统代理不可用，非FQ用途），例如127.0.0.1:7890

**Comment by shuuiran** [comment]
@zzzgydi 试过好几个系统环境，通过软件内升级，下载完到最后都会报错 Verify signature error: InvalidSignature

**Comment by zzzgydi** [comment]
@shuuiran 你是从1.0.3到1.0.4的吗

**Comment by shuuiran** [comment]
> @shuuiran 你是从1.0.3到1.0.4的吗

@zzzgydi 是的，1.0.3 > 1.0.4

**Comment by zzzgydi** [comment]
> > @shuuiran 你是从1.0.3到1.0.4的吗
> 
> @zzzgydi 是的，1.0.3 > 1.0.4

你是什么系统什么版本

**Comment by shuuiran** [comment]
> 

Windows 11 Pro 21H2 Build 22000.795

**Comment by zzzgydi** [comment]
> > 你是什么系统什么版本
> 
> Windows 11 Pro 21H2 Build 22000.795

已经修复了，可以等回再更新一下试试

**Comment by shuuiran** [comment]
> 已经修复了，可以等回再更新一下试试

成功更新。

**Comment by Riajyuu** [comment]
是否可以考虑上架微软商店 这样起码可以自动静默更新
