### ISSUE TITLE
ipv6开关打开后，重新启动软件会自动关闭。

### ISSUE THREAD

**Issue by cfcboy** [zzzgydi/clash-verge#133]
ipv6开关打开后，重新启动软件会自动关闭。

应该在什么地方设置启用ipv6呢。

**Comment by zzzgydi** [comment]
你是说在应用的设置界面开启ipv6，重启软件后会失效吗？

这个有可能是因为重启软件后尝试开启ipv6失败。

**Comment by cfcboy** [comment]
找到问题了。必须在Mixin的dns下面配置`  ipv6: true`，不然软件界面的ipv6开关不起作用。

**Comment by cfcboy** [comment]
谢谢答复。支持一下开发者。

**Comment by duokebei** [comment]
> 你是说在应用程序的设置界面开启ipv6，重启软件后会失效吗？
> 
> 这个有可能是因为重启失败后尝试ipv6。

想问下作者有最佳的config.yaml配置嘛，文档里没有。

**Comment by zzzgydi** [comment]
> 想问下作者有最佳的config.yaml配置嘛，文档里没有。

@duokebei 默认的就挺好，不动他就行
