### ISSUE TITLE
tun模式与服务模式的问题

### ISSUE THREAD

**Issue by duokebei** [zzzgydi/clash-verge#134]
开tun模式没办法系统真全局代理，服务模式的话，安装服务后，也没有系统真全局代理

**Comment by zzzgydi** [comment]
tun模式的开启要确保有管理员权限。

开启服务模式之后也要开tun模式，服务模式是为了开机自启动时可以用管理员权限开启程序。

**Comment by duokebei** [comment]
我已经真全局代理成功，您的意思是，如果想开机自启也能真全局代理的话，得把服务模式才能打开对吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzgydi/clash-verge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzzgydi/clash-verge] tun模式与服务模式的问题 (Issue #134)





 
tun模式的开启要确保有管理员权限。
 
开启服务模式之后也要开tun模式，服务模式是为了开机自启动时可以用管理员权限开启程序。

**Comment by zzzgydi** [comment]
对的

**Comment by duokebei** [comment]
这个唯一的小遗憾就是需要以管理员身份启动，然后就是如果我以管理员身份启动软件，然后我再开启服务模式，那我开机自启后是不是仍然是管理员身份启动的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzgydi/clash-verge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzzgydi/clash-verge] tun模式与服务模式的问题 (Issue #134)





 
对的

**Comment by zzzgydi** [comment]
理论上，服务模式开启后，就再不需要关系权限问题

**Comment by duokebei** [comment]
好的好的，希望作者您可以搞一个群，用作反馈与交流软件方面的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzgydi/clash-verge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzzgydi/clash-verge] tun模式与服务模式的问题 (Issue #134)





 
理论上，服务模式开启后，就再不需要关系权限问题

**Comment by duokebei** [comment]
刚刚重装了系统，发现只要打开软件就立即闪退

**Comment by zzzgydi** [comment]
> 刚刚重装了系统，发现只要打开软件就立即闪退

你系统是win10吗，是的话要装webview2

**Comment by duokebei** [comment]
对的，是win10，现在已经解决。还有个问题就是，我常开了服务模式，也设置了开机自启，但是每次开机，节点就不见了，需要退出重新以管理员身份打开才行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzgydi/clash-verge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzzgydi/clash-verge] tun模式与服务模式的问题 (Issue #134)





  
刚刚重装了系统，发现只要打开软件就立即闪退
  
你系统是win10吗，是的话要装webview2

**Comment by zzzgydi** [comment]
sorry 忘了回

> 每次开机，节点就不见了

这个是配置没加载对吗
