### ISSUE TITLE
无法启动系统代理

### ISSUE THREAD

**Issue by triesc** [zzzgydi/clash-verge#135]
1、win10 ltsc 下，安装新版本，设置好订阅地址，打开系统代理选项，系统代理旁边的小问号显示 true。但是实际上并没有设置成功，需要人工打开win10的网络代理设置页面，才会生效。关闭也一样，都需要软件更改后，win10的设置页面打开才可以。
管理员身份运行，以及安装[Webview2]都无法解决问题。
2、更换clash core也失败，端口为0.
2、代理守卫的用处是？

**Comment by zzzgydi** [comment]
> 但是实际上并没有设置成功

你是怎么
没有设置成功的，在win10设置页面看的？那个设置页面的值不会实时更新的，要关掉那个设置页面再打开，才会看到变更。

> 更换clash core也失败，端口为0.

需要日志

> 代理守卫的用处是？

当你的系统代理会被一些莫名其妙的软件频繁修改的时候，就有用了

**Comment by triesc** [comment]
1、我在软件中设置后。只要我不打开win10的设置页面，永远连接不上。所以我就点开了win10的设置页面去核对，只要打开win10的界面，值就正确，就马上可以使用。重装系统，也一样复现。
2、failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)`

**Comment by triesc** [comment]
1 在使用的过程中，关闭软件的系统代理选项后，也一样可以上网。只要打开win10的系统设置页面，就不能用了。这个问题困扰了很久，不停的测试，判断是，软件设置了后，并不能后台更改系统的值，要打开界面，系统才会更改，不用人工更改系统的设置，只是需要人工打开win10的网络设置页面，才会生效。

**Comment by zzzgydi** [comment]
win10的设置是这样的情况了。这个日志错误是因为没成功启动吧，原因很多，可能是端口占用。

**Comment by triesc** [comment]
> win10的设置是这样的情况了。这个日志错误是因为没成功启动吧，原因很多，可能是端口占用。

我好像没表达清楚，你好像没理解我的意思。

不可能每次打开软件代理，要去win10下网络系统设置一次代理。然后关闭软件代理还要去win10设置一次代理吧。

**Comment by zzzgydi** [comment]
我知道你的意思，这个现象我也有发现，但我换win11后就没有这个问题了。修改代理的原理是修改注册表，这个问题应该是注册表的修改没有立刻生效。

**Comment by triesc** [comment]
> 我知道你的意思，这个现象我也有发现，但我换win11后就没有这个问题了。修改代理的原理是修改注册表，这个问题应该是注册表的修改没有立刻生效。

win10解决不了的话，我升级到11吧。谢谢回复。
