### ISSUE TITLE
软件启动崩溃

### ISSUE THREAD

**Issue by Roiyaru** [zzzgydi/clash-verge#136]
刚刚重装的Win11_22000.832，开机后安装vc++。然后安装verge，软件无法启动，查看是存放配置文件和log的目录没有生成，怀疑是这个原因。系统log看照片。
![IMG_20220726_011321](https://user-images.githubusercontent.com/36790001/180922182-9c49e3d8-f5e8-4b07-842b-0f24daa840f4.jpg)
![IMG_20220726_011415](https://user-images.githubusercontent.com/36790001/180922186-5b9ae8f2-499c-4a00-bcf2-3157e2ef024b.jpg)

**Comment by zzzgydi** [comment]
重装verge能管用不

**Comment by Roiyaru** [comment]
> 重装verge能管用不

不能，便携版也打开不了。

**Comment by zzzgydi** [comment]
理论上win11自带webview2，你看看自带的webview2还在不在

**Comment by Roiyaru** [comment]
> 理论上win11自带webview2，你看看自带的webview2还在不在

在，我去官网下载新的安装不了，说已经安装了。

**Comment by zzzgydi** [comment]
安装1.0.3版本的verge管用吗

**Comment by Roiyaru** [comment]
> 安装1.0.3版本的verge管用吗

可以用，目前正常。

**Comment by zzzgydi** [comment]
如果是在系统上第一次安装运行出现这个问题，我感觉应该是104版本的初始化目录实现逻辑有bug，我排查一下吧

**Comment by Roiyaru** [comment]
> 如果是在系统上第一次安装运行出现这个问题，我感觉应该是104版本的初始化目录实现逻辑有bug，我排查一下吧

好，知道了。

**Comment by zhongfly** [comment]
我最近在win11上运行104版本也是无法启动

**Comment by zzzgydi** [comment]
@zhongfly 可以检查一下是否成功初始化一些文件目录`~/.config/clash-verge`。如果存在也不能启动，还可以检查端口33333是否被占用。

**Comment by XiaofengdiZhu** [comment]
新安装103也无法解决 @zzzgydi

**Comment by zzzgydi** [comment]
@XiaofengdiZhu 可以检查一下33333端口是否被占用
