### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by delphinuz** [zzzgydi/clash-verge#137]
与clash.mini相比，核心是分量的，所以核心更新时，不用等可以直接套用。

1. 但不知道能否加个开关，定时(比如每1/10/30/60等分钟)进行速度测试，以方便随时切换到最快的节点。load-balance里有个 interval: ，也许可用这个时间，也符合load-balance切换的周期。

2. Connections里，能否加上使用的节点名称，方便一看就知道用哪个节点。

Proxies里的proxy detail打开后，都显示udp，应是个bug。

**Comment by betaxab** [comment]
1. 设置一个 auto 策略组，组里边的节点还是那些节点，应该会根据 auto 策略里的 interval 值自动进行延迟测试

2. 这个好，赞同添加

3. 这个 UDP 是配置文件决定的，如果配置里写了 udp: true，那么就会显示 UDP，而不说 clash 能检测到 UDP 是否可用。

**Comment by zzzgydi** [comment]
v1.1.0已经发布啦，connections页面支持yacd那种以表格展示的方式了
