### ISSUE TITLE
[Bug] 窗口拖动异常

### ISSUE THREAD

**Issue by bemarkt** [zzzgydi/clash-verge#14]
版本：v0.0.21 x64.msi
系统：Windows 11
问题：窗口拖动速度缓慢，拖不动的感觉，松开的话会自行移动到最后地点。

gif图最后几帧鼠标已经拖出去了，窗口还在赶来的路上。

![clash-verge1](https://user-images.githubusercontent.com/25723505/157042080-2b3a84a1-338b-4dc4-91ff-fe7849c8cedd.gif)

**Comment by zzzgydi** [comment]
问题还挺大，可能是设置窗口阴影和模糊效果的问题，等我搞个win11再深入debug一下。。。这个窗口在11上还有圆角，还挺好看的。

**Comment by zzzgydi** [comment]
现在的版本 v1.0.1 在win11里拖动应该不卡了

**Comment by bemarkt** [comment]
> 现在的版本 v1.0.1 在win11里拖动应该不卡了

Win11 22621 beta 测试拖动正常。
另有一个问题就是在ui中无法切换到clash的script模式，而且verge是直接修改profile中的mode。换成在verge的profiles config中存储每个profile的mode可能会更好一点。

**Comment by zzzgydi** [comment]
现在支持script模式啦
