### ISSUE TITLE
支持按键开关系统代理，TUN 模式，和不同的代理模式

### ISSUE THREAD

**Issue by yaohappiness** [zzzgydi/clash-verge#141]
能不能给这些常用的命令加上自定义快捷键的功能，类似 Clash for Windows。

或者加上命令行参数，在软件运行时支持调用，方便使用外部命令。比如 `Clash Verge --tun-mode=off`。

对于键盘党是非常实用的功能。

**Comment by zzzgydi** [comment]
v1.1.0支持热键/快捷键功能啦，可以更新一下
