### ISSUE TITLE
建议增加一个默认配置文件！

### ISSUE THREAD

**Issue by a89757** [zzzgydi/clash-verge#142]
为什么要提这个建议呢？
因为我用clash for windows 的正常配置，导入到verge之后， verge是不正常的，代理里面只显示DIRECT 和 GLOBAL，完全识别不出来代理以及规则明细，所以说还是存在json字段识别误差问题，为了省事，建议老板出一个默认配置，我们小白可以尝试修改。

**Comment by zzzgydi** [comment]
`~/.config/clash-verge/config.yaml`这个文件就是默认的文件
