### ISSUE TITLE
能否增加loopback插件

### ISSUE THREAD

**Issue by LD-KiLLer** [zzzgydi/clash-verge#144]
感谢大佬的软件first~

有个建议，能否像cfw一样的增加一个loopback插件，因为我在使用tun模式的时候，发现一些没有写到直连规则里的网址都自动走了代理（我的规则写的比较烂）导致流量暴增。但是要是不开tun模式的话uwp应用又不能走代理，所以想请大佬加个loopback插件方便下我这样的规则小白，万分感谢！

**Comment by zzzgydi** [comment]
其实你可以直接用cfw的loopback插件进行操作。

**Comment by LD-KiLLer** [comment]
额，cfw被我直接删了，实在是没有verge好用😂
我先重新下回来，搞下loop吧，感谢大佬👍👍👍

**Comment by zzzgydi** [comment]
那个插件，也应该可以单独下载的，可以找找链接。或者下了cfw之后，在应用目录里找这个插件

**Comment by zhongfly** [comment]
可以在https://www.telerik.com/fiddler/add-ons上找到，其实是fiddler的插件，但是可以独立使用
页面提供的下载地址：https://telerik-fiddler.s3.amazonaws.com/fiddler/addons/enableloopbackutility.exe

**Comment by LD-KiLLer** [comment]
感谢大佬的回复👍👍👍

**Comment by Cloud0310** [comment]
也可以使用https://github.com/Richasy/LoopbackManager.Desktop 这个开源且支持Windows11UI的uwp应用。

**Comment by PingZi-Wing** [comment]
> 



> 也可以使用https://github.com/Richasy/LoopbackManager.Desktop 这个开源且支持Windows11UI的uwp应用。

fiddler的插件版只有100K，你这个体积200M，吓尿了。正如原项目readme所言，大了亿点点😂
