### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by snakexgc** [zzzgydi/clash-verge#145]
有两个小建议，希望开发者采纳

1.增加热键，可以用过热键快速开启系统代理和关闭系统代理

2.增加更新检测，可以自动检测github上面最新的包的版本，然后进行替换，这样可以实现软件和内核的更新（v2rayn已经实现，或许可以参考）

2个小建议，希望开发者能采纳！软件做得很好，支持！

**Comment by zzzgydi** [comment]
v1.1.0已经发布啦，支持热键功能啦，第二点暂时先不考虑啦
