### ISSUE TITLE
请问支持clash-rules或者v2ray-rules-dat分流吗？

### ISSUE THREAD

**Issue by lin1123** [zzzgydi/clash-verge#146]

**Comment by Cloud0310** [comment]
这个是premium和meta都支持的吧（clash rules provider），后者请移步v2Ray。（这只是一个前端gui）

**Comment by lin1123** [comment]
> 这个是premium和meta都支持的吧（clash rules provider），后者请移步v2Ray。（这只是一个前端gui）

clash-rules规则集如何写进clash-verge配置文件？修改配置文件后还是使用不了。

**Comment by zzzgydi** [comment]
> clash-rules规则集如何写进clash-verge配置文件？

可以新建个profile写。或者导入配置。

> 修改配置文件后还是使用不了。

你是修改了哪个配置文件

**Comment by lin1123** [comment]
> > clash-rules规则集如何写进clash-verge配置文件？
> 
> 可以新建个profile写。或者导入配置。
> 
> > 修改配置文件后还是使用不了。
> 
> 你是修改了哪个配置文件

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT

像这样添加到订阅的配置文件，其他的地方都没有修改。

**Comment by lin1123** [comment]
此贴终结，配置文件没有修改全导致的。
