### ISSUE TITLE
策略组中的auto无法正常显示延迟

### ISSUE THREAD

**Issue by Cloud0310** [zzzgydi/clash-verge#148]

**Comment by Cloud0310** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/60375730/183249063-2266b8de-bde3-4f3f-89ca-4cd3f6ae0f37.png">

**Comment by zzzgydi** [comment]
你这个proxy group 是use proxy provider的，目前的测速对于proxy provider的节点是无效的，所以全error

**Comment by Cloud0310** [comment]
其次在使用多个相同命名节点但连接密码不同的机场多个套餐整合订阅链接时，仅显示一个套餐中的节点，而不是与cfw，cfa，clash premium core的处理方法：### 在相同命名节点后加上数字 一致。
可能是此情况为个例，但是删除配置文件后重新导入也遇到相同情况。

**Comment by Cloud0310** [comment]
> 

这样吗，能否尽快给与支持，我现在尝试使用external control pannel试试看。

**Comment by zzzgydi** [comment]
正在加web ui的跳转支持，这样就可以用别的在线面板了

**Comment by Cloud0310** [comment]
yacd面板显示正常，应该是没有做这个延迟的反馈？
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60375730/183249281-772b55f8-d89d-47e4-a6d1-352516468ea4.png">

**Comment by Cloud0310** [comment]
> 正在加web ui的跳转支持，这样就可以用别的在线面板了

谢谢作者，具体实现思路是本地跑一个web UI吗，还是调用在线托管的UI？
在线托管UI由于 
1.在大陆网络环境下连接不畅 
2.chromium/firefox目前出于安全原因阻止了其对本地的连接，可能需要打开chrome://flags/#block-insecure-private-network-requests
<img width="542" alt="image" src="https://user-images.githubusercontent.com/60375730/183249403-9e8ea4af-1f94-41dc-89a9-f5a2972c46ff.png">
（Firefox同理）选项才能正常使用

**Comment by Cloud0310** [comment]
现在这个urltest的情况是没法正常显示，但是可以正常使用，希望在将来的版本中进行支持与修护，希望clash verge越做越好，成为一个轻量且优质的clash GUI前端。

**Comment by zzzgydi** [comment]
在线ui都只是访问本地的http服务而已，没有限制吧。

**Comment by Cloud0310** [comment]
局域网上的有，我之前用软路由遇到过这个没法链接的情况，最后调试才发现问题。
________________________________

**Comment by zzzgydi** [comment]
局域网才有的话，对操作本机起的clash服务没啥影响
