### ISSUE TITLE
软件启动失败原因排查

### ISSUE THREAD

**Issue by zzzgydi** [zzzgydi/clash-verge#153]
### 1. 端口33333/33331被占用

原因：程序采用端口占用的方式实现程序单例和拉起已开启的程序。
更新：v1.1.0 之后将默认使用33331端口，也支持修改默认端口。

### 2. 初始化config目录失败

原因：程序将在`～/.config/clash-verge`目录下初始化所需的配置文件。可能因为当前用户在该目录下新建目录/新建文件权限不足导致失败（也可能因为别的未知原因）。v1.0.4及以下版本的会因此问题启动失败（代码实现问题，v1.0.5将修复）

### 3. 系统WebView2问题

原因：程序依赖系统的Webview2，当Webview2不存在时将启动失败。

Windows WebView2 Download：https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by XiaofengdiZhu** [comment]
我发现Goodsync使用的端口是33333，冲突了（然后我直接把Goodsync卸了

**Comment by mcxiaoke** [comment]
为啥最新版还没修复这个问题，强行占用端口可不好，单例检测建议用NamedPipe或者UDP

**Comment by mcxiaoke** [comment]
而且本地build失败

error: failed to run custom build command for `rquickjs-sys v0.1.6`

Caused by:
  process didn't exit successfully: `clash-verge\src-tauri\target\release\build\rquickjs-sys-2daffe600c76db7c\build-script-build` (exit code: 101)

  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', github.com-1ecc6299db9ec823\rquickjs-sys-0.1.6\build.rs:136:10

**Comment by XiaofengdiZhu** [comment]
> 而且本地build失败
> 
> error: failed to run custom build command for `rquickjs-sys v0.1.6`
> 
> Caused by: process didn't exit successfully: `clash-verge\src-tauri\target\release\build\rquickjs-sys-2daffe600c76db7c\build-script-build` (exit code: 101)
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', github.com-1ecc6299db9ec823\rquickjs-sys-0.1.6\build.rs:136:10

和我一样的报错，已顺利解决#154

**Comment by XiaofengdiZhu** [comment]
> 而且本地build失败
> 
> error: failed to run custom build command for `rquickjs-sys v0.1.6`
> 
> Caused by: process didn't exit successfully: `clash-verge\src-tauri\target\release\build\rquickjs-sys-2daffe600c76db7c\build-script-build` (exit code: 101)
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', github.com-1ecc6299db9ec823\rquickjs-sys-0.1.6\build.rs:136:10

和我一样的报错，已顺利解决#154

**Comment by yimozi** [comment]
> 我发现Goodsync使用的端口是33333，冲突了（然后我直接把Goodsync卸了

我也发现了，不过Goodsync是必须要用的，所以只能期待大佬修复了。

**Comment by zzzgydi** [comment]
v1.1.0已经发布，现在默认端口改成了33331，支持在配置文件中修改默认端口，`~/.config/verge.yaml`的`app_singleton_port`值改为想要的端口号就行

**Comment by moonlune** [comment]
用的是Portable版本，发现如果加计划任务启动，启动失败，但是如果写个启动Loader来启动 Clash Verge ，反而正常。有时间需要找下原因。

**Comment by zjxuzhj** [comment]
在公司的windows上这几个我都排查了，还是打不开，就是任务栏有图标，进程有，但是没有界面

**Comment by beyond667** [comment]
@zjxuzhj  我公司电脑跟你一样 也是打开只有图标，也有进程，就是没界面，卸载重装也一样。win11

**Comment by zzzgydi** [comment]
Windows系统，任务栏有图标，但是界面出不来，或者点了没反应。

这种情况可能是Webview2有问题，可以尝试重装Webview2或者在设置-应用程序管理那里点修复

**Comment by CHENHUI-X** [comment]
> 

没用，放弃治疗了。还是用原本的clash吧，之前看这个界面好看，还是算了

**Comment by Dykro** [comment]
Windows如果出现无UI并且中断报错error Command failed with exit code 134.的问题建议尝试卸载node.js，并尝试在nodejs官网安装18.15.0版本。*安装时勾选自动安装必要的工具。经测试，UI恢复正常显示。 @zzzgydi

**Comment by zjxuzhj** [comment]
@beyond667 @CHENHUI-X  排查下公司电脑是否安装监控软件 IP guard

**Comment by zzzgydi** [comment]
电脑有装IP Guard的解决方案：https://github.com/zzzgydi/clash-verge/issues/717

**Comment by zlusc** [comment]
1.3.6安装在debian 12上面无法启动，也没有错误提示，是什么问题？
