### ISSUE TITLE
ubuntu中设置规则模式，走的却是全局代理

### ISSUE THREAD

**Issue by pujx233** [zzzgydi/clash-verge#155]
设置规则模式下依然可以正常访问bilibili港澳台番剧，才发现走的是全局代理，这种情况应该怎么解决？

**Comment by pujx233** [comment]
用switchomega插件解决了，但是不明白为啥会出现这种情况，windows使用一切正常

**Comment by zzzgydi** [comment]
可以单跑clash核看看是否正常
