### ISSUE TITLE
退出软件后无法正常浏览网页

### ISSUE THREAD

**Issue by TwooSix** [zzzgydi/clash-verge#157]
提示无法连接至代理服务器
甚至先打开软件，关闭系统代理，再退出软件，也无法正常上网，系统win11。
观察了一下系统代理情况，软件开启时，关闭系统代理模式，能正常关闭系统代理，但右键quit软件后，系统代理又变成开启的情况了，不知道怎么回事。

**Comment by TwooSix** [comment]
手动关闭代理后正常了……应该是关闭软件后会恢复原状态？我也不知道为什么我的系统代理是开启状态的

**Comment by zzzgydi** [comment]
退出程序会恢复原来的系统代理设置

**Comment by TwooSix** [comment]
知道为什么会默认在开启状态了，当开着软件重启电脑的时候，电脑再开机时仍保持着代理开启的状态，这时候无论怎么关闭软件都无法正常关闭系统代理的状态。

**Comment by zzzgydi** [comment]
可以在系统设置——网络和internet——代理——手动设置代理——编辑，关闭代理设置。

后面我优化一下代理设置这段逻辑。
