### ISSUE TITLE
Windows自动更新问题

### ISSUE THREAD

**Issue by ccyuyzs** [zzzgydi/clash-verge#162]
Windows下在**非管理员**用户下使用自动更新，除了重启一次软件什么都不做

**Comment by zzzgydi** [comment]
Win 11 非管理员 复现这个问题，暂时不知道咋搞，只能手动重新安装新版了

**Comment by moranno** [comment]
Win 11管理员用户，用非Administer模式运行Verge，点击更新后也不行（除了重启一次软件什么都不做）
管理员模式运行Verge暂未测试。

**Comment by moranno** [comment]
> 看到1.0.5修复Issues了

没看到1.0.5修复更新的问题呀？

**Comment by zzzgydi** [comment]
> 没看到1.0.5修复更新的问题呀？

自动更新失败，是1.0.4版本的问题。所以1.0.5有没有问题，得等1.0.6发的时候才能知道。

不过1.0.5用的tauri版本和1.0.4是一样的，我估计也是有问题的。

**Comment by zzzgydi** [comment]
> 👀看起来得修复了 只要不以管理员权限运行就更新不了

1.0.6 更新了tauri版本，应该之后就没这个问题了
