### ISSUE TITLE
[bug] Meta core subscription dose not support v2rayn style schema

### ISSUE THREAD

**Issue by TDL3** [zzzgydi/clash-verge#164]
according to the meta core [wiki page](https://docs.metacubex.one/function/proxy), proxy-provider support subscription schema used by clients like v2rayn, shadowrocket.

However when I switch to meta core in the clash-verge settings and try to use a said schema subscription link, I got `the remote profile data is invalid yaml`

**Comment by zzzgydi** [comment]
You can visit your subscription link directly in your browser and check whether its content is in yaml format.

**Comment by TDL3** [comment]
no its not, it uses this format/schema [v2rayn share link ref](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))

**Comment by zzzgydi** [comment]
> Proxy-Provider支持普通订阅：proxy-provider的url参数支持直接解析V2rayN等客户端使用的普通订阅，无需使用SubConverter之类的订阅转换工具。

According to the meta core wiki, only the proxy-provider url param supports the v2rayn format. This is not the same thing as the app's subscription link. You can set the link in the proxy-provider.

**Comment by TDL3** [comment]
indeed proxy-provider works, but if I convert the v2rayn style payload to clash format using [subconverter](https://github.com/tindy2013/subconverter) and put the converted link in the subscription field it works just fine. Is this the intended behavior?

**Comment by zzzgydi** [comment]
yeah, the subscription link must be in yaml format.

**Comment by TDL3** [comment]
ahh, I get it, so the profile url feature works the same way as [clash for windows](https://github.com/Fndroid/clash_for_windows_pkg), thanks for your time!
