### ISSUE TITLE
TUN模式下，BT下载频繁报错。

### ISSUE THREAD

**Issue by lin1123** [zzzgydi/clash-verge#168]
tun模式下日志内，连接会一直不停的报错。
[TCP] dial DIRECT (match RuleSet(Download)) to tracker.publicbt.com:80 error: dial tcp4: lookup invalid IP: no such host
[TCP] dial 🐟 漏网之鱼 (match Match()) to 104.143.10.186:8000 error: dial tcp4 192.168.50.176:0->104.143.10.186:8000: connectex: No connection could be made because the target machine actively refused it.
08-21 01:23:13WARNING[TCP] dial DIRECT (match GeoIP(CN)) to 223.166.104.193:17520 error: never touched

**Comment by zzzgydi** [comment]
可以先检查一下运行生成的配置有没有问题
