### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by WestXu** [zzzgydi/clash-verge#17]
Thanks. Cool project.

**Comment by zzzgydi** [comment]
It had been released for Windows and macOS. https://github.com/zzzgydi/clash-verge/releases

**Comment by WestXu** [comment]
Oh sorry for missing that. Somehow the release tab is not shown on the top of the repo page.

**Comment by zzzgydi** [comment]
I added it to the readme, thanks for reminding.
