### ISSUE TITLE
tun模式下vless协议开启UDP会很慢

### ISSUE THREAD

**Issue by yang05051** [zzzgydi/clash-verge#171]
在vless节点下，添加`udp: true`, clash接管了UDP流量之后会非常慢，DNS无论选择redir-host并使用嗅探器Sniffer，或是fake-ip都是这样

不接管UDP流量（UDP流量不走代理，直连）速度正常

以上结果于澳门本地的网络环境得出，不存在运营商UDP阻断

客户端启用了服务模式

**Comment by yang05051** [comment]
除节点以外的配置文件如下：
![Screenshot_20220822-233000_OneDrive.jpg](https://user-images.githubusercontent.com/31024419/185959980-628597d3-6b99-4893-8ab7-882c0b33a85d.jpg)

**Comment by yang05051** [comment]
经我观察，日志没有任何异常

**Comment by zzzgydi** [comment]
可以在设置页的运行配置/Runtime Config那里，查看生成的配置是否符合预期，再判断

**Comment by yang05051** [comment]
> 可以在设置页的运行配置/Runtime Config那里，查看生成的配置是否符合预期，再判断

确认过了，符合预期

**Comment by zzzgydi** [comment]
符合预期的话，clash的问题可以反馈到clash的仓库那里

**Comment by yang05051** [comment]
已经反馈了 👌
