### ISSUE TITLE
请问1.05更新的 webui 管理要怎么使用呢

### ISSUE THREAD

**Issue by buluw** [zzzgydi/clash-verge#175]
有没有相关文档可以查看

**Comment by zzzgydi** [comment]
直接在web ui弹窗里新建添加web ui的url链接就行，比如可以添加下面这些

- https://clash.razord.top/?host=%host&port=%port&secret=%secret#/proxies
- https://yacd.haishan.me/?host=%host&port=%port&secret=%secret

也可以添加别的自己喜欢的面板

**Comment by buluw** [comment]
感谢，可以使用了。
还有一个问题，现在只能本机使用webui管理，配置文件 config.yaml 中将 external-controller: "127.0.0.1:9090" 改成 
external-controller: "0.0.0.0:9090" 后就无法正常使用meta核心了
<img width="978" alt="Snipaste_2022-08-29_17-30-31" src="https://user-images.githubusercontent.com/45087912/187171274-ef3d48eb-4f50-411d-913b-822b0e752b11.png">

**Comment by zzzgydi** [comment]
external-controller的域名写成0.0.0.0是会导致一些问题，你可以写成`:9090`。

**Comment by buluw** [comment]
写成`:9090`可以运行，本地可以打开。
就是局域网依然无法连通
<img width="1289" alt="Snipaste_2022-08-29_20-03-07" src="https://user-images.githubusercontent.com/45087912/187196980-62b40aed-b383-4406-b73f-9a52d29f87f3.png">

**Comment by buluw** [comment]
改成`:9090`之后可以正常运行，本地可以打开
但局域网依旧无法连通
<img width="1293" alt="Snipaste_2022-08-29_20-06-18" src="https://user-images.githubusercontent.com/45087912/187197483-98e41385-cf7a-4c3b-86e8-690f6e74c129.png">

**Comment by zzzgydi** [comment]
开启allow lan再试试？

**Comment by zzzgydi** [comment]
看起来要修复一下0.0.0.0的问题

**Comment by zzzgydi** [comment]
现在已经修复external-controller是0.0.0.0的问题了

**Comment by buluw** [comment]
nice，好使了
局域网控制测试下来可以用的是
http://clash.metacubex.one/

clash.razord.top和yacd.haishan.me这两个面板是只能连本地~
