### ISSUE TITLE
关于 linux 兼容性问题

### ISSUE THREAD

**Issue by squallliu** [zzzgydi/clash-verge#177]
建议使用 ubuntu 18.04 来构建，以保证 libc 等库的兼容性
https://tauri.app/v1/guides/distribution/linux/#limitations

**Comment by zzzgydi** [comment]
现在的release是用ubuntu 20.04构建的，这个在18.04系统上是会有问题了吗。我看到github action的runner image今年12月就不支持ubuntu-18.04了

**Comment by squallliu** [comment]
> 现在的release是用ubuntu 20.04构建的，这个在18.04系统上是会有问题了吗。我看到github action的runner image今年12月就不支持ubuntu-18.04了

深度系统跑不了就是因为libc最高只到2.28，clash-verge要求最低2.29

**Comment by zzzgydi** [comment]
v1.0.6 我尝试用ubuntu 18.04去构建了，可以试试

**Comment by squallliu** [comment]
> v1.0.6 我尝试用ubuntu 18.04去构建了，可以试试

没问题你，这贴就是用clash-verge回的

**Comment by zzzgydi** [comment]
现在是可以在deepin上用了吗

**Comment by squallliu** [comment]
> 现在是可以在deepin上用了吗

是的

**Comment by gggin** [comment]
大佬 遇到一点问题
1. ubuntu 18.04 无法跑最新的代码 但是自行编译还是精力有限
2. 我使用 v1.0.6 版本，确实好使了，但是 v1.0.6 版本有它自己的问题，就卡住了，能不能持续集成加一个 18.04 的系统？

v1.0.6 的问题
https://github.com/zzzgydi/clash-verge/issues/208

**Comment by zzzgydi** [comment]
> ubuntu 18.04 无法跑最新的代码 但是自行编译还是精力有限

修复了一下linux的问题，现在的最新代码可以了

**Comment by CyanideCentral** [comment]
> > ubuntu 18.04 无法跑最新的代码 但是自行编译还是精力有限
> 
> 修复了一下linux的问题，现在的最新代码可以了

Please put out a new release soon! 这对Ubuntu 18.04用户很重要，谢谢

**Comment by idnsunset** [comment]
Bump!  The latest 1.3.1 version does not even work on Ubuntu 20.04 due to glibc version limit. Ubuntu 20.04 LTS is still under maintenance and being used widely. Really expect  20.04 to be supported, or provide a docker version.
