### ISSUE TITLE
怎么开启Mux

### ISSUE THREAD

**Issue by yang05051** [zzzgydi/clash-verge#178]
在节点配置添加了 `mux: true`，Runtime Config也能看到（如图），但感觉没有真正开启，节点测试延迟仍然没有降低，请问怎么开启Mux呢？
![image](https://user-images.githubusercontent.com/31024419/187149439-0f4575f7-2934-4c67-80d3-12169fa45baa.png)

**Comment by zzzgydi** [comment]
我看只有ss支持mux吧，vless没看到有这个字段 https://docs.metacubex.one/function/proxy/vless

**Comment by yang05051** [comment]
好的，谢谢哈

**Comment by yang05051** [comment]
但Shadowrocket可以识别到Mux

**Comment by zzzgydi** [comment]
这是clash，不是shadowrocket，如果对vless配置有啥建议，你可以到这个仓库反馈 https://github.com/MetaCubeX/Clash.Meta
