### ISSUE TITLE
allowlan不可用

### ISSUE THREAD

**Issue by yiiyahui** [zzzgydi/clash-verge#179]
allowlan无效。
GUI下打开或关闭共享开关，config的参数并不会作出相应的变化.true or false。
同局域网下。P核心共享无效。手机测试QUANX共享可用。

另外，貌似M核心下。连接服务器有问题。表现为，初次配置成功连接后正常，但设备重启后。连接失败。不知道是不是TUN的问题

**Comment by zzzgydi** [comment]
设置页的allow lan和ipv6的开启和关闭，不会实时同步到运行配置中。

开关这俩功能的时候，切到别的页面再切回设置页（一般来说都不用切），如果这个选项的开关状态符合预期，那就是没有问题的，因为这个值的状态是直接从clash接口拿的。
