### ISSUE TITLE
订阅导入成功 Proxies界面没有节点

### ISSUE THREAD

**Issue by screaminrain** [zzzgydi/clash-verge#18]
![111](https://user-images.githubusercontent.com/99682059/157580412-00e30eb3-d868-48bf-8d55-57cb81cdb1ce.png)
![222](https://user-images.githubusercontent.com/99682059/157580428-29394816-cb1d-4b29-ac22-749c7aab484b.png)
是我有什么东西没安装吗  试了好几个订阅都没有显示节点

**Comment by zzzgydi** [comment]
方便把你配置提供一下吗，proxies可以删掉，然后proxy-groups也可以删减，任何隐私相关的字段都可以用*手动打码。另外log日志也可以提供一下。以上均仅用于debug。

**Comment by screaminrain** [comment]
#!MANAGED-CONFIG https://pengui.one/link/wKZUuKJgFsSy9JGj?config=clash

#---------------------------------------------------#
## Last Update：2022-03-10 11:01:02
#---------------------------------------------------#

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 'tcp://223.5.5.5'
  fallback:
    - 'tls://223.5.5.5:853'
    - 'https://223.5.5.5/dns-query'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4


是这样吗 底下都是Proxy了 不是的话我要不把订阅链接给你吧 https://pengui.link/link/wKZUuKJgFsSy9JGj?config=clash

**Comment by zzzgydi** [comment]
你的回复我先删啦，你这个链接属于比较隐私的东西啦，最好不要这样发出来哈。

**Comment by zzzgydi** [comment]
已经查到是什么问题啦，字段名大小写的问题，后面会处理一下的，感谢反馈。

**Comment by screaminrain** [comment]
> 已经查到是什么问题啦，字段名大小写的问题，后面会处理一下的，感谢反馈。

好的蟹蟹 没事反正剩2天 我也不用
