### ISSUE TITLE
GUI调整端口时显示的bug

### ISSUE THREAD

**Issue by Xyfuture** [zzzgydi/clash-verge#181]
在"设置"里调整"端口设置"中，输入新的端口号后，虽然clash的配置成功更改了，同时右上角toast设置成功，但是“端口设置”那个位置仍旧会跳变回原来的端口号。
比如现在端口号 7890 ，输入1080，提示成功，然后立马又回到了7890(输入1080后敲不敲回车一个样)，实际上clash 的 mix port确实变了

**Comment by Xyfuture** [comment]
好像有时侯clash的端口也没调整成功，只是system proxy的端口改了，稍微有点混乱

**Comment by Xyfuture** [comment]
问题解决了，似乎当时我跑了两个clash core，相互冲突了，问题貌似不太好复现，参考意义比较差

**Comment by zzzgydi** [comment]
其实这块还是没做好，我改改输入框触发方式吧
