### ISSUE TITLE
无法保存窗口位置/大小

### ISSUE THREAD

**Issue by anylones** [zzzgydi/clash-verge#185]
在一台电脑上每次启动都是在屏幕左边位置出现界面，但位置并不固定，且窗口大小无法保存。
在另一台电脑上，不知道为什么每次启动都是界面没入左下角，得手动拖到屏幕中间才能看到完整界面。
请问这个该如何解决？或是软件不支持这个选项？

**Comment by zzzgydi** [comment]
暂时不能保存窗口大小和位置，我改成默认居中吧
