### ISSUE TITLE
Cannot set system proxy on m1 pro mbp

### ISSUE THREAD

**Issue by oliverdding** [zzzgydi/clash-verge#186]
设置系统代理失效，需要手动打开设置开关

**Comment by zzzgydi** [comment]
日志有没有什么错误信息

**Comment by zzzgydi** [comment]
你这个图上显示现在已经开启了系统代理，端口7890

**Comment by zzzgydi** [comment]
预期行为是，你打开或者关闭System Proxy：如果设置成功，会和黑色提示框里的设置状态一致。如果设置失败了，就要看看log文件里（设置页最下面有个open logs dir，打开的目录里最下面的文件是最新的）有没有记录到调用出错的原因。

另外如果设置失败，你手动在系统的网络偏好设置里更改了，那么黑色提示框里显示成图上这样，也是合理行为。因为黑色提示框里的内容是同步系统当前的设置，而不是软件的设置。

**Comment by zzzgydi** [comment]
设备选错了，对于mac的代理都设置到wifi那里了。

**Comment by zzzgydi** [comment]
确实应该整一个切换，有空再加一下

**Comment by zzzgydi** [comment]
v1.1.0支持自动检测网络出口设备进行设置系统代理啦

**Comment by sysongyi** [comment]
你好，我的MacOS 使用最新V1.3.3版本，但“系统代理”不能检测出网络出口。
