### ISSUE TITLE
软件不显示代理节点，之后打不开

### ISSUE THREAD

**Issue by Xaiver97** [zzzgydi/clash-verge#190]
Ubuntu22.04，软件版本1.0.6，之前一直用AppImage的版本。今天手动配置了一下系统代理，clash-verge就不显示代理节点了，配置改回自动clash也没好。clash配置界面端口也一直是0，改了也没用。
之后下载了deb的版本安装，无法打开。终端打开报错`clash-verge: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
但是我系统已经安装了openssl，按道理不会出现这个错误的呀，而且之前一段时间都正常使用。希望开发者大大能帮忙看看啥情况，感谢！

**Comment by zzzgydi** [comment]
1.0.6换了构建的系统版本，你可以先回退到1.0.5看看能不能用。

**Comment by Xaiver97** [comment]
感谢！1.0.5版本使用没问题
