### ISSUE TITLE
在manjaro下，使用deb转换的包和appimage均遇到导入但没有节点的状况

### ISSUE THREAD

**Issue by Ktsuruta196** [zzzgydi/clash-verge#191]

**Comment by zzzgydi** [comment]
能导入但没节点，需要看看配置是否格式正确

**Comment by ricky217** [comment]
> 能导入但没节点，需要看看配置是否格式正确

我在fedora下有同样情况，用的appimage。配置是正确的，同样的配置文件在verge的windows客户端就可以正常使用。有如下错误报告：
failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error: Connection refused (os error 111)`

**Comment by zzzgydi** [comment]
@ricky217 你这个是因为clash内核启动失败或者clash的external-controller端口（你的是9090端口）被占用了。

clash启动失败有可能是用的执行文件不合适，verge默认带的是 https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz。
可以先尝试运行这个核心是否正常，不正常的话就需要手动替换符合系统版本的核心。

**Comment by ricky217** [comment]
> @ricky217 你这个是因为clash内核启动失败或者clash的external-controller端口（你的是9090端口）被占用了。
> 
> clash启动失败有可能是用的执行文件不合适，verge默认带的是 [https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz。](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz%E3%80%82) 可以先尝试运行这个核心是否正常，不正常的话就需要手动替换符合系统版本的核心。

fedora 36
1.lsof查看端口，9090没有被占用。
2.下载clash-linux-amd64-2022.08.26.gz运行，运行正常。
3.修改~/.config/clash/config.yaml为自己使用的配置文件（subconverter生成的，在win下和安卓手机上均正常使用），运行clash-linux-amd64-2022.08.26.gz，运行正常可以代理访问。
clash-verge依然不行。

**Comment by kands-code** [comment]
我遇到了类似情况，导入配置后节点无法显示，但是可以代理

![image](https://user-images.githubusercontent.com/59006329/191890451-ebd96232-d81b-4428-993c-089aae00277f.png)

我使用的是 appimage 版本，在软件 log 中看到的可能有关联的是 

```text
xdg-mime: no method available for querying MIME type of '/home/kands/.config/clash-verge' (exit status: 3)
```

在终端运行发现

```text
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - tokio-thread started
2022-09-23 12:13:44 - failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error: 拒绝连接 (os error 111)`
2022-09-23 12:13:44 - [clash]: +socks) listening addr=127.0.0.1:7890
2022-09-23 12:13:44 - [clash]: =127.0.0.1:9090
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
unknown keyword:
  localhost;127.*;10.*;192.168.*;<local>
  ^^^^^^^^^                             
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
2022-09-23 12:13:45 - [clash]: patible provider name=✈️Telegram
2022-09-23 12:13:45 - [clash]: patible provider name=⚓️其他流量
2022-09-23 12:13:45 - [clash]: patible provider name=🔰国外流量
2022-09-23 12:13:45 - [clash]: patible provider name=🚀直接连接
2022-09-23 12:13:45 - [clash]: patible provider name=🍎苹果服务
2022-09-23 12:13:45 - [clash]: patible provider name=🎬哔哩哔哩
2022-09-23 12:13:45 - [clash]: patible provider name=🎬Youtube
2022-09-23 12:13:45 - [clash]: patible provider name=🎬国外媒体
2022-09-23 12:13:45 - [clash]: patible provider name=🎬Netflix
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/usr/lib/gio/modules/libgioenvironmentproxy.so: undefined symbol: g_uri_is_valid
Failed to load module: /usr/lib/gio/modules/libgioenvironmentproxy.so
/tmp/.mount_clash-Ss795R/usr/lib/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
```

但是相关依赖我应该是满足了的

![image](https://user-images.githubusercontent.com/59006329/191891134-d05292a0-cacd-4e27-aee0-d298659b28bd.png)

**Comment by kands-code** [comment]
能够正常代理, 只是无法选择节点什么的

![image](https://user-images.githubusercontent.com/59006329/191891637-01928e2c-0e49-4546-9e04-489326f2375a.png)

- 运行环境 archlinux, 5.19.10-zen1-1-zen
- Rust 通过 rustup 安装rustc 1.66.0-nightly
- node 通过 pacman 安装, v18.9.0
- local/webkit2gtk 2.38.0-2

**Comment by zzzgydi** [comment]
@kands-code 你可以访问这个看看 https://yacd.haishan.me/?host=127.0.0.1&port=9090

**Comment by kands-code** [comment]
@zzzgydi 通过网站可以正常看到节点并操作

![image](https://user-images.githubusercontent.com/59006329/191963974-bf4b8be3-32c4-4387-bf86-249ebdc175e9.png)

为什么在软件内无法正常显示呢？

我不懂 tauri 和 clash，我自己无法排查错误，抱歉，请问需要什么信息吗？

**Comment by valig5** [comment]
> > @ricky217 你这个是因为clash内核启动失败或者clash的external-controller端口（你的是9090端口）被占用了。
> > clash启动失败有可能是用的执行文件不合适，verge默认带的是 [https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz。](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz%E3%80%82) 可以先尝试运行这个核心是否正常，不正常的话就需要手动替换符合系统版本的核心。
> 
> fedora 36 1.lsof查看端口，9090没有被占用。 2.下载clash-linux-amd64-2022.08.26.gz运行，运行正常。 3.修改~/.config/clash/config.yaml为自己使用的配置文件（subconverter生成的，在win下和安卓手机上均正常使用），运行clash-linux-amd64-2022.08.26.gz，运行正常可以代理访问。 clash-verge依然不行。

我也是fedora36，我自己编译安装完美运行，可能是打包的问题。看之前的issue作者提到过他是在ubuntu 20.04打包的，在20.04用就没问题，到了22.04就打不开了

**Comment by kands-code** [comment]
@zzzgydi 抱歉打扰，但是我尝试自己编译打包后 得到了一个 appimage 包，这个包是可以正常显示的

![image](https://user-images.githubusercontent.com/59006329/192079038-400362c8-cc98-4748-8229-70c49873eea7.png)

而从release下载的appimage包却不行，不清楚缘由，是否是release打包存在问题呢？

> PS: 我在尝试编译打包时，遇到了
>
> ```
> Error A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.
> ```
>
> 的错误，但是 appimage 包仍然正常生成了，而且可以正常使用

**Comment by ricky217** [comment]
> > > @ricky217 你这个是因为clash内核启动失败或者clash的external-controller端口（你的是9090端口）被占用了。
> > > clash启动失败有可能是用的执行文件不合适，verge默认带的是 [https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz。](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz%E3%80%82) 可以先尝试运行这个核心是否正常，不正常的话就需要手动替换符合系统版本的核心。
> > 
> > 
> > fedora 36 1.lsof查看端口，9090没有被占用。 2.下载clash-linux-amd64-2022.08.26.gz运行，运行正常。 3.修改~/.config/clash/config.yaml为自己使用的配置文件（subconverter生成的，在win下和安卓手机上均正常使用），运行clash-linux-amd64-2022.08.26.gz，运行正常可以代理访问。 clash-verge依然不行。
> 
> 我也是fedora36，我自己编译安装完美运行，可能是打包的问题。看之前的issue作者提到过他是在ubuntu 20.04打包的，在20.04用就没问题，到了22.04就打不开了

感谢， 我试着编译过，但是出错。nodejs我不会，不知道怎么编译解决的？

  VITE v3.0.9  ready in 265 ms

  ➜  Local:   http://127.0.0.1:3000/
  ➜  Network: use --host to expose
/home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:1356
        return callback(new Error(error), null);
                        ^

Error: The service was stopped: write EPIPE
    at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:1356:25
    at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:678:9
    at afterClose (/home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:656:7)
    at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:2075:11
    at onwriteError (node:internal/streams/writable:415:3)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
       Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zzzgydi** [comment]
@kands-code 你这个打包错误是因为没有私钥导致的，不影响自己使用。

**Comment by kands-code** [comment]
> > > > @ricky217 你这个是因为clash内核启动失败或者clash的external-controller端口（你的是9090端口）被占用了。
> > > > clash启动失败有可能是用的执行文件不合适，verge默认带的是 [https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz。](https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.08.26.gz%E3%80%82) 可以先尝试运行这个核心是否正常，不正常的话就需要手动替换符合系统版本的核心。
> > > 
> > > 
> > > fedora 36 1.lsof查看端口，9090没有被占用。 2.下载clash-linux-amd64-2022.08.26.gz运行，运行正常。 3.修改~/.config/clash/config.yaml为自己使用的配置文件（subconverter生成的，在win下和安卓手机上均正常使用），运行clash-linux-amd64-2022.08.26.gz，运行正常可以代理访问。 clash-verge依然不行。
> > 
> > 
> > 我也是fedora36，我自己编译安装完美运行，可能是打包的问题。看之前的issue作者提到过他是在ubuntu 20.04打包的，在20.04用就没问题，到了22.04就打不开了
> 
> 感谢， 我试着编译过，但是出错。nodejs我不会，不知道怎么编译解决的？
> 
> VITE v3.0.9 ready in 265 ms
> 
> ➜ Local: http://127.0.0.1:3000/ ➜ Network: use --host to expose /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:1356 return callback(new Error(error), null); ^
> 
> Error: The service was stopped: write EPIPE at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:1356:25 at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:678:9 at afterClose (/home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:656:7) at /home/mytest/gitfiles/clash-verge/node_modules/esbuild/lib/main.js:2075:11 at onwriteError (node:internal/streams/writable:415:3) at processTicksAndRejections (node:internal/process/task_queues:85:21) Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

编译还需要 Rust 环境，你这看起来是缺少 Rust 环境，没找到 `cargo` 这个命令

**Comment by kands-code** [comment]
@zzzgydi 好的，谢谢回复

**Comment by zzzgydi** [comment]
@ricky217 你这个应该是没安装rust环境，可以执行这个安装一下，`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by ricky217** [comment]
@zzzgydi @kands-code 感谢，安装环境后编译完毕。确实没有那些问题了。

**Comment by valig5** [comment]
> @zzzgydi 抱歉打扰，但是我尝试自己编译打包后 得到了一个 appimage 包，这个包是可以正常显示的
> 
> ![image](https://user-images.githubusercontent.com/59006329/192079038-400362c8-cc98-4748-8229-70c49873eea7.png)
> 
> 而从release下载的appimage包却不行，不清楚缘由，是否是release打包存在问题呢？
> 
> > PS: 我在尝试编译打包时，遇到了
> > ```
> > Error A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 的错误，但是 appimage 包仍然正常生成了，而且可以正常使用

我猜测是由于ubuntu 22.04和fedora的openssl 版本更新到了3.0.5，而ubuntu 20.04 archlinux等发行版的openssl还在1.1。然后开发者是用的ubuntu 20.04 所以导致编译出来的二进制不能兼容新的openssl

**Comment by kands-code** [comment]
> > @zzzgydi 抱歉打扰，但是我尝试自己编译打包后 得到了一个 appimage 包，这个包是可以正常显示的
> > ![image](https://user-images.githubusercontent.com/59006329/192079038-400362c8-cc98-4748-8229-70c49873eea7.png)
> > 而从release下载的appimage包却不行，不清楚缘由，是否是release打包存在问题呢？
> > > PS: 我在尝试编译打包时，遇到了
> > > ```
> > > Error A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.
> > > ```
> > >
> > > 的错误，但是 appimage 包仍然正常生成了，而且可以正常使用
> 
> @kands-code 我猜测是由于ubuntu 22.04和fedora的openssl 版本更新到了3.0.5，而ubuntu 20.04 archlinux等发行版的openssl还在1.1。然后开发者是用的ubuntu 20.04 所以导致编译出来的二进制不能兼容新的openssl

可是我是 archlinux 来的，如果开发者是 ubuntu20.04，还在使用 openssl-1.1 的话，我应该是可以正常使用的，我是界面显示问题，软件本身，或者说代理功能我这里一直是正常的，我怀疑你是回复错人了

**Comment by zzzgydi** [comment]
可以尝试最新版v1.2.0，已经更新了tauri版本

**Comment by ricky217** [comment]
> 可以尝试最新版v1.2.0，已经更新了tauri版本

感谢,1.2.0版本在我这里运行正常.
