### ISSUE TITLE
win11右键退出后无法正常上网，需要清除代理

### ISSUE THREAD

**Issue by taswsz** [zzzgydi/clash-verge#192]

**Comment by zzzgydi** [comment]
下个版本优化

**Comment by zzzgydi** [comment]
可以尝试一下最新版本

**Comment by Curious-r** [comment]
> 可以尝试一下最新版本

主动退出后系统代理没关闭的问题解决了
但如果没退出软件，直接重启系统，这样系统代理还是开启的，上不了网，必须打开C.V或者手动关闭代理

**Comment by taswsz** [comment]
> 可以尝试一下最新版本
感谢，已解决

**Comment by Curious-r** [comment]
> > 可以尝试一下最新版本
> 
> 主动退出后系统代理没关闭的问题解决了 但如果没退出软件，直接重启系统，这样系统代理还是开启的，上不了网，必须打开C.V或者手动关闭代理

系统关机的时候会自动关闭运行的软件，希望能在这种情况下也添加清除代理的动作
