### ISSUE TITLE
希望提供archlinux的安装包

### ISSUE THREAD

**Issue by mdogwoop** [zzzgydi/clash-verge#194]
RT

**Comment by freddiehsu** [comment]
https://aur.archlinux.org/packages/clash-verge-bin

**Comment by mdogwoop** [comment]
这个AUR没有维护，过时了

> https://aur.archlinux.org/packages/clash-verge-bin

**Comment by inRm3D** [comment]
> 这个AUR没有维护，过时了
> 
> > [aur.archlinux.org/packages/clash-verge-bin](https://aur.archlinux.org/packages/clash-verge-bin)

目前我是手动修改版本号 + 改 SKIP 升级的。因为基本没有依赖变化。

然后 https://github.com/zzzgydi/clash-verge/issues/204 目前这位在维护版本。

后续也许可以在 archcn 源申请加入。

**Comment by reikantanzo** [comment]
可以参考我之前写的PKGBUILD: https://fars.ee/pQzf

**Comment by sukanka** [comment]
可以参考 aur 我打的 [clash-verge](https://aur.archlinux.org/packages/clash-verge)，已经给 archlinuxcn 发了 pr

**Comment by inRm3D** [comment]
https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/clash-verge/

solved.
