### ISSUE TITLE
Ubuntu 上使用 clash meta 内核，无法连接到vmess服务

### ISSUE THREAD

**Issue by Declarcall** [zzzgydi/clash-verge#196]
我的系统是Ubuntu20.04 lts x86版本, Clash Verge v1.0.6，使用deb包安装的。
导入机场给的clash订阅后，使用clash原版内核是可以正常连到vmess+ws+tls(v2ray)服务的。切换成meta内核，就完全连不上了，测速也显示Error。

**Comment by zzzgydi** [comment]
你可以裸跑一下clash meta，看看有没有问题

**Comment by Declarcall** [comment]
单独测了 [Clash.Meta-linux-amd64-compatible-v1.13.1.gz](https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.13.1/Clash.Meta-linux-amd64-compatible-v1.13.1.gz) 这个版本，可以正常使用。但是，运行这个版本 [Clash.Meta-linux-amd64-v1.13.1.gz](https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.13.1/Clash.Meta-linux-amd64-v1.13.1.gz) ，因为我cpu不支持的缘故，报错如下: 

> This program can only be run on AMD64 processors with v3 microarchitecture support.

**Comment by zzzgydi** [comment]
clash verge 内置的就是Clash.Meta-linux-amd64-v1.13.1.gz核心，你可以替换掉clash-meta执行文件

**Comment by Declarcall** [comment]
为什么不直接采用兼容版内核，这样受众更广呀

**Comment by k3bc999** [comment]
附议使用兼容性内核，我这里也是直接用非兼容的不出节点，使用兼容性的就没有问题。

**Comment by ilihu** [comment]
为什么不采取让clash-verge检测的方式呢？clash-verge检测运行机器的cpu是否支持，不支持则自动切换成兼容版

**Comment by zzzgydi** [comment]
下一个版本默认用兼容的

**Comment by k3bc999** [comment]
仔细研究了一下
Go的amd V3级优化（非兼容内核）需要cpu支持AVX、AVX2等指令集

![image](https://user-images.githubusercontent.com/27000015/192687990-cae65b56-5b40-447c-ac0b-b211a560af52.png)

我这颗U是2015年生产的，没有avx2指令集

![image](https://user-images.githubusercontent.com/27000015/192688082-846dd145-f5ab-4caa-9bfd-4106794147a7.png)

因此非兼容版本无法运行

考虑到clash负载没有那么大，不用V3级优化也不会带来过大的性能影响，因此作者使用兼容内核的下一版本令我十分期待。

**Comment by Declarcall** [comment]
支持，期待

**Comment by zzzgydi** [comment]
新版本已经默认使用兼容内核啦
