### ISSUE TITLE
为啥Mac全屏的过程感觉很卡

### ISSUE THREAD

**Issue by yueqianzhang** [zzzgydi/clash-verge#2]
为啥Mac全屏的过程感觉很卡，Tauri 的问题吗?

**Comment by zzzgydi** [comment]
你说的卡是不是指，窗口变大之后，内容才变大，不够流畅的这种感觉。

**Comment by yueqianzhang** [comment]
> 你说的卡是不是指，窗口变大之后，内容才变大，不够流畅的这种感觉。

是的，变化的过程感觉上不流畅

**Comment by spphinslove** [comment]
我全屏不卡，但是我窗口状态下拖动窗口左右晃，会干净有延迟一样，有些慢。

**Comment by spphinslove** [comment]
> 我全屏不卡，但是我窗口状态下拖动窗口左右晃，会干净有延迟一样，有些慢。

很奇怪好像重启软件 没问题了。。。
