### ISSUE TITLE
在ubuntu22.04上启动失败原因不明

### ISSUE THREAD

**Issue by Sincejunly** [zzzgydi/clash-verge#200]
实测在ubuntu20.04上可以正常运行

**Comment by Sincejunly** [comment]
系统刚装的 应该不存在什么端口占用

**Comment by Sincejunly** [comment]
官方的clash内核怎么设置都连不上后台网页，靠大佬了 希望能修复，感觉同类中这个版本最好用

**Comment by zzzgydi** [comment]
你是跑不了clash verge还是点开了软件但是clash内核有问题呢

**Comment by valig5** [comment]
https://github.com/zzzgydi/clash-verge/issues/80#issue-1222232048

**Comment by valig5** [comment]
@Sincejunly 实测在ubuntu2204中自己编译出来的clash-verge可以用没有问题

**Comment by Sincejunly** [comment]
> @Sincejunly 实测在ubuntu2204中自己编译出来的clash-verge可以用没有问题

好 谢谢 感觉是这个问题

**Comment by zzzgydi** [comment]
v1.1.0应该没这个问题了
