### ISSUE TITLE
开机后服务模式启动失败，clash内核无法加载

### ISSUE THREAD

**Issue by blackh1** [zzzgydi/clash-verge#201]
Windows11，设置为开机自启动。
开机后程序启动，但是服务模式无法运行，显示未安装状态，而且clash内核为“-”，也无法上网。重新安装服务模式后即可加载内核。

正常运行后，在日志中还会出现以下内容：
09-21 08:26:40WARNING[TCP] dial Domestic (match GeoIP(CN)) to 222.223.39.185:7680 error: dual stack tcp shake hands failed
不知道是什么问题

**Comment by blackh1** [comment]
还有一个问题是重新设置窗口大小后关闭，再重新打开，窗口大小又恢复成最开始的样子，而且位置是屏幕中间

**Comment by moranno** [comment]
我这边也出现了部分节点无法链接，日志出现：connect error: dual stack tcp shake hands failed
版本：1.1.1
内核：meta

**Comment by zzzgydi** [comment]
服务模式的问题可以试试最新版 v1.1.2
