### ISSUE TITLE
建议允许修改配置文件存储目录

### ISSUE THREAD

**Issue by nick008a** [zzzgydi/clash-verge#202]
方便多开

便携（绿色）版往用户目录里写东西也不合适

**Comment by Curious-r** [comment]
文档里写了：[https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88](url)

**Comment by Curious-r** [comment]
文档[这里](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88)写了该怎么配置
