### ISSUE TITLE
系统托盘切换 mode 后，界面不能及时响应

### ISSUE THREAD

**Issue by Priestch** [zzzgydi/clash-verge#206]
系统：Ubuntu 22.01.1
版本：源代码本地`yarn tauri dev`启动，对应 commit hash a6b2db182d4b30a704adc77b53500405d95e8aab

在系统托盘切换 mode 后，界面不会及时对应改变，切换两次后会触发更新，但界面显示的为第一次选择的 mode。

在 React 组件内对应状态变化后使用 fetch 单独获取 `http://127.0.0.1:9090/configs`，获取到的是未更新的配置，使用 curl 可以获取到更新后的配置，对应的 `~/.config/clash-verge/config.yaml` 文件也已经更新

**Comment by zzzgydi** [comment]
已知bug，已经修复了，但还没发版

**Comment by zzzgydi** [comment]
可以尝试 96e76665d68cc638bb947be925ffb9b27772844c

**Comment by Priestch** [comment]
@zzzgydi :+1: 最新的代码看着没问题了
