### ISSUE TITLE
升级1.0.6后Proxies界面空白，或者偶尔点击切换到Proxies页码时卡死

### ISSUE THREAD

**Issue by genghisun** [zzzgydi/clash-verge#208]
![image](https://user-images.githubusercontent.com/26201304/192111643-b5a72277-4d55-4be5-bbbb-34d20df39fa1.png)

![image](https://user-images.githubusercontent.com/26201304/192111593-eacc88a2-8365-40a6-9612-4a8e38bf9f21.png)

**Comment by zzzgydi** [comment]
你是用什么设备的

**Comment by genghisun** [comment]
ubuntu 20.04，直接下载的AppImage

**Comment by zzzgydi** [comment]
可以试一下v1.1.0

**Comment by BaronChushao** [comment]
win10遇到同样的问题，题主解决了吗？

**Comment by zzzgydi** [comment]
> win10遇到同样的问题，题主解决了吗？

@BaronChushao 你的系统不是arm的吧

**Comment by BaronChushao** [comment]
不是arm的，clash verge只有arm才能用吗？

**Comment by zzzgydi** [comment]
1.1.1应该修复这个问题啦，可以留意一下还有没有再现
