### ISSUE TITLE
能否增加便携版包

### ISSUE THREAD

**Issue by AlterGu** [zzzgydi/clash-verge#21]
能否增加便携版包, 解压即用

**Comment by zzzgydi** [comment]
下个版本可以有。

**Comment by AlterGu** [comment]
好的感谢作者

**Comment by zzzgydi** [comment]
新版已经发布啦，release里有一个green.zip，适用于Windows的。

由于ci出了点小问题，这个包是手动上传的，介意慎入。下个版本修复ci问题后，将由ci自动构建发布。

**Comment by zhongfly** [comment]
> 新版已经发布啦，release里有一个green.zip，适用于Windows的。
> 
> 由于ci出了点小问题，这个包是手动上传的，介意慎入。下个版本修复ci问题后，将由ci自动构建发布。

作者能否考虑绿色版支持保存所有配置到程序文件所在目录（exe所在目录）？

**Comment by zzzgydi** [comment]
> 作者能否考虑绿色版支持保存所有配置到程序文件所在目录（exe所在目录）

这个暂不考虑哈，这个是为了方便迁移程序？还是为了方便删除卸载干净？

为了方便迁移的话，有考虑实现一个导入导出所有应用配置的功能。
如果是为了方便删除的话，除了程序目录，绿色版只会在`~/.config/clash-verge`这里产生文件，所以直接删除这个文件夹就干净了。

**Comment by zhongfly** [comment]
> > 作者能否考虑绿色版支持保存所有配置到程序文件所在目录（exe所在目录）
> 
> 这个暂不考虑哈，这个是为了方便迁移程序？还是为了方便删除卸载干净？
> 
> 为了方便迁移的话，有考虑实现一个导入导出所有应用配置的功能。 如果是为了方便删除的话，除了程序目录，绿色版只会在`~/.config/clash-verge`这里产生文件，所以直接删除这个文件夹就干净了。

既然是绿色版/便携版，期望就是方便迁移，数据保存在当前文件夹里也是正常的。
导入导出这类行为更符合安装版的期望。

**Comment by zzzgydi** [comment]
如果是配置都保存到程序文件所在目录，对现有的用户来说是一个巨大的breaking chang。
如果是可以由用户配置保存到哪里，那这个配置肯定就不能写到原有的那些配置文件中，需要一个额外的配置。

想了一下也可以实现，再在程序目录加个配置文件就好，默认还是保存到原来的目录，需要手动开启。

**Comment by zhongfly** [comment]
> 如果是配置都保存到程序文件所在目录，对现有的用户来说是一个巨大的breaking chang。 如果是可以由用户配置保存到哪里，那这个配置肯定就不能写到原有的那些配置文件中，需要一个额外的配置。
> 
> 想了一下也可以实现，再在程序目录加个配置文件就好，默认还是保存到原来的目录，需要手动开启。

可以参考其他程序的做法，启动时检查当前目录是否存在数据目录(例如叫data文件夹)，如果存在data文件夹，则优先从此处读取。用户想要启用这个功能，也只需要在程序目录里创建空的data文件夹即可

**Comment by zzzgydi** [comment]
> 可以参考其他程序的做法，启动时检查当前目录是否存在数据目录(例如叫data文件夹)，如果存在data文件夹，则优先从此处读取。用户想要启用这个功能，也只需要在程序目录里创建空的data文件夹即可，就是完全的便携了

差不多的思路，可以额外提个issue记录一下

**Comment by SpecterShell** [comment]
文件名里的 `green`（绿色版）可以改成 `portable`（便携版），英文没有“绿色软件”这个说法。

**Comment by zzzgydi** [comment]
@SpecterShell 感谢提醒，已修改

**Comment by zzzgydi** [comment]
@zhongfly 0.0.29已支持修改配置目录到exe所在目录，需要在exe所在目录新建一个`.config`目录，然后再设置一个`.config/PORTABLE` 的空文件即可。

这时还可以直接将`~/.config/clash-verge`之前的配置，直接copy到`exe-dir/.config/clash-verge`。
