### ISSUE TITLE
安装deb文件无法打开

### ISSUE THREAD

**Issue by b1gdea1** [zzzgydi/clash-verge#211]
操作系统ubuntu22.04；
下载了deb文件，安装deb文件后菜单中有clash-verge的图标，**点开后没有反应**；安装的时候也没有报错
下载了AppImage文件后双击就可以打开；

**Comment by ilihu** [comment]
感觉这个软件，Linux平台的用户居多啊

**Comment by b1gdea1** [comment]
> 感觉这个软件，Linux平台的用户居多啊

windows用clash for windows，macos用clashX，其他的clash gui基本上都是linux在用

**Comment by dedsecezio** [comment]
ubuntu18以后缺少一个依赖，可以看这个https://blog.csdn.net/Asgard_Hu/article/details/127532328

**Comment by dedsecezio** [comment]
> ubuntu18以后缺少一个依赖，可以看这个https://blog.csdn.net/Asgard_Hu/article/details/127532328

我用这个成功解决了
