### ISSUE TITLE
clash-meta 内核不能初始化 geoip.dat 模式

### ISSUE THREAD

**Issue by riverscn** [zzzgydi/clash-verge#212]
操作系统： Windows 11
配置文件里写入
`geodata-mode: true`
在设置里打开clash字段geodata-mode

在clash-verge里，没有GeoIP的初始化信息，相关的规则也失效了。
但如果在命令行自己启动 clash-meta，GeoIP初始化成功，说明配置文件本身没问题。
查看了clash-verge-runtime.yaml文件也是正常写入了这条的。
所以很奇怪，不知道为什么。

**Comment by zzzgydi** [comment]
https://docs.metacubex.one/function/general

文档里提到不能正常下载文件的问题吗

**Comment by riverscn** [comment]
> https://docs.metacubex.one/function/general
> 
> 文档里提到不能正常下载文件的问题吗

不是的。

> 但如果在命令行自己启动 clash-meta，GeoIP初始化成功，说明配置文件本身没问题。

![image](https://user-images.githubusercontent.com/555062/192246141-82feb507-94b0-476e-b919-8aa289fd54c1.png)

> 在clash-verge里，没有GeoIP的初始化信息，相关的规则也失效了。

![image](https://user-images.githubusercontent.com/555062/192246393-7aa4d2c9-141b-4e5c-ac15-5880ed64a4c1.png)

**Comment by zzzgydi** [comment]
先通过`./clash-meta -d ~/.config/clash-verge`启动clash meta。

再发个http请求更新配置为`path/to/clash-verge-runtime.yaml`

```
curl -H "Content-Type:application/json" \
     -X PUT \
     --data '{"path":"path/to/clash-verge-runtime.yaml"}' \
     http://127.0.0.1:9090/configs
```

可以测试一下这样是否正常。

**Comment by riverscn** [comment]
> 可以测试一下这样是否正常。

这样果然有问题……看来是 clash-meta 的bug了……

![image](https://user-images.githubusercontent.com/555062/192308295-c1a26acf-2c97-4815-be6d-bc1b4e5d0ae2.png)

**Comment by riverscn** [comment]
dirty workaround:

`let (mut rx, cmd_child) = cmd.args(["-d", app_dir]).spawn()?;`

->

`let (mut rx, cmd_child) = cmd.args([“-m", -d", app_dir]).spawn()?;`
