### ISSUE TITLE
最近两个版本跟新后都无法打开

### ISSUE THREAD

**Issue by lxtx528** [zzzgydi/clash-verge#214]
你好，我使用的是macos10.15.17catalina系统，最近的两个版本跟新了都无法打开，已退回到1.0.5，请问是什么原因呢？是不支持这个系统了吗？

**Comment by ilihu** [comment]
能说说你是怎么使用的吗？比如下载的是那个版本和架构的，你的硬件是x86还是arm架构的，如何安装的。等

**Comment by lxtx528** [comment]
我的电脑是16款的macbookpro15.4寸的，下载的版本是clsh.verge.app.tar.gz，之前一直下载的这个版本。

ilihu ***@***.***> 于 2022年9月28日周三 04:18写道：

**Comment by zzzgydi** [comment]
下载dmg的试试呢，tar.gz的是自动更新下载的包
https://github.com/zzzgydi/clash-verge/releases/download/v1.1.0/Clash.Verge_1.1.0_x64.dmg

**Comment by lxtx528** [comment]
这个安装包也试过，打不开。

GyDi ***@***.***> 于2022年9月28日周三 10:39写道：

**Comment by lxtx528** [comment]
应该是x86

ilihu ***@***.***> 于2022年9月28日周三 04:18写道：

**Comment by lxtx528** [comment]
所有下载链接都是过了，都不行。只有返回到1.0.5才能用。
https://github.com/zzzgydi/clash-verge/releases/download/v1.0.5/Clash.Verge.app.tar.gz这个版本，其他的都不行。16年macbookpro
15.4,系统catalina10.15.7

Aaro Cheung ***@***.***> 于2022年9月28日周三 12:29写道：

**Comment by lxtx528** [comment]
所有下载链接都是过了，都不行。只有返回到1.0.5才能用。
https://github.com/zzzgydi/clash-verge/releases/download/v1.0.5/Clash.Verge.app.tar.gz这个版本，其他的都不行。16年macbookpro
15.4,系统catalina10.15.7

Aaro Cheung ***@***.***> 于2022年9月28日周三 12:29写道：

**Comment by zzzgydi** [comment]
release是用github action macOS 11构建的，可能有不兼容的问题吧，可以尝试自己编译。或者有空我再研究怎么搞个方便自行编译的脚本或ci模版吧。

**Comment by moranno** [comment]
mac系统安装后执行：
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

就不会提示app损坏了。

**Comment by lxtx528** [comment]
没有提示损坏，是直接打不开。

moranno ***@***.***>于2022年10月10日 周一08:17写道：

**Comment by zzzgydi** [comment]
v1.1.2 能使用吗

**Comment by zzzgydi** [comment]
可以尝试 https://github.com/zzzgydi/clash-verge/releases/tag/macOS-10.15

**Comment by lucasmen9527** [comment]
我系统是 mac Ventura 13.1  m1
下载最新版本[clash v1.2.3](https://github.com/zzzgydi/clash-verge/releases/tag/v1.2.3) ,然后使用命令
`sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app`  就可以打开了
<img width="751" alt="image" src="https://user-images.githubusercontent.com/64875226/223045766-3ee6852a-57bc-4046-a480-4c3f0a513078.png">
