### ISSUE TITLE
增加对 ARM64 Windows 的支持？

### ISSUE THREAD

**Issue by ParticleG** [zzzgydi/clash-verge#216]
Github Actions 的 `windows-latest` 容器中似乎是有 arm64 的 MSVC 工具链的，所以稍微修改一下 CI 流程应该就可以支持 Surface Pro X 等 arm64 Windows 设备：#209

**Comment by zzzgydi** [comment]
测了一下，有一个库不支持aarch64-pc-windows-msvc，所以这个不能支持了。

https://github.com/zzzgydi/clash-verge/actions/runs/3142276786/jobs/5105687691
