### ISSUE TITLE
2 small problems for user interface experience

### ISSUE THREAD

**Issue by MikeyWei** [zzzgydi/clash-verge#217]
about v1.1.0：
- First of all, when I want to close the main interface, the shortcut keys(`command+W`) on the Mac are invalid. I can only click the X button in the upper left corner of the main interface. Similarly, when I want to close the APP completely, the shortcut key(`command+Q`) is invalid.
- Secondly, when I close the main interface, the Verge icon will still reside in the program dock.Icons of other apps will only appear in the top menu bar of macOS.（As shown in the following figure）
![menu bar](https://user-images.githubusercontent.com/59159039/192754277-1586c9ab-5cf9-4c85-b62c-24f6ed061991.png)
- Third, there is no in-app update function, so you can only download the latest version from GitHub to manually replace the old version.

**Comment by zzzgydi** [comment]
- you can use `Esc` key to hide the window.
- bug but pending
- todo
