### ISSUE TITLE
多用户兼容性

### ISSUE THREAD

**Issue by Ccyuyzs** [zzzgydi/clash-verge#218]
Windows多用户下只能同时有一个用户使用GUI 其他用户只有Core工作

**Comment by zzzgydi** [comment]
弄了个端口占用实现单例的限制，可以在配置文件verge.yaml里修改app_singleton_port字段的值为其他端口号，这样每个用户就可以开各自的了。

**Comment by 1026742642** [comment]
多用远程的情况下, 一个用户修改配置文件, 另一个用户的节点也发生了改变
[window多用户](https://github.com/stascorp/rdpwrap)
