### ISSUE TITLE
Merge 覆盖机场代理组后，如何把原来的节点信息放在新的代理组呢？

### ISSUE THREAD

**Issue by mx4994** [zzzgydi/clash-verge#219]
使用Merge 覆盖了规则、规则集、代理组，现在就是不知道怎么把原来订阅中的节点信息放在新的代理组中，试了CFW的配置预处理commands不行，不会只能手动复制配置文件名，然后填在USE中吧？

希望解答一下，感谢。

**Comment by zzzgydi** [comment]
merge的功能很有限，复杂的逻辑还是用script写js吧
