### ISSUE TITLE
菜单上右键可以打开浏览器的右键菜单

### ISSUE THREAD

**Issue by spphinslove** [zzzgydi/clash-verge#22]
这个应该关闭吧

**Comment by zzzgydi** [comment]
菜单是指哪个菜单，目前还没有全局拦截右键事件，感觉留着右键也没啥问题。

**Comment by spphinslove** [comment]
![图片](https://user-images.githubusercontent.com/11383988/158010235-dc0a4ece-2fae-4161-8ab9-00ca4a97dc65.png)
任何地方右键都会出现

**Comment by zzzgydi** [comment]
这个确实没关
