### ISSUE TITLE
Can't work on Ubuntu (deb)

### ISSUE THREAD

**Issue by xmha97** [zzzgydi/clash-verge#222]
Hi, I can install deb package on Ubuntu but it doesn't :(

**Comment by zzzgydi** [comment]
You can try the latest version v1.1.1.

**Comment by IsQiao** [comment]
亲测1.1.1已修复，最好把 `cat ~/.config/clash-verge/` 删了

**Comment by zzzgydi** [comment]
try https://github.com/zzzgydi/clash-verge/releases/tag/Ubuntu22 or https://github.com/zzzgydi/clash-verge/releases/tag/Ubuntu18
