### ISSUE TITLE
“静默启动”在win10额外消耗cpu性能问题

### ISSUE THREAD

**Issue by Franinc** [zzzgydi/clash-verge#223]
clash-verge设置 - 打开“静默启动”，退出重新打开`Clash Verge.exe`，此时没有窗口 只有任务栏多个小猫图标，但任务管理器能看见出现多个`msedgewebview2.exe`，在我这如图消耗额外大概4%性能。
然后点击小猫图标 让verge窗口出现后点x关闭这个verge窗口，`msedgewebview2.exe`也随之全部关闭，当然verge并没退出还在后台，小猫图标也还在，但再也不会再消耗额外cpu性能
![Snipaste_2022-10-05_19-20-27](https://user-images.githubusercontent.com/26399054/194051662-3b142efe-f44b-46e4-822a-e62d26d9b40e.jpg)

verge版本1.1

**Comment by zzzgydi** [comment]
1.1.1已经修复这个问题啦
