### ISSUE TITLE
不兼容 clash 本身的 config.yaml.

### ISSUE THREAD

**Issue by Remonli** [zzzgydi/clash-verge#224]
我是手撸clash.exe 在后台，用config.yaml配置，dashboard控制。试了一下最新版，删掉配置中关于dashboard的部分,
依旧启动报错，界面看不到proxy选项下有东西。
```
2022-10-07 00:10:23 - The system cannot find the file specified. (os error 2)
2022-10-07 00:10:23 - failed to parse the server with status 34
```

**Comment by zzzgydi** [comment]
> 删掉配置中关于dashboard的部分

你是删了config.yaml里的一些字段吗，比如`external-controler`

**Comment by Remonli** [comment]
是的，external-controler 删掉了，后来我意识到问题加回去可以了，但报那个os error 2 还是有的。

**Comment by Remonli** [comment]
没啥问题，除了这个报错，其他都正常使用了。
