### ISSUE TITLE
开机启动时最小化启动

### ISSUE THREAD

**Issue by Riajyuu** [zzzgydi/clash-verge#225]
这样在开机时可以减少一个窗口 仅出现一个任务栏图标

这里其实牵着到一个问题：最小化到托盘还是任务栏

不同软件处理不同 有的给出设置有的没有

**Comment by zzzgydi** [comment]
有个静默启动的设置，最小化到托盘的

**Comment by Riajyuu** [comment]
![image](https://user-images.githubusercontent.com/16912240/194685960-f7b3bd13-a51e-4a25-a8ad-77c0ec5fa44f.png)

我已经打开了 但是开机后还是出现窗口

**Comment by zzzgydi** [comment]
1.1.1已经修复了这个问题啦
