### ISSUE TITLE
Problem with hotkey/shortcut

### ISSUE THREAD

**Issue by SirSobhan** [zzzgydi/clash-verge#227]
Problem with hotkey/shortcut

After setting the hotkey in version **1.1.0** to turn on and off the system proxy, the program no longer works. After running, the program closes automatically. **The problem was not solved by uninstalling and reinstalling!** By returning to version **1.0.6**, the program opens.

The only thing in the logs file:
```2022-10-08 - Access is denied. (os error 5)```
```2022-10-08 - The system cannot find the file specified. (os error 2)```

**Comment by zzzgydi** [comment]
Which system do you use

**Comment by SirSobhan** [comment]
> Which system do you use

Windows 10 x64

**Comment by zzzgydi** [comment]
You can try the latest version v1.1.1

**Comment by SirSobhan** [comment]
> You can try the latest version v1.1.1

Thank you, the whole problem is solved, but there is still a problem with some keys like tab, space! When these keys are set, the program closes automatically. Of course, I don't know if the selection of these keys is correct or not. I just chose them for testing. However:)
