### ISSUE TITLE
M1 version cannot be installed

### ISSUE THREAD

**Issue by Kelvinycj** [zzzgydi/clash-verge#228]
启动显示镜像已损坏，Mac OS 12

**Comment by zzzgydi** [comment]
设置 - 安全与隐私 允许

**Comment by Kelvinycj** [comment]
不是这个问题咯，可以安装的，也允许了任何安装源，运行的时候aarch64的报错，就说损坏。arm64的在m1 macos12可以运行，但是无法切换clashmeta core，切换直接假死。麻烦老大看下呢？

**Comment by zzzgydi** [comment]
你安装的这个么 https://github.com/zzzgydi/clash-verge/releases/download/v1.1.0/Clash.Verge_1.1.0_aarch64.dmg

**Comment by moranno** [comment]
安装后执行：
sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

**Comment by Kelvinycj** [comment]
it works well， thanks
2022年10月9日 +0800 22:47 moranno ***@***.***>，写道：

**Comment by ipcjs** [comment]
建议在README里面说明下，我碰到这个报错，还以为真的是文件损坏了😵

**Comment by snape2019** [comment]
> 安装后执行： sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app

感谢🙏
