### ISSUE TITLE
merge似乎不生效？

### ISSUE THREAD

**Issue by lisansas** [zzzgydi/clash-verge#232]
WIN10 19044.2130
CLASH VERGE版本：1.1.1

我做了什么：
在clash字段了勾选了指定字段，切换到meta内核，创建了merge file，并且右键enable。
![Clip_20221013_143738](https://user-images.githubusercontent.com/38862056/195520394-d56dbf24-8594-4326-9fdf-23afa8859d46.jpg)

merge字段如下：
profile:
  store-fake-ip: true 
    
sniffer:
  enable:true
  sniffing:
    -tls
    -http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
    - '*.baidu.com'
  force-domain:
    - 'google.com'  
    
tun:  # Tun 配置
  enable: true  # 启用 Tun 模式
  device: meta
  stack: system  # gvisor/system 使用 system stack 请按照本文后面防火墙放行程序
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true  # 自动检测出口网卡

结果:点击runtime config，config没有改变，查看日志，显示tun依旧为gvisor，sniffer也未开启。

尝试：重启程序，点击程序右上角刷新按钮，点击remote订阅刷新按钮，没有任何改变。

**Comment by zzzgydi** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/27361820/195523198-b604ffca-cdbc-499a-afe8-b4da44f20218.png">

设置页的这个点开，把tun和sniffer勾上就可以了

**Comment by lisansas** [comment]
> <img alt="image" width="542" src="https://user-images.githubusercontent.com/27361820/195523198-b604ffca-cdbc-499a-afe8-b4da44f20218.png">
> 
> 设置页的这个点开，把tun和sniffer勾上就可以了

我点了。

忘记说明一点，我用的是便携版的，有可能和这个有关吗？

**Comment by zzzgydi** [comment]
> 我用的是便携版的，有可能和这个有关吗？

和这个应该没关系的，可以看看日志有没有什么报错信息，如果merge file的yaml格式有问题的话，是会跳过这个处理的。

**Comment by lisansas** [comment]
> > 我用的是便携版的，有可能和这个有关吗？
> 
> 和这个应该没关系的，可以看看日志有没有什么报错信息，如果merge file的yaml格式有问题的话，是会跳过这个处理的。

是的，发现有几个空格没有打进去，我是sb。
