### ISSUE TITLE
说个搞笑的事

### ISSUE THREAD

**Issue by zcg** [zzzgydi/clash-verge#233]
![image](https://user-images.githubusercontent.com/68289686/195532066-e412db6e-d8b4-4809-8a3b-f40a9a6bd5a5.png)
gpu占用比软件本体还大
而且之前发现clash meta内核好像会内存泄漏 占了6/7百兆,这个换clash内核好了

**Comment by zzzgydi** [comment]
windows还算好的，关掉窗口之后，webview2的相关进程都没了。macOS才搞笑，关掉都还在
