### ISSUE TITLE
failed to pares the server with status 32

### ISSUE THREAD

**Issue by Yzcloud** [zzzgydi/clash-verge#238]
![2022-10-19_02-232022-10-19](https://user-images.githubusercontent.com/88927779/196513229-d9f2d188-8533-4448-a244-225fd139e4c6.png)

**Comment by Yzcloud** [comment]
1.1.1版本

**Comment by Yzcloud** [comment]
又换了几个版本都一样，不知道怎么处理，老大指导一下🙈

**Comment by zzzgydi** [comment]
config.yaml文件里少了"external-controller"字段，补上`external-controller: 127.0.0.1:9090`
