### ISSUE TITLE
使用服务模式时，clash无法关闭

### ISSUE THREAD

**Issue by thinkingland** [zzzgydi/clash-verge#241]
环境为 Windows 10 22H2 64bit。

开机自启，开启了 Tun 模式，并使用服务模式时，clash/clash-meta 核心程序不会随着 clash-verge 的关闭而关闭；用任务管理器强制关闭核心后再打开 clash-verge 时，似乎也不会启动 clash/clash-meta 核心。

**Comment by Curious-r** [comment]
参考[微软的文档](https://learn.microsoft.com/zh-cn/dotnet/framework/windows-services/introduction-to-windows-service-applications)，这就是正常的行为。
服务模式就是把clash核心注册为常驻后台的服务程序，核心是否运行取决于服务状态是运行还是停止，和客户端是否打开是没关系的。客户端里的服务模式开关可以改变clash核心服务的状态，你可以尝试一下kill掉后台进程之后在客户端里重新开关一下服务模式的按钮，看看clash核心是否重新启动了。

**Comment by thinkingland** [comment]
按照 https://github.com/zzzgydi/clash-verge/issues/134#issuecomment-1190971620 的表述，服务模式的作用只是用来提升权限的，而不是把clash注册为服务。

**Comment by thinkingland** [comment]
我试过重装……没用。

刚刚用虚拟机试了下，1.0.6版本没有问题，1.1.0及以后的版本才有这个问题。

------- Original Message -------
2022年10月20日 星期四 上午 10:41，GyDi ***@***.***> 来信：

**Comment by zzzgydi** [comment]
> 1.0.6版本没有问题，1.1.0及以后的版本才有这个问题。

ok我排查一下

**Comment by zzzgydi** [comment]
修复了bug，下个版本发
