### ISSUE TITLE
过滤条件

### ISSUE THREAD

**Issue by Yzcloud** [zzzgydi/clash-verge#243]
你好，过滤条件需要什么语法去掉订阅里不需的节点呢？

**Comment by Yzcloud** [comment]
还有就是希望任务栏开启系统代理后图标能变个颜色，这样能很直观的知道有没有开启代理，嘿嘿

**Comment by zzzgydi** [comment]
> 你好，过滤条件需要什么语法去掉订阅里不需的节点呢？

目前只有script写脚本过滤。之后可以在merge里加点规则来实现，可以共享idea？

**Comment by Yzcloud** [comment]
比如正则表达式

**Comment by zzzgydi** [comment]
clash meta 这样的呢 https://docs.metacubex.one/function/proxygroups/filter

**Comment by Yzcloud** [comment]
好像还不错
