### ISSUE TITLE
[Feature Request]更新配置文件失败时仍然使用老配置文件

### ISSUE THREAD

**Issue by Marukon** [zzzgydi/clash-verge#244]
某些时候，订阅更新链接挂掉，但是verge仍然会自动更新配置文件，结果使用了错误的配置文件（如一个404页面），导致网络断开。
建议：对下载的配置文件进行测试，成功则使用新的配置文件，若失败则使用老的配置文件。

**Comment by zzzgydi** [comment]
一个404页面是指订阅链接更新后返回html文件吗？现在是有对配置文件做格式验证的

**Comment by Marukon** [comment]
> 一个404页面是指订阅链接更新后返回html文件吗？现在是有对配置文件做格式验证的

大佬，今早我的某个更新链接挂掉了（浏览器直接访问提示“似乎 XXX关闭了连接”，通过subconverter转换提示“The following link doesn't contain any valid node info”），但是verge仍然能更新成功，节点如下图：
![1](https://user-images.githubusercontent.com/6285343/197099917-a00b9d3a-2a29-4d1e-99eb-5f43aae6cb1c.png)

**Comment by zzzgydi** [comment]
这种情况应该是链接返回了正常的yaml配置，只是没有节点信息

**Comment by Marukon** [comment]
好的，感谢大佬。
