### ISSUE TITLE
[bug]退出软件之后，clash不仅没有退出，甚至还在处理代理

### ISSUE THREAD

**Issue by machine-doll** [zzzgydi/clash-verge#248]
使用的是tun模式，在右键菜单中退出软件之后，clash并没有退出  
<img width="576" alt="image" src="https://user-images.githubusercontent.com/87234334/197398866-7f17663d-c497-40df-b20e-7bb06a2f64a3.png">
不仅如此，clash依旧工作在tun模式，代理流量  
<img width="403" alt="image" src="https://user-images.githubusercontent.com/87234334/197398900-926f75ff-e16d-40ac-9f8e-c4119f2c3dde.png">
而如果强行在任务管理器中结束clash和其服务，再次启动本软件，会遇到无法初始化TUN设备的问题

**Comment by zzzgydi** [comment]
已知bug，已经修复，下个版本发

**Comment by zzzgydi** [comment]
v1.1.2已经修复，可以看看
