### ISSUE TITLE
Failed to download profile

### ISSUE THREAD

**Issue by angryLid** [zzzgydi/clash-verge#249]
Just now I got a link from my airport and added subscription without exceptions.

Then I used [bianyuan converter](https://bianyuan.xyz/) to generate a costom subscription, but when I tried to add it to clash-verge, a error occured.

The following error message was printed to console:

> 2022-10-24 00:35:42 - error sending request for url (https://pub-api-1.bianyuan.xyz/sub?target=clash&url=https%3A%2F%2Fmojie.nl%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Db7f11a90a8581d92a8934829f8fc082a&insert=false): error trying to connect: Connection reset by peer (os error 104)

By the way, I copied that link to clash for android and got the correct result. Therefore I guess the converted profile was capatible with clash but couldn't be download.

**Comment by angryLid** [comment]
My apologize. I just found that it has a option which enables downloading profile through proxy.

**Comment by zzzgydi** [comment]
reqwest will use the system proxy by default.

**Comment by angryLid** [comment]
> reqwest will use the system proxy by default.

However, at least `reqwest` doesn't use system proxy automatically on my device.

Timeout error occured when I send request to `google.com` without extra proxy configration.

As contrast, I received ` 200 OK ` after I appended the  `proxy()` method.

example code:
```rust
use std::time::Duration;

use reqwest::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    const URL:&str = "https://google.com/ncr";

    let builder = reqwest::Client::builder().timeout(Duration::new(10, 0));
    //.proxy(reqwest::Proxy::https("http://localhost:7890")?);

    let req = builder.build()?.get(URL);

    match req.send().await {
        Ok(res) => {
            println!("My Response: {:#?}", res);
        }
        Err(err) => {
            println!("Error: {:#?}", err)
        }
    };

    Ok(())
}
```

**Comment by zzzgydi** [comment]
https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.proxy

**Comment by zzzgydi** [comment]
I get, on linux and macOS, reqwest will get the "system" proxy from environment, which is inconsistent with what we said.

**Comment by maxorbase** [comment]
> My apologize. I just found that it has a option which enables downloading profile through proxy.

i can find option to update through proxy but where is option to downloading profile through proxy??
