### ISSUE TITLE
config.yaml更改配置后无法启动核心

### ISSUE THREAD

**Issue by Axedontworry** [zzzgydi/clash-verge#25]
想修改DNS配置，保存后启动界面空白，Clash Core不显示版本号。

**Comment by zzzgydi** [comment]
是什么系统呢，有没有开启tun模式

**Comment by Axedontworry** [comment]
> 

Window11 没开启TUN

**Comment by Axedontworry** [comment]
> 是什么系统呢，有没有开启tun模式

Windows11 未开启TUN
我把config.yaml自己写的内容删除了 重启就恢复了。不知道什么原因。

**Comment by zzzgydi** [comment]
有个可能就是你写的内容格式或字段有问题，导致clash内核没启动

**Comment by Axedontworry** [comment]
> 有个可能就是你写的内容格式或字段有问题，导致clash内核没启动

mixed-port: 7890
log-level: info
allow-lan: true
external-controller: "127.0.0.1:9090"
mode: rule
secret: ""
ipv6: true
dns:
  enable: true
  ipv6: true
  # listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "stun.*.*.*"
    - "stun.*.*"
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - tls://dot.pub
  fallback:
    - quic://dns.adguard.com
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
      - 不知道哪里有问题，麻烦指出来一下，谢谢。

**Comment by zzzgydi** [comment]
你这个回复里配置的格式，不容易看，你可以在issue回复里附个文件，或者用反引号。

**Comment by Axedontworry** [comment]
> 你看这个回复里配置的格式，不方便用，你可以在发出回复里附个文件，或者反引号。
[config.txt](https://github.com/zzzgydi/clash-verge/files/8237685/config.txt)
由于传不了yaml我发了txt格式。

**Comment by zzzgydi** [comment]
```
  fallback:
    - quic://dns.adguard.com
```

Parse config error:
 DNS NameServer[0] unsupport scheme: quic

quic好像不支持

**Comment by Axedontworry** [comment]
> ```
>   fallback:
>     - quic://dns.adguard.com
> ```
> 
> Parse config error: DNS NameServer[0] unsupport scheme: quic
> 
> quic好像不支持

好的我试一下

**Comment by Axedontworry** [comment]
> ```
>   fallback:
>     - quic://dns.adguard.com
> ```
> 
> Parse config error: DNS NameServer[0] unsupport scheme: quic
> 
> quic好像不支持

已经好了，原来是不支持DoQ，我用昨天DoT的配置是没问题的。

**Comment by Axedontworry** [comment]
> > ```
> >   fallback:
> >     - quic://dns.adguard.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Parse config error: DNS NameServer[0] unsupport scheme: quic
> > quic好像不支持
> 
> 已经好了，原来是不支持DoQ，我用昨天DoT的配置是没问题的。
感谢作者 问题已经解决 我关闭掉这个issue了。
