### ISSUE TITLE
deb包安装后打不开

### ISSUE THREAD

**Issue by Evergreentreejxc** [zzzgydi/clash-verge#250]
之前是用的Ubuntu20.4可以打开，但升级22.4后就打不开了，后面换到Linux mint还是一样。
~~~~
因为我看好像类似的issue也没解决，所以我想问一下可以出一个自行编译的教程吗？
    非常感谢！

**Comment by angryLid** [comment]
probably it's not as simple as your expectation.

1. install `rust` and `nodejs` toolchain
2. set proxy or mirror
3. install dependencies
4. follow the `READMD.md` development chapter

**Comment by Evergreentreejxc** [comment]
> probably it's not as simple as your expectation.
> 
> 1. install `rust` and `nodejs` toolchain
> 2. set proxy or mirror
> 3. install dependencies
> 4. follow the `READMD.md` development chapter 

前面应该可以，就是第4步里面的
~~~~
Then download the clash binary... Or you can download it from clash premium release and rename it according to tauri config.
~~~~
不是很懂，能麻烦解释一下吗。

**Comment by zzzgydi** [comment]
就是你可以直接运行`yarn run check`，就会把clash内核下载下来了，默认下载的是p核。如果想自己下载别的核心，需要下载后按一定的格式命名二进制文件。

**Comment by Evergreentreejxc** [comment]
> 就是你可以直接运行`yarn run check`，就会把clash内核下载下来了，默认下载的是p核。如果想自己下载别的核心，需要下载后按一定的格式命名二进制文件。

我打开了，也按照其他issue里设置了tun权限，还有一个小问题，我下次怎么打开软件呢，如果设置开机启动的话它会显示连接失败，是不是有一个3000端口的网页还是什么的。

**Comment by zzzgydi** [comment]
你应该是执行的`yarn dev`吧，关掉这个，执行`yarn build`，然后在`src-tauri/target/release/bundle`目录下找安装包即可。

**Comment by Evergreentreejxc** [comment]
> 你应该是执行的`yarn dev`吧，关掉这个，执行`yarn build`，然后在`src-tauri/target/release/bundle`目录下找安装包即可。

好的，十分感谢
