### ISSUE TITLE
无法连接到使用ipv6的hysteria节点，日志中显示不是ipv4地址

### ISSUE THREAD

**Issue by 1219099256** [zzzgydi/clash-verge#256]
同一ipv6地址的vmess协议可以连接，cfw换meta核后也能正常使用hysteria

**Comment by zzzgydi** [comment]
这种问题一般俩原因吧，

- verge配置没生成对：在设置页找运行时配置，查看生成的配置是否符合
- verge自带的meta核和你用的 版本不一致：用你的meta替换verge自带的再试试

**Comment by 1219099256** [comment]
解决了，如果server填写解析到ipv6的域名则会报错，填写ip地址就好了
