### ISSUE TITLE
Clash运行后无法联网的问题

### ISSUE THREAD

**Issue by SoDebug** [zzzgydi/clash-verge#259]
打开Clash后导致某些软件无法联网，例如Samsung Notes，即便是已经切换成了Direct Mode。
只有取消 系统代理、TUN 后才能正常联网，不知道是不是由于Loop导致的

**Comment by zzzgydi** [comment]
只开系统代理呢

**Comment by SoDebug** [comment]
> 只开系统代理呢

这倒是可以
