### ISSUE TITLE
负载均衡模式

### ISSUE THREAD

**Issue by 0nion1** [zzzgydi/clash-verge#260]
这个是否有负载均衡模式，有时候网站访问不到的时候自动切换代理。

**Comment by zzzgydi** [comment]
https://github.com/Dreamacro/clash/wiki/Configuration#all-configuration-options 根据clash的配置修改proxy-groups的类型就行，对于自动切换代理有三种，url-test，fallback，load-balance

**Comment by 0nion1** [comment]
是否有类似于ssr的低错误模式，因为我看了clash的方法是按照时间去随机代理的

**Comment by zzzgydi** [comment]
clash好像都是从延迟去搞的，低错误不太清楚

**Comment by 0nion1** [comment]
是的 是否能加一个低错误的方式，这样网站没有封禁我我就不需要换ip，如果网站对我进行了封禁那我就换一个测速最快的ip。
