### ISSUE TITLE
win7,更新了订阅,报403错误

### ISSUE THREAD

**Issue by chokees** [zzzgydi/clash-verge#271]
1 win7,更新了订阅,报403错误(已安装了webview2)
![捕获](https://user-images.githubusercontent.com/8486190/200466591-9d31a878-a01e-4a8f-b05e-144a4099fb6b.PNG)
更新后,代理列表无内容数据,为空.
![捕获4](https://user-images.githubusercontent.com/8486190/200467510-aac5246a-ddd9-4fd0-bb6f-544823335427.PNG)

2 启动clash也会报错,但应用没有退出,可以打开
![捕获2](https://user-images.githubusercontent.com/8486190/200466723-2efcce66-0853-4799-9c94-1e810f538fe5.PNG)

**Comment by chokees** [comment]
调试程序
![捕获3](https://user-images.githubusercontent.com/8486190/200467353-2f77c7b6-46ea-481c-921a-66526ca5578a.PNG)

**Comment by zzzgydi** [comment]
是不是加了secret，或者更新了secret。
