### ISSUE TITLE
误删配置文件该咋办哪

### ISSUE THREAD

**Issue by MorningEcho** [zzzgydi/clash-verge#273]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

1.1.2

### 操作系统

Linux

### 系统版本

archlinux x86_64

### 问题描述

求助，误删 ~/.config/clash-verge下的配置文件夹，之后创建脚本以及更改设置都提示失败（无法创建以及无法写入配置文件），重装软件也找不回被删掉的文件夹，该怎么办呀

### 复现步骤

删除~/.config/clash-verge下的配置文件夹

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by zzzgydi** [comment]
删掉了没法恢复吧。但重新启动verge，会自己初始化默认配置的

**Comment by MorningEcho** [comment]
啊一开始也是这么想的 但后来就算重启，它也没有初始化出配置文件夹，然后又删了重装，但没有什么用，重装后也找不到应该有的配置文件夹
我以为是没卸干净，它重装的时候看到熟悉的东西跳过了某些构建步骤，于是我又卸载了一次，这次连安装包缓存也一起删了，再安，还是没有初始化配置，配置文件夹也没有生成，无法导入或写入配置，安装过程中不见报错，不知道该咋办

**Comment by MorningEcho** [comment]
 ~ ❯ sudo clash-verge   
[sudo] echoo 的密码：

2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - tokio-thread started
2022-11-10 00:57:35 - last failed to save file "/tmp/clash-verge-runtime.yaml"
2022-11-10 00:57:35 - [clash]: level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
2022-11-10 00:57:35 - [clash]: level=info msg="RESTful API listening at: 127.0.0.1:9090"

(clash-verge:27403): libayatana-appindicator-WARNING **: 00:57:35.104: Unable to get the session bus: 生成并运行命令行“dbus-launch --autolaunch=f7148aa9e3664d7c8bae5e1773c3a780 --binary-syntax --close-stderr”时出错：子进程已退出，代码 1

(clash-verge:27403): LIBDBUSMENU-GLIB-WARNING **: 00:57:35.109: Unable to get session bus: 生成并运行命令行“dbus-launch --autolaunch=f7148aa9e3664d7c8bae5e1773c3a780 --binary-syntax --close-stderr”时出错：子进程已退出，代码 1


似乎是安装次数太多，开启的时候开启了多个实例，导致了某种冲突（可能和端口有关？）不是很懂，这种情况应该怎么解决啊？

**Comment by zzzgydi** [comment]
这个看起来不是端口冲突，有点像系统托盘相关的错误

**Comment by MorningEcho** [comment]
那更不懂了qaq 谢谢大佬回复 俺再找找怎么解决

**Comment by zzzgydi** [comment]
可以尝试一下最新版

**Comment by MorningEcho** [comment]
配置文件又可以啦 谢谢作者～
