### ISSUE TITLE
请问局域网连接如何配置代理地址的

### ISSUE THREAD

**Issue by rio-kiomi** [zzzgydi/clash-verge#274]
<img src="https://p.inari.site/usr/266/636a6b988fdab.png" alt="Quicker_20221108_224510.png" title="Quicker_20221108_224510.png" />
<img src="https://p.inari.site/usr/266/636a6b9933fb7.png" alt="Quicker_20221108_224517.png" title="Quicker_20221108_224517.png" />
想配置手机wifi设置，通过电脑代理上网
因为之前用clash for Windows 这个局域网功能是直接有地址显示，这里没有地址显示，手机不知道无法配置代理地址，求指教一下谢谢

**Comment by zzzgydi** [comment]
windows输入 ipconfig；macos输入 ifconfig；

**Comment by rio-kiomi** [comment]
> 

感谢回复，但ipconfig获取IPv4 地址后输入到手机代理的主机名仍无法实现代理，电脑更换clash for windows后能实现代理

**Comment by zzzgydi** [comment]
linux 也是 ifconfig 吧
