### ISSUE TITLE
Merge 合并处理添加自定义规则

### ISSUE THREAD

**Issue by mybdye** [zzzgydi/clash-verge#275]
+10086

**Comment by zzzgydi** [comment]
没看懂指的啥

**Comment by mybdye** [comment]
> 没看懂指的啥

就是 Remote 远程配置下追加自定义的规则。
参考： https://chenjuefei.com:444/117.html

**Comment by zzzgydi** [comment]
参考 [wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)

新建merge profile，可以在prepend-rules里加自定义规则

**Comment by mybdye** [comment]
> 参考 [wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)
> 
> 新建merge profile，可以在prepend-rules里加自定义规则

感谢，可以了。
