### ISSUE TITLE
系统代理无法处理 wss:// websocket 请求

### ISSUE THREAD

**Issue by lvii** [zzzgydi/clash-verge#276]
Hi

平时工作会用到 console 控制台，浏览器对应是 `wss://` **Websocket 请求**：

```
Request URL: wss://10.11.12.13/kvm
```

配置的 **内网** DIRECT 规则直连 `http://` 和 `https://` 之类的 web 请求都没问题的。

但当浏览器打开基于 `wss://` websocket 的控制台页面  **连接** 就没有响应了。

测试相同的配置文件在 ClashX 的 **系统代理模式** 是没问题的。

**Comment by zzzgydi** [comment]
connections或者log里有没有信息

**Comment by zzzgydi** [comment]
mixed port可以走socks的，换clash p核能复现吗

**Comment by zzzgydi** [comment]
clash verge设置系统代理只拿mixed port的值。
这里是想看看clash mixed port是不是代理不了wss，还是说没有成功设置系统代理（还得设置个all proxy？）。
测试流程，你还是用mixed port，然后手动设置系统代理，看看能不能生效
