### ISSUE TITLE
有没有类似 CFW 配置 parsers 的地方

### ISSUE THREAD

**Issue by lusi1990** [zzzgydi/clash-verge#279]
你好 因为需要 预处理 订阅的规则, 需要parsers 这种预处理功能

**Comment by zzzgydi** [comment]
可以看看 [wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)
