### ISSUE TITLE
任务栏图标右击菜单会考虑加个系统代理开关不

### ISSUE THREAD

**Issue by d2184** [zzzgydi/clash-verge#28]
![image](https://user-images.githubusercontent.com/63200181/158149774-13cc2e24-6249-47d9-a730-8b4c3624a0df.png)
是否会考虑在这里加个系统代理的开关

**Comment by zzzgydi** [comment]
考虑

**Comment by ileeoyo** [comment]
@zzzgydi 考不考虑象clashxpro那样，任务栏图标右击菜单快捷切换代理组呢

**Comment by zzzgydi** [comment]
@ileeoyo 主要是状态同步的问题，感觉不太好做。可以挑战试试，先记一下吧。

**Comment by ileeoyo** [comment]
> @ileeoyo 主要是状态同步的问题，感觉不太好做。可以挑战试试，先记一下吧。

可以考虑开一个discussion，汇总一下已知待解决的bug，或者有计划做的feature或者不打算做的feature

**Comment by zzzgydi** [comment]
@ileeoyo good idea，已经开了讨论。

**Comment by zzzgydi** [comment]
系统托盘右键已增加系统代理的设置，代理组的设置暂不考虑了
