### ISSUE TITLE
求助：tun模式碰上direct规则就打不开网页

### ISSUE THREAD

**Issue by baraja** [zzzgydi/clash-verge#280]
你好，开发者大佬

我这里碰到个两个问题，烦请大佬解答：
一，同样的一个yaml，使用clash meta系统代理就完全没问题，放到clash原版使用tun模式也完全没问题。
但开启clash meta的tun模式后，凡是走direct规则的网站都打不开，走代理的网站才能正常打开
这该如何解决？
二、clash meta开启tun模式后，还有个奇怪的问题
hysteria可以正常使用，trojan则打不开网页（延迟测试也failed），log里面显示
WARNING[TCP] dial Proxy (match Match()) to firebaseremoteconfig.googleapis.com:443 error: TEST.COM:443 connect error: read tcp4 192.168.1.15:10342->[SERVER IP]:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

我的yml示例在这里：https://pastebin.com/ZLqW5qJ9

**Comment by zzzgydi** [comment]
先查看运行配置生成的是否正常，然后建议到clash meta的issue里提。
