### ISSUE TITLE
导入订阅地址错误：“Failed to import profile”

### ISSUE THREAD

**Issue by jacobin** [zzzgydi/clash-verge#283]
订阅地址：https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0926clash.yml
OS：windows 10
现象：在浏览器里打开订阅地址很正常，在Clash for windows里也正常

**Comment by jacobin** [comment]
用“创建”进行导入：有消息“the remote profile data is invalid yaml”

**Comment by jacobin** [comment]
但我确信这个yaml是可用的、合规的，我不是第一次用它。我在我的openwrt/openclash里有用它。

**Comment by FoundTheWOUT** [comment]
304，现在不支持

**Comment by jacobin** [comment]
> 304，现在不支持

304是指什么？

**Comment by zzzgydi** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/27361820/201684631-0e5f6d58-bbd4-474b-a2d3-5be6b0b35da4.png">

导入后在vscode里显示的是这个字符集，改了改字符集就能正常使用。但目前确实导入不了。

**Comment by jacobin** [comment]
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/27361820/201684631-0e5f6d58-bbd4-474b-a2d3-5be6b0b35da4.png">
> 
> 导入后在vscode里显示的是这个字符集，改了改字符集就能正常使用。但目前确实导入不了。

我清楚了。是字符集支持不到。这种领域，跟文本处理相关太深，对字符集的处理须要单独建立课题加以解决。

**Comment by jacobin** [comment]
我清楚了。是字符集支持不到。这种领域，跟文本处理相关太深，对字符集的处理须要单独建立课题加以解决。

**Comment by jacobin** [comment]
@zzzgydi：嗨，老大，这个有关字符编码的问题，已经又走过了两个版本了，还是不得以解决吗？ 谢谢！

**Comment by zzzgydi** [comment]
现在处理了，下个版本发，兼容了UTF-8 with BOM这种格式

**Comment by jacobin** [comment]
V1.2.3解决了。谢谢。

**Comment by Andy963** [comment]
clash 1.3.1 core: 1.4.3 meta win10
出现这种问题了，本地在用的配置文件传到远程，下载说invalid yaml, 一个可以正常更新的订阅我保存为yaml后上传，再订阅也提示invalid yaml， 即使上面那个链接我用verge 订阅，正常导入，我将profile里面的yaml上传到onedrive共享再导入，又提示invalid yaml
