### ISSUE TITLE
切换系统代理热键设置为CTRL+ALT+SHIFT+:后，就闪退，无法打开

### ISSUE THREAD

**Issue by pheotry** [zzzgydi/clash-verge#287]
日志：2022-11-17 15:03:26 - 拒绝访问。 (os error 5)

去配置文件里删除热键设置后就可以正常打开
- 'toggle_system_proxy,CTRL+SHIFT+ALT+:'

**Comment by zzzgydi** [comment]
```
thread 'tokio-runtime-worker' panicked at 'invalid accelerator: AcceleratorParseError("Couldn't identify \":\" as a valid `KeyCode`")', tauri-runtime-wry-0.12.0\src\global_shortcut.rs:70:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Windows 11 里报这个错，估计要映射成`Shift+;`

**Comment by pheotry** [comment]
> ```
> thread 'tokio-runtime-worker' panicked at 'invalid accelerator: AcceleratorParseError("Couldn't identify \":\" as a valid `KeyCode`")', tauri-runtime-wry-0.12.0\src\global_shortcut.rs:70:29
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Windows 11 里报这个错，估计要映射成`Shift+;`

解决了
