### ISSUE TITLE
failed to update clash config with status 400

### ISSUE THREAD

**Issue by ikkyusan123** [zzzgydi/clash-verge#289]
用[网上脚本](https://github.com/emptysuns/Hi_Hysteria)安装的hysteria，然后下载的metaHys.yaml，导入到clash verge里面，启动配置时提示failed to update clash config with status 400，请问怎么处理呢？

**Comment by zzzgydi** [comment]
换clash meta核了吗

**Comment by ikkyusan123** [comment]
这是我的配置文件，能否帮忙测试一下，我在clash for windows软件里面能用，但是在clash verge用不了。[metaHys.zip](https://github.com/zzzgydi/clash-verge/files/10040911/metaHys.zip)

**Comment by ikkyusan123** [comment]
我刚重新试了一下，又弹出新的错误，error sending request for url（http://127.0.0.1:9090/configs）:error;trying to connect:tcp connect error:由于目标计算积极拒绝，无法连接。（os error 10061）

**Comment by zzzgydi** [comment]
alpn那里改成`alph: h3`

meta 1.13.1 版本用的是上面这个写法，1.13.2才支持你现在的写法，verge的meta还没更新。

**Comment by ikkyusan123** [comment]
谢谢回复，改了后弹出新的错误error sending request for url（[http://127.0.0.1:9090/configs）:error;trying](http://127.0.0.1:9090/configs%EF%BC%89:error;trying) to connect:tcp connect error:由于目标计算积极拒绝，无法连接。（os error 10061）。
我在日志里面看到了2条错误，提示无法下载geoip.dat，我从别的地方复制了一份geoip.dat到软件目录下，发现可以使用了，谢谢作者回复，可以关贴了。
