### ISSUE TITLE
修改Clash字段后不自动刷新配置，需要手动重启Clash核心

### ISSUE THREAD

**Issue by st-youth** [zzzgydi/clash-verge#292]
修改Clash字段如局域网连接、日志等级后，运行配置里的值没有自动修改，而需要手动重启核心才能生效。不太清楚是bug还是feature，麻烦赐教！

**Comment by zzzgydi** [comment]
修改allow lan log level那些其实是生效的，但是这些不会同步到运行配置里，后续可以优化优化
