### ISSUE TITLE
最新版本【1.2.0】开机时默认为Rule模式

### ISSUE THREAD

**Issue by OnlyFor** [zzzgydi/clash-verge#299]
如题，当配置文件中设定mode: Script时，1.1.2启动时会自动跳到script模式，
但1.2.0版本为rule模式，且小窗口右键显示仍然为script，
启用Merge或Sscipt覆写mode为script均不能改变以上行为

**Comment by zzzgydi** [comment]
你是用的meta核心吧，meta是不支持script的

**Comment by zzzgydi** [comment]
我排查一下

**Comment by zzzgydi** [comment]
你在`~/.config/clash-verge/verge.yaml`文件里加一行`enable_builtin_enhanced: false`，然后重启软件，看看有没有效果

**Comment by zzzgydi** [comment]
你可以再看看，verge.yaml配置里有没有`clash-core: clash`这个字段

**Comment by zzzgydi** [comment]
现在这样也能用，但出现这种情况多多少少是个bug，我这边还复现不了

**Comment by zzzgydi** [comment]
这个问题其实不是bug，是个feature，但也只是针对使用clash-meta的情况，现在的问题就是不知道为啥使用clash也出现这个问题。

**Comment by zzzgydi** [comment]
> 我开始用的时候可以选的地方都试过，是不是切到meta再切回来存在一些异常？

理论上不会，实际上好像也不会

**Comment by tshes** [comment]
大佬们我想一下，我是win10用户安装完成后双击打开，程序只在右下角任务栏闪了一下就没了 该怎么解决？

**Comment by zzzgydi** [comment]
@tshes 有装webview2吗，有log可以提供吗

**Comment by tshes** [comment]
我不太清楚啊 之前的shawdowsocks无法使用后我就安装那个新的安装流程走，说安装好后就可以了，但是我安装后是双击软件没有反应， 就在任务栏闪了一下鼠标靠过去就没了，log我也不知道该怎么打开qwq


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzgydi/clash-verge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzzgydi/clash-verge] 最新版本【1.2.0】开机时默认为Rule模式 (Issue #299)





 
@tshes 有装webview2吗，有log可以提供吗

**Comment by zzzgydi** [comment]
@tshes 在这里下载安装Webview2 https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

不过可能不是没安装的问题，然后再看看log，在你的用户目录下`C:/Users/你的用户名/.config/clash-verge/logs`；

- 如果有文件：发最新的日志文件上来
- 如果没有文件：截图`C:/Users/你的用户名/.config/clash-verge`目录结构
- 如果都没有：确保你不是arm机器
- 如果都不是：新建个issue，附上上述信息，我再排查排查

**Comment by dnvcupid** [comment]
1.2.0，规则模式，把系统代理勾去掉还能上外网，设置-网络-高级-代理  是没启用的，把软件退出，还是能上外网。。。

**Comment by zzzgydi** [comment]
@dnvcupid 软件退出还能用，说明没有正确关闭clash/clash-meta内核，或者你有别的vpn。。。
