### ISSUE TITLE
无法在Windows 7上安装

### ISSUE THREAD

**Issue by Cavolo** [zzzgydi/clash-verge#3]
如果需要更多细节，请指出。

**Comment by zzzgydi** [comment]
可以看看具体是什么错，会不会是没装webview2 <https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section>

**Comment by Cavolo** [comment]
> 可以看看具体是什么错，会不会是没装webview2 https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

是这个问题，已可以正常使用
