### ISSUE TITLE
clash-meta内核不更新

### ISSUE THREAD

**Issue by adaaaaaa** [zzzgydi/clash-verge#300]
系统是arch
clash-verge版本是1.2.0
软件里clash内核是meta的1.10.0
arch系统里面的clash-meta版本是1.13.2了
前天刚从clash-verge的1.1.2升级到了1.2.0,但是clash内核还是1.10.0没有变化
怎么更新呢？

**Comment by zzzgydi** [comment]
1.2.0带的meta核心版本是1.13.2，如果打开软件看到的版本还是旧的，说明可能没有成功替换，你就手动替换核心就好，名字保持一样。

**Comment by adaaaaaa** [comment]
@zzzgydi 
我重装了一次clash-meta和clash-verge都是最新的
但是，最后verge还是给我装了旧版本的meta.。。。
怎么替换核心啊？要替换哪些文件，一般在什么目录？

**Comment by zzzgydi** [comment]
和clash-verge执行文件在同一个目录

**Comment by zzzgydi** [comment]
是替换clash-meta执行文件

**Comment by adaaaaaa** [comment]
@zzzgydi 
我的clash-verge执行文件在/usr/bin/目录下，而且还有一堆其他应用的文件。。。
那个meta文件，看起来就是arch安装的，不是verge下载的meta文件吧？

**Comment by adaaaaaa** [comment]
@zzzgydi 
archlinux重装过两次verge了，一次连配置文件夹都删了
但是，每次选meta内核的时候，都是1.10.0,这次重装，我把clash-premium也装上了，结果里面就能识别到我安装的版本
但是，meta还是1.10.0是显示错了，还是说自带的，还是说默认会去下载这个低版本的meta？

**Comment by zzzgydi** [comment]
有个问题，archlinux版本是在哪安装的

**Comment by adaaaaaa** [comment]
@zzzgydi 
verge，meta都是archlinuxcn源安装的
premium是aur才有最新版本

**Comment by zzzgydi** [comment]
我没有发布到什么源上的，估计是别人维护的。这个要么就自己打包一个吧，要么就找到clash-meta执行文件替换掉

**Comment by adaaaaaa** [comment]
@zzzgydi 
打包者   lilac (on behalf of sukanka) <su975853527@gmail.com>
哦，好吧，我再看看怎么搞。。。

**Comment by matkyla** [comment]
我也出现了类似问题，同是arch aur源安装。请问你后来找到方法了吗？

**Comment by matkyla** [comment]
这个问题应该是aur中clash-meta打包的问题。替换成clash-meta执行文件就解决了。

**Comment by sukanka** [comment]
> 但是，meta还是1.10.0，是显示错了，还是说自带的，还是说默认会去下载这个低版本的meta？

这个问题我才看到，不过确实是显示错了， aur 的构建脚本没有去改这里的 version,就一直是 1.10
https://github.com/MetaCubeX/Clash.Meta/blob/Meta/constant/version.go#L5

**Comment by adaaaaaa** [comment]
@sukanka 
clash-meta还不好用，经常会打不开网页啊，或者卡网速的。。。只能先切换会clash-premium了。。。
