### ISSUE TITLE
希望增加 ：延迟测试超时 的配置 且定时器能用于真正的节点链接

### ISSUE THREAD

**Issue by dongriljf** [zzzgydi/clash-verge#301]
同一个 vless节点在
Clash.Verge （用Clash.Meta核心）超时 在Clash.for.Windows 就能用。

在Clash.for.Windows 发现有此选项 ：【延迟测试超时】 设置。

就像 v2ray 有这个 Handshake: 4 # Handshake time limit, Second 类似的配置保证TCP能链接上。

**Comment by dongriljf** [comment]
也可能不是时延问题，可能是兼容问题。我有一个openVZ的VPS建了一个vmess节点，使用了基于lkl-haproxy 的BBR前置转发加速（但tls还是用Nginx来解，lkl-haproxy的加速效果很好10倍左右，前置tls时延一般都不小，我以为是时延比较大导致的超时，也可能是兼容问题），使用原始V2rayN和Clash.for.Windows 是能够连接的。不知道 Clash.Meta 是不是不认haproxy特征的tcp链接。
另外我发现vmess节点 tls 如果用 xray前置来解也不能连接，但是用Nginx前置来解tls是能链接的正常使用。
希望 能解决一下这个haproxy 前置和xray 前置解tls 的兼容问题（这个情况在客户端使用 V2rayN（xray）和Clash.for.Windows 是能使用的）。

**Comment by zzzgydi** [comment]
看起来和clash verge这个项目没啥关系，就先关了。在meta的issue里反馈就好。
