### ISSUE TITLE
新版本打开墙内网站非常慢

### ISSUE THREAD

**Issue by Lloydqiu** [zzzgydi/clash-verge#305]
设置了规则，打开墙内网站(baiddu.com, bilibili.com, sina.com)非常慢，但是墙外网站很快。日志中频繁出现
[TCP] dial DIRECT (match DomainSuffix(baidu.com)) to passport.baidu.com:443 error: dual stack tcp shake hands failed
用的是系统代理，ipv6梯子，在公司电脑上则没有这个问题。

版本 1.2.0
内核 clash meta 1.13.2

切换成premium内核就很快。

**Comment by zzzgydi** [comment]
可以更新clash-meta核心试试 https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.13.2
