### ISSUE TITLE
Service Mode 问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [zzzgydi/clash-verge#306]
v1.2.0(已重新安装服务模式) 服务模式下启动软件时和切换 clash core 时无法正确加载 profile

**Comment by zzzgydi** [comment]
> 正确加载 profile

有啥报错或者日志提供吗

**Comment by FoundTheWOUT** [comment]
可以确定的是用了旧的 clash service，下午重装 service 的时候没有更新成功。估计是因为 service进程 没有被干掉而导致的，刚刚手动干掉进程再更新就可以了。
另外我发现关掉 service mode，service 进程确实还在跑。
