### ISSUE TITLE
vless+xtls时一直报错

### ISSUE THREAD

**Issue by zqs125** [zzzgydi/clash-verge#308]
在使用vless+xtls模式时，一直报错：connect error: dual stack tcp shake hands failed，页面要刷新好几次才能打开，测试延时全都显示的error，软件版本为：1.2，meta内核是1.13.2版

**Comment by zzzgydi** [comment]
可以自行更换clash meta核心再尝试

**Comment by zqs125** [comment]
这个meta核心要怎么换？我从meta项目里下载了几个win64版本的，放到clash-verge目录里，并改名为clash-meta.exe，可在软件的设置里认不到这个meta的版本号，启用配置也报错

**Comment by zqs125** [comment]
是的，就是执行目录，和Clash Verge.exe同一级目录

**Comment by zzzgydi** [comment]
那应该没啥问题才对，换好了之后重启软件，就ok了。

> 可在软件的设置里认不到这个meta的版本号，启用配置也报错

是什么报错

**Comment by zqs125** [comment]
![image](https://user-images.githubusercontent.com/27925408/204494235-34876dad-90c8-4137-9e0f-1fb9055dfac6.png)
![image](https://user-images.githubusercontent.com/27925408/204494422-d775373a-a409-4bc3-ab83-6a64b267991d.png)
![image](https://user-images.githubusercontent.com/27925408/204494503-d3a8c145-3001-4f70-88f1-a90d8e1f5de6.png)

如图所示

**Comment by zzzgydi** [comment]
看看日志文件

**Comment by zqs125** [comment]
![image](https://user-images.githubusercontent.com/27925408/204502374-abff2044-660b-40e9-bbf2-68cec5ce840e.png)

你方便了可以测试下

**Comment by zzzgydi** [comment]
你关掉服务模式试试，另外，新版服务模式要重新安装服务。

**Comment by zqs125** [comment]
我都没有用服务，使用的是系统代理的方式

**Comment by zzzgydi** [comment]
哦对……那p核是能跑，meta核跑不了吗。方便给个配置看看吗。看下来是配置有问题，然后解析meta输出的错误原因出问题了，就空白了。

**Comment by zqs125** [comment]
![image](https://user-images.githubusercontent.com/27925408/204522068-c4edfacf-33f8-4d20-96c0-a9c2046dfbae.png)
很简单的一个配置

**Comment by zqs125** [comment]
proxies:
  - name: "test"
    type: vless
    server: abc.ml
    port: 443
    uuid: xxxx-xxxx
    network: tcp
    servername: abc.ml
    flow: xtls-rprx-direct
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - test

rules:
  - GEOIP,private,DIRECT
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,Proxy

就这样很简单的一个配置

**Comment by zzzgydi** [comment]
这个应该用proxy-groups

```
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - test
```

另外，可以确认一下 配置目录(`~/.config/clash-verge`)有没有包含geoip.dat和geosite.dat文件

**Comment by zqs125** [comment]
> 这个应该用proxy-groups
> 
> ```
> proxy-groups:
>   - name: Proxy
>     type: select
>     proxies:
>       - test
> ```
> 
> 另外，可以确认一下 配置目录(`~/.config/clash-verge`)有没有包含geoip.dat和geosite.dat文件

配置就是这样的，只是我粘贴到回复框后显示出的格式样子变了
![image](https://user-images.githubusercontent.com/27925408/204526675-9a90b9e3-c2b0-4ed1-ba51-21ae96179185.png)
![image](https://user-images.githubusercontent.com/27925408/204526771-64ca6c22-534b-4622-8b1f-b97419c6b4df.png)

这些都有的

**Comment by zqs125** [comment]
我之前没有用过clash核心的软件，这是第一次用，也不知道是我哪里弄的不对还是什么情况，我重新下了1.1.2版本，然后是一直把下面这个错误，不明白要怎么样才能正常使用呢？
![image](https://user-images.githubusercontent.com/27925408/204776529-3864190c-e08b-4af2-ad10-a04a2445de3f.png)
