### ISSUE TITLE
应用开启后，无法访问墙内网站和代理延迟测试

### ISSUE THREAD

**Issue by Krosec** [zzzgydi/clash-verge#309]
#### Bug描述
- 开启clash.verge，使用系统代理后，打开墙内网站（如百度）和首次打开墙外网站（如谷歌），浏览器会显示“The connection was reset.”。
- 日志频繁出现如下的警告
[TCP] dial AsianTV (match DomainKeyword(bilibili)) to api.vc.bilibili.com:443 error: dual stack tcp shake hands failed
- 使用clash.verge测试代理延迟无法返回正常延迟。

#### 运行环境
- 操作系统：Windows 10 22H2
- Verge Version: v1.2.0
- Clash Core: v1.13.2 Meta

#### 临时解决方案
- 将clash内核回滚至v1.12.0 Meta

**Comment by zzzgydi** [comment]
看下来是meta核心的问题，可以反馈到meta的issue

**Comment by Krosec** [comment]
是meta核心的问题，根据[Clash.Meta #221](https://github.com/MetaCubeX/Clash.Meta/issues/221)提起的方法，用go 1.18重新编译meta核心问题就解决了
