### ISSUE TITLE
该选什么 IDE 编译

### ISSUE THREAD

**Issue by Agoines** [zzzgydi/clash-verge#31]
本来是想自己去学习怎么去制作一个 Clash 的客户端，自己的需求是跨平台。在 github 闲逛的时候，发现了大大的开源库，因为之前自己都是用 idea 之类的，没接触过大大使用的这种方案，然后我自己平时也是做设计的，也想为开源库提供一点自己的贡献，所以想请教下大大是用什么编译的。

**Comment by zzzgydi** [comment]
我是用的VScode，VScode插件推荐有rust-analyzer和Prettier。再安装一些环境：

- 安装Rust
- 安装Nodejs，再安装yarn
- Windows的话，安装Microsoft Visual Studio C++ build tools 2019
- macOS的话，安装xcode

具体的环境要求可以看 https://tauri.studio/docs/getting-started/prerequisites

**Comment by zzzgydi** [comment]
先在项目根目录执行 yarn install

**Comment by Agoines** [comment]
> 先在项目根目录执行 yarn install

在 Mac 该如何 Debug 呢？打开 http://localhost:3000 以后，选项没办法使用，是不是要修改什么地方的指定对应的平台？然后作者大大有 tg 或者其他联系方式没？

**Comment by zzzgydi** [comment]
无tg，执行yarn dev之后，应该是要出现一个应用窗口的。如果没有的话就是有问题。直接在浏览器打开这个链接，是有东西但是没啥用。

**Comment by Agoines** [comment]
> 无tg，执行yarn dev之后，应该是要出现一个应用窗口的。如果没有的话就是有问题。直接在浏览器打开这个链接，是有东西但是没啥用。

当时 yarn dev 出现了下面的

```
error: failed to run custom build command for `clash-verge v0.1.0 (/Users/agoines/Documents/Vs Code/clash-verge/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/agoines/Documents/Vs Code/clash-verge/src-tauri/target/debug/build/clash-verge-e5ae32e62c1d73a8/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: path matching sidecar/clash-x86_64-apple-darwin not found.', /Users/agoines/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.4/src/lib.rs:146:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

是因为没下载 clash 的二进制文件嘛，还是其他的

**Comment by zzzgydi** [comment]
先 `yarn install`
再 `yarn run check`
再 `yarn dev`

**Comment by Agoines** [comment]
> 先 `yarn install`
> 再 `yarn run check`
> 再 `yarn dev`

嗷嗷，昨天 `yarn run check` 以后就没管过了，然后重新 `yarn run check` 以后看了看日志，知道了
`FetchError: request to https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb failed, reason: read ETIMEDOUT`
自己在浏览器下载没问题，然后为了方便我索性使用镜像
`https://doc.fastgit.org/zh-cn/guide.html`
然后解决了，确实比较玄学（或者墙内污染比较严重），
然后`yarn dev`确实没问题了
