### ISSUE TITLE
deb安装的包在普通用户下无法启动TUN模式代理，在root模式下无法保存用户数据

### ISSUE THREAD

**Issue by Bob0111** [zzzgydi/clash-verge#320]
普通用户执行：Start TUN listening error: configure tun interface: operation not permitted
clash for windows是采用向系统里面添加服务的方式来进行的提权，希望本软件也能提供类似的功能。

**Comment by Binly42** [comment]
see https://github.com/zzzgydi/clash-verge/issues/182

**Comment by zzzgydi** [comment]
1.3.0版本支持了针对clash内核提权，使用TUN就没问题了
