### ISSUE TITLE
请问有没有docker版本？想安装在群晖NAS中使用

### ISSUE THREAD

**Issue by zwjie12** [zzzgydi/clash-verge#321]
在docker中没搜到这个名字的镜像，如果没有docker版本的话，群晖Intel 64位的NAS该下载哪个版本？怎么安装？
谢谢。

**Comment by zzzgydi** [comment]
在nas里直接装clash内核就行吧，又不需要gui

**Comment by zwjie12** [comment]
> 在nas里直接装clash内核就行吧，又不需要gui

大佬，nas中该怎么装Clash内核？

**Comment by zzzgydi** [comment]
可以google一下，我也没玩过
