### ISSUE TITLE
ArchLinux上无法启用TUN模式

### ISSUE THREAD

**Issue by br7roy** [zzzgydi/clash-verge#323]
平台:ArchLinux
问题:无法开启TUN模式
和clash有关的包:
![image](https://user-images.githubusercontent.com/14069594/207822721-f0373b7a-d3b5-4be9-98cb-05ced980cee0.png)
日志:
2022-12-15 17:27:38 INFO - [clash]: level=warning msg="[TUN] default interface changed by monitor,  => wlo1"
2022-12-15 17:27:38 INFO - [clash]: level=error msg="Start TUN listening error: configure tun interface: operation not permitted"
配置:
![image](https://user-images.githubusercontent.com/14069594/207823275-6f22a2e0-f3eb-4b57-9f93-e9a963162784.png)
![image](https://user-images.githubusercontent.com/14069594/207823322-27ce4aa9-2fb4-4042-9315-deef572eabeb.png)
clash字段2个没有勾
![image](https://user-images.githubusercontent.com/14069594/207823806-043cf410-7f90-4b1d-9d95-c7d2ea954307.png)
执行了[setcap](https://github.com/zzzgydi/clash-verge/issues/182)方案
相关服务:
![image](https://user-images.githubusercontent.com/14069594/207824355-fc65bcef-ce75-41ee-93f8-5c946671221a.png)

**Comment by xz-dev** [comment]
安装 https://aur.archlinux.org/packages/clash-meta-cap-git

**Comment by br7roy** [comment]
我发现是我这里的协议问题

**Comment by strahe** [comment]
@br7roy 请问是什么问题， 我也碰到一样的情况。

**Comment by jinzhongjia** [comment]
补充：tun模式下直接使用aur的clash-meta或者Community下的clash内核会没有setcap权限，需要额外配置，见#182
