### ISSUE TITLE
希望开发一个强制开启udp转发选项

### ISSUE THREAD

**Issue by BaronChushao** [zzzgydi/clash-verge#324]
就像surfboard那样，弄个全协议强制开启udp转发选项
![image](https://user-images.githubusercontent.com/98247704/208231129-a250fa86-f64d-4506-beb1-d0dd5a4bff8a.png)

**Comment by BaronChushao** [comment]
@zzzgydi

**Comment by zzzgydi** [comment]
这玩意咋实现，强制给所有节点都加上`udp: true`吗

**Comment by BaronChushao** [comment]
我已经给全部节点加上了udp:true了，但是我想要的是流量全部走udp转发，就是下图这个TCP变UDP
![屏幕截图 2022-12-19 115146](https://user-images.githubusercontent.com/98247704/208344481-8de28a64-0cab-4dbf-a436-7b9cfee622f2.jpg)

**Comment by BaronChushao** [comment]
不太懂，这个可以实现吗？
