### ISSUE TITLE
卡顿以及Bug

### ISSUE THREAD

**Issue by kylinholmes** [zzzgydi/clash-verge#328]
运行环境
----
**OS**: Intel, x64, Linux Mint
**DE**: Cinnamon

Enhancement
----
在进行一些操作的时候，很容易产生卡顿。
- 从托盘中打开面板，大概有2-3s的延迟。
- 在代理界面中，展开/折叠selector会有一次可感知的卡顿。

Bug Report
----
另外存在一个Bug：
设置开机自启，每次开机时，不能正常显示代理界面中的节点，
并且代理也并没有正常运行，需要重新打开应用。

**Comment by kylinholmes** [comment]
再提一个enhancement
- UI还有很大的优化空间

**Comment by kylinholmes** [comment]
再提一个enhancement
- UI还有很大的进步空间

**Comment by zzzgydi** [comment]
> UI还有很大的进步空间

这个可以展开讲讲
