### ISSUE TITLE
Windows Bug

### ISSUE THREAD

**Issue by Agoines** [zzzgydi/clash-verge#33]
刚才在 Windows 测试，Theme Blur 选项打开，最大化以后点击关闭选项，必出这个 Bug

![IMG_20220316_132315.jpg](https://user-images.githubusercontent.com/50230626/158522481-933153e5-f846-4054-a8e6-73bfaa28ff13.jpg)

版本：0.0.23
平台：Windows

**Comment by zzzgydi** [comment]
Windows 11? 不开blur选项，这样操作应该也能复现

**Comment by Agoines** [comment]
> Windows 11? 不开blur选项，这样操作应该也能复现

对, Window 11, 不开也能稳定复现

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/blob/ec41bb9c7021a1ade26f6e2e4f6be60111f1e574/src-tauri/src/utils/resolve.rs#L64

可以尝试注释掉这一行，再看看

**Comment by Agoines** [comment]
> https://github.com/zzzgydi/clash-verge/blob/ec41bb9c7021a1ade26f6e2e4f6be60111f1e574/src-tauri/src/utils/resolve.rs#L64
> 
> 可以尝试注释掉这一行，再看看

好的，我去 Windows 配置下编译环境，然后试试，我平时都在 Mac，我这边有 Win11 和 Win10，还有一个英特尔的 Mac 都能测试。

**Comment by Agoines** [comment]
> https://github.com/zzzgydi/clash-verge/blob/ec41bb9c7021a1ade26f6e2e4f6be60111f1e574/src-tauri/src/utils/resolve.rs#L64
> 
> 可以尝试注释掉这一行，再看看

然后没了模糊还有边框，我怀疑是关闭的地方没写好
![IMG_20220316_152222.jpg](https://user-images.githubusercontent.com/50230626/158537421-a2c44bf7-1b88-41f6-9abf-a3aeca6da5aa.jpg)

**Comment by Agoines** [comment]
> Windows 11? 不开blur选项，这样操作应该也能复现

Win10 也能稳定复现

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/blob/ec41bb9c7021a1ade26f6e2e4f6be60111f1e574/src-tauri/src/utils/resolve.rs#L63

那应该是这一行的锅，win10能复现

**Comment by Agoines** [comment]
> https://github.com/zzzgydi/clash-verge/blob/ec41bb9c7021a1ade26f6e2e4f6be60111f1e574/src-tauri/src/utils/resolve.rs#L63
> 
> 那应该是这一行的锅，win10能复现

删除
```
set_shadow​(​&​window, ​true​).​unwrap​();
apply_blur​(​&​window, ​None​).​unwrap​();
```
Bug 不会复现

只删除
```
set_shadow​(​&​window, ​true​).​unwrap​();
```
会出现一个模糊，不会出现线条

**Comment by zzzgydi** [comment]
确实，这是用了 https://github.com/tauri-apps/window-vibrancy 和 https://github.com/tauri-apps/window-shadows 。Windows 里又必须要依赖这些，不然界面不好看

**Comment by Agoines** [comment]
> 确实，这是用了 https://github.com/tauri-apps/window-vibrancy 和 https://github.com/tauri-apps/window-shadows 。Windows 里又必须要依赖这些，不然界面不好看

你觉得这种怎么样，我可以尝试做类似的设计（如果可以的话，我可以先画设计图。但是可能写代码的时候，可能还有很多东西要请教你）
![screenshot.png](https://user-images.githubusercontent.com/50230626/158546515-2bbe2676-70c3-405e-865b-b9dd116f4d5a.png)

![screenshot.png](https://user-images.githubusercontent.com/50230626/158546546-e2d12371-5b36-4c83-bb22-327b792f72ba.png)

**Comment by zzzgydi** [comment]
做这些设计，是指的啥意思

**Comment by Agoines** [comment]
> 做这些设计，是指的啥意思

刚才去找了找，就是类似这种概念图，（因为确实自己没做过跨平台，相比跨平台，我在 UI 这块能有一点点经验），想给开源库出点力，但是似乎就顶多设计方面我可以出力🤣
![IMG_20220316_163742.jpg](https://user-images.githubusercontent.com/50230626/158549786-dc6974c4-929f-45fd-8a4b-cd4c666588c1.jpg)![IMG_20220316_163728.jpg](https://user-images.githubusercontent.com/50230626/158549820-26ef5c6e-609b-409c-bbae-03f4ec3faade.jpg)

**Comment by zzzgydi** [comment]
上面提到的两个库。是因为在Windows里去掉系统默认的窗口最上面那个控制条之后（包含默认的最小化最大化关闭几个按键那个），窗口就没有系统窗口本身的那种阴影，于是引入上面提到的库其中一个，另一个是搞那个blur的。

然后呢，现在用了这两个库，就存在这个issue里提到的bug。用了就有bug，不用就不好看。这里说的不好看，不是你发的那些不好看，emmmm，这个不太好说明。而且在Window11里可能又不像在Window10里那么不好看。

另外，你提到的ui方面呢，确实可以改进改进，毕竟还有Connections页面，我是完全没做的。。。这个ui的改进可以提个新的issue或者在discussion里讨论也行。

**Comment by Agoines** [comment]
> 上面提到的两个库。是因为在Windows里去掉系统默认的窗口最上面那个控制条之后（包含默认的最小化最大化关闭几个按键那个），窗口就没有系统窗口本身的那种阴影，于是引入上面提到的库其中一个，另一个是搞那个blur的。
> 
> 然后呢，现在用了这两个库，就存在这个issue里提到的bug。用了就有bug，不用就不好看。这里说的不好看，不是你发的那些不好看，emmmm，这个不太好说明。而且在Window11里可能又不像在Window10里那么不好看。
> 
> 另外，你提到的ui方面呢，确实可以改进改进，毕竟还有Connections页面，我是完全没做的。。。这个ui的改进可以提个新的issue或者在discussion里讨论也行。

明白了，就是跟其他界面不太一样感觉应用窗口看起来不好看，我刚才理解错了🤣，这个问题找到了问题，我就把议题关闭了吧，作者大大辛苦了

**Comment by zzzgydi** [comment]
现在的项目在界面开发这一块，就是Web开发，应该还算比较简单。然后现在使用的是MUI这个组件库，https://mui.com/zh/getting-started/installation/ 感兴趣也可以看看。

**Comment by Agoines** [comment]
> 现在的项目在界面开发这一块，就是Web开发，应该还算比较简单。然后现在使用的是MUI这个组件库，https://mui.com/zh/getting-started/installation/ 感兴趣也可以看看。

好的，我去看看
