### ISSUE TITLE
怎么修改TUN的stack Mode

### ISSUE THREAD

**Issue by FrankOu2001** [zzzgydi/clash-verge#331]
怎样把TUN的stack mode改为system？

**Comment by FoundTheWOUT** [comment]
现在只能自己改配置文件了。
本来打算写个配置面板的，但由于现在内部用的 external control 去拿的配置，这个是拿不到 tun 配置的。如果要写的话感觉要加个读本地文件的 api。问问 @zzzgydi 的意见。

**Comment by zzzgydi** [comment]
后续我加个设置项修改吧

**Comment by zzzgydi** [comment]
现在可以新建一个merge profile，在里面写一个完整的tun配置，然后在设置页-clash fields里勾上tun。

**Comment by zzzgydi** [comment]
@duokebei tun的设置要放在顶层，不要放在`prepend-proxy-groups`下

**Comment by duokebei** [comment]
> @duokebeitun的设置要放于顶层，不要放于`prepend-proxy-groups`下

是append-proxy-groups这个选项里面吗？

**Comment by duokebei** [comment]
> > 是append-proxy-groups这个选项里面吗？
> 
> 都不是，你把其他文字都剪了吧，只留下
> 
> ```
> tun:
>   enable: true
>   ...
> ```

谢谢作者，问题解决，给后续遇到次此问题的人提供一个截图参考。
![image](https://user-images.githubusercontent.com/75022552/212849490-026de99d-c7c0-45aa-9dd6-0a1037c2f74a.png)

**Comment by duokebei** [comment]
> > 是append-proxy-groups这个选项里面吗？
> 
> 都不是，你把其他文字都剪了吧，只留下
> 
> ```
> tun:
>   enable: true
>   ...
> ```

看作者能不能在UI里实现，改配置文件确实麻烦了点。
