### ISSUE TITLE
TUN模式启动报错

### ISSUE THREAD

**Issue by InspoOnU** [zzzgydi/clash-verge#336]
启动TUN就会显示
Start TUN listening error: configure tun interface: Connect: operation not permitted
系统版本是Ventura 13.1 amd64，似乎是系统升级后出现的错误

**Comment by BackTrackCRoot** [comment]
好像是权限问题，你用管理员权限试试？

**Comment by inRm3D** [comment]
https://github.com/zzzgydi/clash-verge/issues/182#issuecomment-1236334912

**Comment by Ham3D** [comment]
how about mac os, we dont have such a thing as administrator.

**Comment by zzzgydi** [comment]
1.3.0版本已经支持在界面中点击提权啦，可以试试

**Comment by chenjiangui** [comment]
> 1.3.0版本已经支持在界面中点击提权啦，可以试试

Start TUN listening error: configure tun interface: Connect: operation not permitted
目前是1.3.0 无法在界面中提权, 系统13.3
