### ISSUE TITLE
Ubuntu 20.04 LTS 无法启动 

### ISSUE THREAD

**Issue by Declarcall** [zzzgydi/clash-verge#339]
安装的是这个版本的 [clash-verge_1.2.1_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.2.1/clash-verge_1.2.1_amd64.deb) 
```
$ clash-verge
clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
降级安装 [clash-verge_1.2.0_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.2.0/clash-verge_1.2.0_amd64.deb) 则可以正常运行

**Comment by chenxv399** [comment]
同样的情况 [clash-verge_1.2.1_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.2.1/clash-verge_1.2.1_amd64.deb)无法在UBUNTU 20.04 LTS启动，报错为同样的报错。安装旧版本正常运行。

**Comment by inRm3D** [comment]
看起来是缺了 libssl.so.3

参考这个 https://blog.csdn.net/Asgard_Hu/article/details/127532328

http://security.ubuntu.com/ubuntu/pool/main/o/openssl/ 在这里面找找对应的包。

**Comment by limasqbank** [comment]
[clash-verge_1.2.1_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.2.1/clash-verge_1.2.1_amd64.deb)
[clash-verge_1.2.2_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.2.2/clash-verge_1.2.2_amd64.deb)
这两个版本都无法在Debian 11上启动
报错信息如下
org.kde.krunner[1538707]: /usr/bin/clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file:No such file or directory

**Comment by zzzgydi** [comment]
尝试一下1.3.0

**Comment by Declarcall** [comment]
安装了 这个版本的 [clash-verge_1.3.0_amd64.deb](https://github.com/zzzgydi/clash-verge/releases/download/v1.3.0/clash-verge_1.3.0_amd64.deb) 仍旧启动报错
```
$ clash-verge 
clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
再次尝试安装 ``` libssl3_3.0.2 ```

```
sudo apt install -y ./libssl3_3.0.2-0ubuntu1.8_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libssl3' instead of './libssl3_3.0.2-0ubuntu1.8_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl3 : Depends: libc6 (>= 2.34) but 2.31-0ubuntu9.9 is to be installed
E: Unable to correct problems, you have held broken packages.
```
看来必须把系统升级到 21.10 或 22.04， 在 22.04 上则没有任何问题。

**Comment by lblbk** [comment]
> 尝试一下1.3.0

同样报错

```
$ clash-verge
clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
