### ISSUE TITLE
Tun Mode Bug

### ISSUE THREAD

**Issue by Agoines** [zzzgydi/clash-verge#34]
打开 Tun Mode，重启客户端，然后客户端就炸了![IMG_20220316_195353.jpg](https://user-images.githubusercontent.com/50230626/158584576-68465fe0-bf22-47b4-9b0a-91169520ba46.jpg)

**Comment by zzzgydi** [comment]
这个是因为没安装wintun.dll，clash启动失败而已，后面会琢磨琢磨内置这个东西

**Comment by inRm3D** [comment]
linux 也遇到这个问题。开了 tun 模式就出问题。看了下 commit 历史 https://github.com/zzzgydi/clash-verge/commit/7074bbc4055cdf59c642c32d9dc6a8b0858a1d71 只内置了 win 的。

**Comment by zzzgydi** [comment]
@inRm3D 这个dll在linux上也需要的吗，tun模式开启出现问题的话，会不会是没有管理员权限

**Comment by inRm3D** [comment]
不清楚，cfw 闭源不清楚实现。翻了 issue 区没找到有价值的。搜了一下发现这个似乎是安装 tun 的 https://docs.cfw.lbyczf.com/contents/tun.html#linux
