### ISSUE TITLE
如何配置绕行名单

### ISSUE THREAD

**Issue by CloudShen-107** [zzzgydi/clash-verge#340]
如题，我在设置-系统代理设置的proxy bypass中添加了需要绕行的网站，但好像没效果。
要怎么才能配置绕行网站名单呢

**Comment by zzzgydi** [comment]
在bypass里设置，仅在使用系统代理的时候有效。如果使用tun模式，就需要在clash rules里设置过滤规则

**Comment by CloudShen-107** [comment]
把前置的https://去掉好像就行了

**Comment by Kill-pig-fly** [comment]
例如：
    *.abc.com;
    *.bcd.com;
    qwe.com;
    a.bac.com;

**Comment by Zxis233** [comment]
请问proxy bypass支持IP地址掩码的形式吗？

**Comment by zzzgydi** [comment]
> 请问proxy bypass支持IP地址掩码的形式吗？

可以试试

**Comment by LordHumphrey** [comment]
> 请问proxy bypass支持IP地址掩码的形式吗？

支持掩码吗？
