### ISSUE TITLE
win11无法安装Clash Verge Service

### ISSUE THREAD

**Issue by sailangyf** [zzzgydi/clash-verge#355]
win11系统，用的免安装便携版，之前是v1.2.0版本，一切正常，看到更新了，就直接把之前的版本删掉了，然后下了v1.2.1便携版，结果怎么都装不上Clash Verge Service了，报错failed to install service with status 1，猜测应该是更之前的冲突了，已经尝试了各种能想到的办法，包括删除.config目录下的clash verge文件夹，清理注册表等。
求助大佬！

**Comment by zzzgydi** [comment]
管理员权限执行 `sc delete clash_verger_service`

**Comment by sailangyf** [comment]
谢谢开发者大大回复，请问是在windows的powershell里面执行这个命令吗？如果是的话我已经执行了好几遍了，还是没有用，一样的报错。

**Comment by zzzgydi** [comment]
那在程序目录里找`/resources/install-service.exe`这个执行文件，用管理员权限执行一下，看看管用不

**Comment by sailangyf** [comment]
没有任何反应[哭脸]

**Comment by zzzgydi** [comment]
给终端截个图吧

**Comment by sailangyf** [comment]
我在clash verge里面把clash verge service卸载以后又正常下载最新版正常解压再安装就可以了，之前应该是直接删掉那个文件夹没有考虑clash verge service的事情，所以后面出现了冲突。这个的经验教训就是使用便携安装包的版本，如果切换新版本，应该先把service给卸载，然后退出软件删掉文件夹，否则就会有麻烦，希望大家注意这个问题。

**Comment by Luyiay** [comment]
其实是因为注册表里这个服务的路径还是之前的，修改注册表里的值就可以了

**Comment by Luyiay** [comment]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
