### ISSUE TITLE
[BUG] Click "New" in the "Profile"page, nothing happens.

### ISSUE THREAD

**Issue by sdttttt** [zzzgydi/clash-verge#356]
## env

- OS: Windows 11 22621.963
- version: clash-verge 1.2.1
- clash core version: 2022.11.25 Premium

## 描述

点击新建按钮，没有弹出新建对话框。

## 复现

打开clash-verge 仪表盘，切换到”**连接**“页面，切换回“**配置**”页面，点击新建。

https://user-images.githubusercontent.com/42728902/211724072-cf2d6aca-b1f7-45bd-942f-fdfc6162e23c.mp4

## 类似的issue

#329

**Comment by zzzgydi** [comment]
已修复，下个版本发
