### ISSUE TITLE
使用meta内核，无法更新geoip和geosite数据库

### ISSUE THREAD

**Issue by mobilefish** [zzzgydi/clash-verge#357]
clash.verge 1.2.0和1.2.1版本，使用clash.meta内核，使用geoip和geosite数据库来分流，更新最新的geoip.dat和geosite.dat后，重启电脑或者重启clash.verge后，又恢复到clash.verge自带的geoip和geosite。使用Country.mmdb也有同样的问题。
 
希望能修复这个问题。

**Comment by zzzgydi** [comment]
> 更新最新的geoip.dat和geosite.dat后 

 这个你是咋更新的

**Comment by mobilefish** [comment]
geoip.dat和geosite.dat 使用https://github.com/Loyalsoldier/v2ray-rules-dat 来更新，下载最新版本覆盖掉clash.verge中个人配置文件夹里的相应文件。
Country.mmdb 使用https://github.com/Loyalsoldier/geoip 来更新，下载最新版覆盖掉个人配置文件夹里的文件。

**Comment by zzzgydi** [comment]
现在的程序逻辑是，每次启动会将程序目录的resources文件夹里的`Country.mmdb, geoip.dat, geosite.dat, wintun.dll`这些文件拷贝到`~/.config/clash-verge`里。所以你应该换掉程序目录里的对应文件，然后重启应用就行

**Comment by mobilefish** [comment]
已经测试了，的确可以，问题解决，谢谢大佬
