### ISSUE TITLE
ipv6 setting not saved

### ISSUE THREAD

**Issue by LiuTangLei** [zzzgydi/clash-verge#362]
When I open the settings => IPv6 , set it checked, it's work

But if I refresh the profiles, IPv6 will auto off

Even if I add ipv6: true in the configuration yaml file, it is useless

**Comment by LiuTangLei** [comment]
It seems that the bug is triggered by turning on the Tun mode

**Comment by pk000** [comment]
I don't use TUN mode, but IPv6 still tun off every time I start the APP.
I use PORTABLE mode.
