### ISSUE TITLE
配置页面的刷新按钮不能正常工作

### ISSUE THREAD

**Issue by liangxyz** [zzzgydi/clash-verge#363]
如题，在配置页面右上角的刷新按钮，点击以后只提示刷新配置，但是我的所有配置文件都未更新，请问这个按钮是刷新全部配置的意思吗？问题是我当前选择的配置也没有刷新耶？

**Comment by zzzgydi** [comment]
这个刷新配置是指 刷新正在运行的配置，是重新将配置丢给clash。倒不是刷新每个profile的内容

**Comment by liangxyz** [comment]
> 这个刷新配置是指 刷新正在运行的配置，是重新将配置丢给clash。倒不是刷新每个profile的内容

谢谢指点，请问有没有刷新所有配置的按钮呀？

**Comment by zzzgydi** [comment]
> 请问有没有刷新所有配置的按钮呀？

暂时没有，只能一个个点刷新

**Comment by zzzgydi** [comment]
1.3.0版本已经加了更新所有配置的按键，可以看看
