### ISSUE TITLE
希望log-level allow-lan 端口设置 这几项能使用用户自定义中的配置，而不是在设置页面手动调整

### ISSUE THREAD

**Issue by GeorgeRudd** [zzzgydi/clash-verge#364]
开发者你好，我平常使用的方式是导入自定义的yaml配置文件。然后我发现程序的ipv6开关可以根据我导入的yaml文件自动调整，但是log-level allow-lan 端口设置 这几项必须在设置页面单独调整，能不能做成ipv6一样读取用户的yaml配置呢，或者做成clash字段里面打勾的形式，省去调整两次的麻烦。

**Comment by zzzgydi** [comment]
ipv6其实也不是根据导入的yaml文件的，另外两个也不打算这么整
