### ISSUE TITLE
"Clash Verge" is damaged and can't be opened / MacOS

### ISSUE THREAD

**Issue by MRdevX** [zzzgydi/clash-verge#369]
Hi,

I faced this issue while trying to open the Clash Verge. I tried [Clash.Verge_1.2.2_aarch64.dmg] and [Clash.Verge_1.2.1_aarch64.dmg] versions.

I'm using macOS Ventura 13.1 on Macbook Pro M1 Pro.

How to solve this problem?

**Comment by zzzgydi** [comment]
try `sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app` after installed

**Comment by MRdevX** [comment]
Thanks, It worked.
