### ISSUE TITLE
[Bug Report] 打开应用目录的错误提示

### ISSUE THREAD

**Issue by entr0pia** [zzzgydi/clash-verge#37]
系统版本: Windows 10 21H2
软件版本: v0.0.23 绿色版
Bug描述: 应用打开了, 但提示没有打开

![image](https://user-images.githubusercontent.com/30486766/158967124-a109ca26-86d5-4fea-add0-997f5f8c98ec.png)

**Comment by zzzgydi** [comment]
已经修复啦，暂时还没发版。

**Comment by zzzgydi** [comment]
修复已发版
