### ISSUE TITLE
当开启tun模式后能不能不要修改系统代理设置

### ISSUE THREAD

**Issue by myeveryheart** [zzzgydi/clash-verge#375]
![image](https://user-images.githubusercontent.com/6395323/212864381-253772eb-2391-442a-9682-61781d2b0123.png)
当开启了tun模式，系统代理设置可以保持disable。

**Comment by zzzgydi** [comment]
我倾向于开启tun之前手动关闭代理

**Comment by myeveryheart** [comment]
> 我倾向于开启tun之前手动关闭代理

我这样操作了。但是重新打开clash时，它会重新设置代理为手动。
