### ISSUE TITLE
代理组设置好的分流规则不能保持

### ISSUE THREAD

**Issue by lion-goose** [zzzgydi/clash-verge#389]
代理组设置好的分流规则，在重启或者更新、重新载入配置文件都会重置，每次打开软件都要再设置一遍分流。
希望可以记住设置好的分流规则。

**Comment by zzzgydi** [comment]
> 代理组设置好的分流规则

你这个分流规则咋设置的

**Comment by lion-goose** [comment]
> 
![111254](https://user-images.githubusercontent.com/59443350/215653757-354957db-f1bb-4ed4-a1ec-9da3060d66fb.jpg)
就是像这样的，我设置好的分流，每次都要重新设置一遍，就很不方便

**Comment by zzzgydi** [comment]
指的是每个分组选择的节点吗

**Comment by lion-goose** [comment]
> 指的是每个分组选择的节点吗

啊对，是这意思

**Comment by zzzgydi** [comment]
有保存之前选择节点的功能，但是目前最新的版本在这块逻辑上是有点小bug，现在代码里是修复了，下个版本可以再看看。

**Comment by lion-goose** [comment]
> 有保存之前选择节点的功能，但是目前最新的版本在这块逻辑上是有点小bug，现在代码里是修复了，下个版本可以再看看。

好的，谢谢大佬
还有一些小建议，就是Rules分流最终指向的节点可以显示在面板就更好了，可以更直观。
还有现在窗口大小默认的太小了，每次打开都会恢复到默认大小

**Comment by zzzgydi** [comment]
v1.2.3应该修好这个问题了，可以看看。

**Comment by lion-goose** [comment]
> v1.2.3应该修好这个问题了，可以看看。

还是不能够保持以前的选择啊，刷新或重启就恢复默认了，我用的是便携式版本
