### ISSUE TITLE
建议：加上测速后自动按网速排序功能

### ISSUE THREAD

**Issue by objcCodingTogether** [zzzgydi/clash-verge#39]
1. 可以自定义测速的站点？例如：Google或者YouTube之类
2. 是否可以加上两轮测速（以防一轮测速有网络抖动）后自动过滤掉无法连通的节点（或者无法连通的直接放到最后面），以及按网速进行排序的功能？
3. 是否可以支持选择指定的多个节点进行重新测速。例如，把最快的几个节点选中再测一遍。

谢谢！

**Comment by zzzgydi** [comment]
第一个可以，第2和第3个的话可以手动点check重新检测吧

**Comment by zzzgydi** [comment]
0.0.29新增自定义测速的站点以及按节点延时排序
