### ISSUE TITLE
Windows11下应用闪退（failed to create the pid file）

### ISSUE THREAD

**Issue by MikeyWei** [zzzgydi/clash-verge#391]
系统环境：Windows 11 专业版(22H2)，操作系统版本号：22621.1105
硬件信息：Redmi Book Pro 14 锐龙版（AMD R7-6800H、16G & 512G）

问题表现：双击应用图标打开程序后，任务栏短暂出现数秒应用图标后消失，无法出现 GUI 界面、系统进程中存在 clash.exe 程序，但前端无法使用。

日志信息：2023-01-29 19:25:03 ERROR - failed to create the pid file

扫了一遍现有 issue 没有人遇到这个问题，所以发一个。

**Comment by zzzgydi** [comment]
> failed to create the pid file

这个不是问题，只是多打了个log。

> 双击应用图标打开程序后，任务栏短暂出现数秒应用图标后消失，无法出现 GUI 界面、系统进程中存在 clash.exe 程序，但前端无法使用。

之前遇到类似的问题，是Win10上的Webview有问题，修复或者重装之后就好了。

**Comment by ulion** [comment]
webview2也安装了，但是还是一样的跟楼主一模一样的症状，win11

**Comment by ulion** [comment]
暂时换了ClashN

**Comment by a224327780** [comment]
win10 也是一样

**Comment by ty114514** [comment]
刚刚爆炸，所以来检索可能存在的相关 issues

一看好家伙，同款机器，红米 Pro14 6800H

感觉巧合不会那么巧，刚想是不是要 reopen 一下，但试了试又修好了（笑

步骤大概有：
|操作|结果|参考|
|---|---|---|
|将 `v1.3.0` 升级到 `v1.3.1`|false| 无 |
|控制面板 -> WebView 2 Runtime 修复 -> 重启|false| #545  |
|确认了电脑上没有 `IP-Guard` -> 将配置文件的服务模式改成 `false` -> 管理员手动运行 `uninstall-service.exe`|false| #488  |
|参照便携模式，在程序目录创建了 `.config` 目录和 `.config/PORTABLE` 文件 |true|[wiki/使用指南](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88)|

由此发现，是原有配置文件有问题导致爆炸，楼主可以尝试备份了删掉或者创建便携文件进行测试

就我个人的使用来说，昨天测试了 `sub-converter`，配合 `sub-web` 把节点信息追加进 Url，导致配置文件里有一串超长的订阅信息，把对应的参数删干净之后也能正常使用了

以上，仅供参考

: )
