### ISSUE TITLE
macbook m1编译失败error running bundle_dmg.sh

### ISSUE THREAD

**Issue by boy119** [zzzgydi/clash-verge#393]
m1 macos 13.1此环境下编译失败： Error failed to bundle project: error running bundle_dmg.sh: error running bundle_dmg.sh，请问您的arm版本是如何编译出来的，另外，这个问题有没有解决方案，谢谢。
部分日志：
yarn run v1.22.19                                                              
$ tsc && vite build                                                            
vite v3.0.9 building for production...
transforming...
✓ 12879 modules transformed.
rendering chunks...
../dist/assets/logo.30296787.ico        32.71 KiB
../dist/assets/logo.4d45c68e.svg        7.57 KiB
../dist/assets/codicon.71cccbf1.ttf     70.80 KiB
../dist/index.html                      2.25 KiB
../dist/assets/yaml.8b3b060b.js         4.18 KiB / gzip: 1.60 KiB
../dist/assets/javascript.5179c70d.js   6.57 KiB / gzip: 2.36 KiB
../dist/assets/index.a645210f.css       42.40 KiB / gzip: 7.65 KiB
../dist/assets/index.956d236c.js        2957.37 KiB / gzip: 815.42 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✨  Done in 22.83s.                                                            
   Compiling clash-verge v0.1.0 (/client/tarui/src-tauri)
    Finished release [optimized] target(s) in 1m 57s
    Bundling Clash Verge.app (/client/tarui/src-tauri/target/release/bundle/macos/Clash Verge.app)
    Bundling Clash Verge_1.2.2_aarch64.dmg (/client/tarui/src-tauri/target/release/bundle/dmg/Clash Verge_1.2.2_aarch64.dmg)
     Running bundle_dmg.sh
       Error failed to bundle project: error running bundle_dmg.sh: error running bundle_dmg.sh: `failed to run /tarui/src-tauri/target/release/bundle/dmg/bundle_dmg.sh`

**Comment by zzzgydi** [comment]
我13.2.1没复现这个问题

**Comment by VegeBun-csj** [comment]
话说你们M1芯片都是自己编译的吗，有没有老哥发一个编译好的

**Comment by zzzgydi** [comment]
> 话说你们M1芯片都是自己编译的吗，有没有老哥发一个编译好的

我自己有编译发到release，可以看看
