### ISSUE TITLE
请求同步更新brew仓库

### ISSUE THREAD

**Issue by kilvn** [zzzgydi/clash-verge#394]
目前只能下载release，这样不利于保持最新，加入了brew库，定期更新比较好

**Comment by ivaquero** [comment]
目前，因为没有签名，无法提交官方，所以只有作者自己建一个仓库。

**Comment by kilvn** [comment]
这个软件我一直用不了，本地导入配置文件，节点选择出不来，看了很多次没问题，换回clashx了

**Comment by zzzgydi** [comment]
> 这个软件我一直用不了，本地导入配置文件，节点选择出不来，看了很多次没问题，换回clashx了

可以看看运行时的配置是否正确生成，以及打开本软件的时候是不是也开着clashx导致端口冲突

**Comment by kilvn** [comment]
> > 这个软件我一直用不了，本地导入配置文件，节点选择出不来，看了很多次没问题，换回clashx了
> 
> 可以看看运行时的配置是否正确生成，以及打开本软件的时候是不是也开着clashx导致端口冲突

导入后配置文件正常，并且应用了，clashx早就关了，这个常识还是要有的，就是节点选择一直出不来，该确认的都确认了，配置文件也没问题，报错都排除掉了

**Comment by zdrjson** [comment]
期待更新至brew
