### ISSUE TITLE
clash.meta最新alpha特性配置文件识别错误

### ISSUE THREAD

**Issue by kogekiplay** [zzzgydi/clash-verge#398]
dns配置中添加
```
# 配置查询域名使用的 DNS 服务器
  nameserver-policy:
    "geosite:cn": "https://doh.pub/dns-query"
```
订阅后变成
```
  nameserver-policy:
    geosite:cn: https://doh.pub/dns-query
```

**Comment by zzzgydi** [comment]
第二种写法软件是可以识别的，是meta那里识别不了么

**Comment by zzzgydi** [comment]
我测了一下，应该是没问题的

**Comment by kogekiplay** [comment]
哦哦好的，我是怕那样影响使用，测试没问题就行，我这看着也没啥问题

**Comment by mortence** [comment]
`  nameserver-policy:
    geosite:cn: https://doh.pub/dns-query`
这个配置在最新版会报 yaml 解析失败，加引号也不行

**Comment by mortence** [comment]
> ```
> nameserver-policy:
>   geosite:cn: https://doh.pub/dns-query
> ```
> 
> 这个配置在最新版会报 yaml 解析失败`parse config failed error=yaml: unmarshal errors:`，加引号也不行

是我的问题，默认内核是 clash ，要把内核修改为 clash-meta 就可以了

**Comment by james-curtis** [comment]
> > ```
> > nameserver-policy:
> >   geosite:cn: https://doh.pub/dns-query
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个配置在最新版会报 yaml 解析失败`parse config failed error=yaml: unmarshal errors:`，加引号也不行
> 
> 是我的问题，默认内核是 clash ，要把内核修改为 clash-meta 就可以了

哈哈麻了，我本来想删除配置文件测一下的，结果一样的情况 unmarshal errors，原来是忘记换meta 了
