### ISSUE TITLE
merge配置并没有生效

### ISSUE THREAD

**Issue by TTT-TD** [zzzgydi/clash-verge#399]
系统版本：Windows11 22H2 22621.1105
软件版本：v1.2.3
软件语言：中文

复现步骤：
添加了merge类型配置，删除原有字段，添加内容如下，tun模式stack为system
![1675369100105.png](https://input-s3.mn.input.im/adm-group/1/20230203/63dc1a856c0bc.png)
并且Clash字段已经勾选了`tun`
![1675369308863.png](https://input-s3.mn.input.im/adm-group/1/20230203/63dc1b5739d16.png)
启用merge配置并刷新了配置
![1675369390721.png](https://input-s3.mn.input.im/adm-group/1/20230203/63dc1ba832736.png)
重新开关Tun模式后，运行配置tun stack依然为gvisor
![1675369465828.png](https://input-s3.mn.input.im/adm-group/1/20230203/63dc1bf397be6.png)

> **同时使用如上方法也尝试了merge配置dns字段，依然不生效，检查了日志，并没有YAML格式语法报错**

**Comment by zzzgydi** [comment]
配置页截一下图看看整体？

**Comment by BigUIFU** [comment]
> 配置页截一下图看看整体？

上面tun部分就是merge文件的整体了，我没有改变任何缩进，但是我把所有字段的字符串值全部都加上了引号(用的verge上的编辑器)，奇迹般生效了，不过看运行配置那里，有的没有引号，有的是双引号(我全用的单引号)，不知道是不是解析YAML语法有点差异，不过目前正常工作了

**Comment by zzzgydi** [comment]
> 奇迹般生效了

感觉是之前的merge文件里格式有点什么问题吧，导致了解析失败，所以不生效

> 有的没有引号，有的是双引号(我全用的单引号)

最终生成的配置可以理解为经过格式化了
