### ISSUE TITLE
会支持中文吗？

### ISSUE THREAD

**Issue by spphinslove** [zzzgydi/clash-verge#4]

**Comment by zzzgydi** [comment]
会的

**Comment by spphinslove** [comment]
linux系统打算支持吗？CFW那些都不开源

**Comment by zzzgydi** [comment]
应该可以支持，但还没有时间，电脑也没装linux

**Comment by dianso** [comment]
别支持中文，有点low啊

**Comment by banjuer** [comment]
> 别支持中文，有点low啊

不知道是不是反串, 个人觉得这样说话不太礼貌

**Comment by dianso** [comment]
> > 别支持中文，有点low啊
> 
> 不知道是不是反串, 个人觉得这样说话不太礼貌

增加体积，而且英文能看懂的。

**Comment by Wzieee** [comment]
> > > 别支持中文，有点low啊
> 
> > 
> 
> > 不知道是不是反串, 个人觉得这样说话不太礼貌
> 
> 
> 
> 增加体积，而且英文能看懂的。

能看懂是看懂。但是自己人开发的，主要用户也是自己人，为什么用中文就是Low？
难不成English就是逼格高点？

**Comment by banjuer** [comment]
增加体积这个理由... 佩服

> > > 别支持中文，有点low啊
> > 
> > 
> > 不知道是不是反串, 个人觉得这样说话不太礼貌
> 
> 增加体积，而且英文能看懂的。

**Comment by dianso** [comment]
> 增加体积这个理由... 佩服
> 
> > > > 别支持中文，有点low啊
> > > 
> > > 
> > > 不知道是不是反串, 个人觉得这样说话不太礼貌
> > 
> > 
> > 增加体积，而且英文能看懂的。

你自己睁大眼睛看看，这个项目里有中文么？

all english

is right

**Comment by mydebug** [comment]
> 再支持中文，有点低啊

RNM，宝批龙

**Comment by zzzgydi** [comment]
0.0.23版本已经开始支持中文啦。

至于体积问题，相较于之前的版本，Web应用打包后的体积增加不到100k（压缩前），总得来说感知不强。
