### ISSUE TITLE
日志等级似乎设定无效

### ISSUE THREAD

**Issue by inRm3D** [zzzgydi/clash-verge#40]
如图，设置了 silent, 还是不停有 warning.

![image](https://user-images.githubusercontent.com/64240055/159184894-ba3d8868-655d-4ab4-91f6-9de730eb45ce.png)
![image](https://user-images.githubusercontent.com/64240055/159184911-8cdb7737-6a5c-486d-8e4b-0a563a1ee556.png)

**Comment by zzzgydi** [comment]
这个应该是clash的问题，可以单独跑clash core试试。不过这个warning都是请求挂掉了的吧，显示一下比较好
