### ISSUE TITLE
Linux 自启动问题

### ISSUE THREAD

**Issue by Taivasjumala** [zzzgydi/clash-verge#403]
openSUSE-Tumbleweed(KDE)

据我了解，Linux 下自动是通过 `~/.config/autostart/clash-verge.desktop` 脚本实现的

其中可执行文件的路径填写的是 `/tmp/.....`, 然而这个文件夹下的内容每次开机都会被清空(不同发行版可能不同)，然而我自己修改后的路径到`clash-verge.AppImage`也会被 `clash-verge` 自己改成原来的，非常地搞心态。😢

有没有可能改成自动获取自己可执行文件的路径？

**Comment by zzzgydi** [comment]
目前的逻辑就是自动获取执行文件本身的路径，不知道为啥是/tmp的？

https://github.com/zzzgydi/clash-verge/blob/6783355c4d9064393464dc2db4d0015cb2702dea/src-tauri/src/core/sysopt.rs#L144

你也可以用你的平台帮忙调试一下。

**Comment by zzzgydi** [comment]
学习到了，我~~抄~~借鉴一下
