### ISSUE TITLE
windows7无法启动：无法定位程序输入点EventSetInformation于动态链接库 advapi32.dll 上

### ISSUE THREAD

**Issue by G-Fantastic** [zzzgydi/clash-verge#404]
windows7安装完成，无法启动，启动就报：
`无法定位程序输入点EventSetInformation于动态链接库 advapi32.dll 上`

![clash](https://user-images.githubusercontent.com/10738277/217403054-9dd8256b-111b-488f-9800-a86512d7a860.png)

已经尝试用 window11的 `System32` 与 `SysWOW64` 下的 `advapi32.dll`  替换 windows7 下对应的文件，但还是一样的问题。

**Comment by zzzgydi** [comment]
试试这个

- x64: https://www.microsoft.com/en-us/download/details.aspx?id=48636
- x86: https://www.microsoft.com/en-us/download/details.aspx?id=48638

**Comment by G-Fantastic** [comment]
谢谢，这个方法好使。可以使用了。
