### ISSUE TITLE
建议TUN模式可选是否配置默认路由

### ISSUE THREAD

**Issue by ghost** [zzzgydi/clash-verge#405]
部分程序经过clash内核转发（DIRECT）后出问题，建议TUN模式（windows 系统服务+TUN模式）可选是否配置为系统的默认路由，这样可以手动（``route add...``）设置哪些IP段需要走代理（支持ping），其余的直接绕过clash内核。

**Comment by zzzgydi** [comment]
tun配置里的`auto-route`那个设置为false看看呢
