### ISSUE TITLE
top.gydi.clashverge目录有何作用？

### ISSUE THREAD

**Issue by anylones** [zzzgydi/clash-verge#411]
C:\Users\*\AppData\Local下的top.gydi.clashverge目录有何作用？似乎会随着使用时间而增加大小，删了又没有发现什么影响，过一会又会自动生成了。

**Comment by zzzgydi** [comment]
可能是WebView要存东西吧，不太清楚，目前用到了Webview里的localstorage存一下代理页的一些状态，你可以试试删了之后，那些状态是不是被清空了

**Comment by zzzgydi** [comment]
重要数据都集中保存在`~/.config/clash-verge`里了，其他的影响不大
