### ISSUE TITLE
linux 非root启动 failed to save , 没有权限.

### ISSUE THREAD

**Issue by matianhe3** [zzzgydi/clash-verge#413]
不能切换内核, 不能使用配置文件, 不能使用.  必须要用sudo 吗?
![image](https://user-images.githubusercontent.com/24929062/218921031-5da61198-d57c-4623-8a0b-4e750c9428c9.png)

**Comment by zzzgydi** [comment]
查查/tmp/clash-verge-check.yaml文件的权限吧，如果是root的，就sudo rm掉吧

**Comment by matianhe3** [comment]
> 查查/tmp/clash-verge-check.yaml文件的权限吧，如果是root的，就sudo rm掉吧
可以的, 谢谢.
