### ISSUE TITLE
Verge消耗太高不正常请注意&加以解决

### ISSUE THREAD

**Issue by jacobin** [zzzgydi/clash-verge#415]
如下图，Verge的CPU消耗情况，有两个子进程msedgewebview2.exe，它两的CPU消耗始终保持在2.5%左右，一共是5%；IO始终保持在850KB/s左右，一共是1.7M/s。

我是在CPU风扇开始运动的时候，注意到这个区别的。

![Verge比4w耗u](https://user-images.githubusercontent.com/5020373/219256482-5de31492-d0c7-4923-a352-f154ab5c1008.png)

**Comment by zzzgydi** [comment]
这个应该是因为Webview需要不定时地从clash内核那里拿数据更新到视图。有CPU、GPU和网络io都算是正常情况。所以不用界面的时候可以直接关掉窗口。

**Comment by CometYZ** [comment]
待机的时候一晃动鼠标，cpu占用就飙升，太怪了（macbook m1 Ventura
https://imgur.com/a/yyeotMQ

**Comment by CometYZ** [comment]
> 待机的时候一晃动鼠标，cpu占用就飙升，太怪了（macbook m1 Ventura
> https://imgur.com/a/yyeotMQ

发现只要从菜单里选择重启就没问题了

**Comment by yiiyahui** [comment]
我去，你这个N重前置连TOR嘛，建议直接内核加载服务完事

**Comment by jacobin** [comment]
> 我去，你这个N重前置连TOR嘛，建议直接内核加载服务完事

我这里TOR是独立的，根verge无关。跟c4w的electron相比，Verge用的UI引擎明显拉跨，5%的CPU，我这可是12代i7U

**Comment by zzzgydi** [comment]
> 跟c4w的electron相比，Verge用的UI引擎明显拉跨，5%的CPU，我这可是12代i7U

都用的Webview，没啥不一样。我看了一下，消耗CPU资源是因为开了"流量图显"，这个玩意儿我在实现的时候是每一帧都有在计算才实现我想要的丝滑的效果。不想要这个功能的可以在设置里关掉，再看看待机CPU消耗。

**Comment by jacobin** [comment]
> > 跟c4w的electron相比，Verge用的UI引擎明显拉跨，5%的CPU，我这可是12代i7U
> 
> 都用的Webview，没啥不一样。我看了一下，消耗CPU资源是因为开了"流量图显"，这个玩意儿我在实现的时候是每一帧都有在计算才实现我想要的丝滑的效果。不想要这个功能的可以在设置里关掉，再看看待机CPU消耗。
对，经过试验，关掉"流量图显"确实是可以减少U的消耗。但我现在发现一个新情况，计算机从休眠中唤醒的时候，Verge的消耗其起点很高，可达20%。我等它冷却的时候，突然发现界面消失了，然后打开任务管理器看到如下：
![Snap2_](https://user-images.githubusercontent.com/5020373/220701107-7635eb0c-6b01-4c8c-bf2e-bc57be9c9946.png)
