### ISSUE TITLE
win11 dev 22579拖动窗口不跟手

### ISSUE THREAD

**Issue by Cielstar** [zzzgydi/clash-verge#42]
![clash-verge1](https://user-images.githubusercontent.com/43376740/159212729-9ed07c2f-33a7-4c95-b1ad-384eab2702a7.gif)

**Comment by zzzgydi** [comment]
这个问题已收到。另外你的clash应该是没正常启动

**Comment by Cielstar** [comment]
> 这个问题已收到。另外你的clash应该是没正常启动

没启动可能是因为cfw占着端口吧。

**Comment by zzzgydi** [comment]
现在的版本 v1.0.1 在win11里拖动应该不卡了
