### ISSUE TITLE
[Bug]: 即便配置文件里的trojan密码故意改错，测速也显示成功

### ISSUE THREAD

**Issue by baraja** [zzzgydi/clash-verge#420]
当default latency test 为默认值 http://www.gstatic.com/generate_204 时，即便trojan协议的密码跟服务器上的不符，测速也显示出了延迟；
当我把default latency test 加个 s 改成 https://www.gstatic.com/generate_204 时，如密码错误会显示失败

复现步骤：
设置 - 杂项设置 - default latency test 不做任何修改，会遇到此bug
手动修改为https协议，则表现如预期
期望http协议的测速链接也能表现如预期

**Comment by zzzgydi** [comment]
我测试trojan是符合预期的，你看看clash和clash meta核心是不是都有这个问题，如果是，要么检查一下trojan服务，要么到clash或clash meta的issue里问问
