### ISSUE TITLE
[Suggestion]: 希望可以增加选项直接读取配置文件中的全部字段

### ISSUE THREAD

**Issue by ericsyj** [zzzgydi/clash-verge#427]
目前，verge必须在（设置->clash字段）中选定字段才能使配置文件中的相应字段生效，这样有很多局限性，比如上游内核更新新字段之后（meta核经常加新功能），通过verge换核心运行无法生效，必须等待你这边更新之后才能使用新字段，所以不如提供一个选项可以直接全部读取配置文件中的字段。

**Comment by Paulgudring** [comment]
merge就是mixin功能的实现。[看一下官方wiki](https://github.com/zzzgydi/clash-verge/wiki/使用指南)

**Comment by ericsyj** [comment]
> merge就是mixin功能的实现。[看一下官方wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

并不是的，这个merge只是用来增加字段的对应的是cfw的parse中的部分功能，而mixin是用来覆写字段的，两者完全不一样，你可以参考一下cfw的wiki。

**Comment by Paulgudring** [comment]
> 

你说的对，merge只是覆写。verge的script模式才比较接近mixin。

**Comment by ericsyj** [comment]
> 
OK，懂了，原来merge也可以直接覆盖配置文件，那这个功能已经有了，只需要解决一下clash字段的问题就行了

**Comment by zzzgydi** [comment]
1.3.0已经支持啦，在设置-杂项-Clash Fields Filter，把这个关掉就好
