### ISSUE TITLE
建议 Portable 版本可以自带 WebView2 runtime

### ISSUE THREAD

**Issue by luckyreg** [zzzgydi/clash-verge#428]
例如 Win10 LTSC 2019 使用很普遍，但是本身不带 Edge 浏览器或者 WebView2 runtime，就会导致无法打开  clash-verge。因此建议作者在 Portable 版本里把依赖都打包进去。

另外建议 Portable 版本默认有 `.config/PORTABLE` 文件，彻底绿色化。

非常感谢您的辛勤开发，向您致敬。

**Comment by zjxuzhj** [comment]
同意

**Comment by DustinWin** [comment]
哈哈，我当时用火绒拦截了 Edge 相关的所有规则，导致安装 clash verge 失败，查看日志才知道原来它依赖 WebView2 runtime。

**Comment by zbc20110215** [comment]
支持
