### ISSUE TITLE
yacd cannot open on mozilla firefox

### ISSUE THREAD

**Issue by volatilaq** [zzzgydi/clash-verge#439]
yacd can't open in firefox, but can open via opera browser, can you solve this problem?
![yacd error](https://user-images.githubusercontent.com/122660998/224467930-20ccaf50-2d22-48bf-9982-9cd97308a6a8.PNG)

**Comment by zzzgydi** [comment]
Did you open the link through the clash verge?

**Comment by volatilaq** [comment]
> Did you open the link through the clash verge?

what link ? this below screenshot yacd on opera
![oper](https://user-images.githubusercontent.com/122660998/224470725-c2a21e33-a78b-44d9-bf20-842cd79bf026.PNG)

**Comment by zzzgydi** [comment]
You can directly access this `https://yacd.haishan.me` in firefox.

**Comment by volatilaq** [comment]
> You can directly access this `https://yacd.haishan.me` in firefox.

still cannot
![still](https://user-images.githubusercontent.com/122660998/224474683-6c854935-a6ef-477f-8884-38a9d2451187.PNG)

**Comment by volatilaq** [comment]
i try to open on chrome, and success
![chrome](https://user-images.githubusercontent.com/122660998/224474916-2cc18389-8f8f-42ff-b8d5-075237b7b1f3.PNG)

why only firefox get trouble,

**Comment by zzzgydi** [comment]
enter `http://127.0.0.1:9090` in here, and then click the Add button.

<img width="225" alt="image" src="https://user-images.githubusercontent.com/27361820/224475425-cf168edf-e2aa-4d26-9d5c-44ce71353a87.png">

**Comment by volatilaq** [comment]
https://user-images.githubusercontent.com/122660998/224475645-d7ed7ceb-f67c-46e0-b703-ee4621937e34.mp4

nothing happened

**Comment by zzzgydi** [comment]
change the link to  `https://yacd.haishan.me`

<img width="356" alt="image" src="https://user-images.githubusercontent.com/27361820/224477582-d4dfab3b-0655-4ac8-b4a4-e8376ae3ce48.png">

**Comment by volatilaq** [comment]
> https://yacd.haishan.me

thanks, it works fine, yacd can open in mozilla
