### ISSUE TITLE
TUN模式分流规则不生效

### ISSUE THREAD

**Issue by Roiyaru** [zzzgydi/clash-verge#44]
0..0.25版本TUN模式流量不走分流规则，系统代理模式流量走分流规则但是UWP应用无网络。已在系统设置加密DNS。
使用的规则来自https://github.com/ACL4SSR/ACL4SSR/tree/master    配置文件和两种模式的log已经上传。
[r9NAuUd6HWhE.yaml.txt](https://github.com/zzzgydi/clash-verge/files/8323944/r9NAuUd6HWhE.yaml.txt)
[2022-03-22-194009.log](https://github.com/zzzgydi/clash-verge/files/8323877/2022-03-22-194009.log)
[2022-03-22-194249.log](https://github.com/zzzgydi/clash-verge/files/8323878/2022-03-22-194249.log)

**Comment by Roiyaru** [comment]
> 现在这个配置文件的dns字段，默认是不起作用的了，被过滤掉了的。会是这个问题吗。你可以把dns的配置copy到`config.yaml`里看看分流规则是否有问题。
> 
> uwp回环的问题，我看cfw是自带了一个fiddler的插件程序，可以手动去处理

经过几天的测试，手动修改配置文件里的dns设置到config.yaml里分流正常。建议后续版本提供快捷的config.yaml修改功能和默认使用配置文件里的dns设置

**Comment by zzzgydi** [comment]
> 建议后续版本提供快捷的config.yaml修改功能和默认使用配置文件里的dns设置

周末我设计设计

**Comment by ileeoyo** [comment]
> > 建议后续版本提供快捷的config.yaml修改功能和默认使用配置文件里的dns设置
> 
> 周末我设计设计

tun和dns目前都被config.yaml里替换了，这样也不太好。我的配置文件是全平台托管的，tun和dns都按照自己喜欢的调整到最好。但是用clash-verge，我托管的配置里dns和tun其实是不生效的，被config.yaml覆盖了，还得手动改动config.yaml。最好有选项是能读取远程文件的dns配置，如果没有则取config.yaml配置，两个配置merge

**Comment by zzzgydi** [comment]
@ileeoyo 这个0.0.26刚有，可以看看 https://github.com/zzzgydi/clash-verge/issues/12 ，新建一个merge profile，然后填上`use: ["tun", "dns"]`。这样远程配置里的这两个字段就会替换config.yaml里的。

**Comment by ileeoyo** [comment]
> @ileeoyo 这个0.0.26刚有，可以看看 #12 ，新建一个merge profile，然后填上`use: ["tun", "dns"]`。这样远程配置里的这两个字段就会替换config.yaml里的。

刚下载0.0.26，这个功能有点隐蔽一开始没注意到。刚试用了下这个功能，确实可以实现远程配置文件替换config.yaml。但是这种交互有一点问题，就是如果use:[tun，dns]后，UI界面的Tun Mode开关无论是开或者是关都是无效的，这样可能给一些浅度使用的用户一些误导。二是，use: tun，这样简单的配置，其实不必用merge profile实现，这种可以完全通过UI开关去实现交互。
我仅提供一种交互方式，探讨下哪种会更方便些：

增加两个开关：1，tun mode 开关，该开关仅会影响远程配置文件的tun.enable字段，如果远程配置文件没有则新增，存在则修改enable值。2, 增加tun模式具体配置有效性选择开关，打开则默认取远程配置文件的tun配置，关闭则默认选择config.yaml配置中的tun配置，或者单独有个文件入口编辑tun配置，（tun.enable除外，tun.enable由tun mode开关控制）。 
dns开关同理

**Comment by zzzgydi** [comment]
> 如果use:[tun，dns]后，UI界面的Tun Mode开关无论是开或者是关都是无效的

 我也发现了 是个bug :)  目前tun mode的实现是控制config.yaml的tun和dns的enable字段，后续我改成控制最终生效的runtime-config.yaml的tun和dns的enable字段，这样应该就没有问题了。后续可以针对这个use字段，做个ui控制。

**Comment by ileeoyo** [comment]
> 件的tun.enable字段，如果远程配置文件没有则新增，存在则修改enable值。2, 增加tun模式具体配置有效性选择开关，打开则默认取远程配置文件的tun配置，关闭则默认选择config.yaml配置中的tun配置，或者单独有个文件入口编辑tun配置，（tun.enable除外，tun.enable由tun mode开关控制）。
> dns开关同理

是这个意思，意思为use做UI控制，毕竟这个配置太简单了，通过配置实现很麻烦。
希望越来越好，期待下版

**Comment by zzzgydi** [comment]
> 意思为use做UI控制，毕竟这个配置太简单了，通过配置实现很麻烦。

这个在v0.0.28已经处理啦
