### ISSUE TITLE
添加的自定义规则更新后被覆盖

### ISSUE THREAD

**Issue by Alex-coder251** [zzzgydi/clash-verge#440]
请问有办法是解决吗🙈

**Comment by zzzgydi** [comment]
新建一个merge profile，然后在prepend-rules里写规则吧，可以看看[wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86)
