### ISSUE TITLE
tun stack: system不可用

### ISSUE THREAD

**Issue by BaronChushao** [zzzgydi/clash-verge#441]
win10 21H2，clash.vergeV1.2.3版本，V1.14.1meta核
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
改成stack: gvisor就能够正常访问，求大佬解惑！

**Comment by BaronChushao** [comment]
![image](https://user-images.githubusercontent.com/98247704/224529953-d8f54767-2360-4213-b33e-5fb02b4ff0e6.png)
当stack: system开启tun模式后访问国外网站日志里都没有记录

**Comment by eamon-cai** [comment]
这个在网页控制台可以看到
