### ISSUE TITLE
yacd emoticon

### ISSUE THREAD

**Issue by volatilaq** [zzzgydi/clash-verge#443]
I want to ask, why when I open Yacd on Opera, no emoticons appear
![yacd-opera](https://user-images.githubusercontent.com/122660998/224885834-f55bbb24-a559-426c-aca6-8d9eefb81724.PNG)
 but when I open Yacd on Firefox, emoticons appear.
![yacd-firefox](https://user-images.githubusercontent.com/122660998/224885881-2fefcc12-0fdd-4399-89de-ab90cee90e9d.PNG)
I also tried opening yacd in chrome, and it's the same with opera, emoticons don't appear,
![yacd-chrome](https://user-images.githubusercontent.com/122660998/224885931-77eacde9-f874-4ad0-b2f1-4fd955019df2.PNG)
 why can't chrome and opera read emoticons like in firefox?
do you have a solution?

**Comment by zzzgydi** [comment]
You can raise an issue in the yacd repository. https://github.com/haishanh/yacd/issues/new
