### ISSUE TITLE
建议支持配置文件放在clash-verge的运行目录下

### ISSUE THREAD

**Issue by PAINCLOWN** [zzzgydi/clash-verge#446]
建议支持配置文件放在clash-verge的运行目录下  不然重装系统 .config也跟着没了 又要重新配置一遍 而且失去了便携的目的

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88
