### ISSUE TITLE
Clash 版本显示有问题

### ISSUE THREAD

**Issue by RikudouPatrickstar** [zzzgydi/clash-verge#452]
已经更新到了 1.3.0 版本的 clash verge，alpha 版本的 meta 内核是上个版本时手动更换的，当前两个内核版本如下，但 clash verge 一直显示 alpha 版本的 meta

![image](https://user-images.githubusercontent.com/68163551/225789244-8e3f0473-82f8-45d8-939f-a70799889504.png)

![image](https://user-images.githubusercontent.com/68163551/225789022-952df89c-60b2-456e-af68-bf7305106c5b.png)

**Comment by zzzgydi** [comment]
重启一下应用看看

**Comment by RikudouPatrickstar** [comment]
重启过很多遍了，不管是退出重新启动还是点菜单里的“重启应用”和“重启clash”

**Comment by RikudouPatrickstar** [comment]
目前是不管选 clash 还是 clash meta，都显示这个

**Comment by zzzgydi** [comment]
懂了，打开应用管理，看看是不是之前还有一个clash meta进程没被正常关闭吧

**Comment by RikudouPatrickstar** [comment]
我也怀疑，不过关掉 clash verge 之后，任务管理器里面没发现相关进程呀。应该是叫 clash-meta.exe 之类的名称吧？

**Comment by RikudouPatrickstar** [comment]
刚刚点“重启clash”等了一会之后正常了，之前没等直接“重启应用”了

**Comment by zzzgydi** [comment]
版本的信息是直接从内核的接口里拿的，所以如果这里出错，只能是还有个进程在跑

**Comment by RikudouPatrickstar** [comment]
那就是说，目前存在退出 clash verge 之后，clash 进程没被彻底干掉的问题😰

**Comment by zzzgydi** [comment]
手动点退出，是肯定干掉了。但是更新完成之后的自动重启可能没干掉，框架之前就有这个问题，印象中已经修了。但保不齐可能还有bug。

**Comment by RikudouPatrickstar** [comment]
可能和框架有关吧。不过我刚手动退出了好多次呀，最后点“重启clash”等了一会之后才正常的。
