### ISSUE TITLE
关于开机自启的几个小问题和建议 [Windows 0.0.25]

### ISSUE THREAD

**Issue by YohoYang** [zzzgydi/clash-verge#46]
1. 开机自启时会打开界面，希望可以在开机自启的情况下默认不打开界面，只出现任务栏图标（不好区分的话也可以加个设置，打开后默认打开程序时不打开主界面）
2. 当开启TUN模式时，启动时需要管理员权限来创建虚拟网卡，如果在兼容性里把“使用管理员权限启动程序”打勾，软件开机会没有启动。（测试了一下，这个和是否TUN没关系，只要勾选了使用管理员权限，开机就不能启动，原因不太清楚）

系统环境 Windows 11 21H2 22000.556 64位  
软件版本 Clash.Verge_0.0.25_x64_green.zip

**Comment by zzzgydi** [comment]
1. todo
2. 开机自启这个操作好像没管理员权限，所以勾选那个就会导致应用启动不了，因为权限不够。我猜是因为这样。别人都用服务去搞的，我也打算这么搞

**Comment by zzzgydi** [comment]
0.0.26 已支持静默启动，如果遇到啥bug，欢迎反馈哈

**Comment by YohoYang** [comment]
> 0.0.26 已支持静默启动，如果遇到啥bug，欢迎反馈哈

辛苦大佬！已更新，暂时没发现什么问题

**Comment by zzzgydi** [comment]
Windows 的1.0.0版本支持服务模式啦，可以解决你提到的第二个问题。如果安装服务的过程有bug，可以看看 issue https://github.com/zzzgydi/clash-verge/issues/74
