### ISSUE TITLE
可否在订阅规则的基础上补充个别本地规则？

### ISSUE THREAD

**Issue by bicr** [zzzgydi/clash-verge#460]
订阅的规则有些条目不太合适，希望支持添加个别规则，且优先级高于订阅规则。

**Comment by zzzgydi** [comment]
wiki里的[merge profile](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86) 或者 script profile都行。

merge profile可以用`prepend-rules`

```yaml
prepend-rules:
  - xxx
  - xxx
```

**Comment by bicr** [comment]
merge不好用，建议参考clashr auto。直接在规则界面操作，所见即所得
