### ISSUE TITLE
打开 Web UI 出现报错（不影响使用）

### ISSUE THREAD

**Issue by RikudouPatrickstar** [zzzgydi/clash-verge#465]
好像是 v1.3.0 才有的现象，Windows下命令行黑框一闪，打开 Web 控制面板后，clash-verge 出现如下图所示报错：

![屏幕截图(6)](https://user-images.githubusercontent.com/68163551/226780176-f58cc939-2ecc-4015-8649-3d209f41de34.png)

**Comment by FosterHann** [comment]
我也遇到了一样的问题,So do I!
