### ISSUE TITLE
macbook m1 上无法打开 aarch64 的版本

### ISSUE THREAD

**Issue by YouXam** [zzzgydi/clash-verge#466]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/49866772/226809941-c3dd80ca-c44c-42e5-9e73-7ba4128f6258.png">

在 m1 air 和 m1 pro 上均无法打开，前几个版本都试了一下，也有同样的问题。

**Comment by zzzgydi** [comment]
安装后在控制台执行 `sudo xattr -r -d com.apple.quarantine /Applications/Clash\ Verge.app`
