### ISSUE TITLE
[求助] 关于 Verge 配置的自动更新机制

### ISSUE THREAD

**Issue by SamuNatsu** [zzzgydi/clash-verge#468]
Verge 的配置更新时间间隔是要求长期挂在后台才能生效的吗（前端定时器）

每次重启 Verge 的时候就算上次更新时间超过了更新时间间隔也不会触发更新

另外开机自启选项也从来没生效过

**Comment by zzzgydi** [comment]
Linux 桌面确实比较多，不能一一适配，有能力的话，可以直接PR。

**Comment by neovali** [comment]
> 如果可以的话希望能提供一种传统的使用 systemctl 来添加开机自启的方法（同样也是 clash 原生使用的开机启动方法），因为这种方法是 Linux 系统通用的，且不会受到桌面环境的影响

自己写一个就是了，不是很难

**Comment by SamuNatsu** [comment]
问题的起因是 dwm 的自动启动机制使用第三方实现，直接修改 Verge 代码不现实，相当于需要专门为 dwm 实现一套自动启动机制，最后认为不改动 Verge 代码为好
