### ISSUE TITLE
ubuntu权限有点问题？

### ISSUE THREAD

**Issue by ckaak** [zzzgydi/clash-verge#469]
ubuntu 22.04
clash verge v.1.3.0

日志：
INFO - [clash]: ERR [API] external controller listen failed error=listen tcp 127.0.0.1:9090: bind: address already in use addr=127.0.0.1:9090
INFO - [clash]: ERR [DNS] start DNS server failed error=listen udp 0.0.0.0:53: bind: address already in use addr=0.0.0.0:53
INFO - [clash]: ERR [DNS] start DNS server failed error=listen udp 0.0.0.0:53: bind: permission denied addr=0.0.0.0:53
INFO - [clash]: ERR [Inbound] start failed error=listen tcp 127.0.0.1:7890: bind: address already in use addr=127.0.0.1:7890 type=Mixed(http+socks)
INFO - [clash]: ERR [Inbound] start failed error=operation not permitted type=TUN stackType=gvisor inet=198.18.0.1/16

打开软件，代理界面一片空白，没有任何节点，设置里内核版本是空白的。

尝试在/usr/bin给了内核777权限还是不行，设置里点内核提示需要密码，最后安装了yarn install，切换内核没有提示密码，没有报错。

但是打开clash verge 依旧代理界面一片空白，设置里内核版本空白，需要手动点击一遍内核才可以正常使用。

**Comment by zzzgydi** [comment]
应该和权限没啥关系，是端口占用的问题
