### ISSUE TITLE
Linux UI显示问题

### ISSUE THREAD

**Issue by idnsunset** [zzzgydi/clash-verge#472]
Linux i3，dashboard窗口使用floating模式，存在问题：

1. 拉伸窗口，关闭，再从系统托盘打开，窗口回到原始尺寸（非常小）
![screenshot_20230324-144127Z](https://user-images.githubusercontent.com/31075263/227556611-896476ee-ab2c-4686-a61f-66f5b6ef7d01.png)
2. 一些对话窗口的文本显示，挤在一堆的感觉，似乎是字体问题？
![screenshot_20230324-143359Z](https://user-images.githubusercontent.com/31075263/227556805-6db9732d-407e-46b4-b836-aa8f49dd053d.png)

**Comment by zzzgydi** [comment]
现在新版支持保存窗口大小了，可以试试。

> 一些对话窗口的文本显示，挤在一堆的感觉，似乎是字体问题？

感觉是webview兼容性问题

**Comment by zzzgydi** [comment]
看起来这个系统自带的webview版本比较低，很多ui都有问题，这个可能处理不来了

**Comment by AnyWAT** [comment]
不是 Microsoft 的 WebView？不能像 Windows 系统上的一样，不能自动更新但能手动更新？

**Comment by zzzgydi** [comment]
linux 上用的应该是 WebKitGTK
