### ISSUE TITLE
Ubuntu: clash内核提权后开启Tun，任何网站都无法访问

### ISSUE THREAD

**Issue by dnt1996** [zzzgydi/clash-verge#478]
![image](https://user-images.githubusercontent.com/31310280/227756664-e14e927c-dc8d-4a7d-8ab3-096e9da924c6.png)
![image](https://user-images.githubusercontent.com/31310280/227756752-583ff0ee-d142-4b22-a65a-699fc3b3d754.png)
![image](https://user-images.githubusercontent.com/31310280/227756797-3b0601b4-0aae-4b14-9f06-3c99327ea0cf.png)
![image](https://user-images.githubusercontent.com/31310280/227756836-1a164299-453f-44e8-83c4-b35cffbb65a6.png)

**Comment by zzzgydi** [comment]
sorry，没看到这个issue。现在试一下最新版还有这个问题么。

**Comment by dnt1996** [comment]
@zzzgydi 用1.3.5版本在ubuntu 22.04试了一下，还是一样的问题

**Comment by zzzgydi** [comment]
tun:stack 换成system试试？

**Comment by dnt1996** [comment]
@zzzgydi 换成clash-meta就好了，需要好几次root授权，而且每次启动都要手动授权有点麻烦，能不能像windows那样创建一个服务
