### ISSUE TITLE
关于能否加入节点的按延时排序和自定义背景/主题的选项

### ISSUE THREAD

**Issue by ZERO-cloud0** [zzzgydi/clash-verge#48]
1.无节点延时排序，使得很难找到低延时节点
2.不能自行自定义背景和主题

**Comment by zzzgydi** [comment]
1. 现在还没实现排序，但是可以有个节点过滤的功能，你点那个测速之后，点第4个漏斗icon，输入`delay<200`，就可以过滤出延迟小于200ms的节点。
2. 现在还不行

**Comment by zzzgydi** [comment]
0.0.27已实现自定义主题，暂无自定义背景

**Comment by zzzgydi** [comment]
0.0.29已新增节点延时排序
