### ISSUE TITLE
代理端口 

### ISSUE THREAD

**Issue by eamon-cai** [zzzgydi/clash-verge#486]
请问 verge 是只支持mix-port吗，因为某些软件mix-port会导致网络错误 ，  配置文件的port socks-port 并不会生效 运行配置也看不到 。配置文件指定mix-port也不会生效  只能在ui指定。 局域网代理也不生效。

**Comment by zzzgydi** [comment]
设置页 - Clash 字段 - 勾选 socks-port，这样配置文件的这个字段就能用了

**Comment by eamon-cai** [comment]
是勾选的  但还是不可用

**Comment by zzzgydi** [comment]
oh sorry，review了一下代码，socks-port得写在`~/.config/clash-verge/config.yaml`里才会生效
