### ISSUE TITLE
软件无法启动: 无界面，有进程，有任务栏图标但是点击无反应 (Windows)

### ISSUE THREAD

**Issue by Patrick-Ze** [zzzgydi/clash-verge#488]
## 现象
- 启动软件后，没有打开任何界面。有进程，有任务栏图标，但是任务栏图标点击（左键、右键）均无反应
- 尝试过安装版`Clash.Verge_1.3.0_x64_zh-CN.msi`和portable版都有这个问题
- 我已经阅读了 https://github.com/zzzgydi/clash-verge/issues/153 但是问题没有解决
- 已经确认系统上安装了Webview

以上过程无任何错误提示，只在`.config/clash-verge-logs`下找到疑似的日志（注：软件默认端口9090和Hyper-V保留端口段有冲突，我在配置文件中改成了12345）
```
2023-03-29 11:33:07 ERROR - failed to create the pid file
2023-03-29 11:33:07 INFO - [clash]: INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
2023-03-29 11:33:07 INFO - [clash]: INF [API] listening addr=127.0.0.1:12345
2023-03-29 11:33:31 ERROR - failed to create the pid file
2023-03-29 11:33:32 INFO - [clash]: INF [API] listening addr=127.0.0.1:12345
2023-03-29 11:33:32 INFO - [clash]: INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
```
系统版本 `Windows 10 22H2 (OS Build 19045.2728)`

2023-04-02 补充：之前忘了提到，出现这个问题的是公司电脑，受域控制且装有 IP guard。个人电脑无此问题

**Comment by ivaquero** [comment]
同问，Windows 11

**Comment by Patrick-Ze** [comment]
> 同问，Windows 11

@ivaquero 你是在公司电脑上出现此问题的吗？如果是，你电脑上有安装IP guard吗？（公司可能在员工不知情的情况下安装了此软件，可以通过`netstat -ano | findstr 823`检查）

**Comment by ivaquero** [comment]
是个人电脑，一个情况是，本来是有界面的，但系统更新了一次之后就没了，搞不清是因为什么。进程是存在的，就是没有界面，降低版本也不行。

**Comment by zzzgydi** [comment]
我win11，有开启服务模式，然后在任务管理器里直接结束服务进程，就遇到了【打不开界面，有任务栏图标】的问题。重启app也不管用。

你们可以留意一下，是不是有用到服务模式。如果也有同样的情况，可以尝试手动修改`~/.config/clash-verge/verge.yaml`文件里的`enable_service_mode: false`。然后重启app，看看。

**Comment by ivaquero** [comment]
这个方法是有效的，感谢

**Comment by midmaya** [comment]
(base) zzs@zzs-G1-Sniper-B6:~$ sudo clash-verge
[ 
clash-verge: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by clash-verge)
clash-verge: /lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.0.0' not found (required by clash-verge)
clash-verge: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.0.0' not found (required by clash-verge)
clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clash-verge)
clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by clash-verge)
clash-verge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by clash-verge)
启动不了软件，依赖库已经重新安装过，还是不行

**Comment by Patrick-Ze** [comment]
> 我win11，有开启服务模式，然后在任务管理器里直接结束服务进程，就遇到了【打不开界面，有任务栏图标】的问题。重启app也不管用。
> 
> 你们可以留意一下，是不是有用到服务模式。如果也有同样的情况，可以尝试手动修改`~/.config/clash-verge/verge.yaml`文件里的`enable_service_mode: false`。然后重启app，看看。

感谢。我试了一下，我这边默认配置文件里没有这个字段，手动添加这个字段并设置为false也还是不能正常启动

**Comment by a224327780** [comment]
公司电脑 WIN10 一样的问题

**Comment by WangsYi** [comment]
> > 同问，Windows 11
> 
> @ivaquero 你是在公司电脑上出现此问题的吗？如果是，你电脑上有安装IP guard吗？（公司可能在员工不知情的情况下安装了此软件，可以通过`netstat -ano | findstr 823`检查）

安装了ip-guard后打不开，有什么解决方案么，现在公司电脑win10，装上ip-guard，就不能打开了

**Comment by midmaya** [comment]
我是家里ubuntu系统，咱都不是我一个系统



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月23日 15:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zzzgydi/clash-verge] 软件无法启动: 无界面，有进程，有任务栏图标但是点击无反应 (Windows) (Issue #488) |

同问，Windows 11

@ivaquero 你是在公司电脑上出现此问题的吗？如果是，你电脑上有安装IP guard吗？（公司可能在员工不知情的情况下安装了此软件，可以通过netstat -ano | findstr 823检查）

安装了ip-guard后打不开，有什么解决方案么，现在公司电脑win10，装上ip-guard，就不能打开了

**Comment by fefz** [comment]
> > 同问，Windows 11
> 
> @ivaquero 你是在公司电脑上出现此问题的吗？如果是，你电脑上有安装IP guard吗？（公司可能在员工不知情的情况下安装了此软件，可以通过`netstat -ano | findstr 823`检查）

我这边也是同样的现象，也有ip-guard这个软件

**Comment by zjxuzhj** [comment]
我们公司也是ip-guard 求解决方案啊！！！！！！！！！！！！！！

**Comment by WangsYi** [comment]
> 

因为不是我的电脑，我没有再追究，但是前几天看了下代码，猜着修改下pid文件的生成路径可能能解决

**Comment by WangsYi** [comment]
> 

改源码，试了下，不行- - 手上没有ip-guard的机器，也没法调试看看具体原因，暂时没啥办法了

**Comment by AnyWAT** [comment]
> Windows Server 2016，已安装作者推荐的最新版edge WebView2 Runtime。

貌似不会自动更新，试试手动更新WebView（114.0.1823.37）

**Comment by zzzgydi** [comment]
如果是装了ip-guard，我猜测应该是ip-guard影响了webview的唤起。

有条件的朋友可以改源码调试一下的，具体可以试试改 
https://github.com/zzzgydi/clash-verge/blob/6e391df5ee8ff796519e612e2260102f65a036e3/src-tauri/src/utils/init.rs#L46

把这里的日志改成debug的，或者直接`yarn run dev:diff`也可以。

然后日志里就会打印使用到的库的一些debug信息，可以定位到问题。

**Comment by Patrick-Ze** [comment]
> 如果是装了ip-guard，我猜测应该是ip-guard影响了webview的唤起。
> 
> 有条件的朋友可以改源码调试一下的，具体可以试试改
> 
> https://github.com/zzzgydi/clash-verge/blob/6e391df5ee8ff796519e612e2260102f65a036e3/src-tauri/src/utils/init.rs#L46
> 
> 把这里的日志改成debug的，或者直接`yarn run dev:diff`也可以。
> 
> 然后日志里就会打印使用到的库的一些debug信息，可以定位到问题。

改了一下日志等级，然后打了tag尝试跑GitHub action，但是跑不起来……

**Comment by zzzgydi** [comment]
这个操作完之后，不是说就能跑起来了，也是跑不了的，但是日志里应该有具体的出错原因了，可以贴日志看看了

**Comment by Patrick-Ze** [comment]
> 这个操作完之后，不是说就能跑起来了，也是跑不了的，但是日志里应该有具体的出错原因了，可以贴日志看看了

是GitHub action跑不起来。有别的方法可以改日志等级么？或者action里有现场的dev版么

**Comment by zzzgydi** [comment]
目前可以试一下新版v1.3.5（依然还是打不开界面），但是加了app的日志控制，可以在verge.yaml里加上`app_log_level: debug`或者`trace`，可以看到更多启动细节，之后可以把日志分享一下，方便定位问题

**Comment by Patrick-Ze** [comment]
> 目前可以试一下新版v1.3.5（依然还是打不开界面），但是加了app的日志控制，可以在verge.yaml里加上`app_log_level: debug`或者`trace`，可以看到更多启动细节，之后可以把日志分享一下，方便定位问题

感谢跟进，但是我这里复现不出来了😂新版本1.3.5以及我提这个issue时的1.3.0都试了一下，现在两个都可以打开……
@zjxuzhj @fefz @WangsYi 几位试一下新版本能不能在装了ip-guard的机器上打开？我这边可以了，但是可能是不知道什么时候ip-guard后台更新了策略

**Comment by Patrick-Ze** [comment]
感谢 @zzzgydi  跟进，我稳定使用了几天，目前1.3.0和1.3.5都依然是可以打开界面的。ip-guard的策略是个黑箱，也没法做对比验证。
由于暂时没有收到其他人回复，我就先关闭issue了。后续如果其他人有需要的话再re-open

**Comment by poniteru** [comment]
v1.3.5 依然还是打不开界面。日志等级调到了trace：
2023-08-03 17:49:43 DEBUG [clash_verge::utils::init] - skipping resource copy 'Country.mmdb'
2023-08-03 17:49:43 DEBUG [clash_verge::utils::init] - skipping resource copy 'geoip.dat'
2023-08-03 17:49:43 DEBUG [clash_verge::utils::init] - skipping resource copy 'geosite.dat'
2023-08-03 17:49:43 DEBUG [clash_verge::utils::init] - skipping resource copy 'wintun.dll'
2023-08-03 17:49:43 TRACE [mio::poll] - registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
2023-08-03 17:49:44 INFO [clash_verge::core::core] - [clash]: INF [API] listening addr=127.0.0.1:9090
2023-08-03 17:49:44 INFO [clash_verge::core::core] - [clash]: INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890

**Comment by zzzgydi** [comment]
@poniteru 这个你可以在windows的应用设置那里更新修复一下webview

**Comment by poniteru** [comment]
> @poniteru 这个你可以在windows的应用设置那里更新修复一下webview

尝试修复了，但还是不显示界面，日志也还是这几行没有变化。

**Comment by AnyWAT** [comment]
退出 Clash Verge，删除文件夹 C:\Users\用户名\AppData\Local\top.gydi.clashverge
再次启动。。。

貌似其它贴子有说删除配置  C:\Users\用户名\.config\clash-verge 后正常的😢

**Comment by poniteru** [comment]
> 试试：退出 Clash Verge，删除文件夹 C:\Users\用户名\AppData\Local\top.gydi.clashverge 再次启动。。。
> 
> 貌似其它贴子有说删除配置文件夹 C:\Users\用户名\ .config\clash-verge 后正常的😢 [#691 (comment)](https://github.com/zzzgydi/clash-verge/issues/691#issuecomment-1650111456)

尝试了一下并没有变化。另外，除了不显示界面之外，点击托盘图标的右键菜单也不会显示

**Comment by AnyWAT** [comment]
[检查系统组件的完整性并修复](https://answers.microsoft.com/zh-hans/windows/forum/all/%E8%BD%AF%E4%BB%B6%E8%BF%90%E8%A1%8C%E4%B8%AD/7d0d0e86-a00d-4077-ae53-a017c67e1aa5)？
系统上也用了 WebView 的天气正常？
卸载 Clash Verge 后再装？

**Comment by poniteru** [comment]
> 

天气卸载了所以无法尝试，其他尝试了无果，安装版和绿色版的 Clash Verge 都试了。公司电脑是有 IP-GUARD 的

**Comment by zfh18** [comment]
同问题，公司企业 win10 21H2，安装之后只有任务栏图标，点击无反应，右键属性，兼容性中勾选以 windows 7 兼容模式运行，可以正常使用，安装的翻译软件 pot 也是这样解决的。

**Comment by zfh18** [comment]
各位可以试试

**Comment by poniteru** [comment]
> 同问题，公司企业 win10 21H2，安装之后只有任务栏图标，点击无反应。找到程序，右键属性，兼容性中勾选以 windows 7 兼容模式运行，可以正常使用，安装的翻译软件 pot 也是这样解决的。各位可以试试 @Patrick-Ze @poniteru

确认有效！

**Comment by Patrick-Ze** [comment]
目前有可行解决方法，就先关闭issue了
