### ISSUE TITLE
bug: proxy-group中use字段使用的proxy测速报错

### ISSUE THREAD

**Issue by ileeoyo** [zzzgydi/clash-verge#49]

**Comment by zzzgydi** [comment]
这个bug有更多一点的信息吗，有点模糊

**Comment by ileeoyo** [comment]
![image](https://user-images.githubusercontent.com/24651612/160335979-dbbe0a6b-3f7c-43b4-8ceb-acdcf34fa8d5.png)
![image](https://user-images.githubusercontent.com/24651612/160336037-6d40d989-2b8e-432e-b34d-1ee8a5c9f342.png)
这个搬瓦工故障转移的代理组测速全都失败，这个代理组使用了use ProxyBWH，ProxyBWH是一个proxy-provider，里面有3个代理

**Comment by zzzgydi** [comment]
provider的好像用的是另外一个检测接口

**Comment by ileeoyo** [comment]
> provider的好像用的是另外一个检测接口
一个是delay，一个是healthcheck。感觉clash自动的检查接口不是太合理，GUI作者有时会不好适配这个。之前cdn软件也有延迟检测的bug

**Comment by zzzgydi** [comment]
那可能要看看 [clash-dashboard](https://github.com/Dreamacro/clash-dashboard) 这个项目，看看原作者咋处理的

**Comment by ileeoyo** [comment]
刚自己查询了clash API文档，确实provider用的是另一个接口健康检查。
这个用来健康检查`GET /providers/proxies/:name/healthcheck`，这个用来查询检查后的结果`GET /providers/proxies/:name`。使用起来和原来的代理delay测试不同，可能需要区分下。

**Comment by zzzgydi** [comment]
ok，我修复一下

**Comment by zzzgydi** [comment]
有个问题，目前clash的接口拿到的proxy字段里，没看到啥标记标明这个是provider里的，所以就区分不了用哪个查询接口

**Comment by ileeoyo** [comment]
> 有个问题，目前clash的接口拿到的proxy字段里，没看到啥标记标明这个是provider里的，所以就区分不了用哪个查询接口

这个API设计确实有些不方便，不太好处理延迟测试，不知道其他GUI作者都是如何处理的。可以通过`GET /providers/proxies`这个接口看看有没有区分的办法

**Comment by zzzgydi** [comment]
研究了一下clash-dashboard，目前不支持一个个点测速，是全部节点测速。然后provider的节点都不在测速列表里。

不过我感觉可以通过`GET /proxies` 和 `GET /providers/proxies` 两份数据判断某个节点是不是一个provider节点。感觉有操作空间。

**Comment by zzzgydi** [comment]
我理解错了，那个healthcheck是测一整个provider的，对于provider里面的proxy是测不了的，所以proxy-groups use provider的话，里面的节点都测不了速。。。

**Comment by zzzgydi** [comment]
这个已经修复啦
