### ISSUE TITLE
CPU占用怎么会比原版CFW高很多。

### ISSUE THREAD

**Issue by pbnlw123** [zzzgydi/clash-verge#493]
最新的版本的在CPU占用最高可达8%。。。原版CFW最高也就1.x

**Comment by charley008** [comment]
+1

**Comment by ssssssbbb** [comment]
CFW不是原，原是C

CFW内存高，这个不开界面也不高

clash.net界面应该比较完美，但绝后了，也不支持meta

**Comment by zzzgydi** [comment]
界面上关掉“流量图显”，CPU就不那么高了。如果是Windows的话，直接关掉界面，占用是最低的（可以和CFW lighting mode比较），也不影响程序后台运行。

**Comment by CussiusKon** [comment]
界面为什么会占用这么多cpu啊，是Rust本身的原因吗

**Comment by zzzgydi** [comment]
> 原来是流量图显的锅，为什么不默认关闭呢

我花了老多时间写的这个流畅又优雅的小动画，怎么能默认关闭呢（狗头）
