### ISSUE TITLE
有proxy-providers的配置好像用不了？

### ISSUE THREAD

**Issue by Infatuation-Fei** [zzzgydi/clash-verge#5]
我一开始导入了个有proxy-providers的配置，然后软件就卡死了，重启也是一直卡死的状态，我把C盘.config的里的Clash Verge的全删了后又导入了个没有proxy-providers的配置可以正常使用，然后在用着这个配置的情况下去导入那个有proxy-providers的配置，切换过去还是会卡死。

**Comment by zzzgydi** [comment]
虽然现在还没有支持providers的界面，但是卡死有点不正常，应该是哪里出异常了，我先看看吧

**Comment by zzzgydi** [comment]
现在处理了，起码有providers的配置不会卡死，但是providers暂时还不算能用，只能看看，不能选

**Comment by zzzgydi** [comment]
在v0.0.21版本里发了这个修复啦，先close了，之后再琢磨provider咋支持
