### ISSUE TITLE
可以在proxy-groups中使用use并添加filter过滤use中的节点吗

### ISSUE THREAD

**Issue by sdivens** [zzzgydi/clash-verge#505]
- name: usa_from_all_proxies
    interval: 3600
    type: select
    url: http://www.gstatic.com/generate_204
    use: 
      - A
      - B
      - C
在这个配置proxy-groups配置项中引用了很多机场的节点作为一个分组,我想把所有机场中的美国节点通过正则的方式筛选出来单独组成一个分组,可以很方便的按照地域或其他属性管理所有机场的节点
希望可以添加这个特性,谢谢

**Comment by AnYon101** [comment]
用meta核可以过滤节点，但是多文件貌似有点问题，你自己试一下

**Comment by zzzgydi** [comment]
你可以用meta核，proxy group里支持正则过滤。要么你可以新建一个script profile，写逻辑写正则啥都行

**Comment by sdivens** [comment]
> 你可以用meta核，proxy group里支持正则过滤。要么你可以新建一个script profile，写逻辑写正则啥都行

我使用的就是meta核,我试过了,在proxy group中使用filter,但是不管用
  - name: all_proxies2
    interval: 3600
    type: select
    url: http://www.gstatic.com/generate_204
    use: 
      - hneko_proxy
      - mojie_best_proxy
      - subapi1.gardenparty.one_proxy
      - wgetcloud_proxy
    filter: '美国'
在这个配置文件中,我一共有4个机场,每个机场里边都有美国节点,但是这么写我在我的代理页面,查看all_proxies2,还是所有的节点,不是筛选之后的

**Comment by zzzgydi** [comment]
filter不管用，感觉和provider有关

**Comment by sdivens** [comment]
> filter不管用，感觉和provider有关

什么样的provider可以呢?我的provider使用的是proxy-providers提供的

**Comment by aecra** [comment]
请问这个问题解决了吗？

**Comment by StephonBirdsey** [comment]
> 请问这个问题解决了吗？

并没有看到

**Comment by Kiritocyz** [comment]
> 请问这个问题解决了吗？

这个目前cfw是可以用的，但是cfa不支持，cfa只支持在proxy-providers里使用filter
