### ISSUE TITLE
【功能建议】支持多开

### ISSUE THREAD

**Issue by haakuya** [zzzgydi/clash-verge#506]
protable版本在软件路径下保存用户配置，并支持多开

**Comment by zzzgydi** [comment]
改配置目录：[wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#%E6%9B%B4%E6%8D%A2%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95)

不支持多开，建议裸跑clash核心
