### ISSUE TITLE
win11 beta 使用winget 或者 scoop 安装最新 0.0.26 闪退，无法打开主界面

### ISSUE THREAD

**Issue by Cielstar** [zzzgydi/clash-verge#51]
如题

**Comment by zzzgydi** [comment]
我测试win10使用winget安装正常，你可以试试直接在release里下载安装看看是否正常，不清楚是winget这些的问题还是win11的问题

**Comment by Cielstar** [comment]
> 我测试win10使用winget安装正常，你可以试试直接在release里下载安装看看是否正常，不清楚是winget这些的问题还是win11的问题

不行，使用msi安装照样闪退

**Comment by zzzgydi** [comment]
那可能在win11上还是存在一点问题。你可以发一下log日志，文件路径是`~/.config/clash-verge/logs/`，方便debug。

还有种可能是文件夹没创建成功，`~/.config/clash-verge`不存在。

**Comment by zzzgydi** [comment]
那还可以尝试一下，通过终端运行客户端程序，看看控制台输出点啥。

**Comment by Cielstar** [comment]
> 那还可以尝试一下，通过终端运行客户端程序，看看控制台输出点啥。
![clash](https://user-images.githubusercontent.com/43376740/163088548-84dc441c-4ae5-4088-992f-c2e769070909.gif)

是这样吗？好像没什么变化啊

**Comment by zzzgydi** [comment]
可能要检查一下`33333`端口是不是被占用了

**Comment by zzzgydi** [comment]
应该不是端口占用了，我大概知道是个什么情况了，还需要排查一下。

`~/.config/clash-verge/config.yaml`或者`~/.config/clash-verge/verge.yaml`这些文件是不是没有自动创建成功呀。

**Comment by Cielstar** [comment]
> 应该不是端口占用了，我大概知道是个什么情况了，还需要排查一下。
> 
> `~/.config/clash-verge/config.yaml`或者`~/.config/clash-verge/verge.yaml`这些文件是不是没有自动创建成功呀。
确实不是端口被占用，这俩文件也有啊
![图片](https://user-images.githubusercontent.com/43376740/163090619-94ff771d-8642-436f-b69b-a3a16073314a.png)

**Comment by zzzgydi** [comment]
发现一个小问题，log文件打不开可能是win11路径的问题。可以换别的程序输出一下log看看，虽然是0kb，但里面可能有东西的。或者cat一下

![image](https://user-images.githubusercontent.com/27361820/163091890-7f99a39d-0df1-4d4c-97ad-8b6959b3503b.png)

**Comment by Cielstar** [comment]
> 发现一个小问题，log文件打不开可能是win11路径的问题。可以换别的程序输出一下log看看，虽然是0kb，但里面可能有东西的。或者cat一下
> 
> ![image](https://user-images.githubusercontent.com/27361820/163091890-7f99a39d-0df1-4d4c-97ad-8b6959b3503b.png)

还是不行，路径应该是正确的

![clash1](https://user-images.githubusercontent.com/43376740/163093305-c9d9e8f0-2b7a-4dae-b336-6e18c88b1888.gif)

![clash2](https://user-images.githubusercontent.com/43376740/163093482-d3b6e903-80b6-444d-90f1-23228383b044.gif)

**Comment by zzzgydi** [comment]
现在基本排除了程序初始化的问题，如果是程序panic，控制台又没报错。。。但是窗口没生成，暂时也不知道会是啥问题了。

**Comment by zzzgydi** [comment]
尝试修复了一下这个问题，可以下载安装最新版v1.0.1试试

**Comment by Cielstar** [comment]
> 尝试修复了一下这个问题，可以下载安装最新版v1.0.1试试

可以打开了
