### ISSUE TITLE
切换内核失败

### ISSUE THREAD

**Issue by scemsjyd** [zzzgydi/clash-verge#511]
![image](https://user-images.githubusercontent.com/14870062/230826063-b4378888-32c7-48b1-b1dd-18ceac7088da.png)
无法切换到meta内核，也看不出什么错误

**Comment by whosphp** [comment]
我也遇到了同样的问题

**Comment by zzzgydi** [comment]
有空可以试一下alpha release，https://github.com/zzzgydi/clash-verge/releases/tag/alpha，看看有没有修复，如果ok的话，下个版本就ok

**Comment by whosphp** [comment]
> 有空可以试一下alpha release，https://github.com/zzzgydi/clash-verge/releases/tag/alpha ，看看有没有修复，如果ok的话，下个版本就ok

试了一下, 还是不行, 同样的错误信息

**Comment by zzzgydi** [comment]
> 试了一下, 还是不行, 同样的错误信息

可以贴一下错误日志，看看是哪里的问题

**Comment by whosphp** [comment]
> > 试了一下, 还是不行, 同样的错误信息
> 
> 可以贴一下错误日志，看看是哪里的问题
之前切换内核到 `Clash Meta` 都是切不过去的, 今天不知道怎么切了过去, 有其他的报错信息了.
```
ThisPROGRAM
can only be run on AMD64 processors with v3 microarchitecture support.
```

**Comment by zzzgydi** [comment]
这个问题好像修过了，先close了
