### ISSUE TITLE
最新1.3.0版本仍然不能使用TUN模式

### ISSUE THREAD

**Issue by sktkyo** [zzzgydi/clash-verge#512]
RT，服务已经安装且正常启动，但是tun模式下仍然没有流量，请问现在该怎么办。

**Comment by sktkyo** [comment]
看了一下系统的tun虚拟网卡，ip4地址是很奇怪的192.18.0.1 尝试自动获取没有效果，会不会是这个问题？

**Comment by PAINCLOWN** [comment]
tun 用system 需要防火墙放行，你可以试试关闭防火墙看看能不能通

**Comment by sktkyo** [comment]
> tun 用system 需要防火墙放行，你可以试试关闭防火墙看看能不能通

试了一下，不行。

**Comment by sktkyo** [comment]
> 允许 `clash.exe` 或 `clash-meta.exe` 通过专用与公用网络 如果先安装服务再开启 `TUN`，会导致 Windows 防火墙不会自动弹出放行提示，需要手动设置一次

还是不行。

**Comment by yueyejinghun** [comment]
请问你手动修改过主网卡网络连接的跃点数吗？如果 Meta 虚拟网卡跃点数的值大于主网卡网络连接的跃点数，那 TUN 是不会接管流量的。可以在 CMD 或者 PowerShell 中运行 `netsh interface ipv4 show config | findstr /R "[interface]"` 检查 Meta 和 主要网络连接 `InterfaceMetric` 的值。如果不是跃点数的问题，那就需要提供日志了

**Comment by sktkyo** [comment]
> 请问你手动修改过主网卡网络连接的跃点数吗？如果 Meta 虚拟网卡跃点数的值大于主网卡网络连接的跃点数，那 TUN 是不会接管流量的。可以在 CMD 或者 PowerShell 中运行 `netsh interface ipv4 show config | findstr /R "[interface]"` 检查 Meta 和 主要网络连接 `InterfaceMetric` 的值。如果不是跃点数的问题，那就需要提供日志了

没有修改点数，另外，这是我CMD命令的运行情况
C:\Users\HEROREADYO>netsh interface ipv4 show config | findstr /R "[interface]"
接口 "Meta" 的配置
    InterfaceMetric:                      0
    InterfaceMetric:                      1
接口 "VirtualBox Host-Only Network" 的配置
    InterfaceMetric:                      25
    InterfaceMetric:                      25
    InterfaceMetric:                      25
接口 "cfw-tap" 的配置
    InterfaceMetric:                      35
    InterfaceMetric:                      35
    InterfaceMetric:                      65
接口 "Loopback Pseudo-Interface 1" 的配置
    InterfaceMetric:                      75

**Comment by sktkyo** [comment]
> 请问你手动修改过主网卡网络连接的跃点数吗？如果 Meta 虚拟网卡跃点数的值大于主网卡网络连接的跃点数，那 TUN 是不会接管流量的。可以在 CMD 或者 PowerShell 中运行 `netsh interface ipv4 show config | findstr /R "[interface]"` 检查 Meta 和 主要网络连接 `InterfaceMetric` 的值。如果不是跃点数的问题，那就需要提供日志了

日志的话一直提示 An invalid argument was supplied.

04-11 16:01:35WARNING
[UDP] dial GLOBAL 198.18.0.1:57230 --> 66.90.74.74:10085 error: listen udp :0: An invalid argument was supplied.
04-11 16:01:35WARNING
[TCP] dial GLOBAL 198.18.0.1:10098 --> www.msftconnecttest.com:80 error: listen udp :0: An invalid argument was supplied.
04-11 16:01:35WARNING
[TCP] dial GLOBAL 198.18.0.1:10098 --> www.msftconnecttest.com:80 error: listen udp :0: An invalid argument was supplied.
04-11 16:01:35WARNING
[TCP] dial GLOBAL 198.18.0.1:10097 --> static-pcs-sdk-server.alibaba.com:80 error: listen udp :0: An invalid argument was supplied.

**Comment by yueyejinghun** [comment]
> 

这个是内核报错，不是 Clash-Verge 的问题。可以到内核 issue 里搜一下 `An invalid argument was supplied`，我搜了一下类似错误有很多，可能有你需要的方法。

另外 hysteria 协议在两个 tun stack 模式中都是可以正常工作的，只不过就是 gvisor 没法实现 NAT Fullcone

**Comment by sktkyo** [comment]
> > 
> 
> 这个是内核报错，不是 Clash-Verge 的问题。可以到内核 issue 里搜一下 `An invalid argument was supplied`，我搜了一下类似错误有很多，可能有你需要的方法。
> 
> 另外 hysteria 协议在两个 tun stack 模式中都是可以正常工作的，只不过就是 gvisor 没法实现 NAT Fullcone

好吧，我刚更新了一下verge，1.3.1正常了.............郁闷.................
