### ISSUE TITLE
Meta内核无法选中配置文件，报本地连接错误

### ISSUE THREAD

**Issue by PingZi-Wing** [zzzgydi/clash-verge#517]
之前一直在正常使用，然后在切换另一个配置文件的时候报了如下图一样的错误，后续卸载verge、重装、重新配置防火墙，还是报下图的错误，看日志内核能发起对外连接。不过使用clashN的时候，也是一样不能应用配置，我也去meta内核提个Issue。

![屏幕截图 2023-04-14 123409](https://user-images.githubusercontent.com/57025184/231965670-9231726f-0ba5-460d-afe2-7cf89bff9f7a.png)

**Comment by zzzgydi** [comment]
在设置 - 外部控制，这里把端口改一下。或者查查电脑的9090端口被谁占用了

<img width="461" alt="image" src="https://user-images.githubusercontent.com/27361820/231968354-11f2aacc-fd48-4b31-8931-69a02f200c5e.png">

**Comment by PingZi-Wing** [comment]
> 

我用netstat -ano|findstr “9090”查了下没有其他程序占用端口，改成7383端口也报一样的错误

**Comment by PingZi-Wing** [comment]
> 在设置 - 外部控制，这里把端口改一下。或者查查电脑的9090端口被谁占用了
> 
> <img alt="image" width="461" src="https://user-images.githubusercontent.com/27361820/231968354-11f2aacc-fd48-4b31-8931-69a02f200c5e.png">

我用netstat -ano|findstr “9090”查了下没有其他程序占用端口，改成7383端口也报一样的错误

**Comment by PingZi-Wing** [comment]
已解决，定位错误原因是proxy-providers解析V2ray订阅（自建节点）之后报错（本地已看到解析出来的节点），换用clash格式的订阅就正常了。
https://github.com/MetaCubeX/Clash.Meta/issues/504#issuecomment-1510009316
