### ISSUE TITLE
希望下个版本可以直接导入vmess,trojan等节点

### ISSUE THREAD

**Issue by oldmii** [zzzgydi/clash-verge#52]
如题

**Comment by zzzgydi** [comment]
直接导入节点是指在clash的配置里添加这些节点吗

**Comment by objcCodingTogether** [comment]
对，是否可以单个节点或多个节点复制导入。有时候在网上看到别人分享的节点，就想试一试速度之类的。
另外，单个或多个节点因为没有配置规则，是否可以有一份默认的规则，对单节点适用。

**Comment by oldmii** [comment]
> 可以的，可以新建一个merge profile，在里面填单节点的规则，会合并到主配置里。也可以用local profile写。

你说的这种操作 小白实在搞不定呀哈哈 望请指导或者期待下一版 毕竟自建vps的用户还是很多的

**Comment by oldmii** [comment]
> 另外，单个或多个节点因为没有配置规则，是否可以有一份默认的规则，对单节点适用。

说的很实在哦 同求

**Comment by zzzgydi** [comment]
> 你说的这种操作 小白实在搞不定呀哈哈 望请指导或者期待下一版 毕竟自建vps的用户还是很多的

根据clash的配置 文档：https://github.com/Dreamacro/clash/wiki/configuration

在profile页面，点击new，然后type那里选local，点确定。然后对刚刚新建的profile右键，点编辑文件，然后按上面链接里的配置说明，补充下面的内容

```
proxies:

proxy-groups:

rules:
```

**Comment by oldmii** [comment]
> > 你说的这种操作 小白实在搞不定呀哈哈 望请指导或者期待下一版 毕竟自建vps的用户还是很多的
> 
> 根据clash的配置 文档：https://github.com/Dreamacro/clash/wiki/configuration
> 
> 在profile页面，点击new，然后type那里选local，点确定。然后对刚刚新建的profile右键，点编辑文件，然后按上面链接里的配置说明，补充下面的内容
> 
> ```
> proxies:
> 
> proxy-groups:
> 
> rules:
> ```

配置起来实在有难度 能不能添加vmess之类的链接后自动生成配置?

**Comment by anglesccs** [comment]
nodesCatch，你可以搞一下

**Comment by oldmii** [comment]
> 可以的，可以新建一个merge profile，在里面填单节点的规则，会合并到主配置里。也可以用local profile写。

merge或者local都试过了 貌似没有反应 能不能出一份实战指导或者把这个功能写进下个版本呀

**Comment by zhudan** [comment]
+1，只希望用网上的规则，节点信息不想给到转换服务器

**Comment by jsjcjsjc** [comment]
目前所有的小猫都不支持直接添加vless或者trojan的单节点,期待
