### ISSUE TITLE
Seems Clash.Verge_1.3.1_aarch64.dmg still use old clash meta (1.4.2) version..

### ISSUE THREAD

**Issue by zizifn** [zzzgydi/clash-verge#522]
![image](https://user-images.githubusercontent.com/1803942/232287169-ef013805-0685-4c11-921a-a91814495cd5.png)

clash-meta 的build 时间是3月6号，1.4.3的日期应该是4月11号。。请问可以重新build 一份 arm 版本的吗？

**Comment by zzzgydi** [comment]
其实你可以直接在这里 https://github.com/MetaCubeX/Clash.Meta/releases 下载一个新的，然后替换到图里的文件
