### ISSUE TITLE
测速bug，测速error，但是能正常使用。

### ISSUE THREAD

**Issue by lhbdhr** [zzzgydi/clash-verge#530]
忽然有个节点测速是error，但是能正常使用，而且一点儿都不卡。
协议是 vmess+grpc。

我看有人提过issue，作者的解释是超过5秒就error。
但我用v2rayn测速才500，而且这还是因为v2rayn每次测速都会重新启动xray，导致grpc的复用没用上。导致延迟高。
我以前用CFW的时候，这个节点200延迟左右。

是不是测速逻辑有问题啊？才会想要提个issue，
虽然不影响使用，但是明明好着的节点，测速error，很奇怪啊。

**Comment by zzzgydi** [comment]
要不改改测速的链接

**Comment by lhbdhr** [comment]
当时我试过了改测速链接，还是不行。
不过现在已经自行恢复了，什么都没改。
不知道什么情况。

**Comment by paststrange** [comment]
我也是这个问题，但我节点组测速没问题，每个节点的测速有问题，类似于这样。
![image](https://user-images.githubusercontent.com/60778731/236654664-3029d909-7a14-490d-9214-e22f016a6b4c.png)

**Comment by lhbdhr** [comment]
我发现是meta内核的原因，和这个verge无关。
你不用verge客户端，用meta webui，测速也一样error。
只能向meta内核提issue。

**Comment by ilovelxy** [comment]
> 我发现是meta内核的原因，和这个verge无关。 你不用verge客户端，用meta webui，测速也一样error。 只能向meta内核提issue。

我现在也发现在用meta内核时会有很多节点测速Error，但是用clash内核就没问题，这是为啥啊？meta内核的原因么？
