### ISSUE TITLE
[Feature]希望能够提供“测试延迟”、“按延迟排序”、“更新配置”这个功能按钮的快捷键配置

### ISSUE THREAD

**Issue by lost22git** [zzzgydi/clash-verge#531]
对于我来说，或者对于大多数用户来说，应该上述的三个功能才是最常用的

但是却没有它们的快捷键配置 🤔

**Comment by zzzgydi** [comment]
测试延迟和排序，都是和某个proxy group有关。更新配置和某个配置有关的。绑快捷键的话，就不知道要操作哪个了。

**Comment by lost22git** [comment]
或许可以加个定语 当前 🤔

**Comment by zzzgydi** [comment]
当前配置，可以。但是当前proxy group就不行了。
