### ISSUE TITLE
连不上网，求教，谢谢

### ISSUE THREAD

**Issue by 2019GETUP** [zzzgydi/clash-verge#534]
日志warning：
To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+
![选区_002](https://user-images.githubusercontent.com/49505949/233832315-c5e08877-691b-4928-9af2-7533ddb8bdfb.png)

**Comment by zzzgydi** [comment]
他是让你升级xray core，而且也只是一个warning，问题不大。上不了网，是上不了外网还是啥都上不了，是不是开了Tun，或者开系统代理没。

**Comment by 2019GETUP** [comment]
已解决，内核需要用新的。替换下就OK了，谢谢。

**Comment by davedavehong** [comment]
@2019GETUP 请问怎么更新内核，我尝试替换文件更新了，还是有这个警告
![image](https://github.com/zzzgydi/clash-verge/assets/10491999/9f315a4c-60c4-4698-936d-6427cd1cb082)
