### ISSUE TITLE
macos 13 , clash-verge 1.3.1 无法连接

### ISSUE THREAD

**Issue by IC-y** [zzzgydi/clash-verge#536]
系统更新至macos 13 后，clash-verge 无法连接，clash-verge 上节点测速 显示正常，但无法连接google

**Comment by zzzgydi** [comment]
开了系统代理了么，可以开关一次重新设置代理

**Comment by sysongyi** [comment]
我的macos也无法自动设置代理配置，手动设置后是好用的。

**Comment by Toad-stool** [comment]
内核切换那里点击小🔒试试
