### ISSUE TITLE
1.3.1版本

### ISSUE THREAD

**Issue by MINGBOOK** [zzzgydi/clash-verge#545]
正常安装，安装后点击图标没反应

**Comment by neovali** [comment]
试试安装webkit2gtk和libayatana-indicator

**Comment by weyeee** [comment]
我是正常使用后，昨天突然出现楼主的问题

**Comment by MINGBOOK** [comment]
> 试试安装webkit2gtk和libayatana-indicator

谢谢，不过我已经换了CFW，之前不知道CFW在Linux也可以，CFW可能更适合我的使用习惯
