### ISSUE TITLE
[Bug] [Feature Request] 以服务（管理员）模式启动 Clash Verge

### ISSUE THREAD

**Issue by alex3236** [zzzgydi/clash-verge#55]
## 问题
打开 `TUN 模式` 和 `开机自启` 后，Clash Verge 开机自启时无法拿到管理员权限，TUN 模式不生效。相关报错如下：
```
ERROR Start Tun interface error: error creating interface: Access is denied.
```

## 解决
参考 Clash For Windows，将 Clash Verge 注册为服务。

**Comment by alex3236** [comment]
突然发现和 #46 重复了（能快点修吗awa

**Comment by zzzgydi** [comment]
这周末看看 awa

**Comment by shikkoku** [comment]
我尝试以计划任务启动选择高权限运行，结果失败。

**Comment by zzzgydi** [comment]
> 我尝试以计划任务启动选择高权限运行，结果失败。

你是用计划任务执行了哪个进程的呢

**Comment by shikkoku** [comment]
> > 我尝试以计划任务启动选择高权限运行，结果失败。
> 
> 你是用计划任务执行了哪个程序的呢

Clash Verge.exe

**Comment by zzzgydi** [comment]
> 我这边开启了静默启动后，依然需要右键以管理员模式启动才能运行TUN模式。

情况确实是这么个情况，还需要一点点时间看看

**Comment by zzzgydi** [comment]
现在已经实现service mode了，还没发新版，着急或感兴趣的可以源码编译一下

**Comment by shikkoku** [comment]
坐等Releases

**Comment by zzzgydi** [comment]
已经发了1.0.0版本，可以试试。如果安装服务有遇到问题，可以看看issue https://github.com/zzzgydi/clash-verge/issues/74
