### ISSUE TITLE
更新所有配置

### ISSUE THREAD

**Issue by BaronChushao** [zzzgydi/clash-verge#556]
不知道现在默认的更新所有配置通不通过代理，现在发现点击更新所有配置有的机场转圈圈转很久都没更新，单个右键点击更新（代理）就可以了更新，所以能不能默认通过代理更新或者更新所有配置给个代理选项

**Comment by zzzgydi** [comment]
可以手动编辑每个profile的更新逻辑是否通过代理，右键-编辑信息，往下滑。
