### ISSUE TITLE
模拟按键是安全的吗

### ISSUE THREAD

**Issue by ZvZvZ** [zzzgydi/clash-verge#560]
如题，每一次打开都会弹出模拟按键请求，不管我通过还是禁用都可以正常使用，请问为啥会有模拟按键需求以及这安全吗？

**Comment by zzzgydi** [comment]
什么系统，什么样的模拟按键请求，可以来个截图看看的。可能是快捷键功能导致的

**Comment by ZvZvZ** [comment]
> 什么系统，什么类型的模拟按键请求，可以来个截图看的。可能是快捷键功能导向的

Win10；1.3.0版；就只写了模拟按键请求，来自Clash Verge.exe；每一次打开都会出现。如果是快捷键功能的话我完全不用而且禁用不影响正常使用，所以每一次我设置了默认禁用
