### ISSUE TITLE
merge规则无效

### ISSUE THREAD

**Issue by ssssssbbb** [zzzgydi/clash-verge#563]
wiki看了又看，弄出来规则就是在总规则里面看不到，也无效，append/prepennd都无效，往主规则里面一加就有了。。。

**Comment by yswtrue** [comment]
启动之后最好重启一下内核，然后看下那个`运行配置`的内容有没有生效，还有确认`clash 字段`里面有没有加了你加的字段

**Comment by ssssssbbb** [comment]
> 启动之后最好重启一下内核，然后看下那个`运行配置`的内容有没有生效，还有确认`clash 字段`里面有没有加了你加的字段

内核重启过的，整个软件都重启过，规则禁用/启用过，规则不需要看字段的，dns那些才要

你没有出现失效的情况吗

**Comment by yswtrue** [comment]
我这几个版本没有改过规则，但好像现在有时候在运行中启用规则会没反应，我要重启app,然后才能启用规则

**Comment by ssssssbbb** [comment]
> 我这几个版本没有改过规则，但好像现在有时候在运行中启用mix会没反应，我要重启app,然后才能启用mix

找到原因了，我之前研究DNS问题的时候，在主配置那边抄过来DNS字段，这一段在merge配置里面，无论勾选DNS字段与否都被判定无效，进而造成整个merge配置无效了
