### ISSUE TITLE
什么时候发新版呀

### ISSUE THREAD

**Issue by gaoyang385** [zzzgydi/clash-verge#565]
什么时候发版呀？我看订阅无法下载的问题被修复了，我自己build后发现问题已经解决了，跪求发新版~~

**Comment by chen1376** [comment]
通求个新版，也是因为订阅地址无法下载

**Comment by zzzgydi** [comment]
OK的，今晚搞一个

**Comment by chen1376** [comment]
提供一个不能下载的订阅链接做测试
https://hk.ch1376.love:8888/api/auth/subscribe/Qkx2d3Z4dDB0c2VMRzhicV9EanFUY2xJem11QmVNTXR6NC0tc2lDQ3hZRzMzSExG

**Comment by zzzgydi** [comment]
可以试试

**Comment by chen1376** [comment]
![微信图片_20230519101747](https://github.com/zzzgydi/clash-verge/assets/108461131/e54fac42-3148-4578-a12b-34e2365aa782)


> 可以试试

大佬  似乎新版还是不支持上面这种订阅

**Comment by zzzgydi** [comment]
上面这个链接我在浏览器都访问不了呢

**Comment by chen1376** [comment]
https://demo.665599.xyz:8888/api/auth/subscribe/dEZqRDJYMUY2aTlGZldwMkdEVTVWYmkxY29udWFDaERLSVlidzl6TUZycXZNb1N6



这个呢

**Comment by zzzgydi** [comment]
> 提供一个不能下载的订阅链接做测试
https://hk.ch1376.love:8888/api/auth/subscribe/Qkx2d3Z4dDB0c2VMRzhicV9EanFUY2xJem11QmVNTXR6NC0tc2lDQ3hZRzMzSExG

这个链接在新版可以导入。我这里试直接url导入，会报错。新建一个remote再填url就可以。区别在于url导入会经过系统代理。新建remote的话可以在底下选是否经过代理。经不经过代理啥的，会影响域名的解析，所以可以自己试试。



> ![微信图片_20230519101747](https://user-images.githubusercontent.com/108461131/239420079-e54fac42-3148-4578-a12b-34e2365aa782.png)

这个问题是配置有问题，得看看
