### ISSUE TITLE
求助，Profiles页面无法打开

### ISSUE THREAD

**Issue by Raylqj** [zzzgydi/clash-verge#566]
安装版本为Clash.Verge_1.3.1_x64_zh-CN.msi，其他页面正常，Profiles页面报错如下：
Something went wrong:(
Cannot read propeties of undefined (reading 'uid')
点击Profiles页面后，再点击其他5个页面报错相同。请问如何解决？
尝试回退到版本Clash.Verge_1.0.3_x64_zh-CN.msi，Profiles页面为空（不显示）

**Comment by ssssssbbb** [comment]
https://github.com/zzzgydi/clash-verge/issues/475#issue-1640376591

**Comment by Raylqj** [comment]
> [#475 (comment)](https://github.com/zzzgydi/clash-verge/issues/475#issue-1640376591)

问题解决！谢谢。解决方式如下：
删除指定文件：C:\Users\*Username\.config\clash-verge\profiles.yaml，重启客户端
