### ISSUE TITLE
SS协议的cipher: 2022-blake3-aes-128-gcm不支持

### ISSUE THREAD

**Issue by 8MiYile** [zzzgydi/clash-verge#569]
内核本身是支持的
![截图_选择区域_20230518180303](https://github.com/zzzgydi/clash-verge/assets/25455400/6223ff6d-0371-4ff1-b9e6-8bb27bf9c4a3)

**Comment by zzzgydi** [comment]
有切换到clash meta么

**Comment by 8MiYile** [comment]
@zzzgydi 
如何切换呢 是在设置页吗？

**Comment by zzzgydi** [comment]
在设置页-Clash内核旁边的设置

**Comment by 8MiYile** [comment]
好的谢谢 我以为是自动以Meta为主
