### ISSUE TITLE
建议默认不加载msedgewebview2

### ISSUE THREAD

**Issue by sephiroth945** [zzzgydi/clash-verge#57]
Clash Verge打开后会默认加载配置界面，后台看有数个msedgewebview2的进程，占用不少内存，建议可以不默认加载msedgewebview2，打开配置界面时再加载，关闭配置界面后关闭相关进程，减少内存占用，这样相比CFW优势更大。

<img width="705" alt="2022-04-09_183031" src="https://user-images.githubusercontent.com/7221339/162568227-494572bd-664d-4f09-ba6f-38b7292db641.png">

**Comment by zzzgydi** [comment]
建议挺好，就是暂时不知道如何实现

**Comment by sephiroth945** [comment]
太棒了！
