### ISSUE TITLE
不能用 wsl 打包吗？

### ISSUE THREAD

**Issue by MMMMMoris** [zzzgydi/clash-verge#570]
tauri 不能跨平台打包吗？我不想在windows 上面安装 rust，感觉很麻烦，用了wsl打包，但是却一直没有生成可执行文件，只是生成了网页端的依赖文件，就是只运行了 yarn run web:build 这个命令

![image](https://github.com/zzzgydi/clash-verge/assets/63332824/7179bf57-f24f-443c-a933-da3f6424f307)

**Comment by zzzgydi** [comment]
https://tauri.app/v1/guides/building/cross-platform/#experimental-build-windows-apps-on-linux-and-macos 可能得看看这个
