### ISSUE TITLE
m1 pro 无法安装clash-verge

### ISSUE THREAD

**Issue by keiyunwong** [zzzgydi/clash-verge#584]
下载包：Clash.Verge_1.3.2_aarch64.dmg。点开后提示“Clash Verge.app” is damaged and can’t be opened. You should move it to the Trash.

**Comment by charley008** [comment]
#369

**Comment by keiyunwong** [comment]
> #369 但凡你搜一下 issues 就不会发这个问题

ok了 谢谢
