### ISSUE TITLE
关于libssl.so.3缺失问题

### ISSUE THREAD

**Issue by lblbk** [zzzgydi/clash-verge#587]
我现在一直用的1.2.0版本，之前也更新了新版本还是报错，今天本来打算更新一下看到有人还是不能运行，所以想问一下openssl在ubuntu问题有解决吗

**Comment by zzzgydi** [comment]
我更新了一下，可以试一下alpha release，https://github.com/zzzgydi/clash-verge/releases/tag/alpha

**Comment by lblbk** [comment]
> 我更新了一下，可以试一下alpha release，https://github.com/zzzgydi/clash-verge/releases/tag/alpha

好的 谢谢开发大大 另外本来我想提pr但我不会...我在另一仓库看到其他作者也有openssl问题解决是在其它系统编译的 我把链接贴到这儿了 希望能有所帮助 https://github.com/pot-app/pot-desktop/blob/51298bca0116c8a51f8e13fc94f47e34156a4c98/.github/workflows/package.yml#LL322C18-L322C27 universal版本可以在ubuntu20中正常使用

**Comment by lblbk** [comment]
另外这个版本还是会报...

```
bpmf@bpmf-VirtualBox:~/Downloads$ sudo dpkg -i ./clash-verge_1.3.2_amd64.deb 
Selecting previously unselected package clash-verge.
(Reading database ... 166930 files and directories currently installed.)
Preparing to unpack ./clash-verge_1.3.2_amd64.deb ...
Unpacking clash-verge (1.3.2) ...
dpkg: dependency problems prevent configuration of clash-verge:
 clash-verge depends on libayatana-appindicator3-1; however:
  Package libayatana-appindicator3-1 is not installed.

dpkg: error processing package clash-verge (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 clash-verge
bpmf@bpmf-VirtualBox:~/Downloads$ clash-verge
clash-verge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

```

**Comment by cxgreat2014** [comment]
依然报错+1

**Comment by gchust** [comment]
> 我更新了一下，可以试一下alpha release，https://github.com/zzzgydi/clash-verge/releases/tag/alpha

这个版本OK! 
![image](https://github.com/zzzgydi/clash-verge/assets/5254737/546edf37-3ca7-4581-8b21-24785517ee26)

**Comment by zzzgydi** [comment]
Ubuntu 20.04，试试v1.3.6
Ubuntu 22.04，试试v1.3.7
