### ISSUE TITLE
使用meta内核未读取配置文件中的unified-delay字段

### ISSUE THREAD

**Issue by Toad-stool** [zzzgydi/clash-verge#590]
使用meta内核未读取配置文件中的unified-delay字段

![image](https://github.com/zzzgydi/clash-verge/assets/26811405/8fb0d10d-837f-4e4d-a7d3-f5f86b6dd086)

**Comment by BaronChushao** [comment]
可以去设置里的杂项设置把第二个关了试试

**Comment by Toad-stool** [comment]
> 

试了，可以，这个设置的作用是？

**Comment by BaronChushao** [comment]
翻译是clash字段过滤器，如果clash fields filter开了就要去clash字段中勾选对应的字段才能生效，关了就是不需要。
因为你这个没有在verge的clash字段里，所以需要关掉才能生效
