### ISSUE TITLE
请问我在Profiles中启用的script里调用了console.log，这个日志文件写在哪里了呢？

### ISSUE THREAD

**Issue by 1nC0deWeTrust** [zzzgydi/clash-verge#591]
在cfw中是有定位文件的入口的，我猜想可能verge参考了cfw的设计，但是在cfw-parser.log所在的目录我也没有找到相关的日志文件，在本项目的wiki，issue中也没有搜到相关内容。

日志对编写、调试预处理代码至关重要，望作者回复。@zzzgydi

![image](https://github.com/zzzgydi/clash-verge/assets/25895481/cd9ad696-abe0-4ffa-9b66-b626b1e6dc63)

**Comment by zzzgydi** [comment]
这个输出没写到日志文件里，输出全在这里：
<img width="296" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/27361820/74d63f10-c86e-42a9-89dd-5e19810a5508">
