### ISSUE TITLE
meta速度明显比premium内核差

### ISSUE THREAD

**Issue by toyo2333** [zzzgydi/clash-verge#595]
1，windows11，稳定版
2，用的是机场的订阅，应该都是ss
3，之前在CFW，ClashX，iOS上都稳定高速使用，装verge默认速度也不错，切换meta后，就卡了
4，页面刷新慢，youtube慢，刚刚在这里提交issus后直接断网了，什么都没保存，这里再写一遍
5，切回premium正常

本身是冲着简洁的UI，和全开源的目的来的，但现在meta这个体验，劝退了
---------------0630更新-----------

来这里道个歉。现在确认一共是机场订阅导入yaml后和meta内核有兼容性问题。我自己建的都ok。已解决。

**Comment by rmdbbs** [comment]
我这个issue用meta两次都提交不成功，最后用premium内核提交成功了。绝了~

**Comment by rmdbbs** [comment]
我放弃了，最近用V2rayN了

**Comment by rmdbbs** [comment]
还想用，作者能来看下么？想想办法？

**Comment by sakuraDan2023** [comment]
这是meta核的问题吧，和verge无关吧

**Comment by zzzgydi** [comment]
meta速度的问题可以到meta的issue里反馈一下 https://github.com/MetaCubeX/Clash.Meta/issues/new/choose

**Comment by moranno** [comment]
既然要用meta，那就应该用meta才支持的新协议啊，还用啥ss，推荐个hysteria协议机场
https://panel.dg1.top/#/register?code=6hUggsHY

**Comment by toyo2333** [comment]
> 既然要用meta，那就应该用meta才支持的新协议啊，还用啥ss，推荐个hysteria协议机场 https://panel.dg1.top/#/register?code=6hUggsHY


来这里道个歉。现在确认一共是机场订阅导入yaml后和meta内核有兼容性问题。我自己建的都ok。已解决。

**Comment by CellLz** [comment]
我把clash meta内核放在旁路由上开放一个socks端口，然后本地用的是cfw的premium内核，既能直接连接节点也能通过旁路由socks端口对外访问，结果现在通过旁路由上网的延迟比本地直接cfw还低。很不理解这种现象。

**Comment by BiFangKNT** [comment]
> > 既然要用meta，那就应该用meta才支持的新协议啊，还用啥ss，推荐个hysteria协议机场 https://panel.dg1.top/#/register?code=6hUggsHY
> 
> 来这里道个歉。现在确认一共是机场订阅导入yaml后和meta内核有兼容性问题。我自己建的都ok。已解决。
> 
> 自己建的换了reality

请问具体怎么设置？用别人做的订阅转换可以吗
