### ISSUE TITLE
LINUX系统无法开启系统代理

### ISSUE THREAD

**Issue by newyorkthink** [zzzgydi/clash-verge#596]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/dd7062ba-94a3-4d0c-96e0-efaed689eeb8)
选择之后，浏览器还是需要设置端口才能连接

**Comment by AnyWAT** [comment]
规则、全局。。。想不设置端口，需开启系统代理。
![image](https://github.com/zzzgydi/clash-verge/assets/37962734/a18d2679-ada3-4d07-aaee-b3e208148d16)

**Comment by newyorkthink** [comment]
> 规则、全局。。。想不设置端口，需开启系统代理。 ![image](https://user-images.githubusercontent.com/37962734/243087962-a18d2679-ada3-4d07-aaee-b3e208148d16.png)

![image](https://github.com/zzzgydi/clash-verge/assets/87791643/d32a63db-ac88-4ef9-a411-a85c63bf5948)
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/b4264abf-7643-48d2-9c23-306680e73cfa)

**Comment by newyorkthink** [comment]
我刚刚试了下，还是不行

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/244f3e4b-a26d-4255-a619-84ab4bdb589a)

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/c9ba19f6-534b-4c21-b515-2d3992f85fd7)

**Comment by newyorkthink** [comment]
球球，母鸡炸搞，哎哟

**Comment by AnyWAT** [comment]
PC上没开启 Tun 模式、开启系统代理，谷歌浏览器禁用代理插件或使用系统代理，规则、全局军代理正常。

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/bc16010a-b1c4-4cef-aabb-24cea791ab3a)

**Comment by newyorkthink** [comment]
还是不行

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/8fdfb08c-7a63-4f94-aa95-2a6343e4b444)

**Comment by AnyWAT** [comment]
试试：更换内核
![image](https://github.com/zzzgydi/clash-verge/assets/37962734/9b8b121b-5969-4495-977b-d63db8c936f9)

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/e918c2a8-62ab-403c-931d-67e05ef47700)
换了，重启，还是不行

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/41700927-20f5-4afc-88e8-3c2a3236e9a6)
刚刚打开一下youtube 一直在转

**Comment by AnyWAT** [comment]
节点上第二个图标：延迟测试
节点没通？

**Comment by AnyWAT** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/37962734/595798a8-2aeb-459c-978f-d05b54c36624)
![image](https://github.com/zzzgydi/clash-verge/assets/37962734/29a088df-af66-4d7b-a739-d469af810ecb)

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/9f2236be-47f9-4612-8df1-b8c2f682da34)
首先我的节点都是通的

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/b23fab4c-3b1d-458d-be2c-b1f4ac678cf5)
这个y一直是false,我也不清楚

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/13bc93f2-625e-48af-a6f7-b3b19a5c865a)
如果是设置端口的话，就可以，全局就不行

**Comment by AnyWAT** [comment]
> 这个y一直是false,我也不清楚

非Windows系统，无法开启系统代理。。。不是所谓全局无效😆

**Comment by newyorkthink** [comment]
那咋办

**Comment by newyorkthink** [comment]
怎样才能全局 全部流量都转国外

**Comment by newyorkthink** [comment]
类似v2raya 那种透明代理

**Comment by AnyWAT** [comment]
> 那咋办

自己搜索：
XXX操作系统怎样开启系统代理？

**Comment by AnyWAT** [comment]
> 怎样才能全局 全部流量都转国外
> 如果是设置端口的话，就可以

用全局不就是？

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/54031b13-be2e-4a10-852f-0594ad7b18be)

**Comment by newyorkthink** [comment]
太难了，不懂

**Comment by newyorkthink** [comment]
搞了下，还是不行，还是false

**Comment by newyorkthink** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/87791643/a35e1351-76a5-409f-933f-1bb672998e30)

**Comment by AnyWAT** [comment]
有情况：https://github.com/zzzgydi/clash-verge/issues/430#issuecomment-1447823453

**Comment by newyorkthink** [comment]
> 有情况：[#430 (comment)](https://github.com/zzzgydi/clash-verge/issues/430#issuecomment-1447823453)

这个我不是很懂，看了下，没中文说明那些

**Comment by newyorkthink** [comment]
> 有情况：[#430 (comment)](https://github.com/zzzgydi/clash-verge/issues/430#issuecomment-1447823453)

还有 meta出来新内核

**Comment by zzzgydi** [comment]
看起来是系统代理设置失败了，至于为啥失败，可能发一下日志才能知道了。

解决办法：
1. 多开关几次设置页的“系统代理”看看管用不。

上面不行的话，你应该是macOS系统？就手动在系统的设置里，找到WIFI，找到详细设置/或者高级，找到代理。把HTTP和HTTPS勾上，像下面这样填：

<img width="447" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/27361820/6209530b-f95a-4ce7-a5d5-86e41b9a3ab7">

**Comment by AnyWAT** [comment]
> 非Windows系统，无法开启系统代理。。。不是所谓全局无效😆

请贴主修改标题：clash 全局模式无效 #596
为
XXX系统无法开启系统代理 #596

**Comment by zzzgydi** [comment]
linux 啥发行版的呢

**Comment by coco456** [comment]
全局后，浏览器开无痕模式试试YouTube 可以不

**Comment by realwyz** [comment]
> 怎样才能全局 全部流量都转国外

想办法开启TUN模式，系统代理和TUN模式我的理解应该是不同层面实现的同一件事，所以只需使用其中一个。
我之前是TUN模式启用不了，设置了`setcap`也不行，所以也是一样通过端口访问的。
后来发现Linux下需要把tun的`stack`改成`gvisor`，然后就能用了。

**Comment by zwyyy456** [comment]
同 macOS 无法在 clash verge 里面开启系统代理。。。

**Comment by idnsunset** [comment]
在 XUbuntu 20.04 上系统代理不可用，启用了也没有效果。如果说 Xfce 本身就不支持系统级代理可能成为原因，但是我在 Fedora 38 (i3wm，同样没有系统代理设置) 上却可以使用系统代理）。

**Comment by Guanran928** [comment]
xdg-config/chrom{e,ium}-flags.conf
```
--proxy-server="127.0.0.1:7890"
```

**Comment by Guanran928** [comment]
在 Linux 下，Chromium 软件只会在 DE 为 Gnome 或 KDE 下才会使用系统代理设置 [source](https://chromium.googlesource.com/chromium/src/+/master/docs/linux/proxy_config.md)
在其他 DE/WM/Compositor 下，请将以下参数添加至 命令行参数或 `xdg-config/{chrom{e,ium},electron}-flags.conf`  `--proxy-server=<scheme>=<uri>[:<port>][;...] | <uri>[:<port>] | "direct://"` [source](https://www.chromium.org/developers/design-documents/network-settings/#command-line-options-for-proxy-settings)
