### ISSUE TITLE
Clash Verge no connection, no upload speed, no download speed, 

### ISSUE THREAD

**Issue by Laurencesung** [zzzgydi/clash-verge#597]
Clash Verge no connection, no upload speed, no download speed, the proxy are with no problem.
![3891685777166_ pic](https://github.com/zzzgydi/clash-verge/assets/126935837/c4ccc7c6-6aab-47ee-b040-1a6c264a47ae)
![3881685777137_ pic](https://github.com/zzzgydi/clash-verge/assets/126935837/c7fbaf83-5393-43e1-8699-5ae0ec9faad4)

**Comment by AnyWAT** [comment]
😆软件用中文，提问却英文。
该软件与浏览器的代理协议、端口未匹配时，不就如此结果？

**Comment by Laurencesung** [comment]
> 😆软件用中文，提问却英文。 该软件与浏览器的代理协议、端口未匹配时，不就如此结果？
看到这个网站都是英文，就打的英文，平时软件一般用的中文界面。你的意思是要设置一下浏览器吗？

**Comment by AnyWAT** [comment]
该软件不开系统代理，浏览器用代理插件设置。。。

**Comment by Laurencesung** [comment]
> 

貌似还是不行，我用CLASH X， 或者Clash X pro没有任何问题，但是 clash verge 依然不行，没有任何上传下载速度

**Comment by AnyWAT** [comment]
你的节点都有延迟数字了，说明能行，只是该软件与浏览器未连通。
检查该软件“端口设置”，截图代理插件设置？

**Comment by AnyWAT** [comment]
> 用CLASH X

貌似MAC？

**Comment by AnyWAT** [comment]
> 该软件不开系统代理，浏览器用代理插件设置。。。

或：该软件开启系统代理，浏览器禁用代理插件或使用系统代理。

**Comment by Laurencesung** [comment]
> 你的节点都有延迟数字了，说明能行，只是该软件与浏览器未连通。 检查该软件“端口设置”，截图代理插件设置？

![3941685872223_ pic](https://github.com/zzzgydi/clash-verge/assets/126935837/48304c34-a240-4c0d-8521-13cb922d1096)
![3951685872252_ pic](https://github.com/zzzgydi/clash-verge/assets/126935837/82e887a9-cced-4295-a4f1-e660fd312d1e)
这个全球直连 是不是有问题呀，端口看了是7890

**Comment by AnyWAT** [comment]
> 这个全球直连 是不是有问题呀，端口看了是7890

我用的他人配置，不懂。
端口可以自定义，与浏览器插件匹配即可。

**Comment by zzzgydi** [comment]
有没有开启系统代理，默认是不开的

**Comment by Laurencesung** [comment]
> 有没有开启系统代理，默认是不开的

开了的，没用。不知道为什么。

**Comment by AnyWAT** [comment]
> 开了的，没用。不知道为什么。

> > 该软件不开系统代理，浏览器用代理插件设置。。。
> 
> 或：该软件开启系统代理，浏览器禁用代理插件或使用系统代理。

貌似最佳：不开系统代理，浏览器用插件。

https://github.com/zzzgydi/clash-verge/issues/596#issuecomment-1574925781
不同系统：上图正常开启，下图则否。

**Comment by Laurencesung** [comment]
> 

没看到你的图片，浏览器用插件，你的意思是浏览器需要装什么插件吗？这方面不太懂

**Comment by AnyWAT** [comment]
点击链接看图。
如 chrome 用 SwitchyOmega

**Comment by AnyWAT** [comment]
> 貌似最佳：不开系统代理，浏览器用插件。

不影响系统，可运行若干个不同端口的代理。

**Comment by AnyWAT** [comment]
https://github.com/zzzgydi/clash-verge/issues/597#issue-1740202454
https://github.com/zzzgydi/clash-verge/issues/597#issuecomment-1575481482
提问，至少还得说明自己的操作系统、浏览器。。。

**Comment by Laurencesung** [comment]
> [#597 (comment)](https://github.com/zzzgydi/clash-verge/issues/597#issue-1740202454) [#597 (comment)](https://github.com/zzzgydi/clash-verge/issues/597#issuecomment-1575481482) 提问，至少还得说明自己的操作系统、浏览器。。。

mac air 2022的，浏览器 microsoft edge 主要是以前一直都可以，只是最近老版本出问题了，升级了后就不行了。

**Comment by Laurencesung** [comment]
> [#597 (comment)](https://github.com/zzzgydi/clash-verge/issues/597#issue-1740202454) [#597 (comment)](https://github.com/zzzgydi/clash-verge/issues/597#issuecomment-1575481482) 提问，至少还得说明自己的操作系统、浏览器。。。

mac air 2022的，浏览器 microsoft edge 主要是以前一直都可以，只是最近老版本出问题了，升级了后就不行了。

**Comment by AnyWAT** [comment]
Windows下，microsoft edge 同样可以使用 chrome 商店的 SwitchyOmega（edge 商店的貌似冒牌，不要用？）

**Comment by AnyWAT** [comment]
> 浏览器 microsoft edge 主要是以前一直都可以，只是最近老版本出问题了，升级了后就不行了。

也可以轻车熟路，先卸载再安装最新版本？

**Comment by Laurencesung** [comment]
> > 浏览器 microsoft edge 主要是以前一直都可以，只是最近老版本出问题了，升级了后就不行了。
> 
> 也可以轻车熟路，先卸载再安装最新版本？

卸载装过的，clash verge 1.3.1，1.3.2，1.3.2都试过。浏览器都是最新版本的。

**Comment by AnyWAT** [comment]
截图的图标带红NEW，貌似不是最新版本。
Windows下该软件在窗口显示于桌面时貌似用了 WebView，试试更新下？

**Comment by Laurencesung** [comment]
> 截图的图标带红NEW，貌似不是最新版本。 Windows下该软件在窗口显示于桌面时貌似用了 WebView，试试（退出后）更新下？

先试的最新的1.3.2，结果安装了 aarch64版本，根本打不开用不了，一打开都提示卸载之类的。就选的1.3的其他版本。

**Comment by AnyWAT** [comment]
更新下WebView？

**Comment by Laurencesung** [comment]
> 更新下WebView（114.0.1823.37）？

不太了解这个webview怎么更新，你是指 microsoft edge浏览器的吗？ 还是mac 系统的呢？这几天都没有用clash verge了。一直用clash X

**Comment by AnyWAT** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/37962734/132cdc1b-dca9-4274-85ec-691a3c9aeb14)
如PC，设置——应用——应用和功能
第一项，微软浏览器
第二项，浏览器更新之系统任务
第三项， WebView，其它软件的窗口框架？
左键该项，修改。。。更新

**Comment by zzzgydi** [comment]
sorry之前回复错issue了。

这个问题99.99·%是没开系统代理，或者开了但是出错导致流量并没有经过verge。

你可以先把clash x关了，然后再打开verge，在设置页面打开系统代理。如果失败了就反复开关几次。（如何确认有没有失败，点开系统代理旁边的齿轮icon，看看弹窗信息下面的Enable是不是为true，就知道是不是真的失败了）

如果真的失败了，就参考我的这个回复 https://github.com/zzzgydi/clash-verge/issues/596#issuecomment-1576102482 手动在mac系统里设置代理信息就可以了。

如果还是不行，或者不想。也可以参考上面的朋友提到的，在浏览器用SwitchyOmega插件，使用教程可自行谷歌百度。

还有别的方案，比如开TUN，也可以自行查看别的issue。

上述方案都是为了一个目的，将你需要科学上网的流量正确地流到verge里。
