### ISSUE TITLE
蹲一个Linux版

### ISSUE THREAD

**Issue by rsesot** [zzzgydi/clash-verge#6]

**Comment by zzzgydi** [comment]
可能要蹲得比较久...

**Comment by breakings** [comment]
> 可能要蹲得比较久...

哈哈，期待大佬代码适配下 Linux平台，目前这些地方都没定义。

```
yarn dev      
yarn run v1.22.17
$ tauri dev
[tauri:dev] Running `yarn run web:dev`
[tauri:dev] Waiting for your frontend dev server to start on http://localhost:3000/...
$ vite

  vite v2.8.6 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 240ms.

   Compiling clash-verge v0.1.0 (/home/jack/clash-verge/src-tauri)
   Compiling tauri-runtime-wry v0.3.2
   Compiling tauri v1.0.0-rc.3
error[E0425]: cannot find value `DEFAULT_BYPASS` in this scope
  --> src/utils/sysopt.rs:34:32
   |
34 |       bypass: bypass.unwrap_or(DEFAULT_BYPASS.into()),
   |                                ^^^^^^^^^^^^^^ not found in this scope

warning: unused import: `std::io`
 --> src/utils/sysopt.rs:2:5
  |
2 | use std::io;
  |     ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `get_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:101:49
    |
101 |       self.old_sysproxy = match SysProxyConfig::get_sys() {
    |                                                 ^^^^^^^ function or associated item not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- function or associated item `get_sys` not found for this

error[E0599]: no method named `set_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:110:21
    |
110 |         if sysproxy.set_sys().is_err() {
    |                     ^^^^^^^ method not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- method `set_sys` not found for this

error[E0599]: no method named `set_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:125:22
    |
125 |       match sysproxy.set_sys() {
    |                      ^^^^^^^ method not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- method `set_sys` not found for this

error[E0599]: no method named `set_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:214:21
    |
214 |         if sysproxy.set_sys().is_err() {
    |                     ^^^^^^^ method not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- method `set_sys` not found for this

error[E0599]: no method named `set_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:233:23
    |
233 |           if sysproxy.set_sys().is_err() {
    |                       ^^^^^^^ method not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- method `set_sys` not found for this

error[E0599]: no method named `set_sys` found for struct `SysProxyConfig` in the current scope
   --> src/core/verge.rs:316:34
    |
316 |             log_if_err!(sysproxy.set_sys());
    |                                  ^^^^^^^ method not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- method `set_sys` not found for this

error[E0599]: no function or associated item named `get_sys` found for struct `SysProxyConfig` in the current scope
   --> src/cmds.rs:243:29
    |
243 |   wrap_err!(SysProxyConfig::get_sys())
    |                             ^^^^^^^ function or associated item not found in `SysProxyConfig`
    |
   ::: src/utils/sysopt.rs:13:1
    |
13  | pub struct SysProxyConfig {
    | ------------------------- function or associated item `get_sys` not found for this

Some errors have detailed explanations: E0425, E0599.
For more information about an error, try `rustc --explain E0425`.
warning: `clash-verge` (bin "clash-verge") generated 1 warning
error: could not compile `clash-verge` due to 8 previous errors; 1 warning emitted
```

**Comment by zzzgydi** [comment]
@breakings 这些都是和设置系统代理有关的内容，有关linux系统代理的设置我还不懂。。。这个问题只需要针对linux实现两个函数即可，有没有兴趣来个PR啥的呢

**Comment by rsesot** [comment]
写个判断不是Windows就用iproute2和nftables的透明代理呢
系统代理，Linux一条指令就OK了（

**Comment by zzzgydi** [comment]
现在应该可以在linux上编译了，关于linux系统代理实现的讨论在 https://github.com/zzzgydi/clash-verge/pull/15 ，先这样实现看看有没有什么问题。

**Comment by breakings** [comment]
> 现在应该可以在linux上编译了，关于linux系统代理实现的讨论在 #15 ，先这样实现看看有没有什么问题。

好家伙,但我尝试yarn dev出来的包三百多兆 运行 yarn release又提示要github token

**Comment by IWANABETHATGUY** [comment]
> > 现在应该可以在linux上编译了，关于linux系统代理实现的讨论在 #15 ，先这样实现看看有没有什么问题。
> 
> 好家伙,但我尝试yarn dev出来的包三百多兆 运行 yarn release又提示要github token

如果你不需要代理全局的话，可以试一试我的分支，我看了下只需要十几兆

**Comment by zzzgydi** [comment]
> 好家伙,但我尝试yarn dev出来的包三百多兆 运行 yarn release又提示要github token

yarn dev生成的是包含debug信息啥的没优化的执行文件，但也不会是几百M这么多吧，你可能找错了？

yarn release是给ci执行的，你需要构建的话，执行yarn build就好。

**Comment by breakings** [comment]
> > > 现在应该可以在linux上编译了，关于linux系统代理实现的讨论在 #15 ，先这样实现看看有没有什么问题。
> > 
> > 
> > 好家伙,但我尝试yarn dev出来的包三百多兆 运行 yarn release又提示要github token
> 
> 如果你不需要代理全局的话，可以试一试我的分支，我看了下只需要十几兆

好的，我尝试一下

**Comment by breakings** [comment]
> > 好家伙,但我尝试yarn dev出来的包三百多兆 运行 yarn release又提示要github token
> 
> yarn dev生成的是包含debug信息啥的没优化的执行文件，但也不会是几百M这么多吧，你可能找错了？
> 
> yarn release是给ci执行的，你需要构建的话，执行yarn build就好。

这次构建成功了，十几兆是正常了，deb和appimage都打包成功了，另外不支持导入本地yml配置文件吗

**Comment by zzzgydi** [comment]
@breakings 支持导入本地配置的，可以看看pinned issue 使用指南。

**Comment by inRm3D** [comment]
提供一个测试成功的 ci

https://github.com/inRm3D/clash-verge-1/actions/runs/2005500818

**Comment by zzzgydi** [comment]
@inRm3D 已经加了linux的ci，感谢

**Comment by inRm3D** [comment]
> @inRm3D 已经加了 linux 的 ci，感谢

不客气，ubuntu 这个缺包挺折磨人的（拆包狂魔）。我一开始试了 5,6 次，每次 rust build 到最后提示缺包。后面突然发现 https://github.com/tauri-apps/tauri-action 这个有提示依赖，就试成功了。

**Comment by zzzgydi** [comment]
@inRm3D 方便提供一个ubuntu里的界面截图吗，印象中我没有对linux的窗口做啥处理，ui上可能多了一点元素。

**Comment by inRm3D** [comment]
我用的是 Arch + appimage, 一开始用 deb 包 + debtap 转换，结果无法检测流量。appimage 除了似乎开机自启无效都能用。

![image](https://user-images.githubusercontent.com/64240055/159107115-89c3e385-4746-431d-b66a-754ca581515d.png)
![image](https://user-images.githubusercontent.com/64240055/159107134-57358663-f4e1-4d82-97eb-e78999b0b86b.png)
![image](https://user-images.githubusercontent.com/64240055/159107163-d249a602-09c9-45c5-9ca2-4220fa28c81f.png)
![image](https://user-images.githubusercontent.com/64240055/159107192-4c84b905-3687-4301-8cf4-14064b2043ba.png)
![image](https://user-images.githubusercontent.com/64240055/159107197-e86c2b5f-569c-4e5f-b0c9-faa2bf5951eb.png)

另外默认的窗口可以大一些。不然有时会挤到一起。

![image](https://user-images.githubusercontent.com/64240055/159107299-4670e1fe-75b4-490c-ae63-33551ee2d644.png)

**Comment by zzzgydi** [comment]
@inRm3D 右上角最小化最大化关闭那几个按键是不是多余了，linux应该有自己的窗口了

**Comment by inRm3D** [comment]
> @inRm3D 右上角最小化最大化关闭那几个按键是不是多余了，linux 应该有自己的窗口了

好像是的。

**Comment by zzzgydi** [comment]
@inRm3D ok，感谢

**Comment by breakings** [comment]
> @breakings 支持导入本地配置的，可以看看pinned issue 使用指南。

这种 yarn build的缓存怎么清理好些 这依赖的包好多 占用空间

**Comment by breakings** [comment]
> @inRm3D ok，感谢



> @breakings 支持导入本地配置的，可以看看pinned issue 使用指南。

这种 yarn build的缓存怎么清理好些 这依赖的包好多 占用空间

**Comment by inRm3D** [comment]
> > @inRm3D ok，感谢
> 
> > @breakings 支持导入本地配置的，可以看看 pinned issue 使用指南。
> 
> 这种 yarn build 的缓存怎么清理好些 这依赖的包好多 占用空间

debian 及衍生版就拿 deb 安装。其余的拿 AppImage. 然后可以删了整个项目。

以及已经提供了 ci, 作者加上了。后面可以不手动编译了。

**Comment by inRm3D** [comment]
![image](https://user-images.githubusercontent.com/64240055/159149660-ef8ec386-df89-41b0-98e9-81b8e8a9fabb.png)


> @inRm3D ok，感谢

我搞错了，好像还是要画的。现在没有那几个按钮了。可能是 tauri 实现机制不一样？

**Comment by zzzgydi** [comment]
@inRm3D 可以来一个完整的窗口截图吗

**Comment by inRm3D** [comment]
> @inRm3D 可以来一个完整的窗口截图吗

![image](https://user-images.githubusercontent.com/64240055/159186045-56cff6a9-4693-4a46-bdbd-35fbb18022d8.png)

~~那张就是完整的~~

**Comment by inRm3D** [comment]
这个 issue 应该可以关了。

**Comment by ccxka** [comment]
@zzzgydi 
![image](https://user-images.githubusercontent.com/84843406/229060368-3ca99386-24d8-4e84-8693-0940101f4037.png)
这个是咋回事啊

**Comment by ccxka** [comment]
> 

各位大神帮忙看看
