### ISSUE TITLE
Appimage on linux can't update directly.

### ISSUE THREAD

**Issue by inRm3D** [zzzgydi/clash-verge#60]
![image](https://user-images.githubusercontent.com/64240055/163044128-f4de52bf-fc40-4d40-a7ed-30663d4043cc.png)

It will download for a while, then pop out "time out". then behavior like nothing happened.

I find this https://docs.appimage.org/packaging-guide/optional/updates.html#making-appimages-self-updateable

**Comment by zzzgydi** [comment]
这个应该是访问github超时导致的
