### ISSUE TITLE
Class Verge已损坏，无法打开。

### ISSUE THREAD

**Issue by ningnw** [zzzgydi/clash-verge#600]
<img width="260" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/124015827/fb5311d9-2640-4b6c-9691-c9fe3c5c9a4c">
MacBook M1 Max  下载最新版本打不开软件，提示已损坏

**Comment by zzzgydi** [comment]
可以看看这个 https://github.com/zzzgydi/clash-verge/issues/369

**Comment by ningnw** [comment]
尝试之后问题解决了，谢谢
