### ISSUE TITLE
外部控制的 secret 存在 # 字符时，主界面变成了透明的

### ISSUE THREAD

**Issue by Yi-pixel** [zzzgydi/clash-verge#601]
- 设置 -> 外部控制 -> Core Secret

当设置的 secret 中包含 `#` 这个字符时，例如 `12d#s`，保存后，界面会变成透明的。

可以通过右键托盘图标 -> 打开目录 -> 应用目录，然后编辑 `config.yml` 中的 `secret` 删除值后重启恢复。

**Comment by zzzgydi** [comment]
感谢提醒！！已经修复，下个版本发。
