### ISSUE TITLE
微软服务

### ISSUE THREAD

**Issue by bsccw** [zzzgydi/clash-verge#602]
我该如何让uwp软件联网呢

**Comment by AnyWAT** [comment]
关闭 Clash 的系统代理，浏览器用代理插件，其它软件在其内部设置代理——并不影响 uwp 软件联网

**Comment by akschy** [comment]
下载uwploopback打开所有uwp回环设置。
或者clash for windows里有自带的，
![image](https://github.com/zzzgydi/clash-verge/assets/44605406/caf591f2-fa9a-4af8-a6d9-d1c505fe29a3)

win11可以下载云之幻写的网络回环管理器，勾选想要使用代理的uwp应用

**Comment by coco456** [comment]
关闭系统代理，开tun 模式

**Comment by PinkChampagne17** [comment]
https://github.com/zzzgydi/clash-verge/issues/314#issuecomment-1585709849
