### ISSUE TITLE
log level is still silent when set it from silent to debug in the setting panel

### ISSUE THREAD

**Issue by lankylonky22** [zzzgydi/clash-verge#607]
log level is still silent when set it from silent to debug in the setting panel, u can check the logs.
![image](https://github.com/zzzgydi/clash-verge/assets/105496277/f41a792c-812e-47e0-a143-bfe0aff966b8)

**Comment by zzzgydi** [comment]
The logs in this application are currently divided into Clash kernel logs and GUI program logs. The settings in the user interface correspond to the kernel, while the GUI program logs are currently uncontrollable and have always been at the Info level.
