### ISSUE TITLE
merge 类型的配置文件 enable 之后, 在 UI 上还是处于 disable 状态

### ISSUE THREAD

**Issue by wgqimut** [zzzgydi/clash-verge#609]
复现步骤:
创建一个 local 配置, 创建一个 merge 配置, 然后 enable 这两个配置.
再创建一个 merge 配置, 然后 enable, 这个时候看 runtime 的 config 配置, 已经是把这个 merge 配置生效了, 但是 UI 上还是显示这个 配置没有 enable, 这样导致的结果就是, 无法 disable

**Comment by zzzgydi** [comment]
> 创建一个 local 配置, 创建一个 merge 配置, 然后 enable 这两个配置.

指的是哪两个配置，dns和tun？这俩都受ui的控制，而不是反过来控制ui，所以如果在配置里enable了，是不生效的

**Comment by wgqimut** [comment]
“配置” 指的是 profile，local profile 和 merge profile

**Comment by zzzgydi** [comment]
懂了，退出程序再进来看看ui正常么

**Comment by wgqimut** [comment]
> 懂了，退出程序再进来看看ui正常么

退出程序之后，UI 跟实际生效的 profile 是保持一致的，但是是只有一个 merge profile 生效，这并不是我想要的那个结果，我想要的是两个 merge profile 都生效

**Comment by zzzgydi** [comment]
两个merge profile的内容可以分享一下么，感觉是字段覆盖了

**Comment by wgqimut** [comment]
> 两个merge profile的内容可以分享一下么，感觉是字段覆盖了

我检查了一下我的两个 profile, 你说的没错! 确实是两个 profile 里有下面这个重复的配置:
```yaml
append-proxies:
  - name: vpn1
    type: socks5
    server: 127.0.0.1
    port: 1080
```
当然我还有别的 `append-proxies`, 只不过有上面这个重复的部分, 去重之后就可以了, 感谢🙏
