### ISSUE TITLE
null

### ISSUE THREAD

**Issue by NianBroken** [zzzgydi/clash-verge#613]
null

**Comment by hdchieh** [comment]
太好笑了。用个eu.org的免费域名。关键排版一看就瓦房店，稍微有点审美也不至于一点审美也没有。

**Comment by Guanran928** [comment]
根据你的 Issue comment 修改记录，我认为 https://eugnaa.eu-gov.eu.org/ 是可疑的恶意网站，并且目前 Cloudflare 会警告 `Suspected Fhishing`。
![image](https://github.com/zzzgydi/clash-verge/assets/68757440/fb71c9aa-5247-4dcb-bf65-04edfd187c75)

请关闭 Issue。
