### ISSUE TITLE
托盘图标显示连接状态无效吗？

### ISSUE THREAD

**Issue by zzm-note** [zzzgydi/clash-verge#618]
版本1.3.2
根据https://github.com/zzzgydi/clash-verge/pull/537 中的描述，是不是切换系统代理图标会变色？
目前在1.3.2版本切了好像没有反应，切换规则模式也没反应

**Comment by KaetaXpog** [comment]
看起来#537 的合并晚于1.3.2的发布时间

**Comment by zzzgydi** [comment]
现在新版可以试试了，只有Windows生效
