### ISSUE TITLE
TUN模式能否支持redir-host

### ISSUE THREAD

**Issue by RikudouPatrickstar** [zzzgydi/clash-verge#619]
TUN 模式能否支持下 dns enhanced-mode 为 redir-host，而不强制使用 fake-ip，经常碰到大量类似如下错误：

![image](https://github.com/zzzgydi/clash-verge/assets/68163551/fbd0cffe-ba43-4170-b20d-c3c7b46af76e)

**Comment by bigbluebaby1** [comment]
meta核是支持redir-host的

**Comment by zzzgydi** [comment]
clash已经不支持redir-host了，要么用旧版clash，要么用meta吧

**Comment by wuyuqq** [comment]
> clash已经不支持redir-host了，要么用旧版clash，要么用meta吧

meta核心 使用redir-host，开启tun模式 会自动注入几行fakeip的字段....请问是正常的吗？
