### ISSUE TITLE
能否直接定位配置文件，将CLASH面板的配置与真实文件对应起来

### ISSUE THREAD

**Issue by studentluo** [zzzgydi/clash-verge#620]
就像CFW中右键可以直接定位文件一样，因为在Windows中文件的名称都不是能直接辨认的，对于一些本地编辑或者引用同一个文件的用户不是很方便，只能打开文件内容才知道这个文件是对应的哪个配置

**Comment by zzzgydi** [comment]
右键，点击打开文件就可以
<img width="141" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/27361820/1d804cee-91cb-4881-b35d-423ab13fb216">
