### ISSUE TITLE
BUG!开启verge之后onedrive客户端一直正在登陆，直连全局规则都无用，CFW则都可以

### ISSUE THREAD

**Issue by studentluo** [zzzgydi/clash-verge#622]
已替换premium或meta最新内核版本，更换onedrive版本都是如此。百分百复现

**Comment by zzzgydi** [comment]
onedrive客户端是不是uwp应用来着

**Comment by studentluo** [comment]
> onedrive客户端是不是uwp应用来着

定位到原因，verge和cfw的系统代理可能有所差别，确实是同配置verge无法登陆。 解除 【工作或学校帐户
】【电子邮件和帐户】UWP 回环就可以登陆了，而CFW则不需要。

verge的系统代理会改变电脑中这个代理设置，cfw不会改变这个设置
![image](https://github.com/zzzgydi/clash-verge/assets/68803942/db797d60-d0d0-4ada-82e3-b532e9693528)

**Comment by AnyWAT** [comment]
> verge的系统代理会改变电脑中这个代理设置，cfw不会改变这个设置

Wndows 10下都会，包括其它软件，开启系统代理就是自动填写并打开该代理服务器。

**Comment by studentluo** [comment]
好了我发现我的CFW是pac脚本代理，但是很奇怪，切成http代理也会是这样，但是问题已解决，解除那两个UWP回环就可以了，cfw确实是不需要解除，很奇怪 但无所谓
