### ISSUE TITLE
在Ubuntu18.04 上运行不了

### ISSUE THREAD

**Issue by KangShanR** [zzzgydi/clash-verge#624]
Ubuntu18.04
安装 deb 不能运行，窗口也不会弹出。
直接运行 ./clash-verge_1.3.2_amd64.AppImage 文件，error：
clash-verge: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

**Comment by Jaywxy** [comment]
一样的问题

**Comment by qian-you** [comment]
我把系统升级到 Ubuntu 22 了，可以安装 dep 并能正常使用了。

**Comment by zzzgydi** [comment]
中间有个版本开始，Linux的CI构建换了系统版本为ubuntu-latest，构建出来的app在ubuntu 18上就运行不了了。会出现一些什么openssl错误或者libc错误。 解决办法是，需要自己构建一下了，或者fork项目，改CI里的构建系统为ubuntu-18.04。

**Comment by zzzgydi** [comment]
可以试试这两个 
- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.AppImage
- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.deb

**Comment by Jaywxy** [comment]
> 中间有个版本开始，Linux的CI构建换了系统版本为ubuntu-latest，构建出来的app在ubuntu 18上就运行不了了。会出现一些什么openssl错误或者libc错误。 解决办法是，需要自己构建一下了，或者fork项目，改CI里的构建系统为ubuntu-18.04。

请问这个怎么处理呢？能具体说一下吗？

**Comment by zzzgydi** [comment]
我前几天试了Github的action，已经不支持ubuntu 18.04 了，所以只能自己fork项目本地打包了

**Comment by Jaywxy** [comment]
> 我前几天试了Github的action，已经不支持ubuntu 18.04 了，所以只能自己fork项目本地打包了

是的，我意思就是自己打包，改了ci文件的ubuntu版本，不知道怎么打包

**Comment by Jaywxy** [comment]
> 我前几天试了Github的action，已经不支持ubuntu 18.04 了，所以只能自己fork项目本地打包了

就改了ci.yaml文件还需要重新编译吗？我用caogo编译好像有点问题，还是说直接打包成deb就好了呀 
不太了解软件的编译打包

**Comment by zzzgydi** [comment]
自己打包的话，就不用改ci了，在本机上操作吧。

- 先这个 https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
- 再装个nodejs 和 yarn
- 再这个 https://github.com/zzzgydi/clash-verge#development

**Comment by Jaywxy** [comment]
> 自己打包的话，就不用改ci了，在本机上操作吧。
> 
> * 先这个 https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
> * 再装个nodejs 和 yarn
> * 再这个 https://github.com/zzzgydi/clash-verge#development

按你说的弄，好像还是有点问题，最后编译的时候报错：
error: linking with `cc` failed: exit status: 1

warning: `clash-verge` (bin "clash-verge") generated 7 warnings
error: could not compile `clash-verge` (bin "clash-verge") due to previous error; 7 warnings emitted
       Error failed to build app: failed to build app
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zzzgydi** [comment]
这个得自己查查了

**Comment by Jaywxy** [comment]
> 这个得自己查查了

enen ,目前编译好了，能打开了，但不知道是不是还有点问题的原因，还像还有点问题

**Comment by Jaywxy** [comment]
> 这个得自己查查了

谢谢

**Comment by Jaywxy** [comment]
[
![2023-07-27 19-12-18 的屏幕截图](https://github.com/zzzgydi/clash-verge/assets/22788987/fddb3768-75d7-4c85-ab0f-018a3c8665ca)
](url)

就像这样，代理窗口bug，然后容易卡住

**Comment by zzzgydi** [comment]
@Jaywxy 可以试试main分支最新的代码，我尝试修了一下
