### ISSUE TITLE
Unable to save window size

### ISSUE THREAD

**Issue by NecocNeko** [zzzgydi/clash-verge#626]
I tried to enlarge the window, but every time I start the software, it reverts back to the default size

**Comment by juzibugu** [comment]
类似的问题,我做了一个大组来分流不同机场的小组,但是verge不记录最后一次选择的内容,导致每次开启还要重新选择.

**Comment by zzzgydi** [comment]
try new version v1.3.5

**Comment by NecocNeko** [comment]
I did it. Thank you

**Comment by NecocNeko** [comment]
> 试用新版本 v1.3.5

I did it. Thank you
