### ISSUE TITLE
clash-verge自己可以通过全局代理来更新配置吗？

### ISSUE THREAD

**Issue by tuwulin365** [zzzgydi/clash-verge#629]
clash for windows是可以这么操作的。clash-verge好像不行？

**Comment by AnyWAT** [comment]
规则或全局，更新所有配置，均正常呢。或
右键配置——更新
或更新（代理）

**Comment by tuwulin365** [comment]
> 规则或全局，更新所有配置，均正常呢。或 右键配置——更新 或更新（代理）

你确定它是通过代理更新的吗？“连接”里面有记录吗？

**Comment by wanshuizaowanqi** [comment]
得右键订阅-编辑信息-到最下面开启 使用系统代理更新
