### ISSUE TITLE
有没有导入本地配置文件的功能？

### ISSUE THREAD

**Issue by anglesccs** [zzzgydi/clash-verge#63]
如果没有的话，能否增加一个定时导入本地配置文件的功能？

**Comment by zzzgydi** [comment]
有，点击New/新建，选择local类型就好

**Comment by anglesccs** [comment]
本地导入能不能也增加一个定时导入的功能？我用别的软件定时更新本地的配置文件，如果能定时导入就好了

**Comment by zzzgydi** [comment]
我只知道需要定时更新订阅链接，为什么还需要定时更新（导入？）本地的配置，你能简单讲讲你的场景吗

**Comment by anglesccs** [comment]
我用家用的NAS(没有公网IP)装了proxypool筛选IP，然后用openwrt里的openclash生成配置文件,再通过syncthing定时同步到我的电脑上，然后想用clash-verge定时读取配置

**Comment by zzzgydi** [comment]
好像懂了，你可以定时同步修改clash-verge对应的local profile的yaml文件，也可以更新配置。

然后现在还需要手动点击重新选择这个profile，这样就可以用新的配置文件了。后面我再考虑一下怎么搞个定时触发就好了。

**Comment by anglesccs** [comment]
嗯嗯，就是这个意思

**Comment by anglesccs** [comment]
定时器不方便的话，加个可以点击更新也行

**Comment by zzzgydi** [comment]
> 定时器不方便的话，加个可以点击更新也行

现在也可以更新的，你右键local profile，点那个select就会重新加载一次配置【下图一】。或者，如果你新建一个什么merge profile或者script profile，下面这里就会有个更新按键，点这个也会重新加载一次配置【下图二】。

![image](https://user-images.githubusercontent.com/27361820/163359381-db9077c4-fd5b-47b7-972d-a35cf253459e.png)

![image](https://user-images.githubusercontent.com/27361820/163359433-3a91ab08-79f2-4bf9-9246-3e6b6f8da123.png)

**Comment by anglesccs** [comment]
嗯，好的，因为点击“使用”的时候看不到任何反应，不知道是更新了

**Comment by anglesccs** [comment]
试了一下，clash_verge应该是把配置文件自动改了名字复制到profile文件夹下的，点击“使用”的时候，只是使用了这个改过名字的文件，不会再把原配置文件重新复制一次
![2022-04-15_065613](https://user-images.githubusercontent.com/49857157/163490728-8aca2587-9021-4de8-9932-fc0187f31d44.jpg)
？

**Comment by zzzgydi** [comment]
> 嗯，好的，因为点击“使用”的时候看不到任何反应，不知道是更新了

这个我考虑优化一下提示

> 试了一下，clash_verge应该是把配置文件自动改了名字复制到profile文件夹下的，点击“使用”的时候，只是使用了这个改过名字的文件，不会再把原配置文件重新复制一次

这个你要直接修改`profiles/xxx.yaml`，xxx为对应的id，每个profile都会给一个id。所以你的定时程序需要定时覆盖`~/.config/clash-verge/profiles/xxx.yaml`。

**Comment by anglesccs** [comment]
这个名字没办法跟这个id一样，我是从我的软路由里的配置文件同步过来的，那边的名字改不了
> > 试了一下，clash_verge应该是把配置文件自动改了名字复制到profile文件夹下的，点击“使用”的时候，只是使用了这个改过名字的文件，不会再把原配置文件重新复制一次
> 
> 这个你要直接修改`profiles/xxx.yaml`，xxx为对应的id，每个profile都会给一个id。所以你的定时程序需要定时覆盖`~/.config/clash-verge/profiles/xxx.yaml`。

**Comment by zzzgydi** [comment]
> 这个名字没办法跟这个id一样，我是从我的软路由里的配置文件同步过来的，那边的名字改不了

路径也改不了吗

**Comment by anglesccs** [comment]
> 

路径可以改

**Comment by zzzgydi** [comment]
那路径就改到`~/.config/clash-verge/profiles`，然后你的文件名是`NAS_clash.yaml`，对吧，再打开`~/.config/clash-verge/profiles.yaml`这个文件，修改一下对应的文件名。

可以看到大概的内容是这样的：
```yaml
items:
  - uid: xxx
    type: local
    name: ...
    file: NAS_clash.yaml   # 改的是这里
```

在items里找到对应uid的项，修改他的file为你的配置的文件名

**Comment by anglesccs** [comment]
> 那路径就改到`~/.config/clash-verge/profiles`，然后你的文件名是`NAS_clash.yaml`，对吧，再打开`~/.config/clash-verge/profiles.yaml`这个文件，修改一下对应的文件名。
> 
> 可以看到大概的内容是这样的：
> 
> ```yaml
> items:
>   - uid: xxx
>     type: local
>     name: ...
>     file: NAS_clash.yaml   # 改的是这里
> ```
> 
> 在items里找到对应uid的项，修改他的file为你的配置的文件名

可以了，不过.config文件夹在C盘，很不方便，要是能给弄到clash_verge的文件夹下就好了，重装系统都不用重新弄

**Comment by zzzgydi** [comment]
> 要是能给弄到clash_verge的文件夹下就好了，重装系统都不用重新弄

这个现在支持了(v0.0.29)（Windows Only），只不过需要在程序目录下，新建一个`.config`文件夹，再在这个文件夹下建一个`PORTABLE`空文件就好。然后还可以将你现在的配置全部拷贝过去，`~/.config/clash-verge` -> `exe所在目录/.config/clash-verge`

**Comment by anglesccs** [comment]
> > 要是能给弄到clash_verge的文件夹下就好了，重装系统都不用重新弄
> 
> 这个现在支持了(v0.0.29)（Windows Only），只不过需要在exe所在目录，新建一个`.config`文件夹，再在这个文件夹下建一个`PORTABLE`空文件就好。然后还可以将你现在的配置全部拷贝过去，`~/.config/clash-verge` -> `exe所在目录/.config/clash-verge`

搞定了，剩下的就是如果能定时更新就最好了(本地和在线的)

**Comment by zzzgydi** [comment]
定时这块的实现在计划中了，还在琢磨和设计

**Comment by anglesccs** [comment]
再有个bug，tun模式选择后，状态栏右键显示不正常，有时候有，有时候没有，如
![2022-04-15_130313](https://user-images.githubusercontent.com/49857157/163522910-6621190a-1a9f-4856-b57a-c6ea5e1e94e1.jpg)
图

**Comment by zzzgydi** [comment]
托盘里的状态没修改的话，可能是切换tun的时候报错了，然后导致两个状态不一致，我改改吧

**Comment by anglesccs** [comment]
> 定时这块的实现在计划中了，还在琢磨和设计
clash for windows 有这个定时更新功能，有没有参考价值？

**Comment by zzzgydi** [comment]
可以借鉴有什么设置字段而已。

clash verge 对配置里的字段做了过滤，默认只用了部分关键字段而已，其他字段配了跟没配一样，所以没什么问题
