### ISSUE TITLE
希望开发者能添加打开软件界面保持之前尺寸的功能

### ISSUE THREAD

**Issue by Drangleic71** [zzzgydi/clash-verge#632]
现在最新版的程序，关闭主界面之后再打开，会缩放到默认尺寸，如果想要全屏使用，每次打开主界面之后都要点一下窗口最大化，很不方便，希望开发者能让软件界面保持窗口关闭之前的尺寸

**Comment by yoyosbg** [comment]
我这里是必须重新启动才会显示界面.

**Comment by zzzgydi** [comment]
新版1.3.4支持啦！
