### ISSUE TITLE
请问meta内核套Cloudflare后，如何设置优选IP？

### ISSUE THREAD

**Issue by flyhunterl** [zzzgydi/clash-verge#634]
直接套用clash的设置好像不起作用？
hosts:
  'YourDomain': IP

proxies: 
  - type: vmess
    cipher: auto
    name: VA
    server: YourDomain
    port: 443
    udp: false
    uuid: UUID
    alterId: "0"
    network: ws
    tls: true
    ws-path: /
    ws-headers:
      host: YourDomain

**Comment by zzzgydi** [comment]
不太了解
