### ISSUE TITLE
clash.meta 内核 tuic v5 token配置参数报错

### ISSUE THREAD

**Issue by matianhe3** [zzzgydi/clash-verge#636]
![image](https://github.com/zzzgydi/clash-verge/assets/24929062/834c2901-5aa7-4fd2-9777-97e4c551df77)
![image](https://github.com/zzzgydi/clash-verge/assets/24929062/812c590b-b55c-4a57-8c32-f9da9c749169)

clash-verge 1.3.2

**Comment by zzzgydi** [comment]
已经更新内核，更新客户端即可
