### ISSUE TITLE
关于Windows上Allow Lan不生效的问题

### ISSUE THREAD

**Issue by pananfly** [zzzgydi/clash-verge#637]
Windows11上最新的1.3.2版本，在切换到clash meta后Allow Lan没有网络的问题，本机上查看防火墙允许的应用没有clash-meta，只有clash，导致一直网络不通，只能自行手动添加解决。

**Comment by zzzgydi** [comment]
可能第一次用meta的时候，系统有给弹窗提示，选了拒绝？

**Comment by pananfly** [comment]
特意卸载了安装最新的1.3.3测试，可能是之前火绒拦截啥的了，没有印象有拒绝的。

**Comment by pananfly** [comment]
特意卸载了安装最新的1.3.3测试，可能是之前火绒拦截啥的了，没有印象有拒绝的。
