### ISSUE TITLE
tuic v5 报错 没有token ，能支持一下tuic v5 嘛 ？  

### ISSUE THREAD

**Issue by weiluoliang** [zzzgydi/clash-verge#640]
![image](https://github.com/zzzgydi/clash-verge/assets/19885121/0cb42406-3510-485f-8542-cc557019d471)

希望支持下

**Comment by zzzgydi** [comment]
应该是meta的版本没对上吧，可以自己更换meta核心

**Comment by fordes123** [comment]
遇到同样的问题，手动将Meta内核更新至 [1.15.0](https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.15.0) 得以解决

**Comment by zzzgydi** [comment]
已经更新meta到1.15.0 升级客户端即可
