### ISSUE TITLE
Mac无法使用

### ISSUE THREAD

**Issue by sleeeeeeepa** [zzzgydi/clash-verge#642]
选择订阅报错没有内容
![image](https://github.com/zzzgydi/clash-verge/assets/26105843/99847609-dc62-4c96-b51b-e9e18d2d62b8)

切换内核带锁  点击锁输完密码显示成功
![image](https://github.com/zzzgydi/clash-verge/assets/26105843/da4a6ff0-641e-4c62-a978-c78f327cdab8)

选择meta报错无信息
![image](https://github.com/zzzgydi/clash-verge/assets/26105843/20b6d558-7653-464f-8051-a6225764abac)

**Comment by sleeeeeeepa** [comment]
Mac air m2芯片
系统版本 12.5

**Comment by zzzgydi** [comment]
这个问题尝试修复了一下，可以更新新版看看

**Comment by sleeeeeeepa** [comment]
最新版本 1.3.3仍无法使用  问题依旧

**Comment by ZihaoZhou** [comment]
原因是打包的app下，/Contents/MacOS/clash-meta:
This program can only be run on AMD64 processors with v3 microarchitecture support.

**Comment by ZihaoZhou** [comment]
解决方法：下载ARM64版本的meta内核，右键打开后以获取权限后，手动替换掉/Contents/MacOS/clash-meta
mv clash.meta-darwin-arm64-cgo-v1.15.0 '/Applications/Clash Verge.app/Contents/MacOS/clash-meta'

@zzzgydi 希望尽快支持ARM64内核。

**Comment by zzzgydi** [comment]
> 原因是打包的app下，/Contents/MacOS/clash-meta: This program can only be run on AMD64 processors with v3 microarchitecture support.

@ZihaoZhou arm芯片的mac可以安装这个 https://github.com/zzzgydi/clash-verge/releases/download/v1.3.3/Clash.Verge_1.3.3_aarch64.dmg
