### ISSUE TITLE
更新ClashMeta内核后，点击关闭全部连接按钮，页面无法正常显示

### ISSUE THREAD

**Issue by AixLeo** [zzzgydi/clash-verge#643]
ClashMeta内核更新替换为1.15.0版本后，点击Verge连接页面“关闭全部”按钮，页面显示  Something went wrong:( Cannot read properties of null (reading 'length')，然后所有页面都无法则正常显示。关闭窗口，重新打开恢复正常。

**Comment by zzzgydi** [comment]
新版已经修复，可以更新尝试
