### ISSUE TITLE
1.3.3 version Windows system tray icon abnormal

### ISSUE THREAD

**Issue by lainbo** [zzzgydi/clash-verge#647]
![image](https://github.com/zzzgydi/clash-verge/assets/46062895/dc4d01e3-ec9b-4f37-8aed-d72bde90273d)
![image](https://github.com/zzzgydi/clash-verge/assets/46062895/552f3b27-87b8-42a8-b7ae-0c56eeca8863)

24-inch screen 1080P monitor, possibly with a slightly low pixel density
However, it is displayed correctly in version 1.3.2.

**Comment by InspoOnU** [comment]
I experienced the same blurry icon with DPI of 150%

**Comment by MiniFullC** [comment]
win11 22H2

![image](https://github.com/zzzgydi/clash-verge/assets/37063727/1c801f86-ac1c-46de-b7f7-f7b4beee05ec)

**Comment by lainbo** [comment]
I think this is related to the pixel density or resolution of the screen. Everything is normal on a 4K 27-inch screen

**Comment by zzzgydi** [comment]
try new version v1.3.5
