### ISSUE TITLE
麻烦大佬看看 ci 构建失败是什么问题

### ISSUE THREAD

**Issue by MemoryNoodles** [zzzgydi/clash-verge#653]
这是我的 ci
 `
name: publish
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Yarn install and check
        run: |
          yarn install --network-timeout 1000000
          yarn run check
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

`

![image](https://github.com/zzzgydi/clash-verge/assets/19926700/e1d02805-1feb-41e5-96b0-ee330977a0e2)

**Comment by MemoryNoodles** [comment]
感觉问题就出现在这里，我有设置 action 的读写权限
![image](https://github.com/zzzgydi/clash-verge/assets/19926700/84c93555-72c2-44eb-ba29-2a63a3ea60dc)

**Comment by MemoryNoodles** [comment]
原因找到了是这个文件找不到了，是不是文件名换了

https://github.com/Dreamacro/clash/releases/download/premium/clash-darwin-arm64-2023.05.29.gz

**Comment by zzzgydi** [comment]
clash p核会更新的，我已经更新代码了，可以同步一下，再试试ci

**Comment by MemoryNoodles** [comment]
> clash p核会更新的，我已经更新代码了，可以同步一下，再试试ci

嗯嗯，好的。感谢
