### ISSUE TITLE
clash-darwin-arm64-2023.05.29.gz 文件没有了，导致下载失败; 麻烦更新一下

### ISSUE THREAD

**Issue by MemoryNoodles** [zzzgydi/clash-verge#655]
执行 yarn run check 的时候提示报错，原因如下文件找不到了：
https://github.com/Dreamacro/clash/releases/download/premium/clash-darwin-arm64-2023.05.29.gz

**Comment by mybdye** [comment]
https://github.com/zzzgydi/clash-verge/blob/416e7884f5e0b825a6853f0c50c62a2c8201c145/scripts/check.mjs#L17C1-L20C40

https://github.com/zzzgydi/clash-verge/blob/416e7884f5e0b825a6853f0c50c62a2c8201c145/scripts/check.mjs#L59C1-L59C1

**Comment by MemoryNoodles** [comment]
我这边是自己找到相应的文件更新了，不过还是更新一下 check.mjs 更好，这样大家都可以使用。不仅是 mac, windows 的文件也有些找不到了。

**Comment by zzzgydi** [comment]
已更新
