### ISSUE TITLE
ubuntu18.04

### ISSUE THREAD

**Issue by Current-River** [zzzgydi/clash-verge#657]
安装成功后，在应用中点击图标，没有任何反应

**Comment by byerose** [comment]
建议换到低版本，我目前用的1.2.0，比较稳定

**Comment by zzzgydi** [comment]
可以试试这两个 
- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.AppImage
- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.deb
