### ISSUE TITLE
怎么让 cdnfhnfile.115.com:80 流量不过 clash

### ISSUE THREAD

**Issue by ningsibuqu** [zzzgydi/clash-verge#658]
![image](https://github.com/zzzgydi/clash-verge/assets/51028975/c42dcb27-a97a-4c7c-ac5a-ab339805ece5)

**Comment by lbbboy** [comment]
rules:
  - DOMAIN-SUFFIX,115.com,DIRECT

**Comment by ningsibuqu** [comment]
> ```
> rules:
>   - DOMAIN-SUFFIX,115.com,DIRECT
> ```

现在 115 的流量是直连的了，但是我不希望他过 clash
![image](https://github.com/zzzgydi/clash-verge/assets/51028975/22f756e4-90d7-415e-baa3-6e482ab41f82)

**Comment by hawk0344** [comment]
你用baypass阿,在设置,系统代理,点齿轮进去填一下.

**Comment by zzzgydi** [comment]
如果是用的系统代理，可以设置bypass。如果用的tun，那还是设置规则吧

**Comment by ningsibuqu** [comment]
> 你用 bypass 阿，在设置，系统代理，点齿轮进去填一下.

fhnfile.oss-cn-shenzhen.aliyuncs.com:80

这个我设置 *.aliyuncs.com;

不起作用

**Comment by ningsibuqu** [comment]
> 如果是用的系统代理，可以设置 bypass。如果用的 tun，那还是设置规则吧

![image](https://github.com/zzzgydi/clash-verge/assets/51028975/fedf4cd6-db02-4dd8-bcb9-b181c8e1af56)
设置 *.aliyuncs.com;

不起作用
