### ISSUE TITLE
Proxy-groups: Fallback 无法按预期回退

### ISSUE THREAD

**Issue by Bformax** [zzzgydi/clash-verge#659]
版本：Clash.Verge 1.3.3
核心：Clash.Meta 1.15.0

操作系统：Windows11

配置文件节选：
  - name: "fallback-auto"
    type: fallback
    proxies:
      - a1
      - a2
      - a3
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300

遇到的问题：
1、按正常来说，Fallback类型的Groups是不能手动选择的，Clash.Verge内可以手动选择，并覆盖自动测试的结果，这个导致了一些后面的问题。
2、当手动选择a2以后，如果a2节点无故障，那么，**无论是300s以后，或者是重启，关机**，Clash.Verge都不会将节点选择回退到a1。

过程分析：
我认为这个设计不合理。因为Fallback的设计目的就是当a1故障的时候转移至a2，当a1恢复以后复原。
而现在，如果不小心选择上了，也是没有提示的，所有流量就锁死a2节点了，即便重启也不会复原。
我在使用过程中就遇到了这个情况，莫名其妙的所有流量都走了a2，明明a1是通的

希望获得的解决：
方案1:  Fallback类型无法手动选择，这样避免了后面所有的问题（最简单的方案）；
方案2:  Fallback类型可以手动选择，需要出现一个提示：“手动选择将会覆盖自动测试结果，并在重启后失效”，重启后，这个fallback的手动选择应该被reset；
方案3:  Fallback类型可以手动选择，但需要提示，在interval: 300后自动测试结果覆盖掉手动选择的结果；

以上提案的目的都是，让fallback这个自动回退方案发挥应有的作用，其实方案1就行了，我其实不是很理解Clash.Verge为什么要将Fallback变成手动可选，那Fallback自动的意义就没有了啊。

如果要手动选择覆盖自动结果，也要设定期限，至少重启以后要Reset，而且应该给提示一下。

**Comment by zzzgydi** [comment]
fallback可以手动选择，是个feature来的，内核都支持的操作，GUI支持一下也无可厚非。还有种类型是url-test，可以看看是否符合你的需求

**Comment by Bformax** [comment]
> fallback可以手动选择，是个feature来的，内核都支持的操作，GUI支持一下也无可厚非。还有种类型是url-test，可以看看是否符合你的需求

Hi 感谢回复

这个feature我是这么想的，可以override 自动测试结果作为feature是好的，我在用Surge的时候也有用到这个feature. Surge在实现的时候是右键点击然后选择override。那这个行为是非常主动的，可控的。

在Clash.Verge上我遇到的地方是，手动选择的时候，没有提示，那么出现的情况就是，家里有人随意点了一下（或者自己手滑）以后，就永久性切换了。我试了几次都是重启以后结果还在。

所以我想的是：如果这个是一个feature，可不可以弹个提示，或者重启系统以后失效？

**Comment by zzzgydi** [comment]
> 我试了几次都是重启以后结果还在。
> 或者重启系统以后失效？

我想我大概知道问题在哪了，fallback在重启软件之后，用户没有再次手动选择之后，确实从第一个开始比较好。我修复一下。

**Comment by Bformax** [comment]
> > 我试了几次都是重启以后结果还在。
> > 或者重启系统以后失效？
> 
> 我想我大概知道问题在哪了，fallback在重启软件之后，用户没有再次手动选择之后，确实从第一个开始比较好。我修复一下。

这个Issue的起源是，我Fallback的最后一个节点是阿里云香港的按量付费线路，3元/G，看到账单还找了好久原因😂

**Comment by yoohooyoo** [comment]
fallback有两个重要功能：
一是错误转移，二是定义节点优先级。
使用urltest只能解决第一个，不能解决第二个。

增加手选功能，不能覆盖掉这两个功能呀。

个人建议：
增加手选，但是手选节点如果出现问题，自动切回原始模式并按照优先级选择节点。

**Comment by Bformax** [comment]
> fallback有两个重要功能： 一是错误转移，二是定义节点优先级。 使用urltest只能解决第一个，不能解决第二个。
> 
> 增加手选功能，不能覆盖掉这两个功能呀。
> 
> 个人建议： 增加手选，但是手选节点如果出现问题，自动切回原始模式并按照优先级选择节点。

我觉得作者现在做的改变挺好的，重启后复位，
如果要长期改变，应该去改变Fallback的顺序
我上个月没察觉，按量付费就付了200多

**Comment by ShiJie137** [comment]
> > fallback有两个重要功能： 一是错误转移，二是定义节点优先级。 使用urltest只能解决第一个，不能解决第二个。
> > 增加手选功能，不能覆盖掉这两个功能呀。
> > 个人建议： 增加手选，但是手选节点如果出现问题，自动切回原始模式并按照优先级选择节点。
> 
> 我觉得作者现在做的改变挺好的，重启后复位， 如果要长期改变，应该去改变Fallback的顺序 我上个月没察觉，按量付费就付了200多

问下现在的策略是属于你开头说的三种提案的哪一种
