### ISSUE TITLE
Win10TUN模式下不显示连接和日志

### ISSUE THREAD

**Issue by TingTing1990** [zzzgydi/clash-verge#666]
都是空白，且等了很久还是，再就是关了代理和退出应用后还能走代理。

**Comment by zzzgydi** [comment]
是不是开了别的软件比如cfw，占了7890/9090的端口，导致verge的clash启动失败了

**Comment by TingTing1990** [comment]
> 是不是开了别的软件比如cfw，占了7890/9090的端口，导致verge的clash启动失败了

有可能，我尝试完全退出cfw再重启电脑试试，多谢！
