### ISSUE TITLE
日志等级设置失效

### ISSUE THREAD

**Issue by Hades-001** [zzzgydi/clash-verge#668]
日志等级设置为非 info 时，日志选项卡仍显示 info 日志。

![捕获9](https://github.com/zzzgydi/clash-verge/assets/30254702/0b55c192-8869-4516-8ed8-55948bc86a7d)

![捕获10](https://github.com/zzzgydi/clash-verge/assets/30254702/1e8ddbaa-c966-4430-a8c3-8b2f2985ceae)

**Comment by yueyejinghun** [comment]
这个选项更改的是 .config/clash-verge/config/logs 文件夹里的日志等级，并不是主界面的日志等级

**Comment by AnyWAT** [comment]
PC下的
 .config/clash-verge/logs 文件夹里的日志等级
貌似在
设置——杂项设置——App Log Level

**Comment by zzzgydi** [comment]
> 日志等级设置为非 info 时，日志选项卡仍显示 info 日志。

- 一个是可以需要确定这些info日志是不是在切换等级为warn之前产生的；
- 一个是看这个日志等级的修改有没有正确地传给meta，这个可以看看运行配置；
- 正确了之后，看看是不是meta日志有问题。
