### ISSUE TITLE
centos 7 如何安装

### ISSUE THREAD

**Issue by wjcaozhi** [zzzgydi/clash-verge#673]
centos 7 系统使用 clash-verge_1.3.3_amd64.AppImage 双击无响应，./clash-verge_1.3.3_amd64.AppImage 提示异常:clash-verge: /lib64/libgpg-error.so.  0: no version information available (required by /tmp/.mount_clash-9WjsFX/usr/lib/libgcrypt.so.20)clash-verge: error while loading shared libraries: libOpenGL.so.  0: cannot open shared object file: No such file or directory

**Comment by zzzgydi** [comment]
centos 有GUI么

**Comment by atauzki** [comment]
Ubuntu20.04上，deb和appimage都报glibc相关错误

**Comment by zzzgydi** [comment]
@atauzki 可以试试这两个 

- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.AppImage
- https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.deb

**Comment by atauzki** [comment]
> @atauzki 可以试试这两个
> 
> * https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.AppImage
> * https://github.com/zzzgydi/clash-verge/releases/download/alpha/clash-verge_1.3.5_amd64.deb

这两个可以用

**Comment by zzzgydi** [comment]
nice
