### ISSUE TITLE
[BUG] clash-verge is not working properly

### ISSUE THREAD

**Issue by poplar-at-twilight** [zzzgydi/clash-verge#683]
**Describe the bug**

The latest version of clash-verge does not work properly, fails to display the list of proxy nodes, and issues an error message: `os error -13`

**To Reproduce**
1. Download the latest version of the appimage file (`clash-verge_1.3.4_amd64.AppImage`) 
2. Give executable permissions and click launch.

**Expected behavior**

1. Proxy list will not show proxy nodes
2. Clicking on the profile page and performing an update reports an error (os error -13 no permission)

**Screenshots**

- https://imgur.com/a/67fbCBX
- https://imgur.com/G6X56TC
- https://imgur.com/6RZfqiP

**Information**
- OS: 
  - Operating System: openSUSE Tumbleweed 20230718
  - KDE Plasma Version: 5.27.6
  - KDE Frameworks Version: 5.108.0
  - Qt Version: 5.15.10
  - Kernel Version: 6.4.3-1-default (64-bit)
  - Graphics Platform: X11
  - Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
  - Memory: 15.4 GiB of RAM
  - Graphics Processor: Mesa Intel® UHD Graphics 620
- Clash Verge Version:  1.3.4
- Clash Core:  default

**Additional context**

If you need additional information, please feel free to say so.

**Comment by zzzgydi** [comment]
I checked the CI build logs and indeed there are some issues. The Linux/macOS versions are missing Clash core due to the Clash core updated at the same time. I will send a new version again.

**Comment by poplar-at-twilight** [comment]
This bug has been fixed in 1.3.5
