### ISSUE TITLE
[BUG] failed to copy resources 'wintun.dll', 系统找不到指定的文件

### ISSUE THREAD

**Issue by LovelyMuu** [zzzgydi/clash-verge#684]
2023-07-23 05:48:38 ERROR - failed to copy resources 'wintun.dll', 系统找不到指定的文件。 (os error 2)
2023-07-23 05:48:46 ERROR - failed to copy resources 'wintun.dll', 系统找不到指定的文件。 (os error 2)
2023-07-23 05:48:57 ERROR - failed to copy resources 'wintun.dll', 系统找不到指定的文件。 (os error 2)

**Comment by AnyWAT** [comment]
copy .config\clash\wintun.dll to Program Files\Clash Verge\resources ?

**Comment by LovelyMuu** [comment]
I did not find the  .config\clash\wintun.dll on my computer.

**Comment by zzzgydi** [comment]
What is your system, windows or macOS or Linux

**Comment by AnyWAT** [comment]
> I did not find the .config\clash\wintun.dll on my computer.

PC上右键托盘图标——打开目录——应用目录，即是。

**Comment by zzzgydi** [comment]
我检查了一下CI构建日志，确实有点问题，windows的版本没带上wintun文件，以及linux/macOS的没带上clash。。我重新发一版吧。

I checked the CI build logs and indeed there are some issues. The Windows version is missing the wintun file, and the Linux/macOS versions are missing Clash core. I will send a new version again.

**Comment by zzzgydi** [comment]
这个v1.3.5已经修复啦
