### ISSUE TITLE
[BUG] Clash Verge for Windows v1.3.4 和 v1.3.5 Dashboard 均无法在前台显示

### ISSUE THREAD

**Issue by ericclose** [zzzgydi/clash-verge#685]
**Clash Verge for Windows v1.3.4 和 v1.3.5 Dashboard 均无法在前台显示**

**复现过程**
复现步骤:
1. 安装
2. 启动完之后关闭 Dashboard 窗口
3. 再次打开 Dashboard，无法前台显示

**Information**
 - OS: Windows 11 Pro 22H2 22621.1992
 - Clash Verge Version: v1.3.4
 - Clash Core: [Clash or Clash Meta]

**Comment by AnyWAT** [comment]
在 Win10 Pro 上 Clash Verge for Windows 窗口需用到不能被系统自动更新的 WebView（最新115.0.1901.183），试试在系统应用内手动更新一下或许就好。

**Comment by poplar-at-twilight** [comment]
试试 clash-verge 1.3.5

**Comment by ericclose** [comment]
> 在 Win10 Pro 上 Clash Verge for Windows 窗口需用到不能被系统自动更新的 WebView（最新115.0.1901.183），试试在系统应用内手动更新一下或许就好。

Hmmm... 初次安装 clash 的时候有自动获取 Webview 了，**刚才试了下刚发布的 v1.3.5 正常了。。。故关闭 issue**

**Comment by AnyWAT** [comment]
> 初次安装 clash 的时候有自动获取 Webview 了

当时最新，但不会自动更新，除非。。。

**Comment by ericclose** [comment]
> 试试 clash-verge 1.3.5

是的 v1.3.5 正常

**Comment by ericclose** [comment]
> > 初次安装 clash 的时候有自动获取 Webview 了
> 
> 当（第一次安装WebView）时最新，但（更新 Clash Verge 并）不会自动更新，除非。。。

没更新前 Webview 是 v114，相差也不大呀（不过你倒是让我知道了 Webview 居然不会自动更新）。。。我刚才换了 v1.3.5 就正常了

**Comment by ericclose** [comment]
> > 初次安装 clash 的时候有自动获取 Webview 了
> 
> 当（第一次安装WebView）时最新，但（更新 Clash Verge 并）不会自动更新，除非。。。

刚更新了 Webview v115.0.1901.183，发现还是会这样

**Comment by zzzgydi** [comment]
可以贴上日志看看

**Comment by AnyWAT** [comment]
> 刚更新了 Webview v115.0.1901.183

Win10 还有其它如系统天气等需用到 WebView
如果更新时在用 WebView，C:\Program Files (x86)\Microsoft\EdgeWebView\Application 下会有不止1个版本目录，诸如 Clash Verge 重启或会用最新版本。

**Comment by ericclose** [comment]
> 可以贴上日志看看

刚才就是安装 v1.3.4，初次打开 dashboard 能前台显示，退出之后又不能前台显示了；刚才又更新了 v1.3.5 又是初次打开能前台显示，然后退出又不行。

**刚才更新了 webview，发现也是不能前台显示。然后重启了下，现在似乎没遇到前台显示的问题了。**

**Comment by ericclose** [comment]
> > 刚更新了 Webview v115.0.1901.183
> 
> Win10 还有其它如系统天气等需用到 WebView 如果更新时在用 WebView，C:\Program Files (x86)\Microsoft\EdgeWebView\Application 下会有不止1个版本目录，诸如 Clash Verge 重启或会用最新版本。 任务管理器点选 msedgewebview2.exe 进程，打开文件所在的位置会告知版本。

ok，感谢，刚才更新 webview 没重启系统，所以还是不行；重启系统后没再遇到问题了
