### ISSUE TITLE
[BUG]ERROR - No such file or directory (os error 2)

### ISSUE THREAD

**Issue by howdareyo** [zzzgydi/clash-verge#686]
debian12在内核点击锁提权时出现ERROR - No such file or directory (os error 2)
clash-verge版本为v1.3.5

**Comment by EbadiDev** [comment]
Same on Manjaro, installed using `yay -S clash-verge-bin` version v1.3.5

**Comment by dnomd343** [comment]
v1.3.5在macOS下也是相同报错，首次订阅正常，再次打开APP就会出这个问题。

**Comment by zzzgydi** [comment]
可以把app日志调到debug，给更多一点日志看看是哪个文件有问题。

**Comment by morgenanno** [comment]
是verge.yaml下的app log，调整为trace

**Comment by zzzgydi** [comment]
检查一下 ` /usr/bin/clash-meta` 这个文件是否存在，不存在的话，自己软链接一个或者下载一个都可

**Comment by zzzgydi** [comment]
那是不是不存在 `pkexec`
