### ISSUE TITLE
[BUG] v1.3.5 无法打开面板

### ISSUE THREAD

**Issue by OnqiauJliu** [zzzgydi/clash-verge#688]
**Describe the bug**
程序能正常运行， 任务栏有小图标， 但是无法打开面板

**To Reproduce**
更新 v1.3.5 重启电脑后无法打开面板

已经试过方法：
1. 重启电脑
2. 卸载重装verge v1.3.5
3. 任务管理器 -> 结束verge -> 打开verge
4. verge小图标 -> 菜单栏 -> 重启应用
5. verge小图标 -> 菜单栏 -> 打开面板
6. verge小图标 -> 菜单栏 -> 重启clash

最后降级 v1.3.3 正常打开面板

**Expected behavior**

**Screenshots**
![image](https://github.com/zzzgydi/clash-verge/assets/60482496/522018ae-5b57-4165-8a05-4ae3097a7e5c)
注意任务栏 verge 下方蓝色条 表示已经选中 verge 但是桌面并未显示面板

**Information**
 - OS: Windows
 - Clash Verge Version:  v1.3.5
 - Clash Core: Clash Meta

**Additional context**

**Comment by ericclose** [comment]
#685

我也遇到了这个问题，安装完 v1.3.4，初次打开 dashboard 能前台显示，退出之后又不能前台显示了；刚才又更新了 v1.3.5 又是初次打开能前台显示，然后退出又不行。

然后手动更新了 webview（**系统设置** 或 **控制面板** 的**应用管理**，找到 _Webview_，选择**修改** ➡️**修复**，会更新 Webview），**不重启**发现**也是不能前台显示**。

**最后重启了下系统，现在似乎没遇到前台显示的问题了。**

你可以试试

**Comment by AnyWAT** [comment]
貌似不必重启机器。退出 Clash Verge 再更新 WebView，（或再删除 C:\Users\用户名\AppData\Local\top.gydi.clashverge\EBWebView 文件夹，）再运行 Clash Verge 即可。

**Comment by AnyWAT** [comment]
如果想 WebView 自动更新，可去[巨硬官网（左下角的 Download ）](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) 下载 MicrosoftEdgeWebview2Setup.exe 放在 C:\Program Files (x86)\Microsoft\EdgeUpdate 文件夹。
需要手动的还有文件夹 C:\Program Files (x86)\Microsoft\EdgeUpdate 下的 MicrosoftEdgeUpdate.exe
该文件的“产品版本”号貌似比此处的某个版本号文件夹如 1.3.177.11 旧许多，从后者复制同名文件来替换升级。
Google Chrome 也是。。。

**Comment by OnqiauJliu** [comment]
> #685
> 
> 我也遇到了这个问题，安装完 v1.3.4，初次打开 dashboard 能前台显示，退出之后又不能前台显示了；然后又更新了 v1.3.5 又是初次打开能前台显示，然后退出又不行。
> 
> 然后手动更新了 webview（**系统设置** 或 **控制面板** 的**应用管理**，找到 _Webview_，选择**修改** ➡️**修复**，会更新 Webview），**不重启**发现**也是不能前台显示**。
> 
> **最后重启了下系统，现在似乎没遇到前台显示的问题了。**
> 
> 你可以试试

问题解决了 多谢了
