### ISSUE TITLE
[BUG] Clash-Verge 服务导致依赖 Hyper-V Virtual Switch 的组件网络不正常的问题

### ISSUE THREAD

**Issue by yueyejinghun** [zzzgydi/clash-verge#690]
## Describe the bug

以安装服务的方式运行 Clash-Verge 并开启 tun 时， 使用 `stack: system` 会导致 Hyper-V、WSL、Windows Sandbox 等依赖 Hyper-V Virtual Switch 的组件网络不正常

## To Reproduce

1. 安装 Clash-Verge 服务并以普通权限运行，使用 `stack: system`
2. 安装 Hyper-V 与 Linux 虚拟机（Gen 2）
3. 安装 WSL2 与 Windows Sandbox
4. 运行 WSL2 实例，并开启 Hyper-V 虚拟机或 Windows Sandbox
5. 等待 30-120 分钟后，所有实例同时无法联网（即使偶尔网络可用，亦会超时或极不稳定）

## Expected behavior

所有上述实例可稳定正常工作

## Screenshots

_Not applicable_

## Information
 - OS: Windows 11
 - Clash Verge Version: 1.3.2-1.3.5
 - Clash Core: Clash Meta 1.14.1-1.15.0

## Additional context

```
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
```

* 原以为是内核原因，但搜索 meta 的 issue 后并未发现相关内容。遂改用 clashN 测试 (以管理员身份运行)，相同配置使用 clashN 2.17 搭配 1.14.1-1.15.0 的所有内核均正常

* 1.3.5 搭配 1.15.0 内核即使同时使用管理员权限运行 `Clash Verge.exe` 与 `clash-meta.exe` 亦无法成功开启 tun，错误可参考 [#651](https://github.com/zzzgydi/clash-verge/issues/651)

* 测试环境说明：

  1. 以安装服务的方式并以普通用户权限运行 Clash-Verge
  2. 因 1.14.3 表现与其他所有内核不一致，故下文A组特指 1.14.3 内核，B组特指 1.14.1-1.14.2 与 1.14.4-1.15.0
  3. 结果中关于“失去网络”的定义：并非彻底无法使用，但运行 `curl` 等命令或执行其他连接公网操作的响应时间基本在 2 分钟以上，并且有极大概率超时
  4. 必须使用 compatible 内核，若使用其他内核，可复现此 bug 但解决问题的方法（使用管理员权限运行）会失效

* tun 的 stack 设置为 system 时

  1. B组所有内核均不正常，仅运行 WSL 或 Hyper-V 亦会在一段时间后失去网络（60-120 分钟），表现为 `curl ipinfo.io` 等无响应出现 `curl: (28) Failed to connect to ipinfo.io port 80 after 131900 ms: Couldn't connect to server` 等错误
  2. A组若只运行 WSL，则网络基本正常（60-120 分钟后偶尔失去网络但很快可恢复）。若只开启 Hyper-V 虚拟机，会在 5-60 分钟后失去网络。若同时开启 WSL 与 Hyper-V 或 Windows Sandbox，所有实例均会在 5-60 分钟后同时失去网络

* `stack: gvisor` 无此问题
* 以管理员身份运行 `Clash Verge.exe` 1.3.2 并搭配 `clash-meta.exe` 1.14.1-1.14.3 时无此问题

* 另附

  1. 安装 tailscale 并通过其网络使用 SSH 连接其他远程设备时，在 gvisor 模式中运行一段时间后会异常卡顿，在 system 模式中运行正常，此问题可能与 gvisor 无法实现 Fullcone 有关？虽在配置文件中已设置 `100.64.0.0/10`、`tailscale.exe` 和 `tailscaled.exe` 为 `DIRECT`，但这三条规则依旧需要经过 Clash-Verge 与内核处理可能是造成此问题的主要原因

### Logs

Clash-Verge 日志无异常，并且内核日志中可能并无可用于排查错误的内容

debug 日志中出现大量相同内容，其中 `level=debug msg="[Process] find process ... process not found` 刷屏。另外，由于知晓 Hyper-V Virtual Switch 由 `svchost.exe` 等关键进程管理，故从未将任何相关进程与 IP 段添加至规则中。以下为内核日志

```
time="2023-07-23T18:49:34.259553+08:00" level=info msg="[TCP] 198.18.0.1:48396 --> v2.wttr.in:80 match GeoSite(geolocation-!cn) using ***节点***"
time="2023-07-23T18:49:34.259553+08:00" level=info msg="[TCP] 198.18.0.1:48396 --> v2.wttr.in:80 match GeoSite(geolocation-!cn) using ***节点***"
time="2023-07-23T18:49:40.9150095+08:00" level=debug msg="[Sniffer] Sniff TCP [198.18.0.1:48384]-->[v2.wttr.in:80] success, replace domain [v2.wttr.in]-->[v2.wttr.in]"
```

```
time="2023-07-23T18:49:40.9746005+08:00" level=debug msg="[Process] find process v2.wttr.in: process not found"
```

```
time="2023-07-23T18:49:43.2558017+08:00" level=debug msg="ipv4: tcp: session not found: 11207"
time="2023-07-23T18:49:48.6191531+08:00" level=debug msg="ipv4: tcp: session not found: 11548"
```

```
time="2023-07-23T18:49:50.9144189+08:00" level=debug msg="[Sniffer] Sniff TCP [198.18.0.1:48352]-->[v2.wttr.in:80] success, replace domain [v2.wttr.in]-->[v2.wttr.in]"
time="2023-07-23T18:49:55.5842978+08:00" level=debug msg="[Rule] use default rules"
```

fake-ip 除上述日志外，还包含以下额外错误
```
time="2023-07-23T21:10:55.9491594+08:00" level=debug msg="[Metadata PreHandle] error: fake DNS record 198.18.0.3 missing"
```

使用管理员权限运行时，会出现大量下文日志，但可能亦无关联

```
2023-07-23 22:16:21 INFO - [clash]: time="2023-07-23T22:16:21.5376238+08:00" level=debug msg="[Process] find process settings-win.data.microsoft.com: Access is denied."
```

```
2023-07-23 22:18:24 INFO - [clash]: time="2023-07-23T22:18:24.6034072+08:00" level=debug msg="[Process] find process v2.wttr.in: process not found"
```

edit 1: 添加测试环境说明中关于 compatible 内核的内容

**Comment by zzzgydi** [comment]
ok
