### ISSUE TITLE
[BUG]v1.3.5 能正常运行但不显示面板窗口，只有任务栏和托盘的图标。 v1.3.3正常

### ISSUE THREAD

**Issue by GeorgeRudd** [zzzgydi/clash-verge#691]
**Describe the bug**
v1.3.5 能正常运行但不显示面板窗口，只有任务栏和托盘的图标 v1.3.3正常

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [win11 22h2]
 - Clash Verge Version: [e.g. 1.3.5]
 - Clash Core: [Clash Meta 1.15]

**Additional context**

**Comment by AnyWAT** [comment]
试试：退出 Clash Verge，系统应用内更新 WebView，启动 Clash Verge

**Comment by morgenanno** [comment]
删除.config文件就好了

**Comment by 1594853051** [comment]
删除了.config文件夹还真可以了，感谢

**Comment by zzzgydi** [comment]
之前发的v1.3.5包windows的有bug，重新安装就好了
