### ISSUE TITLE
[Feature]本地自定义规则与订阅规则合并

### ISSUE THREAD

**Issue by chenzhiguo** [zzzgydi/clash-verge#692]
**Is your feature request related to a problem? Please describe.**
某些网络环境下需要有些自定义的规则来控制那些地址需要代理或者不用代理，但是又需要使用订阅生成的普通规则。所以就涉及到这两个规则合并的问题。

**Describe the solution you'd like**
我发现Clash for Windows里有个parsers功能，可以达到这个目的。请问Verge可不可以支持类似的功能，让自定义规则和订阅的规则可以一起使用呢？

**Comment by zzzgydi** [comment]
verge也可以写脚本，可以翻翻wiki

**Comment by chenzhiguo** [comment]
感谢指导，采用Merge配置文件方式，达到预期效果。
