### ISSUE TITLE
[BUG]Windows 10下的任务管理器中的图标似乎显示有问题

### ISSUE THREAD

**Issue by GRFTSOL** [zzzgydi/clash-verge#693]
**Describe the bug**
在Windows10的任务管理器中的图标仿佛从中间碎裂了一样

**To Reproduce**
1. Go to 'taskmgr'
2. Click on 'Process tab'
3. Scroll down to 'Clash Verge' Process
4. See the icon error

**Expected behavior**
与任务栏中完整的图标相同

**Screenshots**
![图片](https://github.com/zzzgydi/clash-verge/assets/108245502/0a6ba9dc-f752-403a-b390-c7787f94a422)

**Information**
 - OS: Windows 10 19045.3208
 - Clash Verge Version: 1.3.5
 - Clash Core: Clash

**Additional context**
- Screen Resolution: 2560*1440
- Screen Scale: 100%
- Amount of Monitor: 1
- Tried to rebuild explorer icon cache and restore icon thumbnail, not work for this
- I see a bug fix for taskbar icon fix for Windows in 1.3.5 update log, does this may cause this defect?

**Comment by Guanran928** [comment]
在 Windows 11 Pro x64下 100%，125%，150%，175% Scaling 均无法复现。
![image](https://github.com/zzzgydi/clash-verge/assets/68757440/84bd3d86-75df-4b0c-b8ac-6b4897bb9878)

你是否使用了 MacType 或类似软件？据我所知，有时候 MacType 会导致奇怪问题。

**Comment by GRFTSOL** [comment]
> 在 Windows 11 Pro x64 下，100%、125%、150%、175% Scaling 均无法复现。 ![image](https://user-images.githubusercontent.com/68757440/261376392-84bd3d86-75df-4b0c-b8ac-6b4897bb9878.png)
> 
> 你是否使用了 MacType 或类似软件？据我所知，有时候 MacType 会导致奇怪问题。

没有使用mactype，不会又是amd的问题吧（
