### ISSUE TITLE
[BUG]windows休眠后唤醒网络流量速率显示失效 

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [zzzgydi/clash-verge#695]
之前看到了 #652 
然后发现不仅仅是睡眠 (rundll32.exe powrprof.dll,SetSuspendState 0,1,0)
休眠也会导致图显异常 (rundll32.exe powrprof.dll,SetSuspendState Hibernate)
希望作者可以再修复下,幸苦了
附个截图,这是从休眠后唤醒之后的状态
![image](https://github.com/zzzgydi/clash-verge/assets/95567275/81d804d2-b91d-4a9e-a7f8-93341dad52e7)

**Comment by zzzgydi** [comment]
1.3.6修了这个问题，可以看看有没有复现。
