### ISSUE TITLE
[BUG] malformed mach-o file(os error 88)

### ISSUE THREAD

**Issue by C-starm** [zzzgydi/clash-verge#699]
**Describe the bug**
Report malformed mach-o file error 

**To Reproduce**
1. Upgrade to 1.3.5
2. Click on the profile --> My Profile
3. show the error "malformed mach-o file(os error 88)"

**Expected behavior**
Successful running this Server

**Screenshots**
<img width="648" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/17534292/a422663b-5b27-4ec4-8313-75098e096a59">

**Information**
 - OS: Macos 13.4.1
 - Clash Verge Version: 1.3.5
 - Clash Core: Clash

**Comment by zzzgydi** [comment]
应该是下载的配置有问题，可以删掉重新下试试
