### ISSUE TITLE
[UI] UI 优化建议 

### ISSUE THREAD

**Issue by AmelloAster** [zzzgydi/clash-verge#70]
1. 系统代理，端口设置，自动启动等配置，我觉得可以参考 clash for window 放在首页，因为这些设置是最重要的设置，现在放在setting 隐藏的太深了
2. 更改 profile 的设置希望可以更可视化操作一些，直接更改 clash 的 config 文件不是很易于普通用户操作
3. 更改 port 端口的时候的防抖时间可以放宽一点 现在的时间间隔太短了 还来不及输入完一个 port 就提示 port 输入的不对

**Comment by zzzgydi** [comment]
1. 现在是没有首页的
2. 这个有点繁琐，之后有精力再加。不过这个单独搞个web页面会不会好一点
3. 这个我改改，调大防抖阈值

**Comment by zzzgydi** [comment]
v1.1.0改了更新端口的交互，更友好一点了。
