### ISSUE TITLE
使用meta核心时，stack选择system，tun模式无法使用。

### ISSUE THREAD

**Issue by 13wenwen** [zzzgydi/clash-verge#701]
### 使用meta核心时，stack选择system，tun模式无法使用。
使用meta核心时，stack选择system，tun模式会无法使用，此时虚拟网卡会显示“无internet访问权限”。但是在stack选择gvisor时，tun能正常使用，此时虚拟网卡会显示“internet连接”。这个问题是可以复现的，只要stack选择system就会出现这个问题。

**已经做过的尝试：**
  1. clash verge与clash-meta.exe都授予管理员权限。
  2. 安装服务模式。

**以下时我tun配置**
         enable: true
  stack:  system
  auto-route: true
  device: utun0
  mtu: 90000
  strict-route: true
  inet4-route-address:
     - 198.18.0.1/15
  auto-detect-interface: true
  dns-hijack:
    - any:53

**Comment by zzzgydi** [comment]
这个可以到clash meta的issue里反馈
