### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wowo666** [zzzgydi/clash-verge#705]
**Mac m1 电脑上软件界面里的任何按钮点击无任何反应**
1. 安装成功后，进入到软件界面里，啥也点击不了， 拖动窗口都拖不动

**Comment by zzzgydi** [comment]
意思是，能打开界面，但是点击任何东西都没有反应？

我感觉可能是进程存在死锁，我的m1暂时没有遇到过这种情况，你可以把日志贴一下，能方便排查问题

**Comment by Guanran928** [comment]
请填写 Issue 标题。
