### ISSUE TITLE
[BUG]窗口坐标被自动设置到-32000.0，-3200.0，以致无法显示

### ISSUE THREAD

**Issue by WindBT47** [zzzgydi/clash-verge#706]
**Describe the bug**
窗口坐标被自动设置到-32000.0，-3200.0

**To Reproduce**
1. 更新到1.3.5，启动clash verge
2. 最小化窗口
3. 浏览网页或是干些其他事情
4. 在任务栏点击图标或是右键点击dashboard无法显示窗口
5. 关闭窗口，或是重启clash verge，均无法显示窗口。
6. 打开verge.yaml，发现坐标修改
```
window_size_position:
- 600.0
- 520.0
- -32000.0
- -32000.0
```
7.将-32000.0修改为0，窗口重新显示正常。

**Expected behavior**
点击图标显示窗口，应该限制窗口坐标的范围

**Information**
 - OS: Windows11
 - Clash Verge Version: [1.3.5]
 - Clash Core: [clash]

**Additional context**

**Comment by zzzgydi** [comment]
有修复这个问题，还没发，我争取周末搞一版

**Comment by waeart** [comment]
我也发生这个问题，还好来看一下。

**Comment by zzzgydi** [comment]
这个应该修复了哈，先关了
