### ISSUE TITLE
[Feature]请问作者是否考虑将默认的geo文件由Loyalsoldier切换到meta-rules-dat

### ISSUE THREAD

**Issue by GeorgeRudd** [zzzgydi/clash-verge#707]
使用clash-verge的大多数应该都是用meta内核吧，请问作者是否考虑切换到meta-rules-dat https://github.com/MetaCubeX/meta-rules-dat geosite:cn更准

**Comment by zzzgydi** [comment]
已经更新，下个版本带吧
