### ISSUE TITLE
使用过程中遇到的问题

### ISSUE THREAD

**Issue by Dashan-IZ** [zzzgydi/clash-verge#71]
1、系统为win11 beta版本，clash的ui界面不更手，移动缓慢
2、4k屏下的图标ico，很模糊，建议上传高清图标，
3、建议增加屏蔽测速延迟的节点选项

**Comment by zzzgydi** [comment]
1. 这个问题，我还没想升win11，过一段时间才能处理这个
2. 这个处理一下
3. 你可以先点测速，然后点过滤，在过滤条件里写上`delay<error`，或者按延迟排序

**Comment by zzzgydi** [comment]
Hi，可以升级到v1.0.1，看看Win11拖拽还有没有卡顿

**Comment by Dashan-IZ** [comment]
> 你好，可以升级到v1.0.1，看看Win11拖拽还有没有卡顿

不卡了，希望重新打包一下图标换个高清的，4k屏太模糊了，在优化一下ui就更好了

**Comment by Dashan-IZ** [comment]
> 你好，可以升级到v1.0.1，看看Win11拖拽还有没有卡顿

不卡了，希望重新打包一下图标，换高清的4k屏下太模糊了，在优化一下ui就更好了

**Comment by zzzgydi** [comment]
优化ui是指的哪方面呢

**Comment by Dashan-IZ** [comment]
> 优化ui是指的哪方面呢

状态栏后台图标右键全是英文，汉化后体验会更好，ui没太大建议就感觉差点什么，之前的clash.net很不错，可以参考它，但是它跑路了
