### ISSUE TITLE
[BUG]局域网域名指向问题

### ISSUE THREAD

**Issue by swRains** [zzzgydi/clash-verge#711]
clash-verge版本：1.3.5
系统版本：windows 11
clash内核：meta  官方 都不行
代理模式：系统代理
浏览器版本：chrome 版本 115.0.5790.111（正式版本） （64 位）
在内网搭建了一个网站，dns也覆写了域名指向，ping正常可通，通过ip+端口访问正常，配置文件内无dns相关设置，curl可正常获得页面。
但是只要开了clash代理，通过域名无法访问，即便修改host重新指向也无济于事。配置文件内已有内网相关设置：
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
   单独添加 - 'DOMAIN-SUFFIX,域名,DIRECT'依旧无法访问。只有关闭clash或者关闭系统代理才行。
请问有大佬能支个方法解决嘛？

**Comment by zzzgydi** [comment]
> 单独添加 - 'DOMAIN-SUFFIX,域名,DIRECT'依旧无法访问

这个咋加的，是不是规则没搞对。将模式从规则切到direct看看能不能用就知道了。

**Comment by swRains** [comment]
直连也无法访问，添加规则是另起一行和上面一样对齐，遵循yaml规则

**Comment by swRains** [comment]
> > 单独添加 - 'DOMAIN-SUFFIX,域名,DIRECT'依旧无法访问
> 
> 这个咋加的，是不是规则没搞对。将模式从规则切到direct看看能不能用就知道了。

请问程序是不是内置了dns地址？在配置文件没有指定dns的情况下，根据wireshark抓包，它向223.5.5.5发起了dns请求。因为我只是局域网dns，没做公共解析，所以访问失败。
我找了找程序 的配置文件，没有找到相关设置。即便是在订阅配置文件中修改了dns设置，指向了本地的dns，但仍然无法访问，显示无法找到ip。当然访问其他百度google之类的网站是正常的。抓包分析是请求了doh.pub后走doh访问了，并未使用指定的dns和本地dns


我认为在dns缺省状态下应当用系统dns，期望单独设立个设置能够预处理配置文件，能够指定dns、配置规则之类的，就是配置文件预处理毕竟想改还得写个js脚本对大多数人来说还是比较抽象。

**Comment by zzzgydi** [comment]
应该看看运行配置，是不是带了dns配置

**Comment by swRains** [comment]
> 应该看看运行配置，是不是带了dns配置

[配置文件.txt](https://github.com/zzzgydi/clash-verge/files/12322030/default.txt)
这个是配置文件，除了账户密码做了替换，其他的都没动，确实没有配置dns

**Comment by swRains** [comment]
> 应该看看运行配置，是不是带了dns配置

同样的配置文件，在安卓端chash meta可以访问，但是在电脑端clash-verge不行

**Comment by zzzgydi** [comment]
把域名写到系统代理bypass里吧

**Comment by swRains** [comment]
clash  meta的问题，详见
https://github.com/MetaCubeX/Clash.Meta/issues/677

**Comment by swRains** [comment]
> 把域名写到系统代理bypass里吧

clash meta的问题，详见
https://github.com/MetaCubeX/Clash.Meta/issues/677

**Comment by swRains** [comment]
新版本设置dns:    enable: false 能够正常解析了，但如果能有方便的配置文件预处理的方法就好了
