### ISSUE TITLE
[BUG] 缩短日志最长保留时间

### ISSUE THREAD

**Issue by lilyblessing** [zzzgydi/clash-verge#713]
**Describe the bug**

未能自动清理日志文件，久远庞大的日志文件用占用大量空间

**To Reproduce**

**Expected behavior**

定期清理日志文件

**Screenshots**

![](https://raw.githubusercontent.com/lilyblessing/img/main/img/202308110142343.webp)

**Information**
 - OS: Windows10
 - Clash Verge Version: 1.3.5
 - Clash Core: Clash Meta

**Additional context**

**Comment by lankylonky22** [comment]
lol i have the opposite problem

**Comment by Guanran928** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> 未能自动清理日志文件，久远庞大的日志文件用占用大量空间

请将日志等级更改为 `Warn` 或更高 (Settings -> Log Level)
![image](https://github.com/zzzgydi/clash-verge/assets/68757440/303da3ee-94ee-4750-ac29-c8364b5e11e3)

**Comment by AnyWAT** [comment]
貌似 win10 上此处设置无效，有效的在：
设置——Verge 设置——杂项设置——App Log Level

**Comment by Guanran928** [comment]
> 这并不是自动清理日志。 如果有需要查看保留的日志，保留期限在一周到一个月左右就可以了，完全没必要保留一两年甚至永久保留。

我只是提供一个 Workaround 以减少日志的磁盘占用量，我并不是软件的开发者，请不要把FR/Bug反馈给我。

**Comment by AnyWAT** [comment]
敝人孤陋寡闻，除了 dnscrypt-proxy 可自定义日志大小、特定情况下清空旧的并重建新的，貌似没见过有自动清理日志的应用？除了用户自己手动。。。

**Comment by lilyblessing** [comment]
> 我只是提供一个 Workaround 以减少日志的磁盘占用量，我并不是软件的开发者，请不要把FR/Bug反馈给我。

理解，并感谢提供的解决方案。也许我该考虑用一个脚本来自动清理日志。

**Comment by Guanran928** [comment]
你并不需要关闭此 Issue，这确实是软件的设计缺陷。

**Comment by lilyblessing** [comment]
好的。

同时对于两处日志等级开关分别控制了什么也有疑问，为何控制日志等级需要两处设置项？

**Comment by AnyWAT** [comment]
> 设置——Verge 设置——杂项设置——App Log Level

记得此处是后来添加的。

**Comment by zzzgydi** [comment]
> 同时对于两处日志等级开关分别控制了什么也有疑问，为何控制日志等级需要两处设置项？

一个是clash内核的日志，和其他clash gui或者web ui一样的功能。另外一个是软件本身的日志，软件本身也一堆有的没的逻辑，所以得加点日志，有问题可以辅助定位。

看到你说有19g的日志，那确实也有点恐怖，后续可以加个自动清除日志的功能。

**Comment by AnyWAT** [comment]
> 久远庞大的日志文件

请看看Win10 文件夹C:\Users\用户名\AppData\Roaming\Microsoft\InputMethod\Chs 下有多少个0大小的 tmp 文件

**Comment by lilyblessing** [comment]
> 请看看Win10 文件夹C:\Users\用户名\AppData\Roaming\Microsoft\InputMethod\Chs 下有多少个0大小的 tmp 文件

看了下有4k多条0大小tmp文件，该目录下没有超过10kb的文件。
搜了一下这好像是微软输入法的联想缓存词库吧，我并不使用全拼那种联想词动态调频的输入法。

**Comment by AnyWAT** [comment]
> 有4k多条0大小tmp文件

数量不多，多的三万七千多
不定期手动清理的更少。

**Comment by zzzgydi** [comment]
刚加的功能，在杂项里选择开启，可以选择只保留7天的日志，有任何想法或建议可以补充
提前试用 https://github.com/zzzgydi/clash-verge/releases?q=alpha&expanded=true
