### ISSUE TITLE
[BUG]连接界面 Process 栏进程名显示不正常

### ISSUE THREAD

**Issue by zfh18** [zzzgydi/clash-verge#716]
**Describe the bug**
连接界面 Process 栏进程名显示不正常

**To Reproduce**
1. 分流规则中有 **PROCESS-NAME** 规则
2. 打开 Clash Verge 运行 Tun 模式
3.  查看连接页面 Process 栏

**Expected behavior**
显示正确进程名，如 **msedge.exe**，但实际显示为 **msedge.exemsedge.exemsedge.exemsedge.exemsedge.exemsedge.exe**
![image](https://github.com/zzzgydi/clash-verge/assets/10239284/2abab02a-9f48-498f-af04-9c9bf683d90f)

**Information**
 - OS: 企业版 win10 21H2
 - Clash Verge Version: v1.3.6
 - Clash Core: v1.15.0 Meta

**Additional context**
无

**Comment by zzzgydi** [comment]
我去。。debug代码忘记删了，马上处理一下

**Comment by zzzgydi** [comment]
已经更新，可以重新下载看看

**Comment by zfh18** [comment]
> 已经更新，可以重新下载看看

已确认解决，谢谢！
