### ISSUE TITLE
[BUG] error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by AmazonXYZ** [zzzgydi/clash-verge#719]
**Describe the bug**
Clash-Verge launch failed.

**To Reproduce**
1. Start Clash-verge from terminal
2. It reports the error and refuse to launch

**Expected behavior**
Launch successfully

**Information**
 - OS: Debian 12.1 KDE, with .deb installation
 - Clash Verge Version: 1.3.6

**Additional context**
I have tried to install the 1.3.6 deb by both kde discover and apt install ./<clash-verge-pack-name>.deb, and it won't launch.
Using apt remove clash-verge and reinstall 1.3.5 goes well.

**Comment by alittlemoyu** [comment]
The same for me. Had to downgrade to 1.3.5.

**Comment by 135e2** [comment]
Same here on Debian Sid.  
I suspect that the problem might be related to https://github.com/zzzgydi/clash-verge/commit/241b22a46585f7dc4e474f781de395b549888968, as it's worth noting that older Ubuntu LTS (20.04) still packages [libssl 1.1.x](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libssl1.1_1.1.1f-1ubuntu2_amd64.deb.html), while the current LTS (22.04) has updated to [libssl 3.x](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libssl3_3.0.2-0ubuntu1_amd64.deb.html), leading to a sover dismatch.
Would it be a good idea to provide both ubuntu-20.04 flavor and ubuntu-latest flavor for compatibility?

**Comment by realwyz** [comment]
> Same here on Debian Sid. I suspect that the problem might be related to [241b22a](https://github.com/zzzgydi/clash-verge/commit/241b22a46585f7dc4e474f781de395b549888968), as it's worth noting that older Ubuntu LTS (20.04) still packages [libssl 1.1.x](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libssl1.1_1.1.1f-1ubuntu2_amd64.deb.html), while the current LTS (22.04) has updated to [libssl 3.x](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libssl3_3.0.2-0ubuntu1_amd64.deb.html), leading to a sover dismatch. Would it be a good idea to provide both ubuntu-20.04 flavor and ubuntu-latest flavor for compatibility?

Agreed. Considering the LTS version, I think 22.04 is better. It's easier to upgrade to the new dependencies rather than downgrade to the deprecated ones. 
In this case, you have to deal with the `libssl.so.1.1` and `libcrypto.so.1.1` libraries which were provided by `openssl-1.1.1o`. It is risky to install openssl-1 on Ubuntu 22.04 as it uses openssl-3. You may have to keep these away from root path.

**Comment by zzzgydi** [comment]
The new version indeed has this issue, and in the next release, I will switch back to Ubuntu 22.04 for building.

**Comment by IAMIBM** [comment]
> **Describe the bug** Clash-Verge launch failed.
> 
> **To Reproduce**
> 
> 1. Start Clash-verge from terminal
> 2. It reports the error and refuse to launch
> 
> **Expected behavior** Launch successfully
> 
> **Information**
> 
> * OS: Debian 12.1 KDE, with .deb installation
> * Clash Verge Version: 1.3.6
> 
> **Additional context** I have tried to install the 1.3.6 deb by both kde discover and apt install ./.deb, and it won't launch. Using apt remove clash-verge and reinstall 1.3.5 goes well.

The way to solve this problem on Ubuntu 22.04.3 for clash-verge 1.3.6.
Download [libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb)
Then dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
Start clash-verge will be normal.

**Comment by zzzgydi** [comment]
try v1.3.7
