### ISSUE TITLE
[bug] mac 环境下自动开启无效 

### ISSUE THREAD

**Issue by AmelloAster** [zzzgydi/clash-verge#72]
mac 环境下自动开启无效 ，电脑开机以后，仍需手动启动

**Comment by zzzgydi** [comment]
mac 是M1的吗

**Comment by Damaged-Code** [comment]
> mac 是 M1 的吗

是的

**Comment by Damaged-Code** [comment]
> 开启开机自启之后，你可以看看应用的 “登录时打开” 有没有勾上，我 M1 pro 测试正常。

奥，知道了，光通过 setting 不行

**Comment by zzzgydi** [comment]
> 光通过 setting 不行

这个是指的啥

**Comment by Damaged-Code** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/26178326/165880574-d023a734-9335-4089-9613-24de834a4067.png">

**Comment by zzzgydi** [comment]
可以多开关几次试试

**Comment by Damaged-Code** [comment]
> 可以多开关几次试试

试过几次，这个 setting 感觉在 mac 环境下不生效，只能去手动 open at login

**Comment by zzzgydi** [comment]
可以看看log有没有啥错误信息

**Comment by Damaged-Code** [comment]
> 可以看看 log 有没有啥错误信息

之后我留意一下

**Comment by Damaged-Code** [comment]
> 可以看看 log 有没有啥错误信息

我发现我在 option 里 选择了 open at login 也依旧无效

**Comment by zzzgydi** [comment]
v1.1.0优化了一下mac自启动的设置，可以更新一下试试，应该修复了
