### ISSUE TITLE
[Feature] please consider support vless type

### ISSUE THREAD

**Issue by yudar1024** [zzzgydi/clash-verge#720]
**Is your feature request related to a problem? Please describe.**
please consider support vless type.
**Describe the solution you'd like**
please consider suport vless type

**Describe alternatives you've considered**
use clash for windows, it can support vless

<img width="598" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/1061851/03b04574-6c80-4592-8ac0-8857eeeaf872">

**Comment by zzzgydi** [comment]
clash for windows do not support vless either. Instead, clash verge supports vless, you can switch the core to clash meta on the settings page.
