### ISSUE TITLE
[Feature] Hide icon in taskbar

### ISSUE THREAD

**Issue by omakise** [zzzgydi/clash-verge#722]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
增加隐藏任务栏中的小图标选项

**Describe alternatives you've considered**
none

**Additional context**
隐藏能使得看起来更像是一个后台服务
隐藏了前台的小图标同时也能舒服很多
需要的时候再主动点击图标打开就好了

**Comment by zzzgydi** [comment]
你是啥系统的。如果把小图标隐藏了的话，就再也唤不起窗口了。

**Comment by zzzgydi** [comment]
win键咋打开软件

**Comment by zzzgydi** [comment]
这个功能暂时不考虑哈

> 顺便提一下一个莫名其妙的问题 当我设置窗口为某一个大小时 有时会莫名其妙的窗口大小又缩小回去 真的很奇怪
> 
> 比如我把窗口设置成1000x1000大小 然后最小化程序, 如果立刻打开还是正常大小的 但是有时打开窗口又缩成500x500的大小这样

这个后续有稳定复现的步骤的话，烦请再另外一个issue哈
