### ISSUE TITLE
[Feature] add the `open Dashboard` to the Hotkey Settings

### ISSUE THREAD

**Issue by screw-hand** [zzzgydi/clash-verge#723]
I am a mac user. Sometimes I repeatedly switch windows between `clash verge` and other software to perform actions.
Since the `app icon` of `clash verge` is not displayed in the dock bar.
I can't use `command+tab` to switch between `clash verge` and other programs.
I can only use the mouse to go to the system's status bar (top right corner) and click on the `app icon` of `clash verge` and then click on the `open panel` option.
This is a bit cumbersome.

I'd like to add a "Open Panel" configuration to the "Hotkey Settings".

Your software is very useful, thanks!

---

我是mac用户。有时候我会在`clash verge`和其他软件反复切换窗口进行操作。
由于`clash verge`的`app icon`没有显示在dock栏。
我不能使用`command+tab`切换显示`clash verge`和其他软件。
只能用鼠标去系统的状态栏（右上角）点开`clash verge`的`app icon`，再点击“打开面板”选项。
这有点繁琐。

希望能在“热键设置”，增加一个“打开面板”的配置。

你的软件很有用，谢谢！

**Comment by zzzgydi** [comment]
good idea
