### ISSUE TITLE
无法启动（pop!OS系统）[BUG]

### ISSUE THREAD

**Issue by my1996** [zzzgydi/clash-verge#724]
最新版本 点击图标没有任何响应，
**Information**
 - OS: [pop!os  基于ubuntu 22.04]
 - Clash Verge Version: [e.g. 1.3.6]
 - Clash Core: [e.g. Clash or Clash Meta]

**Comment by my1996** [comment]
amd64 .deb 安装包版本

**Comment by Guanran928** [comment]
请提供日志文件。我们没有办法在没有具体信息的情况下帮助你。

**Comment by my1996** [comment]
> 

已回退 上个版本，下次吧

**Comment by zzzgydi** [comment]
这次应用构建用的是20.04，好像是在22.04上用不了，我下个版本换回22.04构建吧。。。

**Comment by Guanran928** [comment]
> 这次应用构建用的是20.04，好像是在22.04上用不了，我下个版本换回22.04构建吧。。。

可以尝试通过 Flatpak 发行，[#317](https://github.com/zzzgydi/clash-verge/issues/317)、[#424](https://github.com/zzzgydi/clash-verge/issues/424)。
目前 Flathub 似乎有非官方的移植 [Pull Request](https://github.com/flathub/flathub/pull/4359)。
