### ISSUE TITLE
[Feature]希望可以增加如同 Clash for Windows diff 编辑配置文件的功能

### ISSUE THREAD

**Issue by Thundercup** [zzzgydi/clash-verge#725]
建议在配置文件管理界面右键菜单中添加diff编辑功能，将本地编辑的改动永久覆盖到远程配置文件中，使得更新不影响本地改动

**Comment by zzzgydi** [comment]
> 将本地编辑的改动永久覆盖到远程配置文件中，使得更新不影响本地改动

这个的话，我推荐你新建一个merge profile或者script profile，通过这种方式去改远程配置。类似cfw的parsers

**Comment by mesotescode** [comment]
> merge

合并的规则，不像diff那样直观，对照原规则直接修改。对没有编程基础的，真是摸不到头绪，merge列出的规则在说什么。
