### ISSUE TITLE
uwp应用无法联网

### ISSUE THREAD

**Issue by DargonStar** [zzzgydi/clash-verge#726]
cfw有个功能可以使用 Fiddler 4 解除 UWP 应用的网络隔离。这个软件我没找到

**Comment by AnyWAT** [comment]
貌似不影响uwp的最佳：一般不开启系统代理，浏览器采用代理扩展控制，能在自身内部设置代理的就好。此时可同时运行不同端口的若干代理，一个浏览器。。。另一个专职下载。。。再一个。。。又何妨？

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/issues/314
