### ISSUE TITLE
[Feature]没有提供ARM64的Windows支持版本

### ISSUE THREAD

**Issue by Reviona** [zzzgydi/clash-verge#727]
如题

**Comment by Guanran928** [comment]
在作者提供预编译的二进制文件之前，你可以尝试跟随 [README.md](https://github.com/zzzgydi/clash-verge#development) 自行编译 ARM64 Windows 版本。

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/issues/230 试过了，失败了
