### ISSUE TITLE
每次退出后重新启动，窗口都会变得很小

### ISSUE THREAD

**Issue by GeorgeRudd** [zzzgydi/clash-verge#734]
**Describe the bug**
手动更换了一次内核之后就出现了这种情况，无法记忆上次打开的窗口大小。每次退出后重新启动，窗口都会变得很小。

手动删除了.config之后，没有再出现窗口变小的情况

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [win]
 - Clash Verge Version: [1.3.6] Clash.Verge_1.3.6_x64-setup.exe
 - Clash Core: [ Clash Meta]

**Additional context**

**Comment by zzzgydi** [comment]
窗口变得很小的话，可以留意window_size_position的值
