### ISSUE TITLE
[BUG]软件打开一段时间之后meta内核进程的CPU占用就会变得异常的高

### ISSUE THREAD

**Issue by sekurodesu** [zzzgydi/clash-verge#735]
如题，将软件内核切换为clash-meta之后，meta进程就会CPU占用很高，甚至能达到100%，重启软件也没法解决，希望修复此BUG。
![微信图片_20230823005418](https://github.com/zzzgydi/clash-verge/assets/51750095/e8bc31f3-2248-4ed4-bd0a-1b8e500c5f25)

**Comment by zzsc2** [comment]
因为这个问题，我用回了clash_for_windows，把闭源的内核换成了meta就没事了。

**Comment by moranno** [comment]
这个你需要到meta那边反馈下。
