### ISSUE TITLE
[BUG] check.mjs CLASH_MAP中"linux-arm64"项应为"clash-linux-arm64"

### ISSUE THREAD

**Issue by myp0402** [zzzgydi/clash-verge#736]
**Describe the bug**
check.mjs CLASH_MAP中"linux-arm64"项应为"clash-linux-arm64"
在Linux arm64平台编译时，报错出现`[ERROR]: "clash" gz failed: incorrect header check` 查看链接发现“Not Found”，查对下载链接，clash已将`linux-armv8`的命名方式修改为`linux-arm64`

**To Reproduce**
在Linux arm64平台运行`yarn run check`命令

**Expected behavior**
报错出现`[ERROR]: "clash" gz failed: incorrect header check`

**Information**
 - OS: ArchLinuxARM
 - Clash Verge Version: 1.3.6
 - Clash Core: Clash & Clash Meta

**Solution**
手动修改script/check.mjs中28行clash-linux-armv8为clash-linux-arm64

**Comment by zzzgydi** [comment]
已修复
