### ISSUE TITLE
[BUG] AppImage package is missing libthai.so

### ISSUE THREAD

**Issue by xz-dev** [zzzgydi/clash-verge#737]
**Describe the bug**
AppImage is missing libthai.so

**To Reproduce**
1. Not install `dev-libs/libthai` at Gentoo
2. run ./clash-verge_1.3.6_amd64.AppImage
3. Error log: `clash-verge: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory
❯ `

**Expected behavior**
Should running

**Screenshots**
Nope

**Information**
 - OS: Gentoo
 - Clash Verge Version: 1.3.6
 - Clash Core: Clash Meta

**Additional context**
[The issues](https://github.com/OpenShot/openshot-qt/issues/5060) is helpful to solve the problem.

**Comment by zzzgydi** [comment]
try v1.3.7
