### ISSUE TITLE
[bug] Windows服务安装出错

### ISSUE THREAD

**Issue by zzzgydi** [zzzgydi/clash-verge#74]
错误提示 `failed to start service with status 6` 或者 `failed to install service with status 6`。

程序内部调用`sc`命令得到exitcode为6。暂不清楚原因。

解决方法：手动新建一个`install.bat` 内容如下：

```
sc create clash_verge_service binpath=E:\\path\\to\\clash-verge-service.exe type=own start=AUTO displayname="Clash Verge Service"

sc start clash_verge_service
```

Note：需要根据自己的程序安装目录，找到`clash-verge-service.exe`，应该是在`安装目录/resources/clash-verge-service.exe`。然后替换上面`binpath`的值。

**Comment by shikkoku** [comment]
[SC] CreateService FAILED 1072:

The specified service has been marked for deletion.

**Comment by ZetaoYang** [comment]
> 错误提示 `failed to start service with status 6` 或者 `failed to install service with status 6`。
> 
> 程序内部调用`sc`命令得到exitcode为6。暂不清楚原因。
> 
> 解决方法：手动新建一个`install.bat` 内容如下：
> 
> ```
> sc create clash_verge_service binpath=E:\\path\\to\\clash-verge-service.exe type=own start=AUTO displayname="Clash Verge Service"
> 
> sc start clash_verge_service
> ```
> 
> Note：需要根据自己的程序安装目录，找到`clash-verge-service.exe`，应该是在`安装目录/resources/clash-verge-service.exe`。然后替换上面`binpath`的值。

`binpath=` 和 `<binarypathname>`之间是有空格的，见 https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create

![](https://user-images.githubusercontent.com/10769951/165282979-8ec9f400-8326-4380-92c9-0a845651a18f.png)
![](https://user-images.githubusercontent.com/10769951/165283013-e87205e3-ce5c-4917-8537-eb8ca9e39f85.png)

**Comment by ileeoyo** [comment]
手动创建服务成功，但是启动失败

**Comment by zzzgydi** [comment]
这个可能是你路径中有个空格导致找不到exe，加个双引号吧

**Comment by ileeoyo** [comment]
> 这个可能是你路径中有个空格导致找不到exe，加个双引号吧
加了双引号，也不行
![image](https://user-images.githubusercontent.com/24651612/166870241-cc226854-d7f5-406c-9451-99c3b5c99ef1.png)

**Comment by zzzgydi** [comment]
有点奇怪，等我发个新版本吧，已经处理了service安装和卸载的问题

**Comment by ZetaoYang** [comment]
`binpath=` 和 `binarypathname `之间有一个空格
![](https://user-images.githubusercontent.com/10769951/166943090-d5a244f8-957c-4206-92a6-affd664d0255.png)
![](https://user-images.githubusercontent.com/10769951/166943267-f7016318-d797-476a-9ff3-ba0096c18078.png)

link:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create

**Comment by zzzgydi** [comment]
v1.0.1内置了service install 和 uninstall 的程序，应该可以修复服务安装和启动的问题了。

**Comment by ileeoyo** [comment]
> uninstall 的程序，应该可以修复服务安装和启动的问题了。

1.0.1版本已修复问题，服务安装OK

**Comment by vinzst** [comment]
![image](https://user-images.githubusercontent.com/43403042/167773414-aa7d55ef-7176-498d-9520-517c71c270c0.png)
![image](https://user-images.githubusercontent.com/43403042/167773448-d1ca4bf5-d609-4283-9721-9c3cf0cf8555.png)
还是不行额

**Comment by zzzgydi** [comment]
@vinzst 你这个可能是之前装了没启动，导致安装失败的，管理员模式运行 `sc delete clash_verge_service` 试试

**Comment by vinzst** [comment]
> @vinzst 你这个可能是之前装了没启动，导致安装失败的，管理员模式运行 `sc delete clash_verge_service` 试试

ok 完美解决 谢谢大佬

**Comment by asfork** [comment]
```
2022-05-12 18:23:13 - failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)`
2022-05-12 18:23:13 - error sending request for url (http://127.0.0.1:33211/get_clash): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)
```

出现这个 log 后，反复通过 `install-service.exe` 和 `uninstall-service.exe` 重装服务，仍无法解决。只能到 `verge.yaml` 里把 `enable_service_mode` 改为 false 。

随后在应用界面手动 uninstall , Terminal 中提示 `io error`。手动 install 后恢复正常，可是保持 tun模式和 service 模式开启状态，重启 clash verge.exe 后再次复现 `failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error`。任务管理器中 `clash-verge-service` 服务始终保持运行。

**Comment by zzzgydi** [comment]
可能要检查一下 33211 端口是否被占用了，从而导致service运行出错了

**Comment by zzzgydi** [comment]
@asfork 我大概知道啥问题了，已经修复了，下个版本发。

**Comment by cool-ic** [comment]
> @cool-ic 你这个可能是之前装了没启动，导致安装失败的，管理员模式运行 `sc delete clash_verge_service` 再安装试试

更新到了最新的版本，并执行了sc delete clash_verge_service，还是status 1
