### ISSUE TITLE
nameserver解析得到局域网ip会再用fallback dns解析

### ISSUE THREAD

**Issue by superciv** [zzzgydi/clash-verge#741]
**Describe the bug**
dns模块解析得到局域网ip，按照文档的说明应当直接返回，而不是再用fallback dns解析。
同样的配置文件，用终端启动clash meta core，dns表现符合预期。判断是clash verge的问题。

**预期表现**
time="2023-08-25T10:39:09.1347076+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://172.21.201.21:53"
time="2023-08-25T10:39:09.1347076+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://119.29.29.29:53"
time="2023-08-25T10:39:09.1347076+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://223.5.5.5:53"
time="2023-08-25T10:39:09.1362676+08:00" level=debug msg="[DNS] lgn.bjut.edu.cn --> [172.30.201.10 172.30.201.2], from udp://172.21.201.21:53"
time="2023-08-25T10:39:09.1370383+08:00" level=info msg="[TCP] 127.0.0.1:52625(msedge.exe) --> lgn.bjut.edu.cn:80 match RuleSet(Lan) using DIRECT"

**配置文件**
dns:
  enable: true         # 不使用系统 DNS
  ipv6: false          # 关闭 IPV6
  listen: 0.0.0.0:1053 # dns 监听
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - "*.battlenet.com.cn"
    - "*.battlenet.com"
    - "*.blzstatic.cn"
    - "*.battle.net"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:        # 默认 DNS 服务
    - 223.5.5.5
    - 119.29.29.29
    - 172.21.201.21
  fallback:          # 国外 DNS 服务器
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true 

**实际日志**
time="2023-08-25T10:25:58.6747162+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://172.21.201.21:53"
time="2023-08-25T10:25:58.6747162+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://119.29.29.29:53"
time="2023-08-25T10:25:58.6747162+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from udp://223.5.5.5:53"
time="2023-08-25T10:25:58.6757456+08:00" level=debug msg="[DNS] lgn.bjut.edu.cn --> [172.30.201.2 172.30.201.10], from udp://172.21.201.21:53"
time="2023-08-25T10:25:58.6762697+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from https://dns.alidns.com:443/dns-query"
time="2023-08-25T10:25:58.6762697+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn from https://doh.pub:443/dns-query"
time="2023-08-25T10:25:58.6805156+08:00" level=debug msg="[DNS] lgn.bjut.edu.cn --> [], from https://dns.alidns.com:443/dns-query"
time="2023-08-25T10:25:58.6805156+08:00" level=debug msg="[DNS] resolve lgn.bjut.edu.cn error: couldn't find ip"

**Information**
 - OS: windows 11
 - Clash Verge Version: 1.3.6
 - Clash Core:  Clash Meta

**Comment by moranno** [comment]
会不会是你设置中clash字段中没有勾选dns的原因？

**Comment by zzzgydi** [comment]
clash字段中没有勾选dns
