### ISSUE TITLE
[BUG]Ubuntu 22.04 安装1.3.6 后运行无反应

### ISSUE THREAD

**Issue by DanielZWX** [zzzgydi/clash-verge#745]
系统为Ubuntu 22.04 , 之前安装1.3.5，运行正常。 但安装1.3.6后（覆盖安装或卸载1.3.5后再安装1.3.6）运行无反应。

在1.3.5版本下，/usr/bin 下的clash,clash-verge,clash-meta三个文件的【用户：用户组】为 1001:rtkit
在1.3.6版本下，/usr/bin 下的clash,clash-verge,clash-meta三个文件的【用户：用户组】为 1001:lpadmin

不知是否与此有关，

**Comment by zzzgydi** [comment]
无关，我换了构建的系统版本导致了一些问题，1.3.6版本在ubuntu22.04应该是运行不了的了，下个版本我换回去再升级吧

**Comment by zzzgydi** [comment]
try v1.3.7
