### ISSUE TITLE
[BUG] Missing clash-meta on macOS x64 in the latest release.

### ISSUE THREAD

**Issue by AntaresQAQ** [zzzgydi/clash-verge#746]
**Describe the bug**
In the latest release, the clash-meta is missing from the macOS x64 bundle.

**To Reproduce**
1. Remove legacy version app and old config, download and install latest `Clash Verge.app`.
2. Open and click `Settings -> Clash Core -> Clash Meta`.
3. See error `No such file or directory (os error 2)`.
4. Open folder `Clash Verge.app/Contents/MacOS`, missing file `clash-meta`.

**Screenshots**
<img width="515" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/37372723/6c6bd6da-c1aa-4197-a035-7780867e99ba">

**Information**
 - OS: macOS Ventura 13.5 (22G74) x86_64
 - Clash Verge Version: 1.3.6

**Additional context**
[Clash.Verge_1.3.6_x64.dmg](https://github.com/zzzgydi/clash-verge/releases/download/v1.3.6/Clash.Verge_1.3.6_x64.dmg)

**Comment by zzzgydi** [comment]
重新下载安装一下试试

**Comment by AntaresQAQ** [comment]
> 重新下载安装一下试试

并不行，但是发现了更多的信息。

当我直接Mount了dmg，到app里面是可以找到clash-meta的，但是我尝试在终端中执行`./clash-meta`它并不能执行（clash是可以的）。

当我把app copy出来，直接拖到application或者cp命令，clash-meta就会消失。

<img width="744" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/37372723/3364b7db-65b6-42e2-b609-218bcd048a3c">

<img width="707" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/37372723/750dbfb9-001e-4d54-9261-09944c3fb680">

**Comment by AntaresQAQ** [comment]
哦我知道了，因为我电脑上做了公司的enroll，似乎是Microsoft Defender在没有通知我的情况下悄悄把它删掉了，不好意思添麻烦了。
