### ISSUE TITLE
[BUG]安装软件失败， 提示  filed to install webview2! the app can't run without it , 软件安装成功之后打开闪退！

### ISSUE THREAD

**Issue by moneyfly1** [zzzgydi/clash-verge#747]
安装软件的时候 提示 
![3V6UQ~MKX`LGU~Q_ @GQ$54](https://github.com/zzzgydi/clash-verge/assets/93109844/cf98d9d7-b573-49f6-aa6e-c8256c4bceac)
 有的电脑安装之后， 打开软件闪退！ 请修复

**Comment by AnyWAT** [comment]
> 打开软件闪退！ 请修复

如Windows 系统问题，与本软件无关。
Win7 只能支持100.X.X.X 以下的 WebView（最新 116.0.1938.62）
需要新版的 MicrosoftEdgeWebview2Setup.exe 可去[巨硬官网（左下角的 Download ）](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)下载。
据说较新版本能自适应安装 Win7 系统下的 WebView

**Comment by zzzgydi** [comment]
先装一下webview2吧

**Comment by moneyfly1** [comment]
webview2 , 已经解决，  不知道大家遇到过没遇到过，安装这个软件之后， 导致原版的 小猫咪不能用

**Comment by zzzgydi** [comment]
> 安装这个软件之后， 导致原版的 小猫咪不能用 

俩软件默认用的端口都是7890/9090啥的，开了一个，端口不就被占了吗
