### ISSUE TITLE
[bug] tun stack不兼容以system方式使用

### ISSUE THREAD

**Issue by shikkoku** [zzzgydi/clash-verge#75]
Merge Profile里设置

tun:
  stack: system

无法连通

使用的是04.17的p核

**Comment by MetaCubeX** [comment]
> Merge Profile里设置
> 
> tun: stack: system
> 
> 无法连通
> 
> 使用的是04.17的p核

https://github.com/MetaCubeX/Clash.Meta/releases/tag/alpha
欢迎试试

**Comment by zzzgydi** [comment]
你在merge里设置tun的话，要确保use他了，或者Use Clash Fields那里要把tun勾上，不然字段不生效的。然后还要看看设置里的tun mode有没有开启。

**Comment by shikkoku** [comment]
> 你在merge里设置tun的话，要确保use他了，或者Use Clash Fields那里要把tun勾上，不然字段不生效的。然后还要看看设置里的tun mode有没有开启。

不加stack: system这一行可以正常连通。

**Comment by shikkoku** [comment]
> > Merge Profile里设置
> > tun: stack: system
> > 无法连通
> > 使用的是04.17的p核
> 
> https://github.com/MetaCubeX/Clash.Meta/releases/tag/alpha 欢迎试试

建议你们先把[Clash.Mini](https://github.com/MetaCubeX/Clash.Mini)的服务模式搓出来。

**Comment by zzzgydi** [comment]
> 不加stack: system这一行可以正常连通。

你是只加了这一个吗，tun的其他字段可能也要补上的哦，是会把tun整个替换了的。

**Comment by shikkoku** [comment]
> > 不加stack: system这一行可以正常连通。
> 
> 你是只加了这一个吗，tun的其他字段可能也要补上的哦，是会把tun整个替换了的。

我意思是[clash-verge](https://github.com/zzzgydi/clash-verge)只能设置stack: gvisor，设为system就通不了网。

**Comment by zzzgydi** [comment]
可以用clash core测试一下，排除是不是4.17 clash core的问题

**Comment by shikkoku** [comment]
将[clash-verge](https://github.com/zzzgydi/clash-verge)目录下的clash.exe加入允许使用公用网络的权限后解决。

https://github.com/Fndroid/clash_for_windows_pkg/issues/2067
