### ISSUE TITLE
win可以提供便携版吗、什么时候支持安卓

### ISSUE THREAD

**Issue by xiaowenlv** [zzzgydi/clash-verge#757]
我需要win的绿色便携版，希望可以尽快支持安卓。

**Comment by wenliyang** [comment]
早已支持了

https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88

**Comment by zzzgydi** [comment]
有便携版了，没有安卓版的计划
