### ISSUE TITLE
[BUG]proxy provider无法自动更新。

### ISSUE THREAD

**Issue by yoohooyoo** [zzzgydi/clash-verge#758]
proxy provider无法自动更新。
设置更新间隔为10小时（43200），在其他平台客户端均可更新。
但是clash verge没有反应。

**Comment by zzzgydi** [comment]
那可能是clash内核都没跑够10个小时吧

**Comment by yoohooyoo** [comment]
> 那可能是clash内核都没跑够10个小时吧

我测试改为更短的时间试试。

另外，我发现我的clash verge多个配置文件互相切换，里面的代理列表不会跟着一起更新。
这时候如果我手工更新proxy provider，代理列表就会更新了。
感觉是相关的问题。
我就不提另一个issue了。

**Comment by yoohooyoo** [comment]
@zzzgydi 
修改为更短的时间测试，确实成功了。
看来Clash Verge不是基于自然时间来判断的，而是以自己的运行时长。

不过上面提到的多个配置文件切换，代理列表不会切换问题，仍然存在。
我需要重新提一个issue吗。

**Comment by zzzgydi** [comment]
> 多个配置文件切换，代理列表不会切换问题

这个可能是配置文件切换，代理列表的更新要点时间，刷新一下代理页面就好了，或者在代理页和配置页反复切换一下（也是一种刷新代理页面的方式）

**Comment by zzzgydi** [comment]
> 看来Clash Verge不是基于自然时间来判断的，而是以自己的运行时长。

其实这个应该是clash内核的问题，clash verge对每个配置也有一个自动更新逻辑，那个就不是根据运行时长算的

**Comment by yoohooyoo** [comment]
> > 多个配置文件切换，代理列表不会切换问题
> 
> 这个可能是配置文件切换，代理列表的更新要点时间，刷新一下代理页面就好了，或者在代理页和配置页反复切换一下（也是一种刷新代理页面的方式）

还是不行。等了五分钟。还是不会更新。
会不会因为我使用的proxy provider配置文件名字相同，导致识别错误？
因为我尝试换一个使用不同名字的，就可以成功切换。

**Comment by zzzgydi** [comment]
> 会不会因为我使用的proxy provider配置文件名字相同，导致识别错误？

可能是的

**Comment by yoohooyoo** [comment]
> 

这里是不是可以用类似cfw的处理逻辑，把所有的config文件和provider文件都以随机数重新在本地命名。重新做对应关系。

**Comment by yoohooyoo** [comment]
> > 会不会因为我使用的proxy provider配置文件名字相同，导致识别错误？
> 
> 可能是的

这里是不是可以用类似cfw的处理逻辑，把所有的config文件和provider文件都以随机数重新在本地命名。重新做对应关系。
