### ISSUE TITLE
[Feature] Move configuration folder to the same folder under Clash-Verge

### ISSUE THREAD

**Issue by hermanb001** [zzzgydi/clash-verge#759]
**Is your feature request related to a problem? Please describe.**
When share my configuration with my friends, the folder under Clash-Verge does not include my configurations.

**Describe the solution you'd like**
Move the folder under uer\.config\clash-verge to C:\Program Files\Clash-Verge, so when sharing with my friends I can ZIP the whole folder of C:\Program Files\Clash-Verge

**Comment by wenliyang** [comment]
PORTABLE:

https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88

**Comment by hermanb001** [comment]
> PORTABLE:
> 
> https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88

Actually I am using portable version, but all confirgurations are kept in uer\.config\clash-verge

**Comment by hermanb001** [comment]
> PORTABLE:
> 
> https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#windows-%E4%BE%BF%E6%90%BA%E7%89%88

Thanks!!!
