### ISSUE TITLE
[BUG]MacOS 10.13.6 Dashboard打开是白板

### ISSUE THREAD

**Issue by wallinwind** [zzzgydi/clash-verge#767]
测试机器是一台MBA 2015，操作系统版本是macOS High Sierra  10.13.6
MBP M1在最新操作系统macOS Ventura 13.5.1上一切正常

希望作者修复老版本面板的显示问题，如果无法修复，建议直接排除这个版本操作系统的运行。

**Comment by zzzgydi** [comment]
readme里有提到最低支持到10.15+
