### ISSUE TITLE
[BUG]fake-ip storage lost after restart

### ISSUE THREAD

**Issue by Natsuki-Kaede** [zzzgydi/clash-verge#769]
**Describe the bug**
fake-ip storage lost after restart.

**To Reproduce**
added config:
profile:
  store-selected: true
  store-fake-ip: true

The resolve results of the same domain name are different after restarting.

**Information**
 - OS: Windows 11
 - Clash Verge Version: 1.3.6
 - Clash Core: Clash Meta

**Comment by zzzgydi** [comment]
```
profile:
store-selected: true
store-fake-ip: true
```

This config may not have taken effect unless you set this. Setting -> Clash fields -> select profile

<img width="497" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/27361820/1213a1ca-4a14-45e0-bafd-40b5bd632e7d">

**Comment by Natsuki-Kaede** [comment]
> ```
> profile:
> store-selected: true
> store-fake-ip: true
> ```
> 
> This config may not have taken effect unless you set this. Setting -> Clash fields -> select profile
> <img alt="image" width="497" src="https://user-images.githubusercontent.com/27361820/266817124-1213a1ca-4a14-45e0-bafd-40b5bd632e7d.png">

I have checked profile option, it still doesn't work.

**Comment by zzzgydi** [comment]
check the runtime config

**Comment by Natsuki-Kaede** [comment]
> check the runtime config

The config is OK because I tested it on [kogekiplay/ClashMetaForWindows_Mini](https://github.com/kogekiplay/ClashMetaForWindows_Mini), it worked correctly.
But the fake-ip cannot be stored when I use clash-verge. It changes after restarting.
