### ISSUE TITLE
如何修改配置文件目录

### ISSUE THREAD

**Issue by vinzst** [zzzgydi/clash-verge#77]
我看是支持的，但是我研究了好久都没懂

**Comment by zzzgydi** [comment]
仅windows支持，在exe所在目录新建一个`.config`目录，然后再设置一个`.config/PORTABLE` 的空文件即可。

可以看这里 https://github.com/zzzgydi/clash-verge/issues/21#issuecomment-1097467046

**Comment by vinzst** [comment]
> windows，在exe目录下新建一个支持`.config`目录，然后再设置一个`.config/PORTABLE`空文件即可。
> 
> 可以看这里[#21（评论）](https://github.com/zzzgydi/clash-verge/issues/21#issuecomment-1097467046)

谢谢大佬
