### ISSUE TITLE
界面不显示透明状态，提示错误如下：

### ISSUE THREAD

**Issue by yxzhoubing** [zzzgydi/clash-verge#772]
错误提示:failed to construct 'websocket' :an insecure wdbsocket connection may not be initiated from a page loaded over https

**Comment by zzzgydi** [comment]
补充一下什么系统什么版本吧

**Comment by yxzhoubing** [comment]
> win版本，1.3.5或者1.3.6到最新的1.3.7安装后都是如此


![photo_2023-10-04_16-09-23](https://github.com/zzzgydi/clash-verge/assets/70786930/b844477d-d749-4615-9dae-f4d435e5645a)

**Comment by yxzhoubing** [comment]
![photo_2023-10-06_14-26-41](https://github.com/zzzgydi/clash-verge/assets/70786930/8a9addcf-bae4-4ea3-a2e0-bd3cad3d2a22)

**Comment by zzzgydi** [comment]
我改了一点东西，可以试试 https://github.com/zzzgydi/clash-verge/releases?q=alpha&expanded=true 这里的安装包
