### ISSUE TITLE
[BUG]installed 1.3.6 version on debian 12, but it won't start

### ISSUE THREAD

**Issue by zlusc** [zzzgydi/clash-verge#774]
**Describe the bug**
I use "sudo dpkg -i clash-verge_1.3.6_amd64.deb " installed the the app, but after installation, the app won't start, after click the icon, there is nothing happened in gnome, it show the app icon very shortly on the task bar in KDE plasma, then quit without any warning or error message. start from command line won't work either.

I am using HP elitebook with debian 12 installed.

**Information**
 - OS: Linux debian 12
 - Clash Verge Version: [e.g. 1.3.6]
 - Clash Core: [N/A, won't start]

**Comment by zzzgydi** [comment]
try v1.3.7
