### ISSUE TITLE
[BUG] the platform darwin-x86_64 was not found On the response platforms object

### ISSUE THREAD

**Issue by mybdye** [zzzgydi/clash-verge#775]
**To Reproduce**
Click check for updates button

**Screenshots**
<img width="1117" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/21116709/c2a7a62a-4674-466e-9008-a165fb2aed9a">

**Information**
 - OS: macOS 13.5.2 (22G91)
 - Clash Verge Version: 1.3.7
 - Clash Core: Clash Meta

**Comment by zzzgydi** [comment]
try again

**Comment by mybdye** [comment]
> try again

👍 

<img width="836" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/21116709/0cce9389-7458-4fe3-9c57-b73322a5e68a">
