### ISSUE TITLE
更细之后,无法使用vless类型的节点.[BUG] 版本 1.3.7

### ISSUE THREAD

**Issue by fjiabinc** [zzzgydi/clash-verge#777]
<img width="433" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/38276720/ad2dbdbf-db41-423f-83b2-7e3caea35863">

**Comment by zzzgydi** [comment]
更换clash meta内核？

**Comment by fjiabinc** [comment]
> 更换clash meta内核？

啊吐了..我之前一直是clash meta . 更新之后默认不是mate,所有订阅文件都坏掉了. 然后报错,切换mate不成功.要处理错误之后才能切换.......

**Comment by zzzgydi** [comment]
> > 更换clash meta内核？
> 
> 啊吐了..我之前一直是clash meta . 更新之后默认不是mate,所有订阅文件都坏掉了. 然后报错,切换mate不成功.要处理错误之后才能切换.......

有啥错误么

**Comment by fjiabinc** [comment]
> 

看我上面的图啊,这不是错误是啥,有error肯定是返回终止了. 肯定切换不成功了.

**Comment by ERCB** [comment]
@zzzgydi 是这个协议不再支持么，然后配置里其他协议也都用不了。辛苦作者了～🌹🌹

![image](https://github.com/zzzgydi/clash-verge/assets/2218697/e1098e79-4977-4a5b-a674-efe8d291ff4d)
![image](https://github.com/zzzgydi/clash-verge/assets/2218697/25636cc4-e9f6-440f-bc57-21c17348dc5b)
![image](https://github.com/zzzgydi/clash-verge/assets/2218697/ccff45b4-83c6-44a7-883d-93be0066a840)

**Comment by zzzgydi** [comment]
> 看我上面的图啊,这不是错误是啥,有error肯定是返回终止了. 肯定切换不成功了.

图里的错已经说了，是没有用clash meta核心。

> 切换meta不成功

这个问题还有没有别的错误提示，没有啥提示就贴日志

**Comment by fjiabinc** [comment]
> > 看我上面的图啊,这不是错误是啥,有error肯定是返回终止了. 肯定切换不成功了.
> 
> 图里的错已经说了，是没有用clash meta核心。
> 
> > 切换meta不成功
> 
> 这个问题还有没有别的错误提示，没有啥提示就贴日志

这个问题互相矛盾,如果能成功切换到clash meta 核心,那么问题不存在,问题在于刚更新完首次打开会使用默认的clash内核,但是吧,一般自己写的配置是clash meta的版本,所以报错. 出现报错之后就死活切换不到meta核心,造成一个闭环错误.

**Comment by DanielZWX** [comment]
我也是macos系统呀，直接更新替换没任何问题呀。我也是用的meta，替换后还是meta呀。
macos系统上更新过几个版本都没问题

**Comment by fjiabinc** [comment]
> 

在线更新的吗, 我是在软件内在线更新的. 不是下载dmg包手动更新哦

**Comment by zzzgydi** [comment]
> 在线更新的吗, 我是在软件内在线更新的. 不是下载dmg包手动更新哦

可以把`~/.config/clash-verge/verge.yaml`文件里clash_core字段的值改成`clash-meta`重启软件试试

**Comment by fjiabinc** [comment]
> > 在线更新的吗, 我是在软件内在线更新的. 不是下载dmg包手动更新哦
> 
> 可以把`~/.config/clash-verge/verge.yaml`文件里clash_core字段的值改成`clash-meta`重启软件试试

一击致命. 直接解决问题
