### ISSUE TITLE
[BUG]更新之后发现tun模式不能启动，只能用代理模式

### ISSUE THREAD

**Issue by cengzhijie3** [zzzgydi/clash-verge#778]
<img width="754" alt="截圖 2023-09-11 下午9 35 44" src="https://github.com/zzzgydi/clash-verge/assets/89333400/4b625d98-5c95-44c4-97f7-cd03f6892300">
更新之后发现tun模式不能启动，只能用代理模式

**Comment by zzzgydi** [comment]
得重新设置一下权限

**Comment by zzzgydi** [comment]
<img width="260" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/27361820/92326bc7-f89f-41cf-b42c-7d4540aefbcc">
点这个，然后点弹窗里小锁授权

**Comment by wlnxing** [comment]
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/27361820/267527617-92326bc7-f89f-41cf-b42c-7d4540aefbcc.png"> 点这个，然后点弹窗里小锁授权

感谢🙏 终于找到mac能用tun模式方法了
