### ISSUE TITLE
[Feature] 是否可以在设置中提供自定义bypass list的选项?

### ISSUE THREAD

**Issue by BeastSenpai1919810** [zzzgydi/clash-verge#783]
我经常会链接一部分国内网址, 这些网址一般不处于geolist中.
如果一直开关系统代理, 会比较麻烦. 请问有没有解决方案呢?

**Comment by zzzgydi** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/27361820/c13a4687-9813-4744-bef6-360779004f66)
