### ISSUE TITLE
[BUG] 在墙外，不打开系统代理就上不去油管。

### ISSUE THREAD

**Issue by gitony0101** [zzzgydi/clash-verge#787]
**Describe the bug**

在墙外。必须打开系统代理，才能上油管,并且只用直连就行，不需要全局或者规则。
关闭之后，就上不去了。

**To Reproduce**
如bug描述所示。

**Expected behavior**

**Screenshots**

<img width="791" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/53283254/b2ecb1f6-f77f-4aba-9b84-2678f910e748">

<img width="462" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/53283254/168c5ef7-505b-4348-9954-68e08dd1f52b">

**Information**
 - OS: [e.g. macOS] MacOS
 - Clash Verge Version: [e.g. 1.3.4] 13.5.2
 - Clash Core: [e.g. Clash or Clash Meta] clash

**Additional context**

**Comment by zzzgydi** [comment]
把TUN关了

**Comment by gitony0101** [comment]
> 把TUN关了

你好，感谢回复，但是还是不解决问题：

<img width="1117" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/53283254/cf49e9a7-c606-41b9-9856-eedd28c683b3">

一直卡在这里，DNS都清空了没有反应

**Comment by zzzgydi** [comment]
既然已经在墙外，那关闭软件，关闭系统代理，这样呢？

**Comment by gitony0101** [comment]
> 既然已经在墙外，那关闭软件，关闭系统代理，这样呢？

问题就在这里，关掉软件，关闭系统代理，就上不去了

**Comment by liangxu001** [comment]
我的也一样，问题像是TUN模式在macOS版本里不生效。ClashforWindow就很正常。

**Comment by gitony0101** [comment]
> 我的也一样，问题像是TUN模式在macOS版本里不生效。ClashforWindow就很正常。

是啊，我发现很多人都有这样的问题。

**Comment by gitony0101** [comment]
已经解决，检查了一下hosts，发现了三四年前的祖传hosts。。。删掉以后就可以了
