### ISSUE TITLE
[BUG]多用户模式下的ss2022密钥2022-blake3-aes-128-gcm支持有问题

### ISSUE THREAD

**Issue by PingZi-Wing** [zzzgydi/clash-verge#788]
**Describe the bug**
使用2022-blake3-aes-256-gcm没问题，用128-gcm就会提示如下错误（v2rayN可以使用）：
![屏幕截图 2023-09-18 190932-1](https://github.com/zzzgydi/clash-verge/assets/57025184/877c7e3a-e5ff-44a1-965e-2d5ae6ee2b44)

**Information**
 - OS: win11
 - Clash Verge Version: 1.3.7
 - Clash Core: [Clash Meta 1.15.1]

**Comment by zzzgydi** [comment]
反馈到clash meta
