### ISSUE TITLE
Windows平台安装版与便携版都无法启动（闪退）

### ISSUE THREAD

**Issue by dozen007** [zzzgydi/clash-verge#79]
![image](https://user-images.githubusercontent.com/35923210/166098379-2891c12c-dfc2-4c17-a113-a08faca7f032.png)
系统是Windows10 LTSB 2016
已安装webview2
![image](https://user-images.githubusercontent.com/35923210/166098412-4a40b6c5-99a1-47f8-bb56-404ee20618f1.png)
有启动失败的日志，现在不知道怎么解决

**Comment by zzzgydi** [comment]
看看config.yaml文件的内容

**Comment by dozen007** [comment]
![image](https://user-images.githubusercontent.com/35923210/166099055-31c047c1-16f2-4802-9844-b058d71217f6.png)

**Comment by zzzgydi** [comment]
external controller的值加个双引号再重开试试

**Comment by dozen007** [comment]
![image](https://user-images.githubusercontent.com/35923210/166099469-819773f9-74ee-4018-80ff-aab1fc6eb3aa.png)
![image](https://user-images.githubusercontent.com/35923210/166099535-fe45375b-245f-42cd-b32e-6e94360264c1.png)

不行，而且日志为空

**Comment by zzzgydi** [comment]
有可能是之前开的没有正常关闭？还可以看看33333端口是不是被占用了，把对应的进程干了再试试

**Comment by dozen007** [comment]
用netstat -ano命令没有发现33333端口被占用

**Comment by zzzgydi** [comment]
假期后我再仔细看看

**Comment by zzzgydi** [comment]
尝试修复了一下这个问题，可以下载安装最新版v1.0.1试试

**Comment by dozen007** [comment]
![image](https://user-images.githubusercontent.com/35923210/167777130-ffb1bd42-1c54-4ad8-b11f-ae8fb6a994d6.png)
可以用了

**Comment by zzzgydi** [comment]
Nice!
