### ISSUE TITLE
[BUG]Deepin V20上无法使用

### ISSUE THREAD

**Issue by Tsukistar** [zzzgydi/clash-verge#790]
**Describe the bug**
Deepin V20上无法使用

**Information**
 - OS: Deepin Community 20.9
 - Clash Verge Version: 1.3.7
 - Clash Core: Clash

**Additional context**
安装完成后点击Clash Verge无法打开

**Comment by atauzki** [comment]
试下上个版本，这个版本ubuntu20.04也用不了

**Comment by Tsukistar** [comment]
我找到原因了，Deepin V20用的GLIBC 2.28，过于古早

**Comment by apeng-yp** [comment]
> 我找到原因了，Deepin V20用的GLIBC 2.28，过于古早

要升級到哪個版本呢  我看我的版本是2.3.1  也不能用

**Comment by Tsukistar** [comment]
最小2.29，不过它是查询特定GLIBC版本号，2.29、2.30、2.32、2.33、2.34、2.35

**Comment by atauzki** [comment]
> 最小2.29，不过它是查询特定GLIBC版本号，2.29、2.30、2.32、2.33、2.34、2.35

首先，升级glibc有搞坏系统的风险，其次，未加载的符号是按最高版本号来的，编译用系统ubuntu22.04，使用的glibc是2.35

**Comment by zzzgydi** [comment]
Ubuntu22.04之外的系统或版本都不保证，需要自行编译
