### ISSUE TITLE
[Feature] 希望给单个日志大小一个上限,达到后告警或者中断

### ISSUE THREAD

**Issue by howdareyo** [zzzgydi/clash-verge#799]
日志中持续写入
time="2023-09-27T21:07:43.2569603+08:00" level=error msg="[WG](*****) connect to server: proxyName[*****] not found"
写了一个600+g的日志
![Untitled](https://github.com/zzzgydi/clash-verge/assets/91058390/3f2acdf1-879b-4e86-8886-a3355ece6e16)
重启后未修改配置文件,正常运行,没有反复写入的现象
日志文件在ClashVerge\.config\clash-verge\logs\service下,不知是内核的问题还是gui的问题

**Comment by ningsibuqu** [comment]
可以加个定期删除日志吗

**Comment by zzzgydi** [comment]
刚加的功能，在杂项里选择开启，目前可以设置超过7天的日志自动删除，默认不删
提前试用 https://github.com/zzzgydi/clash-verge/releases?q=alpha&expanded=true
