### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fyg369** [zzzgydi/clash-verge#802]
Has anyone encountered this problem during installation? How to solve it?
![lj](https://github.com/zzzgydi/clash-verge/assets/142138034/4982a898-e489-457b-ad3e-73af48ba8f75)

**Comment by AnyWAT** [comment]
需要先安装 Webview2？
可去[巨硬官网（左下角的 Download ）https://developer.microsoft.com/en-us/microsoft-edge/webview2/ 下载。

**Comment by Fyg369** [comment]
> 需要先安装Webview2？ 可去巨硬官网（左下角的下载）https://developer.microsoft.com/en-us/microsoft-edge/webview2/下载。

不是很懂，安装一个软件还需要这些？官方Clash下载直接就可以安装了，貌似Clash  Meta安卓版也需要下载一些辅助的东西才能用，前提得翻墙才能下载这些辅助的东西😂😂😂，每次我都是用原版官方安卓Clash辅助Clash meta才能用上Clash meta,不如原版安卓Clash直接安装就能用方便。

**Comment by AnyWAT** [comment]
Windows 版本软件的用户界面，是以 Webview2 作为框架。。。
如（MSN）天气也是用此框架。

**Comment by Fyg369** [comment]
> Windows版本软件的用户界面，把Webview2作为框架。。。 如（MSN）天气也用这个框架。
> 
> > 是不是很好懂，安装一个软件还需要这些？
> 
> 鄙人码盲，按照报错提示，解决问题就好。https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by Fyg369** [comment]
> > Windows版本软件的用户界面，把Webview2作为框架...如（MSN）天气也用这个框架。
> > > 是不是很好懂，安装一个软件还需要这些？
> > 
> > 
> > 鄙人码盲，按照报错提示，解决问题就好。https://go.microsoft.com/fwlink/p/?LinkId=2124703

感谢解答，我复制安装提示里面的链接解决了https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by Fyg369** [comment]
感谢各位解答，我复制安装提示里面的链接解决了https://go.microsoft.com/fwlink/p/?LinkId=2124703
