### ISSUE TITLE
[BUG] 当节点较多时，测速动画消失

### ISSUE THREAD

**Issue by MarkIvory2973** [zzzgydi/clash-verge#804]
**Describe the bug**
当节点较多时，测速动画消失，且其他节点较少的组也没有测速动画。

**To Reproduce**
1. Go to 'Proxies'
2. Click on 'Delay Check'
3. See error

**Expected behavior**
无论什么节点，都能在测速时拥有测速动画。

**Screenshots**
点了测速后，所有节点延迟和没点一样，无反应。

**Information**
 - OS: Windows 11
 - Clash Verge Version: 1.3.7
 - Clash Core: Clash Meta

**Additional context**
这可能会让人没有耐心。

**Comment by zzzgydi** [comment]
节点较多，大概是有多少，什么数量级吗

**Comment by MarkIvory2973** [comment]
144个节点

**Comment by zzzgydi** [comment]
现在可以试试alpha分支的，已经优化了一下
