### ISSUE TITLE
[BUG]upload和download的值为什么还会变小？

### ISSUE THREAD

**Issue by HarlockHomes** [zzzgydi/clash-verge#809]
**Describe the bug**
C:\Users\Administrator\.config\clash-verge\profiles.yaml
对此文件内容中某条订阅做记录。记录的字段值取自这部分：
  extra:
    upload: 15312794204
    download: 572467040819
    total: 1072668082176
    expire: 1727372148
  updated: 1696737006
--------------------------------
得到如下结果：
Upload: 15214599958, Download: 554938313930, Updated: 1696729207
Upload: 15287785070, Download: 570458614610, Updated: 1696729807
Upload: 15287785070, Download: 570458614610, Updated: 1696730406
Upload: 15261895873, Download: 564435957997, Updated: 1696731007
Upload: 15312794204, Download: 572467040819, Updated: 1696731607
Upload: 15319115034, Download: 572801131799, Updated: 1696732207
Upload: 15319115034, Download: 572801131799, Updated: 1696732207
Upload: 15287785070, Download: 570458614610, Updated: 1696732806
Upload: 15312794204, Download: 572467040819, Updated: 1696733406
Upload: 15319115034, Download: 572801131799, Updated: 1696734007
Upload: 15312794204, Download: 572467040819, Updated: 1696734606
Upload: 15312794204, Download: 572467040819, Updated: 1696735207
Upload: 15366249527, Download: 576824644745, Updated: 1696735807
Upload: 15319115034, Download: 572801131799, Updated: 1696736407
Upload: 15312794204, Download: 572467040819, Updated: 1696737006

---------------------------------------------------
updated很明显是时间戳，让我困惑的是，
upload和download的值为什么还会变小？
这是不是哪里不对？

**Information**
 - OS: [Windows 2016]
 - Clash Verge Version: [1.3.7]
 - Clash Core: [Clash Meta]

----------------------------------------------------
另外对于某订阅的 已用、更新时间取值，有什么更好的别的方法？
cache.db 文件记录的有这些信息吗？如何读取他的内容？
或者 
有什么方法让clash主程序在每次更新完订阅输出这类信息到某个文件？

**Comment by zzzgydi** [comment]
profiles.yaml 里的 upload和download 来自你的订阅链接，为啥变少得问问订阅那边。

cache.db 不记录

> 有什么方法让clash主程序在每次更新完订阅输出这类信息到某个文件？

更新后，写脚本解析profiles.yaml
