### ISSUE TITLE
[feat] Request add profile-update-interval and content-disposition http header support

### ISSUE THREAD

**Issue by betaxab** [zzzgydi/clash-verge#81]
Format:

`profile-update-interval:` `24` (unit: hours)
`content-disposition:attachment;filename=`FileName

The first one is used to specify the subscription update interval, The second is used to specify the subscription name.

`profile-update-interval` is a CFW/Stash supported parameter. Of course, if you don't want to use this parameter, you can also use someting else.

Second, the subscription name will be determined by the subscription, no more confusing names like rAjY2gAFnCqB (The actual filename in .config can still be used with this).

I wish clash-verge would add support for these headers, thanks.

**Comment by zzzgydi** [comment]
Done. These two fields only take effect when importing.
