### ISSUE TITLE
[Feature]可以增加原来clash for windows的diff模式吗

### ISSUE THREAD

**Issue by unknownUser99999** [zzzgydi/clash-verge#810]
配置文件更改之后，如果在线更新的话，就会覆盖掉，采用diff就不会覆盖掉手动修改的

**Comment by zzzgydi** [comment]
看wiki，有merge和script

**Comment by unknownUser99999** [comment]
> 看wiki，有merge和script

但是这个好像没有规则校验，就是乱写的话也不会报错，还有合并冲突校验也没有好像

**Comment by unknownUser99999** [comment]
> 看wiki，有merge和script

但是这个好像没有规则校验，就是乱写的话也不会报错，还有合并冲突校验也没有好像
