### ISSUE TITLE
Hello, can clash-verge_1.3.7_amd64.AppImage run on Ubuntu 18.04? [BUG]

### ISSUE THREAD

**Issue by amiableclarity2011** [zzzgydi/clash-verge#814]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [e.g. macOS]
 - Clash Verge Version: [e.g. 1.3.4]
 - Clash Core: [e.g. Clash or Clash Meta]

**Additional context**
Hello, can clash-verge_1.3.7_amd64.AppImage run on Ubuntu 18.04?

**Comment by zzzgydi** [comment]
No.
