### ISSUE TITLE
macOS 无法开启 tun 模式

### ISSUE THREAD

**Issue by yangchuansheng** [zzzgydi/clash-verge#82]
报错：`Start Tun interface error: operation not permitted`

如何像 CFW 一样开启 Service Mode？

**Comment by yangchuansheng** [comment]
这个问题现在解决了吗？

**Comment by zzzgydi** [comment]
macOS和linux的没那么快处理

**Comment by breakings** [comment]
> macOS和linux的没那么快处理

failed to activate for `error sending request for url (http://127.0.0.1:9090/configs): error trying to connect: tcp connect error: 拒绝连接 (os error 111)` archlinux 这个日志是什么情况 然后也没法正常使用 程序及内核都已运行了

**Comment by zzzgydi** [comment]
@breakings 怎么确定内核成功运行了

**Comment by breakings** [comment]
> @breakings 怎么确定内核成功运行了

啊 这 要怎么诊断

**Comment by zzzgydi** [comment]
> > @breakings 怎么确定内核成功运行了
> 
> 啊 这 要怎么诊断

有可能9090端口占用了导致没有开启成功

**Comment by yangchuansheng** [comment]
@zzzgydi 现在支持了吗

**Comment by breakings** [comment]
> > > @breakings 怎么确定内核成功运行了
> > 
> > 
> > 啊 这 要怎么诊断
> 
> 有可能9090端口占用了导致没有开启成功

端口没有被占用

**Comment by zzzgydi** [comment]
@breakings https://github.com/zzzgydi/clash-verge/issues/98#issuecomment-1138363135  可能和这个原因一样，已经修复了，还没有发版而已。

**Comment by zzzgydi** [comment]
> @zzzgydi 现在支持了吗

还没搞这个

**Comment by breakings** [comment]
> @breakings [#98 (comment)](https://github.com/zzzgydi/clash-verge/issues/98#issuecomment-1138363135) 可能和这个原因一样，已经修复了，还没有发版而已。

OK 目前在ArchLinux确实可以运行且工作正常，但仍然无法使用tun模式

**Comment by skill7899** [comment]
> > @zzzgydi 现在支持了吗
> 
> 还没搞这个

解决了吗？

**Comment by yswtrue** [comment]
我也一样manjaro无法使用tun模式
```
2022-07-25 21:24:53 - [clash]: time="2022-07-25T21:24:53+08:00" level=error msg="Start Tun interface error: operation not permitted"
```

**Comment by yangchuansheng** [comment]
这个问题现在解决了吗？

**Comment by zzzgydi** [comment]
可以直接在终端运行这两个命令

```bash
sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash
sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash
```

修改meta核的权限

```bash
sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
```

**Comment by skill7899** [comment]
> 可以直接在终端运行这两个命令
> 
> ```shell
> sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash
> sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash
> ```
> 
> 修改meta核的权限
> 
> ```shell
> sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> ```

还有一个问题，开启tun模式，mac端还需要修改网络的dns，命令有下面
修改wifi的dns
networksetup -setdnsservers Wi-Fi 198.18.0.2
恢复我就很粗暴，直接清空
networksetup -setdnsservers Wi-Fi "Empty"
就会恢复到dhcp给的
当然也可以用get，恢复的时候set回去，希望作者加一下
networksetup -getdnsservers Wi-Fi

**Comment by skill7899** [comment]
> @skill7899 一直没搞懂clash tun模式下的dns，既然流量都是经过clash-meta了 嗅探功能应该就用不到了吧 可是这个功能并不好使 我看也有dns劫持 总之dns的处理非常混乱 难道是要在系统里面设置dns服务器为tun的网卡吗

是的，必需要tun的dns

**Comment by shallbytwo** [comment]
> 2023年3月份了 还是不能原生开tun模式

+1

**Comment by sarahgdc** [comment]
> 可以直接在终端运行这两个命令
> 
> 
> 
> ```bash
> 
> sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash
> 
> sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash
> 
> ```
> 
> 
> 
> 修改meta核的权限
> 
> 
> 
> ```bash
> 
> sudo chown root:admin /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> 
> sudo chmod +sx /Applications/Clash\ Verge.app/Contents/MacOS/clash-meta
> 
> ```

我修改了clash-meta的权限后还是没用，而且关掉clash verge后正常上网都不行了..比如连百度也打不开，一直显示“Safari can't connect to the server 'www.Baida.com'". 请问该怎么办？

**Comment by ipcjs** [comment]
为啥要Close掉？最新的1.3.0版下面，macOS上依然需要手动执行dns设置命令才能上网呀：
```
networksetup -setdnsservers Wi-Fi 198.18.0.2
```
