### ISSUE TITLE
[Feature]请求更新Clash.Meta内核版本，支持hysteria2

### ISSUE THREAD

**Issue by yourber** [zzzgydi/clash-verge#827]
Clash.Meta v1.16.0 已经出了一段时间了，请求更新，以支持hysteria2

**Comment by wyrain** [comment]
其实你可以自己换，自己去下载最新的clash.meta内核，去替换你安装位置里的内核

**Comment by lukaschan** [comment]
Mac版无法自行更换诶

**Comment by chenzhiguo** [comment]
我用1.3.7版本订阅hy2的机场地址，发现节点下载不了，proxies一直是空的，是否该版本存在hy2节点解析问题？

**Comment by zzzgydi** [comment]
1.3.8已经更新
