### ISSUE TITLE
[BUG] Ubuntu22.04.3 替换clash-meta 1.16.0 后无法识别内核

### ISSUE THREAD

**Issue by leechaojie** [zzzgydi/clash-verge#829]
**Describe the bug**
将 clash-meta 替换到 /usr/bin 后，授予可执行权限，clash-verge 无法切换 clash-meta 内核，报错信息为空；
用户-用户组都更改为目录内相同的用户-用户组后，还是无法识别；

**Information**
 - OS: Ubuntu 22.04.3
 - Clash Verge Version: [1.3.7]
 - Clash Core: [Clash Meta 1.16.0]

**Comment by zzzgydi** [comment]
更新到1.3.8吧
