### ISSUE TITLE
deepin无法使用

### ISSUE THREAD

**Issue by netxiang** [zzzgydi/clash-verge#83]
用deb包安装成功，但运行没反应。appImage程序运行同样没反应，用chmod加了运行权限也不行。deepin是20.5版。

**Comment by zzzgydi** [comment]
其他的系统可能要自己编译一下

**Comment by netxiang** [comment]
linux版本，你用什么系统测试的？

**Comment by zzzgydi** [comment]
ubuntu

**Comment by Nicolas-Gong** [comment]
我说咋打不开...原来是不行啊,还是用deepin商店自带的clash for windows吧

**Comment by kylesean** [comment]
ubuntu 22.04 同样的 deb 包安装后点击无反应

**Comment by squallliu** [comment]
deepin 不能跑，是因为 glibc 版本太低了

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/issues/177
