### ISSUE TITLE
[BUG] Proxies 中, 延迟大于 500 的 proxy 的数字的颜色有误

### ISSUE THREAD

**Issue by foobarjohnny** [zzzgydi/clash-verge#836]
**Describe the bug**
在 Proxies 中, 当 Proxy 能用, 只是延迟大于 500 时, 应该是 Warning Color(棕色), 但是却成了 Error Color (红色).

**To Reproduce**
1. 在 Proxies 中, 点击 Delay Check 按钮.
2. 观察每个 Proxy 后面的数字
3. 当 Proxy 能用, 只是延迟大于 500 时, 数字变成了 Error Color (红色).

**Expected behavior**
延迟大于 500 时, 数字应该是 Warning Color(棕色)

**Screenshots**
![image](https://github.com/zzzgydi/clash-verge/assets/11809464/96caa7c2-b131-479e-b3a3-ba17303112b6)

**Information**
 - OS: Windows 10
 - Clash Verge Version: 1.3.7
 - Clash Core: Clash Meta

**Comment by zzzgydi** [comment]
1.3.8已经更新
