### ISSUE TITLE
存储的日志不会自动删除

### ISSUE THREAD

**Issue by Toperlock** [zzzgydi/clash-verge#837]
version: v1.3.7
clash meta内核: v1.16.0
<div align="left">
    <img src="https://github.com/zzzgydi/clash-verge/assets/86833913/d751785d-a36e-438d-9356-564b068a4cfd" width="50%" />
</div>

**Comment by BunnyYang05** [comment]
建议把日志等级设高一点，比如 Warning 或者更高，能减少很多日志😋。

**Comment by zzzgydi** [comment]
刚加的功能，在杂项里选择开启
提前试用 https://github.com/zzzgydi/clash-verge/releases?q=alpha&expanded=true
