### ISSUE TITLE
M1芯片Mac无法安装

### ISSUE THREAD

**Issue by Idealisten** [zzzgydi/clash-verge#838]
M1芯片Mac，系统Sonoma14.0 (23A344)，版本[Clash.Verge_1.3.7_aarch64.dmg]，安装后打开时提示“Clash Verge”已损坏，无法打开。 你应该将它移到废纸篓。

**Comment by Toperlock** [comment]
> M1芯片Mac，系统Sonoma14.0 (23A344)，版本[Clash.Verge_1.3.7_aarch64.dmg]，安装后打开时提示“Clash Verge”已损坏，无法打开。 你应该将它移到废纸篓。

https://github.com/Toperlock/Clash/wiki/Clash%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B#macos

**Comment by zzzgydi** [comment]
https://github.com/zzzgydi/clash-verge/issues/369
