### ISSUE TITLE
重新启动电脑后，怎么设置都是连接不上外网的。[BUG]

### ISSUE THREAD

**Issue by qq11109071** [zzzgydi/clash-verge#839]
重新启动电脑后，怎么设置都是连接不上网的。关闭后，启动clash for windows就可以了。不知道是哪儿出了问题？
我直接拔号上网的。不知道是不是这个原因？但即便是拔号上网clash for windows都可以正常运行。
不知道到底问题出在哪儿？大家有遇到和我一样的问题吗？

**Comment by yanxiangrong** [comment]
瞎打什么BUG,你把电脑设置里面的代理关掉就行了

**Comment by Itsusinn** [comment]
软件关闭后不会清除系统的代理设置，这就导致了当clash verge关闭后，系统代理被指向了一个无效的代理地址

**Comment by Parallel-Paradox** [comment]
关机之前把 clash 的代理关掉就行

或者开机以后把 clash 打开

或者在系统设置里面手动把下面这个关了

<img width="884" alt="1698925068615" src="https://github.com/zzzgydi/clash-verge/assets/81791934/54126174-cce6-4420-9593-6d4c5bf83059">
