### ISSUE TITLE
[Feature] 为Geosite 、Mmdb 和 Geoip更新添加手动更新按钮

### ISSUE THREAD

**Issue by stevejohnson7** [zzzgydi/clash-verge#844]
针对 #526 中提出的在启动时更新geoip/geosite存在的问题，可以在配置页面增加一个geo更新的按钮，供用户手动点击启动下载，保证下载全部成功后再尝试载入内核启动。
这样可以避免 #526 中出现的下载失败导致内核启动失败的问题。

**Comment by zzzgydi** [comment]
#526 的问题默认带两个dat文件就可以了。手动更新也简单，可以直接手动下载替换文件就好

**Comment by zzzgydi** [comment]
可以在web ui里加上meta的面板，我印象中meta面板支持
