### ISSUE TITLE
[BUG]External controller listen error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by CLAvenger** [zzzgydi/clash-verge#851]
在设置里打开局域网连接或者IPv6，显示“Network error”
而且代理页面无法显示节点
日志中显示External controller listen error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by CLAvenger** [comment]
且代理页面无法显示节点

**Comment by zzzgydi** [comment]
查看是否有别的进程把9090端口占了，有就干掉，或者手动给external-controller换个端口
