### ISSUE TITLE
1.3.8[BUG]1.3.8版，代理处不显示 ，内核外不显示core版本，端口处设置后不显示，以上这内核和端口 功能都可用，代理处能用但完全不显示 

### ISSUE THREAD

**Issue by fyhzc** [zzzgydi/clash-verge#852]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [e.g. macOS]
 - Clash Verge Version: [e.g. 1.3.4]
 - Clash Core: [e.g. Clash or Clash Meta]

**Additional context**

**Comment by zzzgydi** [comment]
关掉所有旧的app进程，重启app
