### ISSUE TITLE
[BUG] Clash Verge Proxy Groups 界面无法显示

### ISSUE THREAD

**Issue by Meonthb** [zzzgydi/clash-verge#853]
**Describe the bug**
Proxy Groups 界面无法显示，但可以正常代理链接。

**Screenshots**
![image](https://github.com/zzzgydi/clash-verge/assets/60881723/42c25ef6-32f6-40e4-bd13-7dc403cc503d)

**Information**
 - OS: Windows 11 22621.2506
 - Clash Verge Version: 1.3.8
 - Clash Core: Clash Meta

**Comment by PillarsZhang** [comment]
同样的问题，看了看 Clash 的 RESTful API 是正常的
日志文件出现：`2023-10-31 02:58:24 ERROR - failed to connect to the Clash Verge Service`

**Comment by LevineWoo** [comment]
今早更新后同样的问题。

**Comment by zzzgydi** [comment]
重启app试试

**Comment by AntarcticBruin** [comment]
同样的问题

**Comment by flacce** [comment]
+1，更新1.3.8就这样了，内核也不显示版本

**Comment by zzzgydi** [comment]
在任务管理器里把所有进程都关了，再重新打开。

**Comment by AntarcticBruin** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/66901840/11675006-d687-46e9-a7ef-7b8331c10762)
关进程，重启电脑都不行

**Comment by LevineWoo** [comment]
> ![image](https://user-images.githubusercontent.com/66901840/279237681-11675006-d687-46e9-a7ef-7b8331c10762.png) 关进程，重启电脑都不行

确实，都试过了，确实不行。

**Comment by lxy35326** [comment]
1.3.8版本太离谱了 是怎么放出来的

**Comment by Meroser** [comment]
同问，直接不显示界面。但是似乎解决了meta内核不会自动延迟测试的问题

**Comment by zzzgydi** [comment]
定位问题了，稍等

**Comment by PillarsZhang** [comment]
新的包确认正常啦

**Comment by Meroser** [comment]
新的包确认正常啦，但是meta内核好像还是没办法自动延迟测试。总是选择第一个节点，要手动点测试。

**Comment by zzzgydi** [comment]
新发的包OK了，为了避免以后频繁出现这种问题，建了个开发和内测tg群，感兴趣可以加https://t.me/+-49pddUeIcdkMjU1
