### ISSUE TITLE
1.3.8[BUG]1.3.8版更新无效。打开的还是老的版本，新的版本的安装过程结束后多出一个新的clash verge

### ISSUE THREAD

**Issue by saufall** [zzzgydi/clash-verge#855]
**Describe the bug**
他怎么要1.38？github只有1.37.点了更新后跳出自我安装，完了后还是一样说要更新。安装了的软件里显示2个clash verge。这个怎么办？
![image](https://github.com/zzzgydi/clash-verge/assets/130485280/6cf73844-7be9-40cf-bccb-77fdeb916dcb)

**To Reproduce**

打开1.37版本的verge。点击红色的new按钮更新。安装过程完成。关闭clash verge.再打开桌面的shortcut结果还是3.17的verge。红色的new还在那还要更新
报错图如上

**Expected behavior**
下载，安装，覆盖，1.38新版本

**Information**
 - OS: win 11 64bit pro
 - Clash Verge Version: 1.37

**Comment by mnq-tec** [comment]
do not install 1.3.8 ,has bugs for showing proxies.

**Comment by saufall** [comment]
> do not install 1.3.8 ,has bugs for showing proxies.

Thank you. So I should wait for the official release?

**Comment by LevineWoo** [comment]
> do not install 1.3.8 ,has bugs for showing proxies.

要是早点看到就好了。

**Comment by zzzgydi** [comment]
关掉所有旧的app进程，重启app

**Comment by dale0525** [comment]
> 关掉所有旧的app进程，重启app

重启电脑都没用

**Comment by HalChoo** [comment]
1.3.8更新meta内核了么

**Comment by ningsibuqu** [comment]
> 关掉所有旧的app进程，重启app
代理页面空白
![image](https://github.com/zzzgydi/clash-verge/assets/51028975/2df618f4-a564-476b-97d8-65bd74b3c03e)

**Comment by Meroser** [comment]
你之前安装是用的exe文件吧

**Comment by Meroser** [comment]
> 关掉所有旧的app进程，重启app

重启电脑 重装都没用

**Comment by LevineWoo** [comment]
> 你之前安装是用的exe文件吧

是的。

**Comment by zzzgydi** [comment]
已经定位问题了，等一下新的包吧

**Comment by PillarsZhang** [comment]
新的包确认正常啦

**Comment by Meroser** [comment]
> > 你之前安装是用的exe文件吧
> 
> 是的。
用msi包，自动更新就不会生成两个软件了

**Comment by zzzgydi** [comment]
新发的包OK了，为了避免以后频繁出现这种问题，建了个开发和内测tg群，感兴趣可以加https://t.me/+-49pddUeIcdkMjU1
