### ISSUE TITLE
[BUG]新的包确认正常啦，但是meta内核好像还是没办法自动延迟测试。总是选择第一个节点，要手动点测试。me too

### ISSUE THREAD

**Issue by fyhzc** [zzzgydi/clash-verge#856]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [e.g. macOS]
 - Clash Verge Version: [e.g. 1.3.4]
 - Clash Core: [e.g. Clash or Clash Meta]

**Additional context**

**Comment by zzzgydi** [comment]
meta内核自动延迟测试是啥feature吗，有啥信息贴一下吗

**Comment by Canda15** [comment]
> meta内核自动延迟测试是啥feature吗，有啥信息贴一下吗

他的意思可能是clash的配置里自动测试延迟选择延迟最低的那个不能用。每次都选择的第一个节点。
```
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 20
```
但我这里好像是正常的
