### ISSUE TITLE
[BUG]代理界面"规则|全局|直连"点击无反应，选择代理的界面为空白

### ISSUE THREAD

**Issue by bobcyw** [zzzgydi/clash-verge#857]
**Describe the bug**
升级到1.3.8以后，点击代理界面，“规则|全局|直连”都不行了，都是空白

**To Reproduce**
1. 升级到1.3.8
2. 点击代理
3. “规则|全局|直连”选择后的面板均为空白

**Expected behavior**
 “规则|全局|直连"点击规则或者全局以后，可以选择具体的Proxy

**Screenshots**
![image](https://github.com/zzzgydi/clash-verge/assets/4155602/e252496f-28ff-409d-b971-be553cf81024)

**Information**
 - OS: [Windows 10 22H2 企业版]
 - Clash Verge Version: [1.3.8]
 - Clash Core: [Clash Meta]

**Additional context**

**Comment by bobcyw** [comment]
降回1.3.7以后界面正常

**Comment by matianhe3** [comment]
> 降回1.3.7以后界面正常

release下载最新1.3.8正常.

**Comment by zzzgydi** [comment]
在release里下载最新的吧

**Comment by zzzgydi** [comment]
顺便问一下，你是啥时候更新的
