### ISSUE TITLE
[BUG] 1.38的安装包被微软win defender报毒

### ISSUE THREAD

**Issue by saufall** [zzzgydi/clash-verge#859]
下载的最新release 1.38的安装包
**Expected behavior**
普通安装

**bug**
用malware bytes 和win defender在未打开的情况下都没毒。
virustotal 显示只有2个杀毒软件表示可能是毒。大多数都过了。sandbox过了。
运行exe的时win defender报毒给删除了。

**Screenshots**
![clash verge virus 1](https://github.com/zzzgydi/clash-verge/assets/130485280/e3957232-37ca-4d01-b3f7-6e46727b9471)

**Information**
 - OS: win 11 pro
windows 1.38 64bit exe安装包

**Comment by zzzgydi** [comment]
这个不知道咋处理，如有担心，请源码编译自用
