### ISSUE TITLE
据悉clash 内置dns将会全部暴露给本地 ISP 运营商与有关部门

### ISSUE THREAD

**Issue by sixgodfan** [zzzgydi/clash-verge#86]
1.据悉clash 内置dns将会全部暴露给本地 ISP 运营商与有关部门
2.x-ui怎么跟clash-verge使用起来？
3.https://github.com/h2y/Shadowrocket-ADBlock-Rules  有没有类似使用这样的规则功能，白名单、黑名单等等？谢谢

**Comment by zzzgydi** [comment]
1。这个不了解，可以分享消息来源学习学习
2。不支持
3。不内置支持，可以自己根据clash规则配置补充这些规则

**Comment by zzzgydi** [comment]
第一点v2ex看的吧，担心这那的就不开启clash的dns就好（clash verge默认不开启dns即使你的订阅里有也不开启，需要手动开启），自行搭配其他dns工具即可。
v2ex评论里还提到可以用meta核，clash verge下个版本也支持切换核心，应该解决了。
