### ISSUE TITLE
ubuntu20.04只能用预发布alpha版

### ISSUE THREAD

**Issue by oxyhexagen** [zzzgydi/clash-verge#863]
今天手贱点了下更新，立马报之前的缺这个lib那个lib，然后再alpha发布的下载才能用。
我记得您之前在一个issue下讨论过github发布编译的问题，然后好像20.04没有那些lib版本，忘了原issue在哪了。
我想请教下alpha是用什么编译的？既然20.04这种老版本用alpha的最新版1.3.8都没问题(而不用像很多issue里说的退回1.3.5/6)为什么不能正式发行也用这个编译的？感谢回答

**Comment by zzzgydi** [comment]
alpha是用20.04构建的。

> 为什么不能正式发行也用这个编译的

因为用了20.04构建，22.04的用户就会报错，这俩互斥
