### ISSUE TITLE
如何增加claude的分流规则

### ISSUE THREAD

**Issue by zhl111** [zzzgydi/clash-verge#865]
openai可以，但我不能claude，请教

**Comment by zzzgydi** [comment]
参考 https://github.com/zzzgydi/clash-verge/issues/520

**Comment by zzzgydi** [comment]
> 这 https://github.com/zzzgydi/clash-verge/issues/520 里的规则是用在什么地方的？这代码也能用在clash Verge里吗？

新建一个script profile，写脚本
