### ISSUE TITLE
谷歌翻译不能正常使用

### ISSUE THREAD

**Issue by zhl111** [zzzgydi/clash-verge#866]
![image](https://github.com/zzzgydi/clash-verge/assets/29135984/bda6e25c-fab2-4ea8-af6a-361ae80ce03b)
 我加了rule也不行只能全局才可以，而clash for windows就没这个问题，求解

**Comment by zzzgydi** [comment]
这个M后面那个方框是乱码了吗

**Comment by zzzgydi** [comment]
> ![image](https://user-images.githubusercontent.com/29135984/279709056-bda6e25c-fab2-4ea8-af6a-361ae80ce03b.png) 我加了rule也不行只能全局才可以，而clash for windows就没这个问题，求解

你图里的规则是加在哪里的

**Comment by zzzgydi** [comment]
用啥都一样，测速正常的话，就看连接页，看看有没有连接，搜这个translate.google.com看连接到哪里了。如果一个连接都没有就看你开系统代理没。
