### ISSUE TITLE
clash verge开启系统代理无效的问题

### ISSUE THREAD

**Issue by RGeyrat** [zzzgydi/clash-verge#884]
之前用过一段时间的clash for windows，现在换成clash verge以后开启系统代理无效，没办法上外网，原clash for windows卸载后重置过电脑网络设置再安装clash verge也还是无效，想请问下这个是什么原因，是中间还有什么步骤没进行吗？

**Comment by AnyWAT** [comment]
> 开启系统代理无效，没办法上外网

貌似最佳：不要开启影响操作系统的系统代理，浏览器采用代理扩展，同时可以运行使用不同端口的N个代理，一个用于浏览器，一个专职下载，一个。。。

**Comment by RGeyrat** [comment]
emm不太懂什么是会影响系统的系统代理，上面没说明白，我换成clash verge后浏览器通过代理扩展程序可以上外网，但是不适用扩展只用clash verge就不行

**Comment by zzzgydi** [comment]
什么系统

**Comment by RGeyrat** [comment]
win11

**Comment by zzzgydi** [comment]
是拨号上网吗

**Comment by RGeyrat** [comment]
哇你这么一说好像是的，移动的校园网

**Comment by zzzgydi** [comment]
拨号上网的话，先手动设置代理吧，这个bug一直存在

**Comment by AnyWAT** [comment]
> 什么是会影响系统的系统代理

开启了系统代理，Windows10 如应用商店、天气、Microsoft Edge、系统更新等等都不能正常联网，所谓影响操作系统。。。

**Comment by RGeyrat** [comment]
> 拨号上网的话，先手动设置代理吧，这个bug一直存在

哦哦好的，请问怎么手动设置代理呢，能指个路吗。还有就是我之前有过一次clash verge 换clash for windows也是换了以后没法代理，请问这两个是同一个问题吗

**Comment by lswsx** [comment]
> 之前用过一段时间的clash for windows，现在换成clash verge以后开启系统代理无效，没办法上外网，原clash for windows卸载后重置过电脑网络设置再安装clash verge也还是无效，想请问下这个是什么原因，是中间还有什么步骤没进行吗？

换个端口号试试，我遇到了跟你一样的问题，换个端口号就好了

**Comment by RGeyrat** [comment]
> > 哦哦好的，请问怎么手动设置代理呢，能指个路吗。还有就是我之前有过一次clash verge 换clash for windows也是换了以后没法代理，请问这两个是同一个问题吗
> 
> * 手动设置代理方法请使用 Google 以找到最适合自己的方式。另外注意，Proxy SwitchyOmega 作者仅在 Google Chrome 商店中发布，其余商店如 Microsoft Edge 中的版本来源不明，请自行甄别。
> * 切换代理软件后若无法联网，请检查系统代理设置是否被清空或已正确配置
> 
> > 开启了系统代理，Windows10 如应用商店、天气、Microsoft Edge、系统更新等等都不能正常联网，所谓影响操作系统。。。
> 
> * 请使用 EnableLoopback.exe （需自行下载） 设置 Exemption，若无效则可能需要使用 tun 模式因某些 UWP 并不使用系统代理

好的谢谢

**Comment by RGeyrat** [comment]
> > 之前用过一段时间的clash for windows，现在换成clash verge以后开启系统代理无效，没办法上外网，原clash for windows卸载后重置过电脑网络设置再安装clash verge也还是无效，想请问下这个是什么原因，是中间还有什么步骤没进行吗？
> 
> 换个端口号试试，我遇到了跟你一样的问题，换个端口号就好了

好的我试试看

**Comment by Mythologyli** [comment]
See #833
