### ISSUE TITLE
Does CV support load balance with group like CFW

### ISSUE THREAD

**Issue by Gavinin** [zzzgydi/clash-verge#887]
## CFW Repository is closed , sad ;( 

Unfortunately I didn't found the concept of  group , so it means CV may not support Load Balance currently.

Is there any means to achieve it , or any development strategies in place?

This is my [CFW js profile](https://raw.githubusercontent.com/Gavinin/GFW-Rule/master/Cfw/paraser.js), thanks!

**Comment by zzzgydi** [comment]
Clash Verge support `script` profiles, which can also use js to process config. [wiki](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#script-%E8%84%9A%E6%9C%AC%E5%A4%84%E7%90%86)

**Comment by Gavinin** [comment]
My expression may not be clear, I understand CV support Script .
But Is there any example for script with group and load balance which can connect to specific group for load balance by rule, Connect to multiple groups at the same time.
![Screenshot 2023-11-03 at 11 03 20](https://github.com/zzzgydi/clash-verge/assets/14181095/d60c2726-ca4a-4a3f-ba32-c7cf7d4fe427)

**Comment by Gavinin** [comment]
I find a script example which show the group and load balance, but thanks
