### ISSUE TITLE
更多协议支持

### ISSUE THREAD

**Issue by GOD-XINGCHEN** [zzzgydi/clash-verge#891]
我希望可以和cfw一样支持非常多的协议，否则真的没法用，因为节点不可能全是vmess协议，有很多其他的协议

**Comment by moranno** [comment]
比cfw支持的协议多多了。用Meta内核

**Comment by coco456** [comment]
支持协议是内核，关软件什么事呢
切换内核不就可以了

用之前，在油管找个教程看

**Comment by zzzgydi** [comment]
切换meta内核
