### ISSUE TITLE
[BUG]v1.3.8的上下行流量统计都是0B

### ISSUE THREAD

**Issue by l1090921084** [zzzgydi/clash-verge#898]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**
 - OS: [e.g. macOS]
 - Clash Verge Version: [e.g. 1.3.4]
 - Clash Core: [e.g. Clash or Clash Meta]

**Additional context**

**Comment by mo3et** [comment]
If you running in Mac. Refer to #490

**Comment by zzzgydi** [comment]
系统代理或者TUN有开吗

**Comment by no-swing** [comment]
> 系统代理或者TUN有开吗

![image](https://github.com/zzzgydi/clash-verge/assets/47711477/1062ad7b-dde3-4d31-a7be-0d90e4cedc25)
有的而且log和链接是正常打印的

**Comment by zzzgydi** [comment]
tun和系统代理二选一就好
