### ISSUE TITLE
Mac版本在MacBook Pro M1 Max 运行闪退

### ISSUE THREAD

**Issue by objcCodingTogether** [zzzgydi/clash-verge#9]
如题。打开后闪退。

直接打开应用里面的clash-verge,显示如下信息：

/Applications/clash-verge.app/Contents/MacOS/clash-verge ; exit;
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/utils/init.rs:72:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

感谢~~

**Comment by zzzgydi** [comment]
看这个报错感觉是创建`~/.config/clash-verge`文件夹失败了

**Comment by objcCodingTogether** [comment]
嗯嗯。手工创建目录： mkdir -p ~/.config/clash-verge
然后打开OK了。谢谢~~

**Comment by yangchuansheng** [comment]
能不能编译一个 M1 芯片原生的安装包？

**Comment by yangchuansheng** [comment]
> 看这个报错感觉是创建`~/.config/clash-verge`文件夹失败了

你好，能不能编译一个 M1 芯片原生的安装包呀，最好是每次 release 都包含 M1 的安装包

**Comment by zzzgydi** [comment]
@yangchuansheng 可以提供，但是有关程序更新那块暂时没搞好，更新之后下载的还会是intel编译的。后续要看看如何优雅的处理updater的ci问题，这个问题才算解决。

**Comment by DawnMagnet** [comment]
tauri也不是平台相关的吧

**Comment by DawnMagnet** [comment]
> > 看这个报错感觉是创建`~/.config/clash-verge`文件夹失败了
> 
> 你好，能不能编译一个 M1 芯片原生的安装包呀，最好是每次 release 都包含 M1 的安装包

@yangchuansheng  #20 你可以看这，我尝试编译了一个包

**Comment by zzzgydi** [comment]
暂不提供M1的release和tauri无关，而且我自己的Mac也是M1的，现在的代码在M1上是完全可以编译没有问题的。原因还是上面提到的，主要是有关程序更新的问题。其他考虑如下：

一是因为项目采用github action做构建发布，github action好像还没有支持M1的平台，所以这个就没做。要做当然也可以，我可以在自己的电脑上编译后发上来，对我来说麻烦了一点而已。但会有第二个问题。

二是因为程序更新目前只会拉取intel版本的安装包，用户更新之后，程序又变成intel版本的了，除非再手动下载安装一遍，总的来说，略麻烦。这一块解决了的话，就可以稳定提供M1版的了。这个问题目前有一点点思路，还没验证实践，所以先待定。这个问题解决了的话，可能还会存在第三个问题。

三是关于安全和信任的考虑，我或者其他任何人，使用本项目代码自己编译后供他人使用，都可能让使用者有一点顾虑。因为不论是我或者其他任何人，对于用户来说是没有任何置信度的，程序也没有经过xxx应用商店的安全验证，所以必然会存在这样的问题。开源以及使用github action 构建，一个是代码即证明，一个是构建的release有迹可循可追溯。同理，如果有证明github action release或者当前的ci流程有任何信任方面的问题，要么完善ci，要么对所有release添加额外说明，要么仅提供源码。

有舍有得，我这里就写一下自己的思考抛砖引玉。后续解决了ci问题的话，还是会尽量提供更多release，同时添加必要的说明信息。
