### ISSUE TITLE
隔壁CFW无了，转来这里了

### ISSUE THREAD

**Issue by voice1230** [zzzgydi/clash-verge#901]
作者加油！！！

**Comment by lwd-temp** [comment]
隔壁 Clash 没了，Clash.Meta archive 了。

**Comment by voice1230** [comment]
> 隔壁 Clash 没了，Clash.Meta archive 了。

做clash内核那个也无了吗？我以为就CFW无了...

**Comment by lwd-temp** [comment]
> > 隔壁 Clash 没了，Clash.Meta archive 了。
> 
> 做clash内核那个也无了吗？我以为就CFW无了...

就在刚才。

**Comment by hubumulity** [comment]
这个也快了

**Comment by voice1230** [comment]
> > > 隔壁 Clash 没了，Clash.Meta archive 了。
> > 
> > 
> > 做clash内核那个也无了吗？我以为就CFW无了...
> 
> 就在刚才。

完了，这是要大清理啊

**Comment by snape2019** [comment]
> 这个也快了

不会吧

**Comment by itsuitsuki** [comment]
作者撑住

**Comment by Libra258** [comment]
这下踩下油门了

**Comment by baizhi958216** [comment]
🤷‍♂️可恶啊

**Comment by akaramatsu** [comment]
？？？？？

> > > 隔壁 Clash 没了，Clash.Meta archive 了。
> > 
> > 
> > 做clash内核那个也无了吗？我以为就CFW无了...
> 
> 就在刚才。

**Comment by Bailey-24** [comment]
fork 啊，愣着干嘛

**Comment by junlongzzz** [comment]
没用，老巢Clash都给端了，GUI的也活不久了，超了！

**Comment by xgblack** [comment]
Clash内核仓库404了

**Comment by TurnOffNOD** [comment]
> 没用，老巢Clash都给端了，GUI的也活不久了，超了！

还有个clash meta。

**Comment by funcdfs** [comment]
> > 没用，老巢Clash都给端了，GUI的也活不久了，超了！
> 
> 还有个clash meta。

没了都已经，仓库 commit force 了。
