### ISSUE TITLE
兼容问题，寻求帮助

### ISSUE THREAD

**Issue by zhl111** [zzzgydi/clash-verge#904]
我用这个获取微博信息：https://github.com/cndiandian/weibo
我用cfw一切正常，但用verge就不能用，提示错误。我不知怎么修改
![image](https://github.com/zzzgydi/clash-verge/assets/29135984/5588e706-f765-4053-93b5-ccc4a41e4ea4)

**Comment by zhuang1234** [comment]
那你这让人家怎么解决？

**Comment by zhuang1234** [comment]
我不是这个软件的开发人员，但我看你这问题像是weibo这个项目的问题，你可以先看看能不能连上谷歌，然后再用终端试试，如果终端连接不了，可以检查一下环境变量
