### ISSUE TITLE
[Feature] 希望关闭 GUI 后结束 tauri 进程

### ISSUE THREAD

**Issue by HytonightYX** [zzzgydi/clash-verge#906]
目前打开了 GUI 后，tarui 会一直留在进程列表中，并且内存占用会从 130MB 逐渐增长到 300MB

<img width="669" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/29689767/221a6e99-ac56-467b-b12b-afefbbe71072">

**Comment by zzzgydi** [comment]
尝试过，没关掉
