### ISSUE TITLE
[BUG]Window 11上无法显示流量信息，请开发者修复！

### ISSUE THREAD

**Issue by gongth0412** [zzzgydi/clash-verge#907]
如图所示，
连接后，流量使用情况不显示，
OS版本：Window11
![屏幕截图 2023-11-03 155546](https://github.com/zzzgydi/clash-verge/assets/149766852/8ff910b5-3edf-45ca-80ca-b03b88e3ed4d)

**Comment by troublewind** [comment]
![image](https://github.com/zzzgydi/clash-verge/assets/107900115/5ada1025-a879-415c-86aa-2af03d869b63)
我这能显示，昨晚刚更新的23H2正式版

**Comment by mw418** [comment]
可以的 没识别到网卡？

**Comment by zzzgydi** [comment]
有开系统代理或者TUN吗

**Comment by gongth0412** [comment]
> 有开系统代理或者TUN吗

开了，已解决，可以显示了，谢谢大佬！
